### ISSUE TITLE
Indicateur de performance par test

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-france#1002]
Relates to #1005

Pour savoir si une branche est plus ou moins performante qu'une autre, ou pour avoir un comparatif pour aider à la prise de décisions.

**Definition of done :**

Un indicateur, n'importe le format (console, tableau...) qui permet de mesurer la variation de performance du test suite entre la branche actuelle et `master`.

Si possible, essayer de ne pas travailler sur CircleCI toute de suite.

Example :

    nose tests/performance.py
    > Test suite run 15% faster than master

**Comment by Anna-Livia** [comment]
CircleCI propose an [API](https://circleci.com/docs/api/v1-reference/#test-metadata) to access the tests metadata.

I haven't found all the options ... yet, however, I wrote the following script to get a sense ho our test performance on cicleCI, through the `build_time_millis` attribute.
Then the script loops on the next successful build.

```py
import requests

start_build = 1774
results = {}
for i in range(1):
    
    response_json = requests.get("https://circleci.com/api/v1.1/project/github/openfisca/openfisca-core/"+str(start_build))
    response_python = response_json.json()
    results[start_build] = response_python['build_time_millis']
    print(response_python['build_time_millis'])
    start_build = response_python['previous_successful_build']['build_num']

print(results)
```py

The result are a bit disconcerning as they are all over the map :
here are the result for the last 10 successful builds :
```
1774: 21487, 
1764: 58359,
1763: 24688,
1761: 60687,
1760: 18019, 
1758: 47312,
1757: 25161,
1755: 36308,
1754: 29151, 
1752: 52760,
1751: 23072,
1749: 63417, 
1748: 11356,
1740: 36227, 
1739: 24624
```
![Capture d’écran 2018-06-04 à 17.52.24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922aa9a25cd102270617380/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b37ef2122f410ea3febc405f4141fee78b2fb4aa2e30c80351b882294d7ed43819a4bf8b16eb03b827d84a83e4bf8b4cc1ef6f77e283dd5d220c4749d7ab0268f9d31e8a4afc59e04a5fa516346be77431794e911c7225792a.png)

**Comment by Anna-Livia** [comment]
Deuxième séries de tests beaucoup plus convaincantes :

```py
import json
import requests


def moyenne(tableau):
    return sum(tableau, 0.0) / len(tableau)


def variance(tableau):
    m=moyenne(tableau)
    return moyenne([(x-m)**2 for x in tableau])


def ecartype(tableau):
    return variance(tableau)**0.5


api_url = "https://circleci.com/api/v1.1/project/github/openfisca/openfisca-france/tree/master"
response = requests.get(api_url2)
if response.status_code == 200:
    response_python = json.loads(response.content.decode('utf-8'))
else:
    response_python = None

build_python2 = []
build_python3 = []
deploy_python2 = []
deploy_python3 = []


for response in response_python:
    if not response['status'] == "success":
        pass
    elif response['workflows']['job_name'] == 'build_python2':
        build_python2.append(response['build_time_millis'])
    elif response['workflows']['job_name'] == 'build_python3':
        build_python3.append(response['build_time_millis'])
    elif response['workflows']['job_name'] == 'deploy_python2':
        deploy_python2.append(response['build_time_millis'])
    elif response['workflows']['job_name'] == 'deploy_python3':
        deploy_python3.append(response['build_time_millis'])
    else:
        print(response['workflows']['job_name'])

build_all = build_python2 + build_python3
deploy_all = deploy_python2 + deploy_python3
builds = [build_python2, build_python3, build_all, deploy_python2, deploy_python3, deploy_all ]

for build in builds:
    print([ k for k, v in locals().items() if v is build][0])
    moyenne_build = moyenne(build)
    ecartype_build = ecartype(build)
    len_build = len(build)
    ration_build_python2 = round(ecartype_build/moyenne_build * 100, 2)
    print("pour {} éléments, la moyenne était de {}, avec un écart type de {} ce qui fait un ratio de {}".format(len_build, moyenne_build, ecartype_build, ration_build_python2))

```
Donne les résultats suivants :
```
build_python2
pour 7 éléments, la moyenne était de 214469.7142857143, avec un écart type de 11581.462771099657 ce qui fait un ratio de 5.4
build_python3
pour 7 éléments, la moyenne était de 210921.57142857142, avec un écart type de 10415.748239457167 ce qui fait un ratio de 4.94
build_all
pour 14 éléments, la moyenne était de 212695.64285714287, avec un écart type de 11156.001751825546 ce qui fait un ratio de 5.25
deploy_python2
pour 7 éléments, la moyenne était de 71679.57142857143, avec un écart type de 19266.973584401905 ce qui fait un ratio de 26.88
deploy_python3
pour 7 éléments, la moyenne était de 15284.285714285714, avec un écart type de 2713.013965225797 ce qui fait un ratio de 17.75
deploy_all
pour 14 éléments, la moyenne éta
```
Ce qui j'analyse de la manière suivante :
Il y a une grande variabilité dans les temps de déploiement. 
Ce qui n'est pas le cas des temps de test (sur les 14 cas disponibles)
```
build_all
pour 14 éléments, la moyenne était de 212695.64285714287, avec un écart type de 11156.001751825546 ce qui fait un ratio de 5.25
```
L'écart type représente 5,25% de la moyenne ce qui semble très prometteur pour construire une baseline.

**Comment by maukoquiroga** [comment]
@Anna-Livia C'est super intéressant, en effet un écart type de ~5% est à mon humble avis acceptable.

Juste une note : cela devrait être en anglais, non ?

BTW, suite aux liens que j'ai ajouté à #1004, j'ai essayé :

    pip freeze | grep -v "^-e" | xargs pip uninstall -y
    pip install --editable ".[test]"
    nosetests --with-xunit

Ce qui génère un fichier `xunit` j'imagine téléversable (CircleCI) cc @sandcha

**Comment by maukoquiroga** [comment]
> Les 5% d'écart type, c'est sur 14 cas, donc il va falloir monitorer pour vérifier que la tendance continue.
> En tout cas, c'est un bon signe.

Super !

> Pour le code que tu as essayé, tu l'as essayé où ? en local ? sur circleci ?

En local, mais je n'ai pas réussi à visualiser le fichier `xml` résultant. Tu devrais pouvoir le visualiser sur CircleCI par contre.

> Est ce que tu as une idée où on pourrait faire un appel à l'api et comparer les metadata du build qui vient d'être fait ?

Pas pour l'instant, mais si tu fais ces commandes sur ta machine, tu auras un json et du xml à comparer 😄 

> Et petite question : Qu'est ce qui devrait être en anglais ?

Je parlais du STDOUT :

    build_python2
    pour 7 éléments,
    ...

**Comment by sandcha** [comment]
Super ! Pour les premiers résultats, les écarts importants me semblent explicables par le fait que les 10 derniers builds réussis comprenaient en particulier nos essais de tests de performance.

Côté junit xml, il y en a un de généré sur circle via [cette commande](https://github.com/openfisca/openfisca-france/blob/73c738892c0237c621d863244e45638364cfa733/.circleci/config.yml#L38) (les options fonctionnent aussi en local).

Sinon, pour ce qui est de l'emplacement du fichier effectuant cette analyse : si on ne souhaite pas l'ajouter aux `tests/`, une autre possibilité serait de le placer dans `scripts/`. Aujourd'hui, on y a par exemple cet autre type de [script](https://github.com/openfisca/openfisca-france/blob/7ce3678b1fce069b9991acfecedded495779add4/openfisca_france/scripts/measure_performances.py) de mesure de performance.
