### ISSUE TITLE
Ajouter test de performance sur CircleCI ou autre

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1004]
Relates to #1005

Pour que l'indicateur de performance soit vraiment actionnable, il faut qu'il soit automatisable. Et cela veut dire stocker l'historique quelque part (#1003) et pouvoir le récupérer pour faire des comparaisons.

**Definition of Done :**

Automatiser le test de performance.

Soit :

- Directement sur CircleCI avec des outils built-in comme jUnit ;
- directement sur CircleCI avec des outils externes comme load impact ; ou
- avec des outils externes comme JMeter ou Locust.

_Note : si le calcul de variation des performances lui-même est trop gourmand, on ne merge pas encore._

**Liens utiles :**

- https://circleci.com/docs/2.0/collect-test-data/
- https://www.viget.com/articles/using-junit-on-circleci-2-0-with-jest-and-eslint/
- https://loadimpact.com/integrations/performance-testing-circleci/
- https://stackoverflow.com/questions/47236086/test-summary-not-populated-with-test-results-in-circleci
- https://startups-detat.slack.com/messages/C0HU81DSM
- https://support.circleci.com/hc/en-us

_Note :_

_Donnez vous un **budget de temps** pour résoudre le problème par vous-mêmes, et n'hésitez pas de demander de l'aide une fois que vous trouviez que vous tournez en cercles._

**Comment by Anna-Livia** [comment]
Le script `openfisca_france/scripts/performance_tests/test_circleci_builds.py`prend en argument les `id`de build_python2` et `build_python3`d'un workflow circle ci.
exemple :
```sh
python  openfisca_france/scripts/performance_tests/test_circleci_builds.py 2209 2208
```
Le script compare le temps d'execution de ces builds avec la moyenne des builds  réussis sur master.

Challenge 1 : Arriver à récupérer les numéro de builds dans le workflow lui-même
Challenge 2 : Que se passe t'il si un build dépasse le plafond de performance ? (warning ? post sur slack ? crash ? )
Challenge 3 : Que se passe t'il si la moyenne de comparaison n'est pas solide (pas assez de build, déviation standard trop élevée) ? (warning ? comparaison au dernier build ?)

**Comment by maukoquiroga** [comment]
> Challenge 1 : Arriver à récupérer les numéro de builds dans le workflow lui-même

👍 (si non ce n’est pas possible de le lancer programatiquement)

> Challenge 2 : Que se passe t'il si un build dépasse le plafond de performance ?

IMHO l’objetif est de nous aider à réagir vite.

Un `exit 1` va bloquer nos builds sans que l’on sache forcement comment débloquer les choses.

Un warning peut nous inciter à ouvrir la conversation.

Slack c’est une bonne idée.

Par rapport au challenge 3, via openfisca/openfisca-core#679 :

> ##### Note
> 
> I've also tried
> 
>     python openfisca_france/scripts/performance_tests/test_circleci_builds.py 1717 1716
> 
> However, there's a ~10/15s penalty per build from not test-related stuff (like having to install OpenFisca-Core from a branch), so at this level of improvement the results of that test seem a bit unreliable.

J'ai fini par ne pas utiliser ce test de performance pour savoir si la performance avait « amélioré », mais je vois un plot twist : garde-fou pour voir s'il y a eu un abaissement du temps du build *circleci* d'au moins 10%.

_Note : pour que les résultats soient plus précises, il faudrait isoler au plus possible l’execution des tests du reste des jobs. comme `pip install` par exemple_.

**Comment by Morendil** [comment]
Je ferme suite aux discussions sur #926 et IRL.
