### ISSUE TITLE
Renommer des variables peu explicites

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/openfisca-france#1009]
Certaines variables d'openfisca-france ont des noms peu explicites. 

L'objectif de cette issue est d'identifier ces variables et d'obtenir un consensus sur leur nouveau nom.

Un point qui reste à déterminer est la mise en place de ce changement.

Proposition de [@benjello](https://github.com/openfisca/openfisca-france/pull/992#discussion_r193084397) :

> "Ne pourrait-on pas ouvrir une issue où l'on recenserait les noms à modifier régulièrement et on la mentionnerait dans le guide de contribution pour que les gens suggèrent des changement de noms même quand c'est hors du scope de la PR. "

`rev_cap_lib` --> `revenus_capitaux_prelevement_liberatoire`

`rev_cap_bar` --> `revenus_capitaux_prelevement_bareme`

`retraite_titre_onereux`--> `rente_viagère_titre_onereux`

issue #808 
issue #612

**Comment by alexsegura** [comment]
Oui. Moi qui débarque, je me demandais s'il fallait utiliser des noms explicites ou des sigles obscurs 😅

Je suppose qu'il faudra conserver les deux noms, au moins jusqu'à un changement de version majeur ?

Une possibilité serait d'introduire un concept d'alias

```
"aah": {
  "description": "Allocation adulte handicapé (Individu) mensualisée",
  "alias": "allocation_adulte_handicape"
}
```

**Comment by Morendil** [comment]
Comme explicité dans [ce commentaire](https://github.com/openfisca/openfisca-france/issues/808#issuecomment-428366642) je rejoins complètement @Anna-Livia sur le fond (améliorer la lisibilité des formules en adoptant des noms de variables plus explicites), et il me semble que traiter le sujet par une issue de longue durée n'apporte pas de plus-value, car celles-ci ne sont dans les faits pas mises à jour régulièrement pour refléter les éléments nouveaux (par exemple #1027). Avec plus de 100 issues ouvertes c'est mission impossible.

Je ferme pour refléter la résolution par #1027
