### ISSUE TITLE
Utiliser ruaml.yaml ou PyYaml avec libyaml (tests)

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1016]
Relates to #926 

Quoi qu'il arrive, l'utilisation d'un parser/loader yaml écrit en C est certainement plus rapide, et nous donnera de gagnes de performance, même si modestes (à corroborer).

**Definition of done :**

Choisir entre ruaml.yaml ou PyYaml avec libyaml pour l'utiliser sur `test_runner.py`

**Tips :**

Cela va être probablement plus rapide d'implémenter ces changements que de continuer à investiguer.

**Retours d'investigations sur le sujet :**

- https://github.com/openfisca/openfisca-france/issues/1014#issuecomment-398763662
- https://github.com/openfisca/openfisca-france/issues/1014#issuecomment-398690811

@sandcha N'hésites pas à compléter

**Comment by sandcha** [comment]
@maukoquiroga Après avoir testé les deux, je serais pour `PyYaml`. Pas tant pour l'écart de performance (non remarqué) mais plus parce que [ruamel.yaml](http://yaml.readthedocs.io/en/latest/overview.html) m'a semblé manquer de documentation sur les erreurs et le fait qu'il emploie un C loader n'est pas explicite dans sa syntaxe.

Draft d'implémentation disponible sur la branche openfisca-core `yaml-fr1016` (cf. [test_runner.py](https://github.com/openfisca/openfisca-core/blob/yaml-fr1016/openfisca_core/tools/test_runner.py)).
