### ISSUE TITLE
Ajout de divers dispositifs manquants dans l'impôt sur le revenu

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#1023]
Certains dispositifs de l'impôt sur le revenu sont manquants dans Openfisca : 

- Régime du micro-bénéfice agricole (depuis 2016) cf. Issue #963 
- Crédit d'impôt pour investissements forestiers (depuis 2014) qui prend en partie le relais de la réduction d'impôt *"invfor"*
- Crédit d'impôt pour investissements dans les DOM-TOM dans le cadre d'une entreprise (depuis 2015), en complément de la réduction d'impôt *"doment"*
- Réduction d'impôt pour souscription au capital d'entreprises de presses (depuis 2016)
- Plafonnement global des niches fiscales (depuis 2009) : les paramètres sont renseignés mais ils ne sont pas utilisés

... (à compléter si nécessaire) ...

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
