### ISSUE TITLE
Variable taux_livret_a non utilisée dans aide_logement_base_ressources_patrimoine

### ISSUE THREAD

**Issue by marchand-laetitia-msa** [openfisca/openfisca-france#1035]
@guillett Bonjour,
La variable taux_livret_a n'est pas utilisée dans [aide_logement_base_ressources_patrimoine](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/aides_logement.py#L105).
Faut-il la supprimer ou la conserver et l'utiliser?

**Comment by benjello** [comment]
@marchand-laetitia-msa, @guillett :  `taux_livret_a` ne devrait-elle pas être plutôt un paramètre de la législation ?

**Comment by guillett** [comment]
@benjello, il s'agit bien d'un paramètre de la législation (cf. `taux_livret_a = parameters(period).epargne.livret_a.taux`).

@marchand-laetitia-msa effectivement cette variable peut être supprimée. Dans le calcul des ALs, le livret A est considéré comme générant des revenus à 3% et non pas au taux réel (contrairement au calcul du RSA).

**Comment by Morendil** [comment]
Ce défaut a apparemment été corrigé, je ne crois pas utile de repérer précisément par quel commit. Je ferme.
