### ISSUE TITLE
Impossible de calculer l'impôt sur le revenu avant 2002

### ISSUE THREAD

**Issue by jeremiecook** [openfisca/openfisca-france#1041]
Calculer l'impôt sur le revenu (irpp) avant 2002 génère une erreur python. La formule actuelle dépend de impot_revenu.quotient_familial.enf1, qui n'existait pas avant 2002.

Détail de l'erreur :
_File “python”, line 38, in <module>
ParameterNotFound: The parameter ‘impot_revenu.quotient_familial.enf1’ was not found in the 2000-01-01 tax and benefit system.”_

Code complet pour reproduire le problème : https://repl.it/@jeremiecook/ImpotSurLeRevenu

**Comment by benjello** [comment]
Merci @jeremiecook : si certains paramètres de la législation sont bien présents avant 2002, la législation n'a jamais été vraiment codées pour ces années là. Je dirais qu'elle est à peu près correcte à partir de 2003.

Mais on est preneur des contributeurs qui voudraient remonter dans le passé ;-) !

**Comment by Morendil** [comment]
Ce paramètre est désormais renseigné à compter du 1/1/2000 mais c'est désormais l'absence de `cotsoc.gen.smic_h_b` qui fait échouer le même calcul. On pourrait s'appuyer sur l'analyse des dépendances (cf openfisca/openfisca-core#719) à grain fin (au niveau de la formule datée) pour diagnostiquer des carences de définition de façon plus systématique.

**Comment by Morendil** [comment]
En attendant, je ne vois pas de valeur à laisser cette issue ouverte.
