### ISSUE TITLE
Fiabilisation des paramètres OpenFisca pour l'allocation de solidarité spécifique (ASS)

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1048]
Ce besoin a été remonté lors de l'analyse des cas de test pour la revalorisation de l'ASS au 1er avril 2018 suite aux écarts/différences entres les paramètres fournis par l'outil de simulation des tests MSA et les paramètres dans OF.

**Comment by guillett** [comment]
Bonjour @JenniferTelep, peux-tu enrichir cette issue pour permettre à la communauté de comprendre les limites actuelles et les objectifs que se donne la MSA. Merci.

**Comment by JenniferTelep** [comment]
Bonjour @guillett , cette issue concerne l'abattement sur le revenu de substitution.

L'article R.5423-5 du Code du travail dispose, en matière de conditions d’attribution de l’ASS :  
« Il n'est pas tenu compte, pour la détermination des ressources, des allocations de solidarité, des allocations d'assurance, des rémunérations de stage ou des revenus d'activité perçus pendant la période de référence lorsqu'il est justifié que leur perception est interrompue de manière certaine à la date de la demande et que le bénéficiaire de ces ressources ne peut prétendre à un revenu de substitution 
Lorsque le bénéficiaire peut prétendre à un revenu de substitution, un abattement de 30 % est appliqué sur la moyenne des ressources auxquelles ce revenu se substitue.»

**Comment by guillett** [comment]
Merci beaucoup. Je posais cette question car l'ASS était faussée en production depuis #899, j'ai fais une correction avec #1252 . Il serait d'ailleurs intéressant de faire un post-mortum sur ce trou dans la raquette généré par #899.

**Comment by Morendil** [comment]
A réouvrir au moment du début des travaux sur ce point.
