### ISSUE TITLE
Revalorisation des plafonds de ressources de l'ASPA au 01/04/2018

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1051]
Les barèmes pour l'allocation de solidarité aux personnes âgées sont revalorisés au 1er avril 2018.

**Comment by claireleroy** [comment]
Dans la PR #1066 j'introduis cette revalorisation, si quelqu'un veut y jeter un coup d'oeil !

**Comment by benjello** [comment]
cc @guillett
