### ISSUE TITLE
auto-cancel redundant CI builds

### ISSUE THREAD

**Issue by magopian** [openfisca/openfisca-france#1055]
There's a setting that can be [set on CircleCI](https://circleci.com/docs/2.0/skip-build/#auto-cancelling-a-redundant-build) to automatically cancel redundant builds (eg pushing several times to the same branch, before the previous builds were finished).

This might (or might no) be desirable. It saves some CPU power (and thus saves the planet and polar bears). The drawbacks seem minimal (not having a complete build on a previous version of the branch).

**Comment by magopian** [comment]
There are situations were the builds clearly feel useless, and even sometimes annoying, because they delay the useful ones:
- a typo fix
- a bad commit (forgot to add a file to the git index, typo in the commit message...)
- a CI configuration change

I'm sure there's more, and each time it's the same scenario:
1/ let me commit this so we see what the CI has to say
2/ oh no, I did one of the above mistakes, let's just quickly fix it and re-push
3/ oh, ok, I now have to wait for the current builds to end, even though I know they will fail: loss of time and CPU and energy

It's not a big deal at all, and if it's not doable (I know in Travis you can manually cancel a build, and new builds can replace current ones), then let's not sweat it and close this issue ;)

**Comment by MattiSG** [comment]
We can definitely cancel builds manually.

I agree with your theoretical observations, but I personally haven't been frustrated by those on OpenFisca in real situations :wink:

I'll close this until someone gets pissed and requests that we investigate more on balancing usage of workflows with waiting for builds 🙂

**Comment by magopian** [comment]
Yeah, I found out (later) that you can manually cancel a build, but not on the build page itself (didn't find a link or way to do it), but rather on the circleCI page that list the builds for a given branch/PR/tag (you can access it via the breadcrumbs for example, by going "one up").

On this page you'll see a `cancel` link 👍
