### ISSUE TITLE
CI is not running the formatting check

### ISSUE THREAD

**Issue by magopian** [openfisca/openfisca-france#1057]
This follows up on the issue #1054 and "completes" the PR #1056 .

There's a `make flake8` check in the Makefile, but it's not run in the CI. Running it shows hundreds of errors and warnings.

Those could be fixed (partially?) in bulk by using [autopep8](https://github.com/hhatto/autopep8), or even better, [black](https://github.com/ambv/black) (which isn't fully compatible with flake8, and will need a specific flake8 config ignoring some errors and issues).

Currently, running `black --check` returns:

```
126 files would be reformatted, 31 files would be left unchanged.
```

**Comment by Morendil** [comment]
Voir aussi #1114, #372

**Comment by Morendil** [comment]
Corrigé par #1135
