### ISSUE TITLE
Supprimer la variable activite

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1067]
La variable activité est ambiguë et peu informative.
Elle est donc très peu utilisée et peut être facilement remplacée par d'autres conditions.
Je pense qu'il faut la supprimer à terme.

cc @guillett  @openfisca/france-msa @bfabre01 @claireleroy

**Comment by benjello** [comment]
Le but est de 
- soit mieux définir cette variable: 
  - que faire alors de présence de plusieurs sources de revenus ?
  - a-t-on assez de modalités pour satisfaire les besoins ?   
  - collision possible avec données d'enquêtes ?
- soit de la supprimer du système socio-fiscal pour coller aux définitions retenues dans les prestations 
  - option qui à ma préférence

Elle intervient dans:
 - la [prime de solidarité active](https://github.com/openfisca/openfisca-france/blob/9db5c10a28c2d3db0ef1d6179a0d51c3740b4ff7/openfisca_france/model/prestations/minima_sociaux/anciens_ms.py#L123)
 - le [rmi](https://github.com/openfisca/openfisca-france/blob/9db5c10a28c2d3db0ef1d6179a0d51c3740b4ff7/openfisca_france/model/prestations/minima_sociaux/anciens_ms.py#L123)
 - [l'aide_logement_abattement_depart_retraite](https://github.com/openfisca/openfisca-france/blob/37ac36752c8379b99112252389485684f1f4e0c1/openfisca_france/model/prestations/aides_logement.py#L296)
 - [l'ass](
        openfisca-france/openfisca_france/model/prestations/minima_sociaux/ass.py
      )
 - [la cmu](
        openfisca-france/openfisca_france/model/prestations/minima_sociaux/cmu.py
      ) 

@guillet : aurais-tu des éléments qui permettrait de caractériser le statut d'actif ou de chômeur pour ces différentes prestations ?

**Comment by Morendil** [comment]
Voir aussi #1269.

**Comment by JenniferTelep** [comment]
Bonjour @morendil, @benjello,
Apparemment les travaux de cette issue bloque la validation de la PR #1269.
Serait-il possible de faire valider notre PR sans adhérence avec les travaux de cette issue? En effet nos travaux sur la PR doivent être terminés dans les prochains jours pour respecter nos jalons.

Pour info : @ThibaultCCMSA , @jmdallais, @LacombeEric, @frtomas , @mtifarine

**Comment by benjello** [comment]
Tant que la variable `activite`n' a pas été supprimée pourquoi pas mais j pense que l'on gagnerait à définir expressément la qualité de chômeur dont il est question.

**Comment by Morendil** [comment]
Bonjour @JenniferTelep 

Pour moi il n'y a pas particulièrement d'adhérence entre #1269 et cette issue. Les points qui faisaient obstacle pour merger #1269 étaient
- le manque de certains tests permettant de caractériser la différence de comportement avant/après la correction apportée par @mtifarine ; ce point a été traité
- le risque d'occasionner des régressions pour Mes Aides par l'introduction de la variable `date_debut_chomage` ; ce point est en cours d'investigation, et il serait peut-être utile d'échanger de vive voix à ce sujet

D'ailleurs plus généralement il me semble que nous avons un besoin mutuel de visibilité sur les prochaines étapes, j'ai noté que @monbocal souhaitait des informations sur #1118, un point téléphonique nous permettrait peut-être d'avancer plus rapidement sur plusieurs sujets.

(Pour revenir à la variable `activite`, j'avais noté ici un lien entre les deux sujets car il semble utile se préoccuper de la cohérence entre les variables `activite` et `date_debut_chomage` (parmi d'autres), et de prendre des décisions judicieuses sur la façon dont nous souhaitons modéliser plus globalement la notion d'activité. Par exemple le nom et la nature de la variable `date_debut_chomage` présupposent que nous ne modéliserons jamais des périodes de chômage multiples, cette décision peut être tout à fait légitime d'un point de vue métier, et il est important de la rendre explicite si c'est bien celle qu'on souhaite entériner. Et c'est plus un sujet de fond, qui ne doit pas forcément bloquer les travaux en cours.)

**Comment by Morendil** [comment]
Je ferme faute d'un plan d'action suffisamment précis pour ce qui serait un "breaking change".

J'ai l'impression qu'on pourrait remplir ce besoin plutôt dans Core en introduisant des "énumérées non exclusives" - des variables qui correspondraient à un ensemble de checkbox plutôt qu'à un bouton radio, pour parler en langage IHM, ou encore à des "bitmask" pour parler implémentation. Le principal reproche fait à cette variable est qu'elle implique des choix mutuellement exclusifs alors que ce n'est pas le cas. A contrario elle a l'avantage de regrouper ces choix sous un nom unique et donc de montrer que ces valeurs sont apparentées et non totalement indépendantes.
