### ISSUE TITLE
Allocation de base PAJE

### ISSUE THREAD

**Issue by jdesboeufs** [openfisca/openfisca-france#107]
Les modalités de calcul de la PAJE pour les enfants nés après le 1er avril 2014 ont été changées.

Il faudra s'organiser pour corriger ça.

[Ceci est un reminder]

**Comment by jdesboeufs** [comment]
Chantier encore à venir, probablement pour fin avril / mai.

**Comment by benjello** [comment]
@jdesboeufs done ? ;-)

**Comment by MattiSG** [comment]
Assignee : @fpagnoux. Probablement en attente dans #306.

**Comment by MattiSG** [comment]
Fait dans #244 et #306.
