### ISSUE TITLE
Gérer le décalage temporel entre revenus du patrimoine et de placement

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1071]
L'application des nouveaux taux de prélèvements sociaux sur revenus du capital s'appliquent à partir des revenus du patrimoine de 2017, et des revenus de placement 2018. En revanche pour les revenus du patrimoine, le changement de CSG déductible ne se fait que pour les revenus 2018.
Références législatives:
II.B de l'art. 67 de loi 2017-1837 et 3° et 4° du V.A de l'art. 8 de loi 2017-1836
OpenFisca pour le moment ne considère pas des taux différents pour revenus du patrimoine et revenus de placement. Introduire cette différenciation pour pouvoir avoir ce décalage.
Il existe peut-être d'autres décalages de ce type, comme le passage de la CSG de 7,5% à 8,2% qui selon les barèmes IPP est en 2004 pour les revenus du patrimoine et en 2005 pour les revenus de placement.
Pour le moment, on fait passer le taux de CSG à 9,9% à partir de 2017, et le taux déductible à 6,8% à partir de 2018, pour tous les revenus du capital.

**Comment by benjello** [comment]
Il y a deux stratégies:
 - créer des paramètres spécifiques aux différents revenus
   - pour: plus explicite
   - contre: très redondant, plus long à mettre en oeuvre (création de nouveaux fichiers etc) 
 - utiliser la variable period pour gérer les décalages temporels
   - pour: moins redondant, facile à mettre en oeuvre
   - contre: l'explicitation est dans le code qui devient plus touffu et donc moins lisible

Un point qui pourrait aider à trancher et que @bfabre01 pourrait éclairer est le suivant: comment est-ce indiqué dans la législation: y a-t-il explicitement une séparation entre les deux taux ou juste un décalage temporel ?

**Comment by bfabre01** [comment]
@benjello : actuellement, il n'y a qu'un seul taux de CSG totale ([ici](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006173099&cidTexte=LEGITEXT000006073189)) et CSG non-déductible ([ici](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=69D54FF98FD1D7099AD2BB7025B54683.tplgfr28s_2?idArticle=LEGIARTI000037075063&cidTexte=LEGITEXT000006069577&categorieLien=id&dateTexte=20180901)) dans les textes. Il est juste préciser que ces deux taux s'appliquent aux deux bases fiscales que sont les revenus du patrimoine (définis [ici](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006173130&cidTexte=LEGITEXT000006073189)), et les revenus de placement (définis [ici](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006173129&cidTexte=LEGITEXT000006073189)). Le décalage temporel est mentionné dans des textes à parts (qui sont ceux mentionnés au début de l'issue).

@benjello : en effet, s'il s'avère que cette structure des textes est la même depuis la 1ère année de simulation, autant opter pour ta 2ème solution.

Dans la pull request #1065 (version `22.8.0`), j'applique le timing des revenus du patrimoine, car c'est ce choix qui avait été fait dans les versions précédentes. Mais pour la flat tax (pull request #1075), on compte dans un premier temps faire l'hypothèse que tous les taux changent pour les revenus 2018, et résoudre l'issue dans un second temps.

**Comment by bfabre01** [comment]
Autre commentaire : le taux sur les plus-values professionnelles passe à 12,8% au titre de la loi de finances 2018 non pas à partir des plus-values 2018, mais des plus-values 2017 déclarées en 2018. Ce timing est bien pris en compte dans OpenFisca, où le taux `parameters(period).impot_revenu.plus_values.pvce` appliqué à `rpns_pvce` change bien en 2017. Mais du coup, peut-être approfondir davantage la question du timing du changement des taux pour les plus-values en général. Actuellement, on a gardé ce paramètre. Puis, à partir de 2018, on ne le neutralise pas mais on utilise à la place `parameters(period).impot_revenu.prelevement_forfaitaire_unique_ir.taux`.

**Comment by Morendil** [comment]
@bfabre01 @benjello Je n'ai pas du tout d'inspiration sur ce qu'on pourrait faire sur cette issue; OK pour fermer ? Sinon, comment voulez-vous avancer ?

**Comment by bfabre01** [comment]
@Morendil : ok pour fermer. Cette issue n'est pas une priorité. En plus, nous allons avoir normalement de nouvelles données sur les revenus du capital prochainement. Cela serait donc plus optimal (pour nous en tout cas) de revoir ce point une fois ces données obtenus.
