### ISSUE TITLE
Erreurs obscures retournées par OpenFisca

### ISSUE THREAD

**Issue by Alpam** [openfisca/openfisca-france#1076]
Bonjour,

Je travaille actuellement sur un microservice utilisant OpenFisca-France (vraisemblablement la dernière version disponible via pip).
Nous voulons faire en sorte à proposer un regard exhaustif sur les aides françaises ; nous voulons faire calculer l'intégralité des arguments calculables par OpenFisca (même si, nous le savons, beaucoup de champs resterons à leur valeur par défaut).
Dans ce sens lors de mes tests (sur un serveur local non modifié d'OpenFisca France) j'envoie un Json à OpenFisca, auquel j'ajoute tous les arguments calculables set à Null pour la période voulue. 
(ces champs ont été récupérés via http://locahost:6000/variable/)
Comme vous vous en doutez si je suis venu poster ici c'est que j'ai rencontré certains problèmes avec un bon nombre d'arguments.
Voici la liste des erreurs que j'ai rencontré avec les arguments les déclenchant:

_"error": "Internal server error: formula() takes exactly 4 arguments (3 given)":_
ppa_base_ressources_prestations_familiales
ppa_bonification
ppa_ressources_hors_activite_individu
ppa_revenu_activite_individu

_"error": "Internal server error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()":_
apa_domicile
apa_domicile_participation
apa_domicile_taux_participation
apa_etablissement

_"error": "Internal server error: global name 'autonomie' is not defined"_
apa_urgence_domicile

_"error": "Internal server error: global name 'periop' is not defined"_
check_csg

_"error": "Internal server error: 'function' object has no attribute 'apa_institution'"_
apa_urgence_institution

_"error": "Internal server error: Unable to compute variable 'apprenti' for period 2018: 'apprenti' must be computed for a whole month. You can use the ADD option to sum 'apprenti' over the requested period, or change the requested period to 'period.first_month'."_
prime_apprentissage

_"error": "Internal server error: You tried to compute the variable 'ass' for the entity 'individus'; however the variable 'ass' is defined for 'familles'."_
professionnalisation
remuneration_professionnalisation

_"error": "Internal server error: Unable to compute variable 'cotisations_employeur_contributives' for period 2018: 'cotisations_employeur_contributives' must be computed for a whole month. You can use the ADD option to sum 'cotisations_employeur_contributives' over the requested period, or change the requested period to 'period.first_month'."_
revenu_initial_individu
niveau_de_vie_initial

_"error": "Internal server error: Unable to compute variable 'tns_micro_entreprise_benefice' for period 2018-08: 'tns_micro_entreprise_benefice' must be computed for a whole year. You can use the DIVIDE option to get an estimate of tns_micro_entreprise_benefice by dividing the yearly value by 12, or change the requested period to 'period.this_year'."_
tns_micro_entreprise_revenus_net

_"error": "Internal server error: Unable to compute variable 'revenus_capitaux_prelevement_bareme' for period 2018: 'revenus_capitaux_prelevement_bareme' must be computed for a whole month. You can use the ADD option to sum 'revenus_capitaux_prelevement_bareme' over the requested period, or change the requested period to 'period.first_month'."_
csg_deduc_patrimoine_simulated

_"error": "Internal server error: NumPy boolean array indexing assignment cannot assign 2 input values to the 1 output values where the mask is true"_
revenu_disponible
taxe_habitation
type_menage
impots_directs
cheque_energie
cheque_energie_montant
exonere_taxe_habitation
niveau_de_vie

_"error": "Internal server error: Unable to compute variable 'cotisations_employeur_contributives' for period 2018: 'cotisations_employeur_contributives' must be computed for a whole month. You can use the ADD option to sum 'cotisations_employeur_contributives' over the requested period, or change the requested period to 'period.first_month'."_
revenu_initial

"error": "Internal server error: You tried to compute the variable 'revenus_du_travail' for the entity 'menages'; however the variable 'revenus_du_travail' is defined for 'individus'."
revenu_primaire

Ps : voici le Json utilisé sans les 600 et quelques arguments ajoutés
`{
	"foyers_fiscaux":{
        "f_f1":{
            "declarants":["Ricarda","Bill"],
            "personnes_a_charge":["Janet"]
        }
    },
    "familles":{
        "f1":{
            "parents":["Ricarda","Bill"],
            "enfants":["Janet"]
        }
    },
    "individus":{ 
        "Ricarda": {},
        "Bill": {},
        "Janet": {}
    },
    "menages":{
        "m1":{
            "personne_de_reference": ["Ricarda","Bill"],
            "enfants":["Janet"]
        }
    }
}`

J'ajouterais également que tous les autres arguments ne génèrent aucune erreur avec ce Json.
Et question bonus : avez vous une idée de ce qui déclenche ces erreurs et comment les corriger ?

**Comment by fpagnoux** [comment]
Bonjour @Alpam,

Merci d'utiliser OpenFisca et d'avoir pris le temps de nous contacter!

Calculer toutes les variables est une démarche inhabituelle... Mais on dirait que ça a permis d'identifier un certain nombre de bugs dans la législation!

Vu que ce sont des "Internal server error", il n'y a hélas probablement pas grand chose à faire côté client. Nous allons de notre côté enquêter sur les bugs reportés individuellement (cc @benjello)

Une remarque générale: OpenFisca-France est une modélisation du système socio-fiscal français maintenu par de multiples acteurs, qui couvre de multiples aspects de la législation. Parfois certains blocs sont ajoutées sans doute un peu trop tôt, sans être suffisamment testés, et des bugs peuvent subsister. D'autres sections (notamment les aides sociales) sont utilisées par des sites en production et testées minutieusement.

**Comment by benjello** [comment]
@fpagnoux @Alpam : réponse rapide avant plus d'investigation.
Certaines variables erronées et obsolètes ont été virées récemment.
S'il est possible de régénérer l'output, cela me permettra de me concentrer sur les erreurs qui restent.
Et si l'on pouvait avoir un test équivalent en python, cela nous permettrait de détecter ces erreurs à l'avenir ...

**Comment by Alpam** [comment]
@fpagnoux @benjello 
Bonjour,
Etant donné que la fondation Crésus, via Crésus Lab, a besoin d'OpenFisca France j'ai voulut y contribué en consacrant quelques heures pour vous sortir une petite fonction python (compatible avec Python2 et 3) qui permet de tester toutes les variables calculables en envoyant un json minimaliste (celui que j'ai mis dans mon premier poste avec la variable testée).
J'ai fais le teste sur ma machine et je ressort une liste un peu plus longue de variables qui provoquent une erreur. J'ai l'impression que certaine n'apprécie pas d'être calculée sans en calculer certaines autres.
Voici le script :
```
import requests
import json
import sys

def test_calculables_variables(url,year,month):
    rep_all_v = requests.get(url+'/variables')
    variables = rep_all_v.json()
    
    p_month = month
    p_year  = year
    p_eternity = "ETERNITY"

    json_err = {}
    
    nb_var = len(list(variables.keys()))
    print('have to test : '+str(nb_var)+' variables')
    i=1
    for variable in variables.keys():
        sys.stdout.write('                                                                                               \r')
        sys.stdout.flush()
        sys.stdout.write('  '+str(i)+'/'+str(nb_var)+' :: '+variable+'\r')
        sys.stdout.flush()

        i=i+1
        to_send={"foyers_fiscaux":{
                        "f_f1":{
                            "declarants":["Ricarda","Bill"],
                            "personnes_a_charge":["Janet"]
                        }
                    },
                    "familles":{
                        "f1":{
                            "parents":["Ricarda","Bill"],
                            "enfants":["Janet"]
                        }
                    },
                    "individus":{
                        "Ricarda":{},
                        "Bill": {},
                        "Janet": {}
                    },
                    "menages":{
                        "m1":{
                            "personne_de_reference": ["Ricarda","Bill"],
                            "enfants":["Janet"]
                        }
                    }
                }
        rep_var = requests.get(url+'/variable/'+variable)
        focus = rep_var.json()
        var_cal = {}
        try :
            focus['formulas']
            if focus['definitionPeriod']=='YEAR':
                var_cal[p_year]=None
            elif focus['definitionPeriod']=='MONTH':
                var_cal[p_month]=None
            elif focus['definitionPeriod']=='ETERNITY':
                var_cal[p_eternity]=None
            else:
                print('deinitionPeriod unknow, critical error')
                return
            if focus['entity']=='individu':
                for ind in to_send['individus'].keys():
                    to_send['individus'][ind][variable]=var_cal
            elif focus['entity']=='famille':
                to_send['familles']['f1'][variable]=var_cal
            elif focus['entity']=='foyer_fiscal':
                to_send['foyers_fiscaux']['f_f1'][variable]=var_cal
            elif focus['entity']=='menage':
                to_send['menages']['m1'][variable]=var_cal
            else:
                print('entity unknow, critical error')
                return
            rep_focus = requests.post(url+'/calculate',json=to_send)
            focus = rep_focus.json()
        except KeyError:
            continue
        try:
            focus['error'] 
        except KeyError:
            continue
        try:
            json_err[focus['error']].append(variable)
            continue
        except KeyError:
            json_err[focus['error']]=list()
            json_err[focus['error']].append(variable)
            continue
    f = open('rapport_err.log','w')
    f.write(json.dumps(json_err, indent=4))
    f.close()
    print(json.dumps(json_err, indent=4))
    return

if __name__ == '__main__':
    y="2018"
    m="2018-08"
    test_calculables_variables('http://localhost:6000',y,m)
```

**Comment by guillett** [comment]
Bonjour @Alpam et merci d'avoir ajouté du contexte à cet issue. Je pense que [le code](https://github.com/betagouv/mes-aides-ui) de [Mes Aides](https://mes-aides.gouv.fr/) pourrait vous intéresser pour connaitre les variables à définir pour le calcul de certaines prestations.

Je vous envoie un mail avec mes coordonnées pour échanger par téléphone si vous voulez.

**Comment by benjello** [comment]
@Alpam je vais regarder les problèmes que vous soulevez mais ce ne sera pas avant  quelques jours.

**Comment by guillett** [comment]
@Alpam, je partage ici les liens échangés par email.


Ce qui est envoyé à OpenFisca
https://mes-aides.gouv.fr/api/situations/5b7d5e291da8e46cd19d7dae/openfisca-request

Ce qui est renvoyé par OpenFisca
https://mes-aides.gouv.fr/api/situations/5b7d5e291da8e46cd19d7dae/openfisca-response

Un outil que détaille les étapes de calculs
https://mes-aides.gouv.fr/trace?situationId=5b7d5e291da8e46cd19d7dae
mes-aides.gouv.fr/api/situations/5b7d5e291da8e46cd19d7dae


Avec ces informations, avez-vous encore des blocages ?

**Comment by benjello** [comment]
@Alpam : je vois que @guillett vous a fourni une réponse. Je vais donc m'abstenir sauf relance de votre part.

**Comment by Alpam** [comment]
Bonjour,

@benjello Je vous remercie, j'avoue que je n'avais pas vraiment de questions et que c'était plus à titre d'information que je partageais ce rapport d'erreurs.

@guillett j'ai finis de mettre en place mon mappage et l'écriture d'un petit scripte qui permet de trouver l'intégralité des variables non calculables nécessaires au calcule d'une variable calculable. Pour faire plus simple je vous transmet un dépôt avec mes scriptes : https://github.com/Alpam/openfisca_helper

**Comment by guillett** [comment]
Merci beaucoup pour ce rapport d'erreur. J'espèque que nos échanges vous ont aidé.
