### ISSUE TITLE
Corriger la mesure des plus-values dans le revenu fiscal de référence

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1080]
Les abattements sur plus-values (ou du moins certains) ne sont pas pris en compte pour le revenu fiscal de référence. Cf. par exemple [https://www3.impots.gouv.fr/simulateur/calcul_impot/2018/aides/gains.htm](https://www3.impots.gouv.fr/simulateur/calcul_impot/2018/aides/gains.htm).
Or, ceci n'est pas pris en compte apparemment dans OpenFisca.
Par exemple, la case `3VG` en 2017 est prise en compte dans `rfr` via la variable `rev_cat` (`f3vg` -> `rev_cat_pv` -> `rev_cat` -> `rbg` -> `rng` -> `rni` -> `rfr`). Mais il s'agit du montant net, après application des abattements.

**Comment by aguillouzouic** [comment]
En fait @bfabre01 les abattements étaient déjà pris en compte dans le RFR via la variable désormais renommée abattements_plus_values (anciennement nommée abattements_duree_detention_retraite_dirigeants_pme).

**Comment by claireleroy** [comment]
Etant donné la solution proposée par @aguillouzouic dans #1190, je pense qu'on peut fermer.
