### ISSUE TITLE
Adapter le code aux formulaires d'impôt sur le revenu 2019

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1083]
Le code de la flat tax (prélèvement forfaitaire unique) mis dans place dans la PR #1075 suppose que les formulaires 2042 et 2042C de l'impôt 2019 sur les revenus 2018 sont identiques à ceux de l'impôt 2018 sur revenus 2017. Lorsque les nouveaux formulaires seront publiés, adapter le code.

Voici les hypothèse que l'on a faites en attendant les nouveaux formulaires:
- Structure identique des cases des formulaires entre l'impôt sur le revenu (IR) 2018 sur revenus 2017 et IR 2019 sur revenus 2018. Un exemple d'implication : les revenus des PEL ouverts en 2018 sont tous soumis au PFU, contrairement à avant où ils l'étaient à partir de 12 ans d'ancienneté. Pour les PEL ouverts à partir de 2018, on crée donc une nouvelle variables, pour les plans de moins de 12 ans, car ceux de plus de 12 ans sont déjà déclarés en 2TR ou 2FA dans le formulaire de l'IR 2018.
- Pour les assurances-vie, cette hypothèse de structure constante des cases n'est pas directement applicable car les catégories de différenciation de ces produits d'un point de vue fiscal a lourdement changé avec le PFU, et donc, le formulaire de l'IR 2018 est forcément obsolète. Dans ce formulaire, les produits d'assurance-vie soumis à IR sont déclarés soit en case 2DH, 2EE, 2CH ou 2TS. On ne veux pas supprimer les variables associées à ces cases (`f2dh`, `f2ee`, `f2ch` ou `f2ts`) pour éviter les erreurs de calcul (ces variables pouvant être utilisées à différents endroits du simulateur). Les nouvelles variables d'assurance-vie sont définies dans `model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique`, et le montant de ces variables est injecté dans `f2dh` et `f2ee`, les variables `f2ch` et `f2ts` étant elles neutralisées à partir de 2018 (cf. code pour le détail).
- On neutralise à partir de 2018 les variables d'acomptes de l'impôt sur le revenu. L'imposition au titre de ces revenus n'ayant toujours pas eu lieu, garder des variables d'acompte n'a pas trop de sens. Il s'agit des variables `acompte_ir_elus_locaux`, `prelevement_forfaitaire_non_liberatoire` et `acomptes_ir`. En revanche, lorsqu'on aura les formulaires 2019, avec les cases d'acomptes actualisées, il faudra les ajouter.
- On sort de la variable `irpp` toute imposition forfaitaire au titre des revenus du capital. Techniquement, ceci est associé au fait que `tax_rvcm_forfaitaire` et `taxation_plus_values_hors_bareme` sont neutralisées à partir de 2018, et que `prelevement_forfaitaire_unique_ir` n'est pas incluse dans `irpp`. Normalement, `irpp` correspond à l'impôt tel que calculé par le simulateur de la DGFiP, qui correspond à une notion d'impôt plus administrative qu'économique. L'inclusion ou non d'une imposition hors barème dans cette notion administrative d'impôt n'est pas systématique. On ne sait pas encore quelle sera cette notion administrative de l'IR 2019 calculé sur le simulateur, et on fait ce choix de l'exclusion de  `prelevement_forfaitaire_unique_ir` en attendant.
- On a neutralisé `prlire`, plus par hypothèse, en attendant d'avoir les nouveaux documents officiels des impôts. Avant 2018. l'abattement de 4600 euros est appliqué à 2CH (imposé au barème), et l'éventuel reliquat pouvait être réinjecté dans 2DH (revenus au prélèvement forfaitaire libératoire). Mais maintenant, tous les revenus d'assurance-vie sortent du barème, et sont apparemment éligibles à l'abattement. Donc, on applique à tous les revenus d'assurance-vie les abattements, et on n'a plus besoin de ce crédit d'impôt. Mais peut-être à vérifier via les nouveaux formulaires et nouvelles notices.
- On n'a pas modéliser le choix entre prélèvement forfaitaire unique (PFU) et imposition au barème. En général, les cases sont directement associées à ce choix, car elles distinguent les revenus de ces deux types d'imposition. Ceci veut dire qu'il faudra coder en plus l'inclusion possible au barème des revenus du capital (actuellement hypothèse : les revenus du capital ne sont plus dans la variable `rni`, ce qui explique la neutrelisation de certaines variables comme `rev_cat_pv` `rev_cat_rvcm` `rfr_rvcm`.

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser), dans la mesure où cette issue ne peut pas avancer avant le début de la campagne fiscale. (Avons-nous un accès particulier à ces formulaires, en avance du grand public ?)
