### ISSUE TITLE
Doutes sur fiscalité assurance-vie

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1084]
Plusieurs doutes/limites concernant le code de la variable `prelevement_forfaitaire_unique_ir_sur_assurance_vie` :
1. On applique l'abattement de 4600 (9200 euros) séparément à chaque variable éligible à cet abattement. On aurait pu l'appliquer à la somme de ces variables. Comment l'abattement est-il appliqué en pratique ?
2. Seuil de 150 000 euros (`parameters(period).impot_revenu.prelevement_forfaitaire_unique_ir.seuil_taux_reduit_av`) : il s'agirait des "revenus au titre des primes inférieures versus supérieures à 150 000 euros". Qu'est-ce que cela signifie exactement ? Et comment le taux réduit associé à ce seuil (`parameters(period).impot_revenu.prelevement_forfaitaire_unique_ir.taux_reduit_av`) est-il appliqué ? De plus, ce seuil est-il appliqué aux montants avant ou après abattements ?

**Comment by pbourdu** [comment]
Bonjour @bfabre01, il convient d'appliquer l'abattement de 9200/4600  à la somme des variables éligible à l'abattement pour une même période d'imposition.

**Comment by Morendil** [comment]
Merci @pbourdu !

@bfabre01 tu as assez d'éléments pour ouvrir une PR ?

J'ai jeté un oeil sur cette implémentation du PFU et j'avoue ne pas tout comprendre, par exemple comment obtient-on des données d'entrées pour les variables comme `assurance_vie_pfu_ir_plus8ans_1990_19970926` ?

**Comment by bfabre01** [comment]
@pbourdu: merci pour ta réponse (et désolé pour le retard). Je viens d'ouvrir une PR qui fait la correction (#1279 ).

**Comment by bfabre01** [comment]
@Morendil : pour le moment, on n'a pas de données en input aussi précises que la décomposition de ces variables d'assurance-vie. Mais on espère bien les avoir un jour. Pour le moment, j'ai préféré donner le détail de l'ensemble des contrats d'assurance-vie, en guise de précis de législation. Pour que les choses soient plus claires.
