### ISSUE TITLE
Ajouter le seuil de non-assujettissement dans le barème de la cotisation exceptionnelle de solidarite

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1087]
Il devrait être possible de rajouter [le seuil](https://github.com/openfisca/openfisca-france/blob/62d77a9effdcf1cef92dc72ff17d7ab56c88f3f2/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py#L81) dans le barème au moins pour l'inversion.

**Comment by Morendil** [comment]
Corrigée par #1097
