### ISSUE TITLE
Améliorer les taux de primes

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1089]
Pour calculer les traitement brutes des fonctionnaire à partir de leur salaire brut, il est nécessaire d'avoir un taux de primes. Celui-ci est fixée à 19.5 % qui est une valeur trop ancienne.

Or il n'est pas homogène sur toute le fonction publique. 

Il serait utile d'utiliser les rapports sur la rémunération des fonctionnaires ([exemple](https://www.fonction-publique.gouv.fr/files/files/statistiques/rapports_annuels/2017/Rapport_annuel-FP_2017.pdf) pour affiner cela.

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
