### ISSUE TITLE
Complément Familial Avril 2014

### ISSUE THREAD

**Issue by jdesboeufs** [openfisca/openfisca-france#109]
Le barème du Complément Familial a été mis à jour au 1er avril 2014.

Par ailleurs en décembre 2013 a été créé le Complément Familial Majoré pour les familles vivant sous le seuil de pauvreté. Son barème a même été réévalué le 23 avril 2014.
À vue de nez, le Complément Majoré n'existe pas encore dans OpenFisca.

**Comment by benjello** [comment]
@jdesboeufs  @nanocom  Can I close this ?

**Comment by jdesboeufs** [comment]
Bientôt ;)

**Comment by jdesboeufs** [comment]
Je suis dessus.
