### ISSUE TITLE
Ajouter un script pour automatiser les revalorisations

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#1095]
L'article [L161-25 du CSS](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006741258&dateTexte=&categorieLien=cid) est à l'origine de nombreuses revalorisations.

Il serait intéressant d'avoir:
- un paramètre de la législation qui suit le coefficient de revalorisation
- un script qui modifie les bons fichiers de paramètres
- un script qui génère le décret de revalorisation.

**Comment by benjello** [comment]
Le problème est que parfois cette revalorisation est gelée.
Et puis il peut y avoir des problèmes d'arrondi et on aura des paramètres qui ne seront pas exactement égaux à ceux publiés.
Mais je suis d'accord que faire la liste des paramètres pour les mettre à jour même temporairement (il est facile de rajouter un champ aux fichiers yaml des paramètres) avant leur publication officielle ce serait super. 
@guillett : j'ai fait un [inflateur de législation pour les PLF](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/utils.py#L52) qui peut peut-être t'intéresser.

**Comment by guillett** [comment]
Merci @benjello, j'avais bien en tête ton souhait de prendre en compte l'inflation pour faire évoluer la législation future.

Je me dis qu'un tel script/module pourrait aussi outiller le législateur (exhaustivité du périmètre de la revalorisation) surtout quand je vois https://www.legifrance.gouv.fr/eli/decret/2016/4/1/AFSS1605622D/jo/article_3

**Comment by guillett** [comment]
@benjello tu parles de problèmes d'arrondi mais cela te parait-il raisonnable sur des calculs aussi simples que des revalorisations ?

**Comment by benjello** [comment]
@guillett : Ce que je veux dire c'est que souvent la règle de revalorisation n'est pas unique c'est on inflate avec tel coefficient et on arrondit au centimes/euros le plus proche/(immédiatement supérieur/inférieur).
D'où des erreurs d'arrondi.
Après on peut spécifier les règles de revalorisation dans les paramètres etc.

Mais bon, un inflateur sera toujours une très bonne approximation.

**Comment by Morendil** [comment]
C'est une bonne idée, et je ne pense pas que notre lien avec les usagers dans la catégorie "Législateur" nous permette de nous lancer dans une implémentation à court terme; je vais fermer cette issue qui me semble en dehors de notre modèle actuel d'exécution, en prévoyant de reprendre la réflexion quant on se sera rapprochés de ces persona.
