### ISSUE TITLE
Gérer l'hétérogénéité d'imposition des produits d'assurance-vie

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1096]
Pour les années avant 2018, renseigner directement les variables `f2ee` et `f2dh` entraîne une valeur nulle de `prelevement_forfaitaire_liberatoire`. Cet impôt est calculé via les variables commençant par `assurance_vie`. Et le montant de ces variables est injecté dans `f2ee` ou `f2dh`. Justification : une même case peut contenir des revenus taxés à des taux différents (c'est le cas de la case `f2ee` mais pas de `f2dh`). Mais renseigner directement  `f2ee` ou `f2dh` sans renseigner les variables commençant par `assurance_vie` entraîne  `prelevement_forfaitaire_forfaitaire` = 0. Que faire par rapport à ça ? Coder de telle sorte que si AUCUNE variables commençant par `assurance_vie` n'est renseignée, un taux par défaut s'applique ?

La même logique est adopée pour le prélèvement forfaitaire unique.

**Comment by Morendil** [comment]
@bfabre01 je ne sais pas quoi faire non plus :) et pas bien certain d'avoir compris le problème. On ferme? Sinon je veux bien que tu détailles ce qui ne vas pas actuellement et vers quoi aller.

**Comment by bfabre01** [comment]
@Morendil : Idem que pour #1071 . On peut fermer. Ça n'est pour nous pas une priorité pour le moment.
