### ISSUE TITLE
Revoir les variables de revenus fonciers

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1102]
Revoir les mesures des revenus fonciers:
- Gérer la présence conjointe de la variable revenus_locatifs et des revenus fonciers fiscaux. Pour le calcul des minima sociaux, les revenus fonciers sont pris en compte dans la variable `revenus_locatifs`, qui n'a pas de formule. En parallèle existent les revenus fonciers fiscaux. Si les revenus fonciers fiscaux ne sont pas renseignés, la valeur de `revenus_locatifs` y est injectée. Mais dans le sens inverse, cela ne peut pas se faire. Autrement dit, si l'on a des revenus fonciers fiscaux déclarés, mais `revenus_locatifs` = 0, les revenus fonciers ne vont pas être pris en compte dans les minima sociaux. Revoir cette articulation ?
- S'assurer que l'on a bien les bons concepts de revenus fonciers dans les différents dispositifs, notamment les bases ressources. De ce point de vue, deux pistes:
    - Mutualiser davantage les variables ? Par exemple, pour les prestations familiales, il s'agit des revenus catégoriels. Donc, pourquoi ne pas utiliser `rev_cat_rfon` ?
    - A partir des cases de la déclaration de revenus, définir un concept de revenus fonciers correspondant au concept adapté aux minima sociaux. Par exemple, doit-on prendre en compte les déficits fonciers ? Ou les abattements ?

**Comment by Morendil** [comment]
Je ferme après avoir [consolidé sur le wiki](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le).
