### ISSUE TITLE
Questions sur `crds_mini`

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1108]
La variable `crds_mini`:
  (1) n'entre jamais dans le revenu disponible;
  (2) est codée comme étant assise sur le rsa activité, qui n'existe plus maintenant.
Eclaircir ce point: réétudier la législation sur ce point, et modifier le code en conséquence.

**Comment by Morendil** [comment]
Merci @bfabre01 pour l'alerte sur ce point. Je ne vois pas bien comment avancer sur cette question, qui dépasse l'expertise métier de l'équipe DINSIC, et l'issue commence à traîner. Tu es OK pour la fermer?

Dans le cas contraire, quand pourrais-tu envisager d'analyser ce point ?

**Comment by bfabre01** [comment]
@Morendil : je fais une PR.
