### ISSUE TITLE
Se mettre d'accord representation taux versement transport

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1117]
Aujourd'hui les paramètres du [versement_transport](https://github.com/openfisca/openfisca-france/blob/4701fd665937f17f1aa88c27f1b64e2dbbba7a85/openfisca_france/assets/versement_transport/taux.json) sont un exemple type de paramètres par commune. 

Ils sont dans un format qui diffère du yaml usuel des paramètres OpenFisca.
De ce fait, ils ne sont pas exposés par l'API et n'apparaissent pas dans le legislation explorer.

**Comment by Morendil** [comment]
Je ferme en faveur de #1167
