### ISSUE TITLE
[AL 2019] Réforme du calcul des droits aux aides au logement à partir d'avril 2019 tenant compte des ressources contemporaines 

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1118]
À partir d’avril 2019, les ressources prises en compte pour ouvrir et calculer les droits aux aides au logement seront calculées non plus sur l’année fiscale N-2, mais sur les 12 derniers mois connus de manière glissante, avec une réactualisation trimestrielle des droits.

**Comment by Morendil** [comment]
A réouvrir au début des travaux sur ce point.

**Comment by monbocal** [comment]
Bonjour, c'est un sujet qui nous intéresse fortement sur Mes Aides. Comment est ce que nous pouvons vous aider à tester la nouvelle formule ?

**Comment by monbocal** [comment]
Bonjour, avez-vous des nouvelles sur ce sujet ? Merci !

**Comment by JenniferTelep** [comment]
@monbocal, il est prévu que l'on vous communique les éléments métier au début des travaux.

**Comment by guillett** [comment]
Merci @JenniferTelep y-a-t-il une raison pour ce délai ? Ces éléments ne sont-ils pas déjà consolidés ?

**Comment by JenniferTelep** [comment]
@guillett, Etant donné que le sujet n'est pas encore stabilisé, il a été décidé en accord avec la DSS d'attendre la stabilisation du périmètre avant de communiquer sur les travaux en cours.
