### ISSUE TITLE
Intégration des paramètres des allocations familiales spécifiques aux Outre-mer

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1128]

**Comment by Morendil** [comment]
Dans quelle mesure cette issue recouvre-t-elle le périmètre de https://github.com/openfisca/openfisca-france/issues/647 ?

**Comment by JenniferTelep** [comment]
> 
> 
> Dans quelle mesure cette issue recouvre-t-elle le périmètre de #647 ?

Cette issue a pour but d'intégrer des paramètres spécifiques aux AF (ex: dans les Dom, y compris Mayotte, les AF sont versées à partir du premier enfant (24,10 (net) au 1er avril 2018). 
Ce sujet est en cours de travaux, mais je crois qu'il ne recouvre pas vraiment le périmètre de l'issue mentionnée.

**Comment by mtifarine** [comment]
Pour cette issue, les paramètres DOM sont à jour et il n'y a aucune modification dans le code sauf l'ajout des nouveaux cas de tests (quatre cas).
Est-ce que je vais créer une nouvelle PR pour cette issue?

**Comment by Morendil** [comment]
@mtifarine Je resterais bien sur la même ligne que précédemment: pas besoin d'ajouter des tests pour des revalorisations sans aucune évolution structurelle, si les paramètres sont déjà à jour il suffit de fermer l'issue.
