### ISSUE TITLE
Il semble que les tests prennent plus de temps

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1133]
<img width="1049" alt="capture d ecran 2018-09-25 a 01 08 52" src="https://user-images.githubusercontent.com/329236/45984124-e28b3480-c05f-11e8-8318-e1ea5ca1f13b.png">

**Comment by Morendil** [comment]
Ce n'est pas vraiment ce que montre le [dashboard Insights](https://circleci.com/build-insights/gh/openfisca/openfisca-france/master) de Circle; les 50 derniers builds (9 jours) montrent un maximum lègèrement en-dessous de 5 minutes quasiment constant, le graphe des durées médianes sur 90 jours montre une amélioration.

Je ferme cette issue qui ne semble pas avoir de valeur ajoutée par rapport à #1003 et #1005 où nous avons des pistes d'actions concrètes et des mesures empiriques.
