### ISSUE TITLE
Transformer en documentation les commentaires python

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1141]
Connected to openfisca/openfisca-core#717

Transformer des commentaires python de paramètres et de variables en documentation visualisable dans legislation explorer

Objet : présenter des exemples d'éditorialisation des paramètres et des variables afin que cela soit appliqué petit à petit à l'ensemble du modèle

**Comment by maukoquiroga** [comment]
L'idée/périmètre de l'issue est de :

- montrer un exemple de comment passer les commentaires à de la doc ; ou bien
- recenser la liste d'endroits où c'est possible aujourd'hui le faire, pour en évaluer l'effort ; ou bien
- les deux ?

**Comment by Morendil** [comment]
Ce ne sont pas des commentaires Python, sauf erreur de ma part, mais bien des docstrings. La différence est de taille car contrairement aux commentaires nous pouvons identifier automatiquement les docstrings grâce aux mêmes mécanismes de recherche dans l'AST que ceux utilisés par openfisca/core#719. Transformer automatiquement les fichiers sources serait un peu plus délicat par contre.

En attendant une regex dans Sublime fait aussi l'affaire, je compte 351 docstrings réparties dans 27 fichiers.

Je m'interroge sur:
> afin que cela soit appliqué petit à petit à l'ensemble du modèle

Je ne suis pas très optimiste sur le "petit à petit" compte tenu du backlog conséquent qui est déjà accumulé sur France. J'ai l'impression que cela risque de ne jamais être fini (voire jamais commencé). Je pencherais plutôt en faveur d'un effort priorisé explicitement avec une une personne responsable et libre du choix de stratégie d'implémentation (manuelle, automatique, semi-automatique).

**Comment by maukoquiroga** [comment]
> Je pencherais plutôt en faveur d'un effort priorisé

https://waffle.io/openfisca/openfisca-core

> explicitement avec une une personne responsable

Y en a toujours une

>  et libre du choix de stratégie d'implémentation

Ça c'est par défaut, ce qui n'empêche de faire appel à l'intelligence collective :)

**Comment by Morendil** [comment]
@sandcha @maukoquiroga OK pour fermer?

**Comment by Morendil** [comment]
@sandcha La PR n'a pas avancé depuis plus de 6 mois, et on va consacrer notre énergie à des sujets plus prioritaires.

**Comment by sandcha** [comment]
Effectivement, suite au bilan de l'équipe dinsic, c'est dépriorisé pour cette saison et en l'absence d'une suite claire pour l'explorateur de la législation.
