### ISSUE TITLE
Clarifier le statut des décompositions

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1165]
Cf. #281 #374 #530 #644 https://github.com/openfisca/openfisca-web-api/issues/32

## Date de cloture de ce RFC: 1er novembre 2018

L'état actuel du code gérant les décompositions me semble très instable:
- les décompositions sont implémentées dans Core mais pas du tout testées
- des données de décomposition existent dans France mais ne sont pas utilisées
- un seul test unitaire existe dans France sans grande valeur informative ni robustesse
- cette fonctionnalité n'est pas du tout documentée à ma connaissance

Je pencherais pour supprimer les décompositions de Core et de France et de repartir de 0 lors de l'analyse du besoin plus global de visualisation de ce que peut faire OpenFisca, probablement dans un autre dépôt. Mais je manque sans doute d'information sur les usages qui en ont été fait, les besoins qui peuvent exister actuellement.

**Comment by benjello** [comment]
Je pense que les décompositions sont essentielles à openfisca pour garder une vue d'ensemble.
Elles consistent essentiellement en un arbre dont les noeuds sont les sommes algébriques de leurs enfants.
Je pense qu'elles sont indépendantes des pays donc je suis pour que l'on les garde dans core.
Elles sont essentielles à des outils de visualisations comme les waterfall etc.

Je pense par contre que leur état actuel (utilisant des xml) et même leur implémentation (redondance avec certaines formules) doivent être traités.

A long terme je verrai bien l'ajout d'une decomposition à un tax-benefit-system comme une extension permettant de calculer des variables supplémentaires, individuellement ou d'un bloc, qui seraient essentiellement des sommes algébriques (on peut également penser à autoriser une division pour passer en unité de consommation par exemple). 

Je propose donc une stratégie graduelle pour nettoyer cette partie du code sans casser ses usages actuels (waterfall etc) dont les premières étapes seraient:
 - passage d'un format xml à un format yaml éventuellement épuré (ou à épurer)
 - s'assurer que l'on puisse adjoindre une décomposition à un tax-benefit-system pour créer à la volée de nouvelles "variables".

S'il y a un dev qui se porte volontaire, je suis prêt à tester, faire des retours sur la mise en oeuvre, participer à l'amélioration du dispositif tant au niveau code que de l'usage.  

@fpagnoux : je veux bien le lien vers ce qu'explore la Nouvelle-Zélande. Merci !

**Comment by benjello** [comment]
@Morendil : sur l'intérêt des décompostions voir aussi cette app https://openfisca-dash-ui.herokuapp.com/.

**Comment by Morendil** [comment]
@benjello Je l'ai vue fonctionner (et relativement récemment genre vendredi), mais ça ne semble plus fonctionner actuellement.

C'est peut-être lié à des évolutions de France et un rebuild décalé dans le temps ? On a par exemple un renommage de revenus_du_travail en revenus_nets_du_travail, datant d'il y a trois mois, qui a sans doute cassé la décomposition par défaut dans France.

> Je pense qu'elles sont indépendantes des pays

La structure de données peut être indépendante, mais pas son contenu, puisque ce sont des noms de variables qui doivent être dans le modèle.

D'ailleurs c'est à peu près la seule contrainte que je vois qui mérite une adhérence avec OpenFisca, sinon une décomposition c'est essentiellement un `dict` récursif dont les clés sont soit des noms de variables du modèle, soit des décompositions. Quant aux valeurs associées à ces clés (autres que le résultat de la simulation) elles sont assez arbitraires puisque dépendantes de l'outil qu'on utilise pour l'UI.

L'opération principale qu'on fait sur cette structure c'est un `map()` récursif, qui va transformer chaque clé en ajoutant la valeur de simulation.calculate() pour cette clé, et ses enfants de la même façon récursivement. Sauf grosse découverte j'ai l'impression que c'est assez simple pour qu'on n'ait pas besoin de le faire supporter à Core.

Je veux bien faire l'implémentation directement dans dash-ui, si tu me fournis un YAML avec la hiérarchie des variables.

**Comment by fpagnoux** [comment]
> @fpagnoux : je veux bien le lien vers ce qu'explore la Nouvelle-Zélande. Merci !

Je ne sais pas s'ils ont aussi arrivé au concept de décomposition, mais ils font des comparaisons de plusieurs pays et ont défini une ontologie des concepts de leur législation. Je suppose donc qu'ils ont fait émerger des structures à un niveau plus haut que celui de la variable. Ils ont publié [un document](https://www.digital.govt.nz/dmsdocument/95-better-rules-for-government-discovery-report) il y a un moment, mais je n'ai pas encore eu le temps de regarder en détails.

**Comment by benjello** [comment]
Elles ont déjà ressucitées (un peu zombies) mais il faudrait nettoyer le code je pense. On pourrait le faire avec l'objectif de maintenir certains usages fonctionnels:
 - https://github.com/openfisca/openfisca-matplotlib/blob/migrate-enums/notebooks/test_graphs.ipynb
 - https://github.com/cbenz/openfisca-dash-ui

**Comment by fpagnoux** [comment]
Si on part sur la création de nouvelles variables à la volées à partir d'une décomposition, est-ce que toutes les variables de type `f7aa` ne feraient pas de bonnes candidates (cc @Morendil).

**Comment by Morendil** [comment]
Pour moi non, ce ne sont pas les mêmes que les variables visées par les décompositions, et je ne suis pas sûr de comprendre le besoin "créer des variables à la volée". Sur les variables des feuilles d'impôt il y a aussi un chantier à mener mais pour moi sans lien évident avec les décompositions.

A ce stade ma meilleure proposition pour les décompositions reste celle ci-dessus, partir d'un fichier YAML exprimant le besoin, et implémenter ça de façon plus simple dans Dash-UI directement, ça nous permettrait de supprimer le code actuel des décompositions dans Core.

**Comment by Morendil** [comment]
Je ferme, la date de cloture étant dépassée; je note pour moi-même l'action consistant à implémenter directement une décomposition dans Dash UI en supprimant la dépendance sur France et Core, et on repartira de cette base pour clarifier ce qu'est le besoin.

**Comment by Morendil** [comment]
@benjello Can you add me as collaborator for the Dash UI repo ?
