### ISSUE TITLE
Réparer https://fr.openfisca.org/legislation/swagger

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#1169]
À l'adresse suivante
https://fr.openfisca.org/legislation/swagger

![capture d ecran de 2018-10-16 21-32-43](https://user-images.githubusercontent.com/1410356/47042378-65993980-d18b-11e8-8bac-a96bfe95b452.png)

Les URLs ne sont pas bien formées, `https://http://fr.openfisca.org/api/v24/parameters` est utilisée à la place de `https://fr.openfisca.org/api/v24/parameters`.

**Comment by Morendil** [comment]
Déjà recensée sur le dépôt de proximité: https://github.com/openfisca/legislation-explorer/issues/209 - je ferme ici.
