### ISSUE TITLE
Éviter de manière proactive les erreurs de packaging

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1177]
See #1174  

-------- EDIT by @fpagnoux 

- By definition, packaging errors are not detectable in the CI, because CI tests are run _before_ the package is published. 
- In #1174, an asset was introduced, but not added to the manifest. It was therefore not published in the Pypi package, making this package unusable.
- From memory, I don't recall that we have encountered any other kind of packaging error

**Comment by Morendil** [comment]
Meta: ajoute un [RFC] et une date de cloture ?

**Comment by fpagnoux** [comment]
Possible strategies:
1. Country-template's one: just include[ _everything_. ](https://github.com/openfisca/country-template/blob/master/MANIFEST.in#L1). It's radical and efficient, but assumes that `openfisca_france` doesn't contain useless assets. 
2. Add an `assets` directory to the manifest, and always put necessary assets in it. This still gives room for error though: nothing prevents me from adding assets out of this directory.
3. Investigate ways to run the tests in a way that is involves packaging. We definitely don't want to upload anything on Pypi each time we run tests, but there may be a way to mimic a publication locally.

The approach I'd would take is:
- Try 1, and see how much bigger the bundle gets
- If significant, try to get some non-packaged assets out of the `openfisca_france` directory
- If this approach fails, then only into 3.

**Comment by maukoquiroga** [comment]
Stratégie 4 : faire le `build` et l'utiliser pour faire tourner les tests :

```sh
python setup.py bdist_wheel
find dist/*.whl | xargs pip install --upgrade
openfisca-run-test --country-package openfisca_france tests
```

Voir #1178

**Comment by fpagnoux** [comment]
En regardant rapidement:

- Taille du package avec le `Manifest.ini` actuel: 1880824 bytes
- Taille en incluant tout le contenu du `openfisca_core: 1880824 bytes

Oui, on package déjà tout en fait 🙄 .
