### ISSUE TITLE
Doute sur le code des APL (seuil de non versement supprimé)

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#1179]
Dans la PR #1058 qui a introduit la réduction de loyer de solidarité (RLS) dans le calcul des APL, je remarque qu'une modification sur le seuil de versement des APL a aussi été introduite : 
- Avant le 01/03/2018, il y a un seuil de non versement qui s'applique à tout le monde
- Après le 01/03/2018, le seuil de non versement ne s'applique plus aux locataires HLM (bénéficiaires des APL)

Or je n'arrive pas à trouver de **référence législative** concernant ce changement dans le calcul des APL. Est-ce que quelqu'un dispose de cette référence par hasard ?

Formule de la variable `aide_logement_montant_brut_avant_degressivite` suite au changement : 
```
 # Montant minimal de versement il s'applique sur l'ALS et l'ALF et non pas sur l'APL
 locataire_hlm = statut_occupation_logement == TypesStatutOccupationLogement.locataire_hlm
 minimum_atteint = montant >= al.al_min.montant_min_mensuel.montant_min_apl_al
 montant = (montant * minimum_atteint * not_(locataire_hlm)) + (montant * locataire_hlm)
```

P.S : je crée une issue à ce propos plutôt que d'intervenir sur Slack, car j'ai l'impression que @mtifarine qui est l'auteur de la PR n'est pas sur le Slack d'Openfisca-france.

**Comment by Morendil** [comment]
@mtifarine @frtomas @guillet une idée à ce sujet ?

**Comment by Morendil** [comment]
@claireleroy On est bien dans ce qui pour moi relève d'une issue - ça devrait pouvoir se résoudre (ou se fermer) rapidement après investigation. Merci en tout cas pour le signalement!

**Comment by Morendil** [comment]
Je m'interroge aussi sur le lien entre la dernière ligne de code, et le commentaire qui suggère un traitement différencié des ALS/ALF et des APL. Ce n'est pas un texte officiel, mais [cet article de l'ADIL 92](http://www.adil92.org/boite-a-outils/actualite-juridique-financiere-et-fiscale/aides-au-logement-les-mesures-applicables-des-le-1er-octobre-2017) tend à confirmer que le seuil de versement est appliqué de façon uniforme à toutes ces aides.

**Comment by JenniferTelep** [comment]
Bonjour @Morendil,
Le seuil de versement est bien supprimé pour l'APL
cf.  l'arrêté du 27 février 2018 relatif à la prise en compte de la réduction de loyer de solidarité dans le calcul de l'aide personnalisée au logement, article 1er : https://www.legifrance.gouv.fr/eli/arrete/2018/2/27/TERL1801552A/jo/texte

Pour info, voici l'explication fournie par nos experts sur cette suppression:

Jusqu’à présent, lorsque le montant mensuel de l'APL (avant déduction de la CRDS) était inférieur à 10€, il n'était pas procédé à son versement dans le but de limiter les coûts de gestion pour les caisses.
Or, il est apparu que certains allocataires situés juste au-dessus du seuil de non versement de l’APL avant la réforme RLS, pouvaient être pénalisés en termes de reste à charge sur leur loyer, du fait du passage de leur APL en dessous du seuil de non versement après l’entrée en vigueur de cette dernière.
Les pouvoirs publics ont alors décidé de supprimer ce seuil de non versement afin de respecter l’objectif de la loi de ne pas augmenter les dépenses de logement restant à la charge des ménages les plus modestes.
NB : Cette suppression vise tous les titulaires d’APL du secteur locatif et pas uniquement ceux visés par la RLS. Elle conduira les régimes à verser potentiellement des aides personnalisées au logement d’un montant d’un euro minimum dans le secteur locatif.

**Comment by benjello** [comment]
@claireleroy tu as ta réponse !

**Comment by Morendil** [comment]
Ah oui, et l'article de l'ADIL92 est effectivement antérieur au texte de février 2018. Merci !

Pour répondre à ma propre question ci-dessus, le commentaire précise une inférence: ne sont éligibles à l'APL que les locataires d'un logement conventionné, alors qu'ALF et ALS concernent les locataires d'un logement non conventionné.

Au passage je regrette que cette modification ait amené à faire un copier-coller de toute la formule (duplication = dette technique), mais c'était pendant la revue de #1058 que cette remarque aurait été pertinente. Comme évoqué dans les discussions sur #1163 ce fichier `aides_logement.py` contient d'autres cas de duplication qu'il faudrait unifier, on en fera un chantier en soi.
