### ISSUE TITLE
Simplification du mode de calcul du plafond de ressources pour les bénéficiaires de l'allocation adulte handicapé (AAH)

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1185]
Le montant de l'AAH va être porté à 860 € le 1er novembre 2018.
Parallèlement, dans un objectif de simplification, le mode de calcul du plafond de ressources pour les bénéficiaires de l’AAH en couple sera rapproché de celui des autres minima sociaux, notamment du RSA, tout en tenant compte des spécificités liées au handicap.

**Comment by guillett** [comment]
@JenniferTelep, je suis curieux d'en savoir plus sur cette issue et les délais de résolution.

Quand avez-vous l'intention de travailler sur la revalorisation au 1/11 ? #1189 correspond déjà au travail nécessaire.

Qu'entendez-vous par rapport à la simplification du "mode de calcul du plafond de ressources pour les bénéficiaires de l’AAH en couple".

Avez-vous des tests en échec qui faciliterait la création d'une réalité commune sur le travail à faire ?

Merci.

**Comment by JenniferTelep** [comment]
Bonjour @guillett , 
Oui cette issue concernait bien la revalorisation de l'AAH au 1er novembre 2018. Nous n'avons pas encore de test.
Vu que vous traitez déjà le sujet et que nous avons d'autres travaux en cours, je propose de descoper la revalorisation de novembre de cette issue pour ne garder que le sujet sur le plafond de ressources.

Voici les éléments que nous avons sur le mode de calcul du plafond de ressources (nos travaux sont en cours):
Dans un objectif de simplification, le mode de calcul du plafond de ressources pour les bénéficiaires de l’AAH en couple sera rapproché de celui des autres minima sociaux, notamment du RSA, tout en tenant compte des spécificités liées au handicap. A ce titre, le coefficient multiplicateur entrant dans le calcul du plafond de ressources sera abaissé progressivement et affiné au gré des revalorisations de l’AAH, afin que le plafond de ressources pour les couples atteigne 1629 euros en novembre 2019.
Il est prévu qu'au deuxième alinéa de l’article D. 821-2 du code de la sécurité sociale, le mot « doublé » soit remplacé par les mots « majoré de 89% ».

**Comment by JenniferTelep** [comment]
PR validée (#1264)
