### ISSUE TITLE
Modifier la garantie de ressources / CAAH pour la rapprocher de la législation

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#1188]
@benjello que penses-tu de changer
`minima_sociaux.caah.garantie_ressources`
en
`minima_sociaux.caah.montant`.

L'article suivant détaille le CAAH et non pas la garantie de ressources. 
https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=6D9841673220B972DCA864BE1DF93490.tplgfr36s_3?idArticle=LEGIARTI000019505277&cidTexte=LEGITEXT000006073189&dateTexte=20181023

L'objectif est d'éviter de devoir modifier 2 endroits pour la revalorisation de l'AAH à venir.

**Comment by benjello** [comment]
@guillett : a priori pas d'objection.
Mais pour info avec le merge des barèmes IPP il risque d'y avoir du sport et du renommage.
Mais demain est un autre jour.

**Comment by Morendil** [comment]
Je ferme dans l'attente de la nouvelle structure des barèmes.
