### ISSUE TITLE
Nettoyage des revenus non salariaux (RPNS)

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#1201]
Constat : il existe deux variables de revenus non salariaux (`rpns` et `rpns_individu`) dont il est difficile de distinguer l'usage. 

- La variable **`rpns`** est utilisée dans le calcul :
    - des revenus du travail nets
    - de la base ressource de la PPE
    - de la base ressource des prestations familiales
    - de l'assiette d'un abattement pour les aides au logement (`aide_logement_assiette_abattement_chomage`)

- La variable **`rpns_individu`** est utilisée dans le calcul : 
    - de la base ressource de l'AAH
    - du revenu catégoriel non salarial pour le calcul de l'impôt sur le revenu et du RFR
    - de la CSG/CRDS sur revenus non salariaux
    - de diverses cotisations sociales pour les non salariés (`deces_artisan_commercant`, `formation_artisan_commercant`, `maladie_maternite_artisan_commercant`, `retraite_complementaire_artisan_commercant`, `vieillesse_artisan_commercant`, `famille_independant`, `formation_profession_liberale`, `maladie_maternite_profession_liberale`, `retraite_complementaire_profession_liberale`, `vieillesse_profession_liberale`)

Pistes possibles :
- Harmoniser les variables et n'en garder qu'une
- Clarifier les usages de chacune de ces variables

Par ailleurs, il faudrait : 
  - déplacer la variable `rpns` qui n'a pas sa place dans le script de l'impôt "irp.py" puisqu'elle n'entre pas dans le calcul de l'impôt
  - nettoyer la variable `rpns_individu` (nombreux commentaires, formules peu claires et peu fiables ...)

**Comment by Morendil** [comment]
@claireleroy Tu penses prendre le sujet à courte échéance ? Sinon on peut l'ajouter à la page du wiki sur les [mises en cohérence](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le).

**Comment by claireleroy** [comment]
Pas forcement en effet. Mais enfait je vois que mon issue se relie à #564, on peut la mettre à côté.

**Comment by Morendil** [comment]
[C'est fait](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le), je ferme l'issue.
