### ISSUE TITLE
Unifier la formule d'agrégation des crédits d'impôts

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1202]
Même travail que #1195 mais sur `credits_impots.py`, ici [la grille d'analyse](https://docs.google.com/spreadsheets/d/1QpzdzPeLDKaYjdN7jJtuowG9-sjFV93XRwDB508v7A4), il y a une seule incohérence apparente (`autent` définie dès 2009 mais appelée seulement à partir de 2010). Le gain est plus modeste, seulement (!) 250 lignes de code.

**Comment by benjello** [comment]
Point d'attention : de mémoire certains crédits deviennent  des réductions et/ou vice - versa.

**Comment by Morendil** [comment]
Oui il y a `cotsyn` qui est partagé entre les deux.
