### ISSUE TITLE
Factoriser une formule de réduction d'impôts

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1203]
…constituée de sommes

L'objectif c'est de réduire la complexité de la formule, par exemple, ses LOC.

**Comment by maukoquiroga** [comment]
Basé sur les résultats de #1205 et #1213, je propose qu'on avance sur la version #1213 dans une prochaine session collective.

**Comment by Morendil** [comment]
Nous avons réfléchi ensemble depuis l'ouverture de cette PR sur la priorisation des travaux d'amélioration de la qualité du code aussi bien de France que de Core, en produisant une [Mikado Map](http://mikadomethod.info/) concernant Core, ces travaux prennent le pas sur cette PR qu'il me semble préférable de fermer.
