### ISSUE TITLE
`reduction_ss_condition_revenus` est elle une réduction ? 

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#1204]
Une question qui concerne peut être principalement @benjello et les autres économistes.

L'impôt sur le revenu fonctionne dans cet ordre là pour l'instant:

ir_plaf_qf --> ip_net (Impôt net avant réductions) --> 
iaidrdi (Impôt après imputation des réductions d'impôt).

`reduction_ss_condition_revenus` introduit en 2016 est à priori une réduction, pourquoi l'avoir mis dans la formule d'ip_net et non pas dans iaidrdi ?

Ps: Je pense qu'il est possible de factoriser et d'améliorer la lisibilité des réductions d'impôt, là c'est assez ardu à lire.

**Comment by claireleroy** [comment]
@adrienpacifico @benjello C'est moi qui ais mis en place cette réduction :)

Malgré son nom, cette réduction d'impôt sous condition de revenus n'est pas franchement similaire aux autres réductions d'impôt. Elle s'apparente plus à une décote bis. Dans la [feuille de calcul de la DGFiP](https://www.impots.gouv.fr/portail/files/formulaires/2042/2018/2042_2324.pdf) elle intervient bien juste après l'application de la décote dans la partie 7 *"Diminution de l'impôt"* et non pas dans la partie 8 *"Déduisez vos réductions"*.

**Comment by benjello** [comment]
OK

 @adrienpacifico que suggères-tu comme.commentaire pour éviter ta confusion
?

Je rabâche mais si on pouvait changer le nom en passant ce serait cool.
-- 
Mahdi Ben Jelloul

**Comment by Morendil** [comment]
@benjello @adrienpacifico oui sur le refactoring des réductions j'avais très envie d'inscrire ça dans nos priorités, ça vous dit de programmer un atelier à ce sujet ?

**Comment by benjello** [comment]
Je vais être un peu chargé pour les prochains mois et je ne me vois pas investir autant de temps si tôt.
Désolé. Mais peut-être que @claireleroy est moins chargée ;-)

**Comment by Morendil** [comment]
Pas de souci. Je pense qu'on peut simplifier la formule de ip_net qui est inutilement dupliquée, dans la mesure où la formule de `reduction_ss_condition_revenus`est effectivement datée. Je pousse une branche en ce sens.

Pour les renommages ça me semble important qu'on en discute à plusieurs, plutôt que de les faire de façon unilatérale ou dans des PR liées à d'autres sujets, car ce seront nécessairement des "breaking changes". Il me semble qu'ils nécessitent plus de consensus et de formalisme que des modifications d'implémentation de formules. Au minimum une issue de type RFC pour proposer un jeu de renommages cohérents sur un sujet donné, qui permettrait de recenser les consommateurs des variables concernées, de s'assurer que ça ne casse pas une appli qui en dépend, et d'apporter un peu plus de cohérence au passage.

Qu'en pensez-vous ?

**Comment by benjello** [comment]
OK. Je ne suis pas contre un commentaire succint au bout de la ligne contenant  `reduction_ss_condition_revenus`

Merci @Morendil !
