### ISSUE TITLE
Clarifier la notion derrière rpns_individu

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#1220]
Être au clair sur la notion de revenus non-salariés qui sont déclarées sur la feuille d'impôt. Actuellement, il y a des incohérences, notamment sur la variable `rpns_individu`:
- Cette variable est la base pour calculer les cotisations incluses dans la variable `cotisations_non_salarie`, ce qui suggère que `rpns_individu` est avant tout prélèvement.
- En revanche, la variable `assiette_csg_crds_non_salarie` est la variable `rpns_individu` à laquelle on ajoute des cotisations sociales, ce qui suggère que `rpns_individu` est net de ces cotisations.

@benjello : as-tu des éléments sur ce point ?

**Comment by benjello** [comment]
@bfabre01 : il y a des commit que j'avais rééalisé sur le CASD qui sont reliés à ce point. Je regarderais quand je me pencherai là-dessus  en début de semaine prochaine.

**Comment by bynome** [comment]
Bonjour,
Pour m'intéresser depuis peu à cet formidable outil qu'est OpenFisca, je vous confirme avoir du mal à comprendre comment est structuré la partie TNS (Travailleur Non Salarié), notamment le calcul des cotisations. Pour avoir programmé de mon côté les différentes cotisations sociales des TNS en fonction de ma compréhension de la législation en vigueur, le résultat ne correspond pas à celle de `cotisations_non_salarie`.

Une règle macro dit que les charges sociales d'un TNS sont d'environ 45% de sa rémunération nette. Je suppose que cette règle doit inclure les cotisations sociales, mais aussi la CSG et la CRDS. Or lorsque je cumule les variables `cotisations_non_salarie`, `csg_non_salarie ` et `crds_non_salarie`, je n'arrive pas retrouver ce ratio...

Cordialement,

**Comment by Morendil** [comment]
Bonjour @benjello @bfabre01 et @bynome merci pour vos contributions sur ce sujet!

Je ne vois pas bien comment avancer sur cette question, qui dépasse l'expertise métier de l'équipe DINSIC, et l'issue commence à traîner. Voulez-vous qu'on la ferme pour l'instant, en la consolidant avec le [backlog des incohérences](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le) (qui contient d'ailleurs déjà une entrée sur les RPNS) ?

Dans le cas contraire, quand pourriez-vous programmer de consacrer du temps à son analyse ?

**Comment by bynome** [comment]
Bonjour,
Pour répondre au tout premier commentaire initial de @bfabre01 et après quelques recherches sur Internet (notamment sur les sites [URSAF](https://www.urssaf.fr/portail/home/taux-et-baremes/taux-de-cotisations/les-professions-liberales/bases-de-calcul-et-taux-des-coti.html) et [Sécu des Indépendants](https://www.secu-independants.fr/baremes/cotisations-et-contributions/?reg=ile-de-france-centre&pro=commercant&act=actif&ae=non)), je trouve que les termes utilisés portent à confusion au niveau de ces sites (site de confiance cela dit en passant). 

Après avoir consulté ces sites ( [Le coin des entrepreneurs](https://www.lecoindesentrepreneurs.fr/cotisations-tns-base-de-calcul/l) et [AfeCreation](https://www.afecreation.fr/pid14845/tns-calcul-et-paiement-des-cotisations.html)  ), et notamment les paragraphes suivants:

"_...la base de calcul des cotisations TNS d’une année est composée des éléments suivants :
- la rémunération versée,
- la quote-part éventuelle de dividendes assujettie aux charges sociales perçue,
- les cotisations complémentaires facultatives et les sommes versées au titre de contrats d’assurance groupe qui le concerne,
- et le montant des indemnités journalières reçues.
Par ailleurs, **la base de calcul de la CSG et la CRDS est égale aux revenus bruts d’activité, ce qui signifie qu’il convient d’ajouter au total ci-dessus les cotisations sociales obligatoires hors CSG-CRDS qui ont été payées sur l’année**._"

et 

" _La DSI permet de collecter le **revenu servant de base au calcul des cotisations sociales obligatoires d'assurance maladie, maternité, vieillesse, invalidité-décès et allocations familiales, ainsi qu'au calcul des contributions sociales (CSG et CRDS)** des travailleurs indépendants._"

On pourrait en conclure donc que le revenu brut d'activité (Bénéfices industriels et commerciaux, ou BIC, par exemple) sert de base à la fois au calcul des cotisations sociales obligatoires d'assurance maladie, maternité, vieillesse, invalidité-décès et allocations familiales, **mais aussi** au calcul des contributions sociales (CSG et CRDS) des travailleurs... et donc que la variable `assiette_csg_crds_non_salarie` doit se baser sur la variable `rpns_individu` **sans avoir à ajouter les cotisations sociales**...

Mais ce n'est pas ce que semble affiché l'[outil de simulation de cotisation du site de la secu des indépendant](https://www.secu-independants.fr/simulateur-cotisations-sociales/?reg=ile-de-france-centre&pro=commercant&act=actif&ae=non). Cet outil prend bien en compte comme assiette le revenu pro de l'indépendant pour le calcul des cotisations type Assurance maladie et Allocations familiales mais quand il s'agit de calculer la CSG/CRDS il réintègre les cotisations obligatoires dans l'assiette de calcul....

Bref je suis un peu perdu en ce qui me concerne....

**Comment by bynome** [comment]
PS: La plupart des sites consultés confirme bien le fait de devoir inclure les cotisations sociales obligatoires en plus du revenu professionnel afin de définir l'assiette de calcul de la CSG CRDS. Ce qui est constaté au niveau d'OF semble donc correct en l'état...

**Comment by bfabre01** [comment]
@bynome : merci pour tous ces éléments. En effet, les sources que tu évoques sont unanimes sur ce point (base CSG/CRDS = revenus + cotisations obligatoires). Mais je pense qu'il y a toujours un problème. La notion de "revenus" utilisée comme base pour les cotisations obligatoires doit être différente de la notion de revenus auxquels on ajoute ces cotisations pour avoir l'assiette de la CSG/CRDS. La première doit être avant paiement des cotis, la seconde doit être après déduction de ces cotis. Sinon, cela veut dire que l'on prélève deux fois les mêmes revenus. Or, pour ces deux notions, on utilise dans OpenFisca la même variable (`rpns_individu`). J'avoue que ma connaissance de la législation des RPNS est proche de zéro, donc, je prends des pincettes. De mon côté, je n'ai actuellement pas assez de temps pour me lancer dans ce chantier. Tu penses que tu pourrais regarder ça de plus près ?

**Comment by Morendil** [comment]
J'ai l'impression qu'on a pas assez de bande passante sur ce sujet, je ferme après avoir consolidé dans la page wiki.
