### ISSUE TITLE
Générer la liste des variables qui ne sont pas mises en cache dynamiquement

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#1231]
En tant que contributeur à OpenFisca je souhaite pouvoir ajouter des variables intermédiaires pour séparer les différentes parties d'algorithmes.

En particulier, je souhaite créer des variables intermédiaires qui correspondent à des champs dans des référentiels externes pour valider et améliorer le moteur de calculs.

L'ajout de variables peut détériorer l'expérience d'autres usagers, c'est pourquoi [`conf/cache_blacklist.py`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/conf/cache_blacklist.py#L4) a été créée.

Cela dit, cette liste est compliquée à maintenir.
L'analyse statique des formules pourrait permettre de lister les variables qui ne devraient pas être mise en cache.

J'ai en tête la logique suivante :
1. Une variable qui n'est utilisée que par *une seule* autre variable ne devrait pas être mise en cache.
2. Toute variable directement demandée dans une simulation devrait être mis en cache (sans prendre en considération la règle 1.

WDYT ? En particulier @benjello dont l'usage repose sur `conf/cache_blacklist.py`.

**Comment by Morendil** [comment]
@guillett Un titre en français ? ;)

**Comment by benjello** [comment]
Cela me paraît tout à fait raisonnable @guillet. Et si on peut en plus explicitement black blacklister des variables cela me va.

**Comment by Morendil** [comment]
@guillett Pour l'instant l'implémentation d'OpenFisca ne nous permet pas de calculer statiquement les dépendances entre variables. Nous continuons à investiguer le sujet, et j'anticipe qu'il exigera des  évolutions dans la façon d'écrire les formules. La gestion du cache sera forcément dans notre radar à ce moment là.

Les mesures qui existent actuellement sont, sinon satisfaisantes, du moins un compromis accepté; je ferme donc cette issue pour l'instant.
