### ISSUE TITLE
Prise en compte d'un parent agé non handicapé à charge dans l'aide au logement

### ISSUE THREAD

**Issue by frtomas** [openfisca/openfisca-france#1236]
Bonjour,

après avoir cherché des issues similaires et trouvé celle ci : [Relier un parent âgé au foyer fiscal](https://github.com/openfisca/openfisca-france/issues/588)

Nous sommes confrontés @mtifarine et moi à un problème concernant les personnes a charge dans l'aide au logement.

Comme mentionné dans cette ancienne issue il est impossible de prendre en compte une personne agée comme personne à charge dans un foyer fiscal si elle n'est pas handicapée.

Nous avons essayé d’écrire un cas yaml dans lequel la personne agée fait partie d'un foyer fiscal différent mais nous n'y sommes pas parvenus.

Existe-t-il une façon "officielle" de procéder ? Cette limitation est-elle destinée à rester ou va-t-elle évoluer ?
(Peut-être que rouvrir l'issue existente et y ajouter ce message serait préférable ?)

Cordialement.

**Comment by Morendil** [comment]
@mtifarine Comme tu as fait en faisant le lien avec l'ancienne c'est parfait, pas besoin de la rouvrir. Je crois que Github fait mieux le lien si on met l'identifant numérique: #588 par exemple.

Cette restriction est imposée seulement dans les cas de tests construits par `scenarios.py`, nous avons prévu de supprimer cette façon de lire les cas de tests, pour la remplacer par une nouvelle classe de Core appelée SimulationBuilder, qui ne soulèvera plus d'erreur dans ce cas de figure. Dans France c'est la PR #1227 qui bascule sur ce nouveau mécanisme.

**Comment by frtomas** [comment]
Merci pour cette réponse @Morendil 
J'ajoute @JenniferTelep et @ThibaultCCMSA pour qu'ils aient une visibilité sur ce point.

**Comment by frtomas** [comment]
@Morendil est-ce que vous avez une idée approximative de quand cette PR sera mergée ?

**Comment by Morendil** [comment]
@frtomas Probablement courant janvier, difficile d'être plus précis pour l'instant; entre-temps, il est toujours possible de créer une PR (pour écrire le test YAML ci-dessus par exemple) qui prendrait #1227 comme base, ça nous permettrait de vérifier la faisabilité…

**Comment by Morendil** [comment]
@frtomas On a fini par merger #1227 (fin février!), et depuis nous n'avons pas revisité cette issue, tu prends d'écrire un test (ou de publier celui que vous aviez travaillé alors) ? Sinon OK pour fermer l'issue ?

**Comment by Morendil** [comment]
Je ferme l'issue comme étant à priori corrigée par #1227 - n'hésitez pas à réouvrir si cela s'avère incorrect.
