### ISSUE TITLE
Revalorisation des allocations familiales au 1er janvier 2019

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1238]
Le plafond de ressources permettant de déterminer le montant des allocations familiales à verser à la famille est fixé à 56 849 € (56 286 € en 2018) pour la tranche 1 (versement du montant maximum) et 79 558 € (78 770 € en 2018) pour la tranche 3 (versement du montant minimum). Il est majoré 5 684 € (5 628 € en 2018) pour chaque enfant à charge.

**Comment by JenniferTelep** [comment]
[20180504 EMP_PPA_Reval_01avril18_v1.2.docx](https://github.com/openfisca/openfisca-france/files/2773141/20180504.EMP_PPA_Reval_01avril18_v1.2.docx)

**Comment by benjello** [comment]
@JenniferTelep : serait-il possible d'avoir une référence législative où figurerait ces valeurs ?
Merci beaucoup.

**Comment by JenniferTelep** [comment]
> 
> 
> @JenniferTelep : serait-il possible d'avoir une référence législative où figurerait ces valeurs ?
> Merci beaucoup.

Bonjour @benjello , la référence est la suivante (article 1er) : 
[Arrêté du 21 décembre 2018 relatif au montant des plafonds de ressources de certaines prestations familiales et aux tranches du barème applicable au recouvrement des indus et à la saisie des prestations ](https://www.legifrance.gouv.fr/eli/arrete/2018/12/21/SSAS1835267A/jo/texte )

**Comment by benjello** [comment]
Merci !

**Comment by Morendil** [comment]
Fermé via #1248
