### ISSUE TITLE
Revalorisation exceptionnelle de la PPA au 1er janvier 2019

### ISSUE THREAD

**Issue by jmdallais** [openfisca/openfisca-france#1241]
Revalorisation exceptionnelle de la PPA au 1er janvier 2019.
Cette issue pour mettre les travaux MSA en visibilité de la communauté.
Date prévisionnelle de soumission de la PR le 04/01/2019.

Notifiés pour info : @Lashchuk, @JenniferTelep , @frtomas , @ThibaultCCMSA , @LacombeEric, @mtifarine , @SChiusa

**Comment by guillett** [comment]
Cool ! @jmdallais  aurais-tu les documents de référence. Cela facilitera grandement la revue.

De plus, la date prévue pour la soumission de la PR est après la date d'effet, aucune chance que la PR arrive avant le 01/01/19 ? Merci.

**Comment by guillett** [comment]
J'ai trouvé [l'article 82 du PLF 19](http://www.assemblee-nationale.fr/15/projets/pl1255.asp#P5168_663886) pour la revalorisation normalement prévue au cours de l'année 2019 et
[le rapport de la commission pour le projet de loi portant mesures d’urgence économiques et sociales](http://www.assemblee-nationale.fr/15/pdf/rapports/r1547.pdf).

Ce n'est que la partie législative mais l'exposé des motifs du PLF permet de comprendre ce qui sera décrit dans la partie réglementaire.

**Comment by guillett** [comment]
[Cette page](http://www.caf.fr/allocataires/actualites/2018/la-prime-d-activite-revue-a-la-hausse) de caf.fr permet d'identifier 1.5 SMIC comme le point où la nouvelle bonification devient nulle.

**Comment by guillett** [comment]
Pour info, sur Mes Aides nous avons utilisé [la branche suivante](https://github.com/openfisca/openfisca-france/tree/reval-ppa) pour avoir une première estimation de la PPA dès demain en production. Nous la comparerons à celle qui sort du simulateur de caf.fr mercredi 2 janvier.

**Comment by jmdallais** [comment]
Bonjour @guillett et tous mes voeux.
Désolé, suis en congés jusqu'à jeudi matin. Mais on devrait soumettre notre PR cette fin de semaine.
Je te communiquerai les éléments de legis. en notre possession d'ici jeudi ou vendredi.

**Comment by guillett** [comment]
En fait la revalorisation ne s'est pas faite en ajoutant la bonification du PLF mais en modifiant la première bonification.

- Elle est augmentée de 90€.
- Le seuil d'éligiblité nes inchangé toujours à 0.5 SMIC ie 59 x SMIC horaire brut
- Le plafond est changé de 0,8 SMIC à 1 SMIC.

C'est cette nouvelle version que contient désormais la branche indiquée.

**Comment by jmdallais** [comment]
La décret : [ Décret n° 2018-1197 du 21 décembre 2018 relatif à la revalorisation exceptionnelle de la prime d'activité ](https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=31E8CDE5D5DEA2E7B97759286A79B1A8.tplgfr41s_1?cidTexte=JORFTEXT000037846000&dateTexte=&oldAction=rechJO&categorieLien=id&idJO=JORFCONT000037845541l)
L'article du code de la sécurité sociale modifié :  [Décret n° 2015-1710 du 21 décembre 2015 relatif à la prime d'activité - Article 2 ](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=C013DD75A89A8D1695C711D9EB4EBA58.tplgfr41s_1?cidTexte=JORFTEXT000031665094&idArticle=LEGIARTI000031673709&dateTexte=20151222&categorieLien=cid#LEGIARTI000031673709)
Une fois la PR soumise par @frtomas (normalement demain) , je te propose d'échanger avec lui directement via la PR pour toute questions / compléments.

**Comment by guillett** [comment]
Parfait, très proche de l'implémentation que j'avais faite

**Comment by frtomas** [comment]
Bonjour @guillett @jmdallais,

de ce que j'ai vu rapidement, la différence repose surtout sur le calcul de la bonification, avec une modification du taux_bonification_max.

**Comment by guillett** [comment]
Effectivement, car je n'ai pas changé le taux mais ajouté 90€ en dur.

**Comment by guillett** [comment]
Résolu avec #1247
