### ISSUE TITLE
Gestion du passage au prélèvement à la source

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#1254]
Dans Openfisca, l'impôt sur le revenu est codé en année "revenus". Ainsi une formule datée de 2017 se rapportera à l'impôt sur les revenus 2017 payé en 2018. Le prélèvement à la source entre en vigueur à partir de janvier 2019. Comment coder l'impôt sur revenus 2019 ? Et quid de l'impôt sur revenus 2018 ?

- Si l'on suit la logique actuelle, on continue de raisonner en année revenus et les nouveaux paramètres et formules seront donc renseigné pour 2019. Il y aura donc un "trou" en 2018 dans les formules mais pour le calculateur cela signifie que l'impôt sur revenus 2018 est calculé avec les mêmes formules et paramètres que l'impôt sur revenus 2017. Or dans les faits, l'impôt sur revenus 2018 est égal à zéro.

- On pourrait également modifier l'impôt pour passer à une logique en année "paiement". Ce serait un changement rétroactif sur tout le code de l'impôt. Dans ce cas, une formule datée de 2017 correspondrait désormais à l'impôt sur revenus 2016 payé en 2017. Cela a peut-être plus de sens économiquement notamment pour le calcul du revenu disponible.

Je n'ai pas trop de réponses juste des questions sur la façon de gérer ce changement.. La question est importante en ce moment car nous sommes entrain d'actualiser les barèmes IPP et la question est de savoir quelle année renseigner dans nos paramètres.
cc @bfabre01 @benjello

**Comment by benjello** [comment]
Il faut garder l'année revenu pour tout ce qui concerne le calcul des variables du foyer fiscal.
Il est alors facile de gérer l'année paiement en spécifiant l'année pour laquelle on appelle les variables de l'impôt en tenant compte du décalage ou de son absence.

**Comment by bfabre01** [comment]
@claireleroy : pour la question des barèmes, pas sûr qu'il y ait trop de changement du timing, car les barèmes de la loi de finances pour 2019 sont toujours appliqués aux revenus 2018. La différence (si je ne me trompe pas), c'est que ces barèmes appliqués aux revenus 2018 seront, non plus utilisés pour calculer l'impôt sur les revenus 2018, mais utilisés pour calculer un taux de prélèvement mensuel sur les revenus de septembre 2019 à août 2020.

**Comment by bfabre01** [comment]
Il faut aussi garder en tête que le prélèvement à la source ne concerne pas tous les revenus. Par exemple, les revenus du capital ne sont pas concernés par la réforme.

**Comment by bfabre01** [comment]
@claireleroy : je pense que la bonne solution est de passer en année paiement.
   (1) Sachant que maintenant, certains revenus sont imposés à la source, et d'autre toujours avec ce décalage d'un an, l'année paiement est probablement la seule solution pour simuler l'impôt de manière propre.
  (2) On applique déjà l'année de paiement pour les prestations sociales: par exemple, les prestations familiales dépendant des revenus en N-2, mais des caractéristiques familiales courantes, ne sont pas allouées à l'année N-2. L'impôt dépend aussi maintenant de caractéristiques relatives à différentes années. L'année de paiement me parait la seule solution viable et correcte.

**Comment by Morendil** [comment]
Tout ça serait plus clair pour moi si on avait un ou deux exemples concrets sous les yeux… une formule et ce qu'elle devient selon qu'on choisit l'une ou l'autre option; quels avantages et inconvénients on peut trouver sur un exemple à l'une et à l'autre.

**Comment by Morendil** [comment]
@claireleroy @bfabre01 @benjello Avez-vous assez d'élément pour qu'on ferme l'issue?

**Comment by claireleroy** [comment]
@Morendil Désolé, j'avais oublié de fournir les exemples (j'avais été un peu prise par le temps) ! Je pense que l'issue n'a pas été résolue du coup.. Cf. la position divergente de @benjello et @bfabre01 dans les commentaires ci-dessus...

**Comment by claireleroy** [comment]
Je ne pense pas qu'un exemple avec formule soit très parlant. C'est plutôt une question théorique sur ce l'on veut comme logique dans OpenFisca. 

Pour la variable `irpp` :
- soit on reste en logique année revenus : le calcul de `irpp` en 2018 est donc celui des revenus 2018 imposés (seulement une partie : ceux qui ne sont pas imposés à la source). On a donc une sorte d'année "blanche" en 2018 (impôt très faible).
- soit on passe en logique année paiement : le calcul de `irpp` en 2018 est donc celui sur les revenus 2017 (good) et en 2019 c'est celui sur revenus 2019 (prélèvement à la source) ou revenus 2018 (dans le cas des revenus non imposés à la source). Pas d'année "blanche".

Sinon, je pense que même si peu de gens utilisent la partie "Impôt sur le revenu" d'OpenFisca, cette question mérite d'être discutée plus largement par la communauté. Le passage au prélèvement à la source est un changement important et pourrait nous permettre de passer à une logique plus proche de la réalité du contribuable.

**Comment by Morendil** [comment]
@claireleroy Je ne suis pas totalement sûr d'avoir encore bien compris ce que recouvre "le passage au prélèvement à la source", j'essaie de rendre les choses concrètes pour bien comprendre ce qui change. Par exemple là je viens d'avoir ma première paie soumise au prélèvement à la source, à quel barème de l'IR ce revenu a-t-il été soumis ?

Tu disais plus haut que vous deviez actualiser les barèmes pour cette année. Quelles sont les références législatives dont vous disposez ?

**Comment by claireleroy** [comment]
@Morendil on a nous même un peu de mal à comprendre la logique du passage au prélèvement à la source.. et c'est bien pour ça que cette issue est importante à mon sens !

Pour l'actualisation des barèmes IPP que nous avons faites, je n'ai finalement pas eu de problèmes car les barèmes IPP renseignent à la fois l'année revenu et l'année paiement. J'ai actualisé le barème de l'IR avec les nouveaux seuils des tranches de l'IR qui ont été votées dans le cadre de la [loi de finances pour 2019](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037882341&dateTexte=&categorieLien=id) : cf. 2° du I de l'article 2 de la LF. L'[article 197 du CGI](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000006308322) qui a été modifié par cet article de la LF n'indique pas à quels revenus de quelle année ce nouveau barème s'appliquera... Il indique juste que l'impôt est calculé en application de ce barème.

**Comment by Morendil** [comment]
@claireleroy Est-ce que tu as une idée plus précise maintenant de ce qu'il faudrait faire? Pour ma part j'ai toujours le sentiment que la réponse est "rien", puisque la spécificité du prélèvement à la source n'est pas le montant de l'impôt mais les modalités de son paiement par le contribuable et que cette dernière question n'est pas traitée par OpenFisca.

Si j'ai bien tout compris, l'administration a calculé mon impôt sur les revenus de 2018 et s'en sert pour déterminer mon taux de prélèvement à la source. Par contre je n'aurai pas à payer "réellement" l'impôt sur ces revenus car il est annulé par le [CIMR](http://bofip.impots.gouv.fr/bofip/11235-PGP). Mais on me retient à la source, depuis janvier, des sommes constituant l'impôt sur les revenus de 2019, dont le calcul définitif ne pourra avoir lieu qu'à la fin de l'année, et qui fera donc éventuellement l'objet d'une régularisation.

Dans OpenFisca on peut donc calculer l'IRPP sur les revenus de 2018 mais ce calcul ne se traduira pas, pour la plupart des contribuables, par une imposition effective, c'est "l'année blanche". On pourrait envisager de calculer le CIMR mais cela n'a peut-être qu'un intérêt limité, hormis de démontrer par le calcul l'effet "imposition des revenus exceptionnels".

Si tu n'y vois pas d'inconvénient je te propose donc de fermer l'issue.

**Comment by claireleroy** [comment]
@Morendil Entièrement d'accord avec toi sur ces points !
