### ISSUE TITLE
Exonération de la taxe d'habitation

### ISSUE THREAD

**Issue by thbz** [openfisca/openfisca-france#1281]
Bonjour,

Je débute sur OpenFisca.

En essayant d'utiliser la variable `exonere_taxe_habitation` via l'[API Web](https://fr.openfisca.org/api/latest/calculate), je ne parviens pas à obtenir une autre valeur que `true`, alors même que l'individu ne remplit aucun des critères d'exonération (âge inférieur à 60, pas d'AAH, etc.). Le montant de la TH demeure lui aussi nul. J'ai eu beau consulter la formule utilisée  [dans la documentation](https://fr.openfisca.org/legislation/exonere_taxe_habitation?q=exonere_taxe_habitation), je ne comprends pas pourquoi l'individu est exonéré de TH dans cet exemple.
Merci.
Voici la requête :
```
{
    "individus": {
        "Claude": {
            "date_naissance": {
                "ETERNITY": "1972-01-01"
            },
            "salaire_de_base": {
                "2014": 100000,
                "2015": 100000,
                "2016": 100000,
                "2017": 100000
            },
            "age": {
                "2017-01": null
            },
            "statut_marital": {
                "2017-01": null
            },
            "aah": {
                "2017-01": null
            },
            "asi": {
                "2017-01": null
            }
        }
    },
    "menages": {
        "menage_1": {
            "personne_de_reference": [
                "Claude"
            ],
            "statut_occupation_logement": {
                "2017": "locataire_vide"
            },
            "taxe_habitation": {
                "2017": null
            },
            "exonere_taxe_habitation": {
                "2014": null,
                "2015": null,
                "2016": null,
                "2017": null
            }
        }
    },
    "familles": {
        "famille_1": {
            "parents": [
                "Claude"
            ],
            "aspa": {
                "2017-01": null
            }
        }
    },
    "foyers_fiscaux": {
        "foyer_fiscal_1": {
            "declarants": [
                "Claude"
            ],
            "isf_tot": {
                "2017": null
            },
            "nbptr": {
                "2017": null
            },
            "rfr": {
                "2017": null
            }
        }
    }
}
```

**Comment by sandcha** [comment]
Bonjour @thbz, 

Merci pour cette première contribution à OpenFisca !
Ca paraît effectivement surprenant. Nous analysons ça avec @Morendil et revenons asap avec les résultats.

Par ailleurs, les retours des nouveaux usagers sont particulièrement précieux pour l’amélioration du produit et de sa documentation. 
Pourrions-nous prendre contact par un autre canal ? 
Nous sommes joignables via contact@openfisca.org ou, si vous avez quelques minutes, nous serions ravis d’avoir vos retours sur ce [questionnaire](https://goo.gl/forms/9cQmHCpuxQ4V4gFl1).

**Comment by Morendil** [comment]
Bonjour @thbz - malheureusement tu n'es pas tombé sur la partie la plus reluisante du modèle socio-fiscal français, cette formule est en-dessous des standards de qualité que nous essayons de maintenir actuellement.

Pour la question précise sur le résultat "true", la réponse se trouve dans les deux dernières lignes de la formule de `exonere_taxe_habitation`:

```Python
elig = ((age >= 60) + (statut_marital == TypesStatutMarital.veuf)) * (isf_tot <= 0) * (rfr < seuil_th) + (asi > 0) + (aspa > 0) + (aah > 0)
return not_(elig)
```

La première ligne colle bien avec le commentaire, elle dit “pour être exonéré de taxe d’habitation il faut **soit** avoir plus de 60 ans ou être veuf, ne pas payer d’ISF et avoir un RFR inférieur à 10,000 et quelque euros; **soit** être éligible à l’ASI, l’ASPA ou l’AAH.

Dans le cas ci-dessus aucune de ces conditions n’étant vérifiée on renvoie `False` et tout va pour le mieux jusque-là. Mais la formule dans son ensemble _renvoie la négation de cette valeur_.

Est-ce grave? A coup sûr cela prête à confusion, et il faudra le corriger.

Ce qui me semble plus gênant c’est la dernière ligne de la formule `taxe_habitation` qui doit (je suppose) retourner le montant:
```
return - 0 * not_(exonere_taxe_habitation)
```

J’ai l’impression que cela va toujours renvoyer une valeur nulle. :grimacing:

Je constate par ailleurs que nous ne disposons d’aucun test fonctionnel couvrant cette formule, et au vu des TODO qui parsèment le code il est clair qu’elle représente un début de modélisation qui n’a jamais été vraiment achevé.

Je t'invite à nous donner plus de détails sur ce que tu souhaiterais arriver à faire avec OpenFisca, ici même ou via les coordonnées de contact ci-dessus, pour nous aider à décider comment traiter le sujet.

**Comment by benjello** [comment]
@Morendil @thbz c'est un travail qui n'a pas abouti mais qui permet cependant de savoir si une personne est exonérée ou pas de la TH (même si celle-ci n'est pas calculée) si on a bien renseigné tous ses revenus.

**Comment by thbz** [comment]
Merci pour ces réponses.

Je n'avais pas fait attention à cet appel à `not_`, trop focalisé sur la ligne précédente...

Pour ce qui est de la fonction qui calcule la taxe d'habitation elle-même, l'idéal serait que la documentation contienne un indicateur du niveau de « finition » du développement. Je sais bien que ce serait compliqué (existence de tests fonctionnels ? utilisation de cette formule dans des projets réels ? revue de code par des personnes qualifiées ?...), d'autant que la qualité d'une formule dépend de celle des formules qu'elle utilise, mais cela pourrait être un facteur pour donner confiance dans l'utilisation.
