### ISSUE TITLE
Bug dans calcul RSA

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#1283]
Bonjour à tous, 

Le calcul du RSA semble dépendant de l'ordre de calcul lorsque l'on fait une Simulation.. Ce qui est assez embêtant. 

Voici un code ci-dessous qui montre que si l'on souhaite calculer le `revenu_disponible` et le `rsa`, le résultat change selon la variable calculée en premier....

Est-ce que l'un d'entre vous aurait une intuition sur l'origine de ce problème et la façon de le résoudre ?

Merci beaucoup :)

```
from openfisca_france.scenarios import init_single_entity
from openfisca_france import FranceTaxBenefitSystem
from openfisca_france.model.base import *


tax_benefit_system = FranceTaxBenefitSystem() 
options = dict(
    period = 2018,
    parent1 = dict(age = 30),
    menage = dict(statut_occupation_logement = TypesStatutOccupationLogement.locataire_vide.name)
    )
```
```
### CAS 1

scenario = tax_benefit_system.new_scenario()
scenario = init_single_entity(
    scenario = scenario,
    **options,
    )
simulation = scenario.new_simulation()
revenu_disponible = simulation.calculate_add('revenu_disponible', '2018')
rsa = simulation.calculate('rsa', '2018-01')
print("RSA : {}".format(rsa))
```
RSA : 0

```
#### CAS 2

scenario = tax_benefit_system.new_scenario()
scenario = init_single_entity(
    scenario = scenario,
    **options,
    )
simulation = scenario.new_simulation()
rsa = simulation.calculate('rsa', '2018-01')
revenu_disponible = simulation.calculate_add('revenu_disponible', '2018')
print("RSA : {}".format(rsa))
```
RSA : 536

NB : Le problème du RSA nul ne semble concerner que les trois premiers mois de l'année...

**Comment by claireleroy** [comment]
Avec @benjello, on a commencé à investiguer ce problème.

On pense avoir trouvé et résolu une première source du problème : le calcul de la variable `aide_logement_neutralisation_rsa` incluait un calcul du RSA avec un nombre de cycles maximal de 0, ce qui pourrait impliquer le renvoi de valeurs par défaut pour le RSA... ?

**Comment by claireleroy** [comment]
cc @guillett @Morendil

**Comment by claireleroy** [comment]
cc @bfabre01

**Comment by Morendil** [comment]
Oui c'est un défaut identifié sur Core depuis un moment: https://github.com/openfisca/openfisca-core/issues/749

On a une PR qui traite le sujet: https://github.com/openfisca/openfisca-core/pull/817

Tu pourrais éventuellement faire tourner le cas ci-dessus contre cette branche ?

On pensait expérimenter d'abord cette branche sur Mes Aides, on voulait vérifier qu'elle n'engendrait pas de régression ni sur les calculs ni sur les performances, si vous pouvez tester ce dernier aspect dans le contexte CASD ça serait top et ça nous permettrait d'avancer en confiance.

**Comment by claireleroy** [comment]
@Morendil Je viens de tester avec votre branche `simplify-cycle-detection-redux` en local et effectivement ça marche, le RSA n'est plus nul ! Donc parfait!

Tu penses que la PR va aboutir rapidement ou bien vous avez encore beaucoup de choses à voir là-dessus ?

Concernant le CASD, c'est exactement le même code que je lançais qui buggait donc je pense qu'un test en local suffit non ?

**Comment by Morendil** [comment]
@claireleroy Pour être sûrs qu'il n'y a pas d'impacts sur les perfs il vaut mieux reproduire les conditions au plus proche, comme je disais à @benjello quand il nous a rendu visite; c'est quelque chose qu'on ne sait pas encore bien faire en test… On peut mettre des valeurs random dans les variables et faire des vecteurs de la même taille par exemple, mais on ne sait pas quelles variables sont renseignées ou non, quelles sont les entités ou quelle est la taille des vecteurs dans le cadre d'une exécution typique au CASD.

En tout cas de notre côté on est favorable à merger rapidement :)

**Comment by bfabre01** [comment]
@Morendil : merci pour ce retour. Le problème venait d'OpenFisca. Donc, CASD ou pas, c'est exactement la même chose. Donc, si c'est bon pour vous, on peut merger !
