### ISSUE TITLE
Actualisation des paramètres des bourses de l'enseignement supérieur

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1285]
Je suis tombé là-dessus en regardant les helpers (notamment apply_thresholds qui n'est utilisé que là), j'ai l'impression que ce n'est pas actualisé depuis 2016.

**Comment by monbocal** [comment]
A vue de nez les montants sont indexés sur la BMAF. Un calcul naif à partir des formules d'OpenFisca m'a donné le même montant max mensuel que sur https://www.service-public.fr/particuliers/vosdroits/F984 . A confirmer mais je pense que ça n'a jamais demandé de modification ?

**Comment by Morendil** [comment]
Top ! Merci d'avoir investigué, je ferme.
