### ISSUE TITLE
Prise en compte des revenus fonciers pour les prestations familiales

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#1299]
Bonjour,

Dans la base ressource du complément familial, les revenus fonciers ne sont pas pris en compte.

A priori, si j'ai bien lu le code, ça toucherait toutes les aides qui se basent sur la même formule : https://fr.openfisca.org/legislation/prestations_familiales_base_ressources_individu .

**Comment by Morendil** [comment]
Voir aussi #1234 #1216 #1278 #861 #1102

**Comment by bfabre01** [comment]
@monbocal : ça m'étonne un peu : normalement, ils devraient être pris en compte, non pas via la variable `prestations_familiales_base_ressources_individu`, mais via la variable `prestations_familiales_base_ressources`, qui dépend de la variable  `rev_coll`, qui elle dépend de la variable `revenu_categoriel_foncier`.

**Comment by bfabre01** [comment]
Ah ok, je comprends, le complément familial n'utilise que `prestations_familiales_base_ressources_individu`, et pas `prestations_familiales_base_ressources`...

**Comment by bfabre01** [comment]
@monbocal : j'ai ouvert une PR : #1303
