### ISSUE TITLE
Revalorisations PFs au 1er Avril 2019

### ISSUE THREAD

**Issue by frtomas** [openfisca/openfisca-france#1300]
Bonjour,

Pour information, nous avons préparé les revalorisations des PF au 01/04 d'après les informations qui nous ont été fournis.
Nous attendons de recevoir les références législatives pour ensuite créer les PRs au plus tôt.
Voici les branches concernées qui existent déjà sur github : 
- [x] [Revalorisation RSA](https://github.com/openfisca/openfisca-france/tree/msa_revalorisation_rsa_avril_2019)
- [x] [Revalorisation AF](https://github.com/openfisca/openfisca-france/pull/1302)
- [x] [Revalorisation ASI](https://github.com/openfisca/openfisca-france/pull/1302)
- [x] [Revalorisation CMUc-ACS](https://github.com/openfisca/openfisca-france/pull/1302)

Cordialement.

**Comment by ThibaultCCMSA** [comment]
@JenniferTelep @MehdiBenHnin

**Comment by frtomas** [comment]
Je m'interroge sur un point.
Ne serait-il pas préférable de ne créer qu'une seule PR regroupant ces revalorisations, afin d'éviter de multiplier les versions d'OpenFisca pour des changements mineurs pouvant être regroupés de manière cohérente ?

**Comment by Morendil** [comment]
@frtomas Pas d'objection pour ma part!

**Comment by monbocal** [comment]
Je vote pour n'importe quoi du moment que ça arrive vite ;)

**Comment by frtomas** [comment]
Nous sommes toujours en attentes des références du RSA, du coup en attendant je vais quand même créer une PR pour les trois autres.

**Comment by Morendil** [comment]
Trois de ces points ont été traités dans #1302 - j'ai mis à jour le descriptif pour refléter l'état d'avancement.

**Comment by Morendil** [comment]
Le RSA a été traité dans #1319 - je ferme donc.
