### ISSUE TITLE
Roadmap OF MSA jusqu'à Juin 2019

### ISSUE THREAD

**Issue by MehdiBenHnin** [openfisca/openfisca-france#1316]
Bonjour @Morendil @sandcha @maukoquiroga 

Cette issue présente les prochains développements prévus par l'équipe OF MSA jusqu'à juin 2019.

NB: Les développements prévus par l'équipe OF MSA sont classés par date de validation souhaité et par typologie. 

**Date de validation souhaité ( 20/05/2019 )** 

**Réforme des aides au logement** 

- [Réforme du calcul des droits AL ] Règles métiers et principe de la réforme #1315 
- [Réforme du calcul des droits AL ] Tableau des données de la base ressource #1315

**Date de validation souhaité [ 13/06/2019 ]**

**Fiabilisation** 

- Fiabilisation des paramètres Open Fisca pour l'ASS
- Intégration de la ressource "bénéfice agricole" dans la base ressource des aides au logement

**Réforme**

- Prise en compte du net perçu avant déduction des impôts pour les ressources entrant dans le calcul de la PPA et du RSA
- Rétablissement de la dérogation pension d'invalidité et rente AT-MP pour le calcul de la PPA

@ThibaultCCMSA @JenniferTelep @mtifarine @frtomas

**Comment by Morendil** [comment]
@MehdiBenHnin Je ferme cette issue maintenant que nous avons #1352, n'hésite pas à reporter des éléments de celle-ci vers celle-là.
