### ISSUE TITLE
Unable to use OpenFisca serve and other simple simulations

### ISSUE THREAD

**Issue by Pierre-Assemat** [openfisca/openfisca-france#1318]
Hi, 

I'm trying to use openfisca france for a little prototype.
I first try to use the python API, and I saw an example on your documentation about housing allowance. The example was working fine using the openfisca_country_template. Once I try to adapt the basic simulation to use Openfisca_france, I fall into a multitude of errors.

I also try in parallel to serve the web API, using "openfisca serve ...". But this time, I had no errors, no other logs, and no server running... 
I don't know where to find the help I need. 

Could you reference me some good example, or help me figure out why even the simple serve command does not have any action..?

I'm using Windows btw.

Thanks

**Comment by sandcha** [comment]
Hi @Pierre-Assemat,

Thank you for your message.

**Python API**

> I first try to use the python API, and I saw an example on your documentation about housing allowance. The example was working fine using the openfisca_country_template. Once I try to adapt the basic simulation to use Openfisca_france, I fall into a multitude of errors.

Could you share your example with `openfisca-france` and the error stacktrace that you get please? I will try to help you with it 🙂  

Besides, you can find some executable examples using the last version of `openfisca-france` in the [notebooks tutorials](https://github.com/openfisca/tutorial#notebooks) : clic on `launch binder` (it takes some seconds) and, you might be interested by the `Getting started` > `Calculate a variable` section (you can also edit a cell and re-run them all to see the result). 

 
**Web API**

> I also try in parallel to serve the web API, using "openfisca serve ...". But this time, I had no errors, no other logs, and no server running...

Did you try to serve it with the `country-template` or with `openfisca-france`?
Could you share the result of this command to check the list of your installed libraries? : 
`pip list`

In the meantime, you can also use these adresses for your Web API **tests**:
*  the [swagger interface](https://fr.openfisca.org/legislation/swagger) for `openfisca france` (based on this [latest API](https://fr.openfisca.org/api/latest))
* the [swagger interface](https://demo.openfisca.org/legislation/swagger) for the `country-template` (based on this [latest API](https://demo.openfisca.org/api))

Hope it helps! 🙂 

P.S: For any question on `openfisca-france`, feel free to write in French.

**Comment by Morendil** [comment]
Bonjour @Pierre-Assemat je vais fermer cette issue ne sachant pas quelle suite nous pouvons donner. N'hésite pas à réouvrir à un autre moment avec des informations complémentaires.

**Comment by MattiSG** [comment]
Probablement une conséquence de https://github.com/openfisca/openfisca-core/issues/962
