### ISSUE TITLE
Ajouter un mécanisme "barèmes à parts ou demi-parts"

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#1323]
Pour transposer les textes de loi qui spécifient, par exemple, un plafond de base pour la première part fiscale, puis une augmentation pour la première demi-part, puis un incrément par demi-part supplémentaire.

Ce mécanisme aurait été utile dans au moins deux PR récentes (TH, Livret d'épargne populaire) pour remplacer des lignes quasi-illisibles, par exemple:

```Python
mayotte = min_(1, nbptr) * p_mayotte.base + 2 * (min_(max_(0, nbptr - 1), 0.5) * p_mayotte.premiere_demi_part + max_(0, nbptr - 1.5) * p_mayotte.demi_part_supplementaire)
````

Par une invocation plus explicite:
```Python
plafond_mayotte = construit_bareme_demi_parts(p_mayotte).calc(nbptr)
```

On trouve différentes variantes: par nombre d'enfants, par nombre de parts, avec un nombre variable de "tranches fixes" (celles qui précisent des incréments différents) et de "tranches récurrentes" (par enfant supplémentaire, part ou demi-part supplémentaire). Mais l'abstraction sous-jacente est la même.

**Comment by maukoquiroga** [comment]
cc @magemax @DorineLam

**Comment by Morendil** [comment]
Je vais fermer en attendant une discussion sur, et une éventuelle issue à, https://github.com/openfisca/openfisca-core/issues/890

**Comment by maukoquiroga** [comment]
Arf, mais nous en avons besoin 😢
