### ISSUE TITLE
Messages d'erreur à l'import des barèmes de taxe d'habitation

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1339]
Connected to #1320 

OpenFisca-France m'apporte de la joie mais j'ai un petit soucis.

**Le problème**

L'exécution du test yaml d'import des barèmes pour la taxe d'habitation avec :
`openfisca test --country-package openfisca_france tests/formulas/taxe_habitation.yaml`

Indique un test s'exécutant avec succès mais trace des messages débutant par `ERROR`:

```sh
openfisca test --country-package openfisca_france tests/formulas/taxe_habitation.yaml 
libyaml is not installed in your environment. This can make OpenFisca slower to start. Once you have installed libyaml, run 'pip uninstall pyyaml && pip install pyyaml --no-cache-dir' so that it is used in your Python environment.

 libyaml is not installed in your environment, this can make your test suite slower to run. Once you have installed libyaml, run `pip uninstall pyyaml && pip install pyyaml --no-cache-dir` so that it is used in your Python environment.
======================================================= test session starts =======================================================
platform darwin -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /.../openfisca-france, inifile: setup.cfg
collected 12 items                                                                                                                

tests/formulas/taxe_habitation.yaml ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
...ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
..ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.ERROR:4473024240_-6627832805331079547_taxe_habitation:Les taux de taxe d'habitation de l'année 2000 utilisés pour la réduction du plafonnement ne sont pas disponibles pour cette commune. Nous mettons donc cette réduction à zéro.
.

============================================ 12 passed, 396 warnings in 133.63 seconds ============================================
```

De même sur l'intégration continue [CircleCI#9218](https://circleci.com/gh/openfisca/openfisca-france/9218).

**Ce que j'attendais**

Un test s'exécutant sans problème et pas de message d'erreur en sortie.

**Informations complémentaires**

Test du fichier pouvant être pris en exemple : `th_exon_2017`
En local, le test a été exécuté dans un environnement sans `libyaml` mais ce n'est pas le cas sur CircleCI.

**Comment by Morendil** [comment]
C'est plutôt un "request changes" sur #1320 à mon sens, plutôt qu'une issue qui n'est pas applicable sur France en l'état actuel, la PR n'étant pas mergée…

Sur le fond, à bien y regarder, ça émet une erreur parce que nous n'avons pas les fichiers CSV pour l'année 2000 c'est bien ça ? Il me semble que pour bien faire il faudrait soit ne pas inclure le code qui essaie de calculer des choses en fonction d'une donnée que nous ne fournissons pas, soit fournir la donnée. Bref ce message me semble incohérent. Il va signaler à tous nos usagers une "erreur" à laquelle ils ne peuvent rien.

**Comment by Morendil** [comment]
Poke @bfabre01

**Comment by sandcha** [comment]
Effectivement, c'était plutôt une demande de modification (mise en issue parce qu'en premier test, on ne semblait pas reproduire le même résultat sur deux machines différentes).

Ca me semble bon pour fermeture : la question sur le message d'erreur a été résolue par la suppression des logs (cf. [ce commit](https://github.com/openfisca/openfisca-france/pull/1320/commits/ac28f017b055943a87c9c1ba3d8e1117479fd698)) et le fait de mettre la réduction à zéro (comme l'indiquait le message) répond aux besoins du calcul.
