### ISSUE TITLE
Doublon pour la référence de la MVA

### ISSUE THREAD

**Issue by ManonLger** [openfisca/openfisca-france#1344]
(Majoration pour Vie Autonome)
https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/prestations/minima_sociaux/caah/majoration_vie_autonome.yaml
https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/prestations/minima_sociaux/aah/mva.yaml

**Comment by Morendil** [comment]
Merci @ManonLger ! On va corriger en prenant une seule référence.

**Comment by ManonLger** [comment]
Je peux prendre si tu veux. Ce sera l'occasion pour que tu m'expliques ce qui se passe quand on supprime une variable de `openfisca-france`, pour vérifier s'il y a des extensions qui l'utilisent par exemple, ou autres précautions à prendre.

**Comment by Morendil** [comment]
Avec plaisir !

Au niveau du code, assure-toi simplement que les références au paramètre que tu ne conserves pas sont bien supprimées. Garde en tête qu'on accède parfois aux paramètres en une seule fois:
```
mva = parameters(period).prestations.minima_sociaux.aah.mva
```
et parfois en plusieurs fois:
```
P = parameters(period).prestations.minima_sociaux
mva = P.aah.mva
```

En pratique la suppression d'un paramètre est sans grand risque (ça peut l'être plus quand on supprime une variable), si les tests de la CI de France continuent à passer on pourra merger sans état d'âme. C'est plus sur l'identification et la description de la version qu'il faudra être attentive.

La suppression d'un paramètre modifie l'API publique d'OpenFisca France. Comme on utilise Semver on va donc publier la version concernée avec une montée de version majeure. Au sens de Semver, cela veut dire "non rétro-compatible" et rien de plus, donc ça peut très bien être un changement de petite ampleur.

C'est aux personnes qui maintiennent les paquets réutilisant France (extensions, applications) d'être attentives lors de l'intégration d'une nouvelle version majeure, idéalement grâce à la couverture apportée par leurs propres tests, et on essaie de les aider. On s'oblige donc depuis peu à inclure une section "Guide de migration" dans le descriptif de toutes les montées de version majeure.

Dans ton cas ça se limite à dire "Si vous interrogiez le paramètre prestations.minima_sociaux.aah.mva, utilisez maintenant prestations.minima_sociaux.caah.majoration_vie_autonome" ou vice-versa selon ce que tu décides de garder.

N'hésite pas à poser des questions :)

**Comment by ManonLger** [comment]
Génial merci !
Je ne crois pas avoir les accès pour push ma branche, tu préfères que je fork ou tu peux m'ajouter à l'orga ?

**Comment by Morendil** [comment]
@ManonLger je t'ai invitée à rejoindre l'équipe @openfisca/france-contrib - bienvenue :)
