### ISSUE TITLE
Type Error APA

### ISSUE THREAD

**Issue by nico5655** [openfisca/openfisca-france#1359]
J'utilise le cas d'exemple ci-dessus. Il peut-être retrouvé sur [ce lien](https://hub.gke.mybinder.org/user/openfisca-tutorial-dsdi2wfh/notebooks/notebooks/getting_started.ipynb
). 

```
TEST_CASE = {
    'individus': {
        'parent1': {
            'age': {'2015-01': 30},
            'salaire_de_base': {'2015': 80000}
        },
        'enfant1': {
            'age': {'2015-01': 12}
        },
        'enfant2': {
            'age': {'2015-01': 18}
        }
    }
}
TEST_CASE['foyers_fiscaux'] = {
    'foyer_fiscal1': {
        'declarants': ['parent1'],
        'personnes_a_charge': ['enfant1', 'enfant2']
    }
}

TEST_CASE['menages'] = {
    'menage1': {
        'personne_de_reference': ['parent1'],
        'enfants': ['enfant1', 'enfant2']
    }
}

TEST_CASE['familles'] = {
    'famille1': {
        'parents': ['parent1'],
        'enfants': ['enfant1', 'enfant2']
    }
}
```

Ce cas ne devrait pas poser problème. Mais après avoir initialisé la simulation.
`from openfisca_core.simulation_builder import SimulationBuilder
from openfisca_france import FranceTaxBenefitSystem
tax_benefit_system = FranceTaxBenefitSystem()
simulation_builder = SimulationBuilder()
simulation = simulation_builder.build_from_entities(tax_benefit_system, TEST_CASE)`

Cette ligne: `simulation.calculate('apa_domicile', '2015-1')` renvoie l'erreur suivante:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

ValueError                                Traceback (most recent call last)
<ipython-input-6-d2c7919c0396> in <module>
----> 1 value = simulation.calculate('apa_domicile', '2015-1')
      2 value

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in calculate(self, variable_name, period)
    109 
    110         try:
--> 111             result = self._calculate(variable_name, period)
    112             self.tracer.record_calculation_result(result)
    113             return result

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in _calculate(self, variable_name, period)
    139         try:
    140             self._check_for_cycle(variable.name, period)
--> 141             array = self._run_formula(variable, population, period)
    142 
    143             # If no result, use the default value and cache it

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in _run_formula(self, variable, population, period)
    245             array = formula(population, period)
    246         else:
--> 247             array = formula(population, period, parameters_at)
    248 
    249         return array

~\.conda\envs\openEnv\lib\site-packages\openfisca_france\model\prestations\autonomie.py in formula(individu, period, parameters)
    180         dependance_plan_aide_domicile_accepte = individu('dependance_plan_aide_domicile_accepte', period)
    181 
--> 182         apa_domicile_participation = individu('apa_domicile_participation', period)
    183 
    184         apa = dependance_plan_aide_domicile_accepte - apa_domicile_participation

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\populations.py in __call__(self, variable_name, period, options)
     99             return self.simulation.calculate_divide(variable_name, period)
    100         else:
--> 101             return self.simulation.calculate(variable_name, period)
    102 
    103     # Helpers

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in calculate(self, variable_name, period)
    109 
    110         try:
--> 111             result = self._calculate(variable_name, period)
    112             self.tracer.record_calculation_result(result)
    113             return result

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in _calculate(self, variable_name, period)
    139         try:
    140             self._check_for_cycle(variable.name, period)
--> 141             array = self._run_formula(variable, population, period)
    142 
    143             # If no result, use the default value and cache it

~\.conda\envs\openEnv\lib\site-packages\openfisca_core\simulations.py in _run_formula(self, variable, population, period)
    245             array = formula(population, period)
    246         else:
--> 247             array = formula(population, period, parameters_at)
    248 
    249         return array

~\.conda\envs\openEnv\lib\site-packages\openfisca_france\model\prestations\autonomie.py in formula_2002(individu, period, parameters)
     54         condition_ressources_domicile = [
     55             base_ressources_apa_domicile <= (seuil_inf * majoration_tierce_personne),
---> 56             (seuil_inf * majoration_tierce_personne) < base_ressources_apa_domicile <= (seuil_sup * majoration_tierce_personne),
     57             base_ressources_apa_domicile > (seuil_sup * majoration_tierce_personne),
     58             ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

J'ai ensuite ajouté les ligne suivantes dans autonomie.py à la ligne 53 (juste avant l'erreur).
`print(type(proratisation_couple),proratisation_couple)        
print(type(base_ressources_apa),base_ressources_apa)
print(type(base_ressources_apa_domicile),base_ressources_apa_domicile)`

Le résultat renvoyé était le suivant:
<class 'numpy.ndarray'> [1. 1. 1.]
<class 'numpy.ndarray'> [0. 0. 0.]
<class 'numpy.ndarray'> [0. 0. 0.]

Tout cela semble indiquer que la variable base_resources_apa_domicile est un tableau alors qu'il devrait s'agir d'un entier, ce qui cause l'erreur lorsqu'elle est comparée à un entier.
Mais pourquoi? Je ne pense pas que cela vienne de mon TEST_CASE, puisque je l'ai tiré d'un exemple officiel.
Merci d'avance pour votre aide.

**Comment by guillett** [comment]
Bonjour @nico5655,

Merci pour ton message.

Le problème vient de [cette ligne](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/autonomie.py#L51-L55) qui n'est pas compatible avec la librairie que l'on utilise.

Il faudrait la remplacer par

`((seuil_inf * majoration_tierce_personne) < base_ressources_apa_domicile) * ( base_ressources_apa_domicile<= (seuil_sup * majoration_tierce_personne))`

Pourrais-tu faire une PR avec un tel correctif ?

**Comment by benjello** [comment]
Good catch @guillett  et @nico5655. Il y a d'autres occurrences de double comparaison. Ne pas hésiter à les modifier. Cette partie de code n'a pas été beaucoup utilisée donc il se peut qu'il y ait encore pas mal de bugs.

**Comment by nico5655** [comment]
Même problème [ici](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/autonomie.py#L84-L88) et [ici](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/autonomie.py#L217-L221).
