### ISSUE TITLE
Erreur dans la formule APA urgence institution

### ISSUE THREAD

**Issue by nico5655** [openfisca/openfisca-france#1364]
https://github.com/openfisca/openfisca-france/blob/a8a88e026c459d9be197f04ec5178e3c3c5801cc/openfisca_france/model/prestations/autonomie.py#L313-L318

J'ai une erreur à la ligne 316 disant que 'parameters' est une fonction et qu'il n'a pas d'attribut nommé 'apa_institution.apa_d_urgence.part_du_tarif_dependance_gir_1_2_de_l_etablissement_d_accueil'.

**Comment by benjello** [comment]
Bonjour @nico5655. Merci pour ces retours.
Il semble qu'il y ait déjà une erreur (typo) à la ligne 315.
Et je dirait que `part_urgence_institution` serait plus une variable qu'un paramètre car dépendant de l'établissement. Ceci dit je ne suis pas spécialiste. @elsaperdrix confirmes-tu ?

@guillett tu as peut-être aussi des ressources de ton côté ?

**Comment by elsaperdrix** [comment]
part_urgence_institution = 0.5. L'apa d'urgence en établissement est de 50% du tarif hébergement de l'établissement pour le gir de l'individu. Ce qui dépend de l'établissement, c'est donc dependance_tarif_etablissement_gir_1_2

**Comment by benjello** [comment]
Donc réintroduire parameters.apa_institution.apa_d_urgence.part_du_tarif_dependance_gir_1_2_de_l_etablissement_d_accueil à une valeur de 0.5.

Merci @elsaperdrix 

@nico5655 une petite PR ?

Merci à tous

**Comment by Morendil** [comment]
@benjello J'ai une autre analyse (pas forcément incompatible avec la tienne).

@nico5655 Les paramètres législatifs sont toujours compris dans OpenFisca comme relatifs à une période; par exemple je ne demande pas "le SMIC horaire brut" mais "le SMIC horaire brut en septembre 2019". Dans la [syntaxe](https://openfisca.org/doc/coding-the-legislation/legislation_parameters.html) ça se traduit par quelque chose comme

```Python
  smic = parameters(period).smic_horaire_brut
```

Ou encore comme dans cette autre formule dans `autonomie.py`:
https://github.com/openfisca/openfisca-france/blob/a8a88e026c459d9be197f04ec5178e3c3c5801cc/openfisca_france/model/prestations/autonomie.py#L300

Dans la formule il manque ce procédé, et c'est ça (il me semble) la cause immédiate de l'erreur.

**Comment by benjello** [comment]
Good catch @Morendil. @nico5655 désires-tu corriger ? 
Je peux le faire surtout si tu m'écris un test qui ne passerai pas en l'état. 
Et désolé pour le retard à corriger ce point.

**Comment by benjello** [comment]
@nico5655 j'ai fait la correction proposée par @Morendil. Si tu pouvais ajouter un test ce serait parfait.
