### ISSUE TITLE
[Question] Correspondance "nom des champs" / "champs cerfa" 

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1385]
Bonjour,

J'aimerais savoir s'il existe une liste de correspondance entre les champs d'entrée que l'on peut saisir dans l'API et leur équivalent CERFA dans une déclaration d'impôts. 

Idéalement, j'aurais aimé pouvoir entrer mes infos telles qu'elles apparaissent sur ma déclaration (1AJ = 30000, 1BJ = 25000, ...) pour obtenir le résultat.

Merci d'avance.

**Comment by Morendil** [comment]
Salut @PhunkyBob !

Une liste à proprement parler pas vraiment, mais tu peux chercher l'attribut `cerfa_field` qui a à peu près cette intention. C'est un sujet qu'on a déjà abordé, cf #853 sans toutefois le résoudre de façon parfaite. @claireleroy peut éventuellement apporter des compléments.

**Comment by claireleroy** [comment]
Salut @PhunkyBob , de notre côté (TAXIPP) on utilise bien les CERFA en inputs de nos simulations. Pour traduire les CERFA en variables OpenFisca, on utilise la fonction ["build_cerfa_fields_by_variable"](https://github.com/openfisca/openfisca-france-data/blob/release/1.0.0/openfisca_france_data/utils.py) d'Openfisca-france-data.

**Comment by izneo-get** [comment]
C'est justement en lisant #853 que j'ai eu l'espoir qu'il y ait une équivalence disponible quelque part. 
J'ai récupéré le code source en me disant qu'il y aurait peut-être dedans un dictionnaire. J'ai fait une recherche dans le code de "1AJ" en espérant tomber sur ce dictionnaire, mais en vain. 

Je ne comptais pas développer en Python, mais me contenter de créer un JSON pour appeler l'API, d'où mon besoin d'équivalence. 
Je vais essayer de remonter la piste de "build_cerfa_fields_by_variable".

**Comment by PhunkyBob** [comment]
C'est justement en lisant #853 que j'ai eu l'espoir qu'il y ait une équivalence disponible quelque part.
J'ai récupéré le code source en me disant qu'il y aurait peut-être dedans un dictionnaire. J'ai fait une recherche dans le code de "1AJ" en espérant tomber sur ce dictionnaire, mais en vain.

Je ne comptais pas développer en Python, mais me contenter de créer un JSON pour appeler l'API, d'où mon besoin d'équivalence.
Je vais essayer de remonter la piste de "build_cerfa_fields_by_variable".

**Comment by PhunkyBob** [comment]
Je suis passé dans tous les fichiers "openfisca_france/model/*.py" pour lire le contenu de "cerfa_field". 

Je partage ici le résultat : 

Tables Generator

    LaTeX Tables
    HTML Tables
    Text Tables
    Markdown Tables
    MediaWiki Tables
    Contact

Markdown Tables Generator

↧ Expand ↧
Put tabs between columns
Compact mode
Line breaks as <br>
Result (click "Generate" to refresh)
Copy to clipboard

| class OF               | cerfa |
|-------------------------------|-----|
| sal_pen_exo_etr               | 1AC |
| chomeur_longue_duree          | 1AI |
| salaire_imposable             | 1AJ |
| frais_reels                   | 1AK |
| pensions_alimentaires_percues | 1AO |
| chomage_imposable             | 1AP |
| retraite_imposable            | 1AS |
| hsup                          | 1AU |
| ppe_du_sa                     | 1AV |
| ppe_tp_sa                     | 1AX |
| pensions_invalidite           | 1AZ |
| sal_pen_exo_etr               | 1BC |
| chomeur_longue_duree          | 1BI |
| salaire_imposable             | 1BJ |
| frais_reels                   | 1BK |
| pensions_alimentaires_percues | 1BO |
| chomage_imposable             | 1BP |
| retraite_imposable            | 1BS |
| hsup                          | 1BU |
| ppe_du_sa                     | 1BV |
| ppe_tp_sa                     | 1BX |
| pensions_invalidite           | 1BZ |
| sal_pen_exo_etr               | 1CC |
| chomeur_longue_duree          | 1CI |
| salaire_imposable             | 1CJ |
| frais_reels                   | 1CK |
| pensions_alimentaires_percues | 1CO |
| chomage_imposable             | 1CP |
| retraite_imposable            | 1CS |
| hsup                          | 1CU |
| ppe_du_sa                     | 1CV |
| ppe_tp_sa                     | 1CX |
| pensions_invalidite           | 1CZ |
| sal_pen_exo_etr               | 1DC |
| chomeur_longue_duree          | 1DI |
| salaire_imposable             | 1DJ |
| frais_reels                   | 1DK |
| pensions_alimentaires_percues | 1DO |
| chomage_imposable             | 1DP |
| retraite_imposable            | 1DS |
| hsup                          | 1DU |
| ppe_du_sa                     | 1DV |
| ppe_tp_sa                     | 1DX |
| pensions_invalidite           | 1DZ |
| chomeur_longue_duree          | 1EI |
| salaire_imposable             | 1EJ |
| frais_reels                   | 1EK |
| pensions_alimentaires_percues | 1EO |
| chomage_imposable             | 1EP |
| retraite_imposable            | 1ES |
| ppe_du_sa                     | 1QV |
| ppe_tp_sa                     | 1QX |
| f1tt                          | 1TT |
| f1tv                          | 1TV |
| f1tw                          | 1TW |
| f1tx                          | 1TX |
| f1tt                          | 1UT |
| f1tv                          | 1UV |
| f1tw                          | 1UW |
| f1tx                          | 1UX |
| f3vd                          | 3SD |
| f3vf                          | 3SF |
| f3vi                          | 3SI |
| f3va_2016                     | 3VA |
| f3va_2016                     | 3VB |
| f3vd                          | 3VD |
| f3vf                          | 3VF |
| f3vi                          | 3VI |
| f3vj                          | 3VJ |
| f3vj                          | 3VK |
| f3va_2016                     | 3VO |
| f3va_2016                     | 3VP |
| abic_impm                     | 5HA |
| arag_exon                     | 5HB |
| arag_impg                     | 5HC |
| frag_fore                     | 5HD |
| arag_pvce                     | 5HE |
| arag_defi                     | 5HF |
| pveximpres                    | 5HG |
| nrag_exon                     | 5HH |
| nrag_impg                     | 5HI |
| nrag_pvce                     | 5HK |
| cncn_exon                     | 5HK |
| nrag_defi                     | 5HL |
| nrag_ajag                     | 5HM |
| frag_exon                     | 5HN |
| frag_impo                     | 5HO |
| mbnc_exon                     | 5HP |
| mbnc_impo                     | 5HQ |
| mbnc_pvce                     | 5HR |
| mbnc_mvlt                     | 5HS |
| mbnc_pvct                     | 5HV |
| frag_pvct                     | 5HW |
| frag_pvce                     | 5HX |
| revimpres                     | 5HY |
| arag_sjag                     | 5HZ |
| pvtaimpres                    | 5HZ |
| abic_impm                     | 5IA |
| arag_exon                     | 5IB |
| arag_impg                     | 5IC |
| frag_fore                     | 5ID |
| arag_pvce                     | 5IE |
| arag_defi                     | 5IF |
| pveximpres                    | 5IG |
| nrag_exon                     | 5IH |
| nrag_impg                     | 5II |
| nbic_pvce                     | 5IK |
| nrag_defi                     | 5IL |
| nrag_ajag                     | 5IM |
| frag_exon                     | 5IN |
| frag_impo                     | 5IO |
| mbnc_exon                     | 5IP |
| mbnc_impo                     | 5IQ |
| mbnc_pvce                     | 5IR |
| mbnc_mvlt                     | 5IS |
| mbnc_pvct                     | 5IV |
| frag_pvct                     | 5IW |
| frag_pvce                     | 5IX |
| revimpres                     | 5IY |
| arag_sjag                     | 5IZ |
| pvtaimpres                    | 5IZ |
| abic_impm                     | 5JA |
| arag_exon                     | 5JB |
| arag_impg                     | 5JC |
| frag_fore                     | 5JD |
| arag_pvce                     | 5JE |
| arag_defi                     | 5JF |
| cncn_aimp                     | 5JG |
| nrag_exon                     | 5JH |
| nrag_impg                     | 5JI |
| cncn_adef                     | 5JJ |
| nrag_pvce                     | 5JK |
| cncn_exon                     | 5JK |
| nrag_defi                     | 5JL |
| nrag_ajag                     | 5JM |
| frag_exon                     | 5JN |
| frag_impo                     | 5JO |
| mbnc_exon                     | 5JP |
| mbnc_impo                     | 5JQ |
| mbnc_pvce                     | 5JR |
| mbnc_mvlt                     | 5JS |
| mbnc_pvct                     | 5JV |
| frag_pvct                     | 5JW |
| frag_pvce                     | 5JX |
| revimpres                     | 5JY |
| arag_sjag                     | 5JZ |
| pvtaimpres                    | 5JZ |
| nbic_impm                     | 5KA |
| abic_exon                     | 5KB |
| abic_impn                     | 5KC |
| abic_imps                     | 5KD |
| abic_pvce                     | 5KE |
| abic_defn                     | 5KF |
| abic_defs                     | 5KG |
| nbic_exon                     | 5KH |
| nbic_impn                     | 5KI |
| nbic_imps                     | 5KJ |
| nbic_mvct                     | 5KJ |
| nbic_pvce                     | 5KK |
| nbic_defn                     | 5KL |
| nbic_defs                     | 5KM |
| mbic_exon                     | 5KN |
| mbic_impv                     | 5KO |
| mbic_imps                     | 5KP |
| mbic_pvce                     | 5KQ |
| mbic_mvlt                     | 5KR |
| nbic_apch                     | 5KS |
| mncn_impo                     | 5KU |
| mncn_pvce                     | 5KV |
| mncn_mvlt                     | 5KW |
| mbic_pvct                     | 5KX |
| mncn_pvct                     | 5KY |
| mbnc_mvct                     | 5KZ |
| nbic_impm                     | 5LA |
| abic_exon                     | 5LB |
| abic_impn                     | 5LC |
| abic_imps                     | 5LD |
| abic_pvce                     | 5LE |
| abic_defn                     | 5LF |
| abic_defs                     | 5LG |
| nbic_exon                     | 5LH |
| nbic_impn                     | 5LI |
| nbic_imps                     | 5LJ |
| nbic_mvct                     | 5LJ |
| nrag_pvce                     | 5LK |
| cncn_exon                     | 5LK |
| nbic_defn                     | 5LL |
| nbic_defs                     | 5LM |
| mbic_exon                     | 5LN |
| mbic_impv                     | 5LO |
| mbic_imps                     | 5LP |
| mbic_pvce                     | 5LQ |
| mbic_mvlt                     | 5LR |
| nbic_apch                     | 5LS |
| mncn_impo                     | 5LU |
| mncn_pvce                     | 5LV |
| mncn_mvlt                     | 5LW |
| mbic_pvct                     | 5LX |
| mncn_pvct                     | 5LY |
| mbnc_mvct                     | 5LZ |
| nbic_impm                     | 5MA |
| abic_exon                     | 5MB |
| abic_impn                     | 5MC |
| abic_imps                     | 5MD |
| abic_pvce                     | 5ME |
| abic_defn                     | 5MF |
| abic_defs                     | 5MG |
| nbic_exon                     | 5MH |
| nbic_impn                     | 5MI |
| nbic_imps                     | 5MJ |
| nbic_mvct                     | 5MJ |
| nbic_pvce                     | 5MK |
| nbic_defn                     | 5ML |
| nbic_defs                     | 5MM |
| mbic_exon                     | 5MN |
| mbic_impv                     | 5MO |
| mbic_imps                     | 5MP |
| mbic_pvce                     | 5MQ |
| mbic_mvlt                     | 5MR |
| nbic_apch                     | 5MS |
| mncn_impo                     | 5MU |
| mncn_pvce                     | 5MV |
| mncn_mvlt                     | 5MW |
| mbic_pvct                     | 5MX |
| mncn_pvct                     | 5MY |
| mbnc_mvct                     | 5MZ |
| alnp_imps                     | 5NA |
| aacc_exon                     | 5NB |
| aacc_impn                     | 5NC |
| aacc_imps                     | 5ND |
| aacc_pvce                     | 5NE |
| aacc_defn                     | 5NF |
| aacc_gits                     | 5NG |
| aacc_defs                     | 5NG |
| nacc_exon                     | 5NH |
| nacc_impn                     | 5NI |
| nacc_meup                     | 5NJ |
| nacc_pvce                     | 5NK |
| nacc_defn                     | 5NL |
| nacc_defs                     | 5NM |
| macc_exon                     | 5NN |
| macc_impv                     | 5NO |
| macc_imps                     | 5NP |
| macc_pvce                     | 5NQ |
| macc_mvlt                     | 5NR |
| cncn_bene                     | 5NS |
| cncn_pvce                     | 5NT |
| cncn_defi                     | 5NU |
| ppe_du_ns                     | 5NV |
| ppe_tp_ns                     | 5NW |
| macc_pvct                     | 5NX |
| alnp_defs                     | 5NY |
| nlnp_defs                     | 5NZ |
| alnp_imps                     | 5OA |
| aacc_exon                     | 5OB |
| aacc_impn                     | 5OC |
| aacc_imps                     | 5OD |
| aacc_pvce                     | 5OE |
| aacc_defn                     | 5OF |
| aacc_gits                     | 5OG |
| aacc_defs                     | 5OG |
| nacc_exon                     | 5OH |
| nacc_impn                     | 5OI |
| nacc_meup                     | 5OJ |
| nacc_pvce                     | 5OK |
| nacc_defn                     | 5OL |
| nacc_defs                     | 5OM |
| macc_exon                     | 5ON |
| macc_impv                     | 5OO |
| macc_imps                     | 5OP |
| macc_pvce                     | 5OQ |
| macc_mvlt                     | 5OR |
| cncn_bene                     | 5OS |
| cncn_pvce                     | 5OT |
| cncn_defi                     | 5OU |
| ppe_du_ns                     | 5OV |
| ppe_tp_ns                     | 5OW |
| macc_pvct                     | 5OX |
| alnp_defs                     | 5OY |
| nlnp_defs                     | 5OZ |
| alnp_imps                     | 5PA |
| aacc_exon                     | 5PB |
| aacc_impn                     | 5PC |
| aacc_imps                     | 5PD |
| aacc_pvce                     | 5PE |
| aacc_defn                     | 5PF |
| aacc_gits                     | 5PG |
| aacc_defs                     | 5PG |
| nacc_exon                     | 5PH |
| nacc_impn                     | 5PI |
| nacc_meup                     | 5PJ |
| nacc_pvce                     | 5PK |
| nacc_defn                     | 5PL |
| nacc_defs                     | 5PM |
| macc_exon                     | 5PN |
| macc_impv                     | 5PO |
| macc_imps                     | 5PP |
| macc_pvce                     | 5PQ |
| macc_mvlt                     | 5PR |
| ppe_du_ns                     | 5PV |
| ppe_tp_ns                     | 5PW |
| macc_pvct                     | 5PX |
| alnp_defs                     | 5PY |
| nlnp_defs                     | 5PZ |
| abic_defm                     | 5QA |
| abnc_exon                     | 5QB |
| abnc_impo                     | 5QC |
| abnc_pvce                     | 5QD |
| abnc_defi                     | 5QE |
| nbnc_exon                     | 5QH |
| nbnc_impo                     | 5QI |
| nbnc_pvce                     | 5QJ |
| nbnc_defi                     | 5QK |
| f5qm                          | 5QM |
| abic_defm                     | 5RA |
| abnc_exon                     | 5RB |
| abnc_impo                     | 5RC |
| abnc_pvce                     | 5RD |
| abnc_defi                     | 5RE |
| cncn_aimp                     | 5RF |
| cncn_adef                     | 5RG |
| nbnc_exon                     | 5RH |
| nbnc_impo                     | 5RI |
| nbnc_pvce                     | 5RJ |
| nbnc_defi                     | 5RK |
| f5qm                          | 5RM |
| abic_defm                     | 5SA |
| abnc_exon                     | 5SB |
| abnc_impo                     | 5SC |
| abnc_pvce                     | 5SD |
| abnc_defi                     | 5SE |
| cncn_aimp                     | 5SF |
| cncn_adef                     | 5SG |
| nbnc_exon                     | 5SH |
| nbnc_impo                     | 5SI |
| nbnc_pvce                     | 5SJ |
| nbnc_defi                     | 5SK |
| cncn_bene                     | 5SN |
| cncn_pvce                     | 5SO |
| cncn_defi                     | 5SP |
| cncn_jcre                     | 5SV |
| cncn_jcre                     | 5SW |
| cncn_jcre                     | 5SX |
| ebic_impv                     | 5TA |
| ebic_imps                     | 5TB |
| cncn_info                     | 5TC |
| ebnc_impo                     | 5TE |
| abnc_proc                     | 5TF |
| mncn_exon                     | 5TH |
| nbnc_proc                     | 5TI |
| ebic_impv                     | 5UA |
| ebic_imps                     | 5UB |
| cncn_info                     | 5UC |
| ebnc_impo                     | 5UE |
| abnc_proc                     | 5UF |
| mncn_exon                     | 5UH |
| nbnc_proc                     | 5UI |
| ebic_impv                     | 5VA |
| ebic_imps                     | 5VB |
| cncn_info                     | 5VC |
| ebnc_impo                     | 5VE |
| abnc_proc                     | 5VF |
| mncn_exon                     | 5VH |
| nbnc_proc                     | 5VI |
| f6ps                          | 6PS |
| f6ps                          | 6PT |
| f6ps                          | 6PU |
| f6rs                          | 6RS |
| f6rs                          | 6RT |
| f6rs                          | 6RU |
| f6ss                          | 6SS |
| f6ss                          | 6ST |
| f6ss                          | 6SU |
| f7ac                          | 7AC |
| f7ac                          | 7AE |
| f7ac                          | 7AG |
| f8vm                          | 8UM |
| f8vm                          | 8VM |
| f8vm                          | 8WM |

**Comment by PhunkyBob** [comment]
Et pour info, j'ai généré la correspondance comme ça : 

```
directory_in_str = "C:/Python Scripts/openfisca-france/openfisca_france/model/"
pathlist = Path(directory_in_str).glob('**/*.py')
for path in pathlist:
    path_in_str = str(path)
    with open(path_in_str, 'r') as content_file:
        content = content + content_file.read()


cerfa_fields = {}

all_classes = re.findall(r"class (.+?)\(", content)
for c in all_classes:
    c_content = re.findall(r"class " + c + "\((.*?)class", content.replace("\n", "\t") + "class")[0]
    cerfa_field = re.findall(r'cerfa_field\s+=\s+{([^}]+)', c_content)
    if cerfa_field:
        cerfa_fields[c] = re.findall(r'"(\w+)"', cerfa_field[0])

for c in cerfa_fields:
    for f in cerfa_fields[c]:
        print(f"{c}\t{f}")
```

**Comment by tbelhalfaoui** [comment]
Bonjour,
Si cela peut servir à quelqu'un, voilà le code que j'ai utilisé pour récupérer la liste des cases (en listant toutes les classes qui héritent de `Variable`). Ca permet en plus d'avoir la description en français de la case et le type de la variable :)

```python
import pkgutil
from openfisca_france import model
from openfisca_france.model.base import Variable

# Import all modules from OpenFisca-France model (so that __subclass__ finds them)
__all__ = []
for loader, module_name, is_pkg in pkgutil.walk_packages(model.__path__):
    __all__.append(module_name)
    _module = loader.find_module(module_name).load_module(module_name)
    globals()[module_name] = _module

variables = []
for cls in Variable.__subclasses__():
    try:
        cerfa = cls.cerfa_field
    except AttributeError:
        continue
    if isinstance(cerfa, dict):
        boxes = [cerfa[k] for k in sorted(cerfa)]
    elif isinstance(cerfa, str):
        boxes = [cerfa]
    else:
        raise ValueError("cerfa_field is neither a dict nor a string.")
    variable = {
        'boxes': boxes,
        'type': cls.value_type.__name__,
        'description': getattr(cls, 'label', None),
    }
    variables.append(variable)
```
