### ISSUE TITLE
[Question] Quel est le champ qui retourne le taux marginal d'impôsition ? 

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1386]
Bonjour,

Je trouve bien le "taux_moyen_imposition", mais je souhaite savoir la tranche marginale.

Je ne trouve pas le champ dans la documentation. 
J'ai essayé de regarder les formules qui utilisent "impot_revenu.bareme", mais en vain.

**Comment by PhunkyBob** [comment]
Workaround :
```
	SI (ir_brut == 0)
	ALORS 
		0
	SINON 
		nb_demi_part_sup = (nbptr - nb_adult) * 2
		SI(ir_ss_qf - ir_brut > nb_demi_part_sup * 1551)
		ALORS 
			tranche(rni / nb_adult)
		SINON
			tranche(rni / nbptr)
```

**Comment by benjello** [comment]
Merci @PhunkyBob pour votre intérêt et vos efforts.

Je vous conseille d'utiliser l'objet `bareme` et de comparer `(rni / nptr)` aux seuils des tranches pour récupérer le taux marginal (vous pouvez vous inspirer de `ir_brut`). Cela vaudrait le coup d'enrichir l'object `TaxScale` dans openfisca-core pour qu'il retourne directement le taux marginal.

Je vais essayer de trouver un peu de temps pour le mettre en oeuvre (sans garantie) mais vous pouvez déjà essayer en rajoutant une méthode [ici](https://github.com/openfisca/openfisca-core/blob/273e17b65ccbe6941aa5576140d9c880990483bc/openfisca_core/taxscales.py#L204) en vous inspirant de la méthode `calc`.

**Comment by PhunkyBob** [comment]
Malheureusement, cela dépasse mes compétences... :'(

**Comment by benjello** [comment]
@PhunkyBob : je viens de créer les méthodes génériques. Vous pourrez désormais (dès que la PR https://github.com/openfisca/openfisca-core/pull/920 sera acceptée) ajouter très facilement des variables donnant la tranche et le taux marginal applicable à une base taxable.

**Comment by izneo-get** [comment]
Merci beaucoup !

**Comment by PhunkyBob** [comment]
Merci beaucoup !
Quel champ devrais-je appeler dans l'API ?

**Comment by benjello** [comment]
Il faut coder la variable (champ à appeler par l'API). C'est désormais très facile car les méthodes pour extraire l'index de la tranche d'impôt et le taux marginal d'imposition existent dans `openfisca-core` ((dès que la PR https://github.com/openfisca/openfisca-core/pull/920 sera acceptée). Il suffit de s'inspirer de la variable `ir_brut`. Je vais essayer de trouver un peu de temps pour le faire mais je suis sûr que vous pouvez y arriver seul ;-) .
