### ISSUE TITLE
Problème de calcul de part quand enfant handicapé

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1389]
Bonjour,

Je pense qu'il y a une erreur de calcul du nombre de parts ("nbptr").
Lorsque je déclare un couple avec 2 enfants dont 1 handicapé, je m'attends à avoir 3.5 parts.

Or la requête suivante :
```
{
  "individus": {
    "Parent 1": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Parent 2": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Enfant 1": {
		"handicap": {
			"2018-12" : true
		}
	}
	,
    "Enfant 2": {}
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Parent 1",
        "Parent 2"
      ],
      "personnes_a_charge": [
        "Enfant 1",
		"Enfant 2"
      ],
		"nbptr": {
		"2018": null
		}
    }
  }
}
```
retourne 4 parts, la requête
```
{
  "individus": {
    "Parent 1": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Parent 2": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Enfant 1": {
		"invalidite": {
			"2018-01" : true
		}
	},
	"Enfant 2" : {}
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Parent 1",
        "Parent 2"
      ],
      "personnes_a_charge": [
        "Enfant 1",
		"Enfant 2"
      ],
		"nbptr": {
		"2018": null
		}
    }
  }
}
```
en retourne 3 et la requête 

```
{
  "individus": {
    "Parent 1": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Parent 2": {
      "revenu_assimile_salaire": {
        "2018": 100000
      }
    },
    "Enfant 1": {
		"handicap": {
			"2018-12" : true
		},
		"invalidite": {
			"2018-01" : true
		}
	},
	"Enfant 2" : {}
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Parent 1",
        "Parent 2"
      ],
      "personnes_a_charge": [
        "Enfant 1",
		"Enfant 2"
      ],
		"nbptr": {
		"2018": null
		}
    }
  }
}

```
en retourne 4.5.

**Comment by PhunkyBob** [comment]
Désolé, je viens de comprendre que les enfants sont considérés comme des adultes quand on ne précise pas leur date de naissance.

**Comment by guillett** [comment]
Salut @PhunkyBob, c'est top que le problème n'en soit finalement pas un.
Par curiosité, dans quel cadre utilisez-vous OpenFisca ?
On cherche à en savoir plus sur les utilisateurs.
Bonne journée,
Thomas

**Comment by PhunkyBob** [comment]
Dans le cadre d'un projet, j'ai besoin de pouvoir faire une estimation de l'IR en fonction des revenus et du nombre d'enfants. 
J'avais 3 solutions : 
- redévelopper tout le moteur de calcul
- faire un appel sauvage à https://www3.impots.gouv.fr/simulateur/calcul_impot/2019/simplifie/index.htm (ça fonctionne très bien)
- utiliser une API existante

J'ai opté pour la solution OpenFisca, mais j'avoue que c'est parfois un peu compliqué tellement elle est complète.
