### ISSUE TITLE
Calcul "reduction_ss_condition_revenus" incorrect ?

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1390]
Bonjour,

Je constate un écart entre le résultat du champ "reduction_ss_condition_revenus" d'OpenFisca et le montant retournée par le site des impôts.

Exemple : 
```
{
  "individus": {
    "Parent 1": {
      "revenu_assimile_pension": {
        "2018": 25000
      },
      "age": {
		"2018": 65
	}
    },
    "Parent 2": {
      "revenu_assimile_pension": {
        "2018": 25000
      },
      "age": {
		"2018": 65
	}
    },
    "Enfant 1": {
	"age": {
		"2018": 17
	}
	}
	,
    "Enfant 2": {
	"age": {
		"2018": 16
	}
	}
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Parent 1",
        "Parent 2"
      ],
      "personnes_a_charge": [
        "Enfant 1",
		"Enfant 2"
      ],
	  "ip_net": {
		"2018": null
		},
		"reduction_ss_condition_revenus": {
		"2018": null
		}
    }
  }
}
```
retourne 
```
"reduction_ss_condition_revenus": {
                "2018": 171.49345
            }
``` 
alors que [le site des impôts](https://www3.impots.gouv.fr/simulateur/cgi-bin/calc-2019.cgi?0AX=&0AY=&0AZ=&0AH=&simplifie=1&pre_0AXJ=&pre_0AXM=&pre_situation_famille=M&pre_0AAJ=&pre_0AAM=&pre_0AYJ=&pre_0AYM=&pre_0AZJ=&pre_0AZM=&pre_situation_residence=M&0DA=1954&0DB=1954&0CF=2&0F0=2002&0F1=2003&0F2=&0F3=&0F4=&0F5=&0CG=&0G0=&0G1=&0G2=&0CH=&0H1=&0H2=&0H3=&0H4=&0H5=&0H6=&0CI=&0I1=&0I2=&0I3=&0CR=&0R0=&0R1=&0R2=&0DJ=&0DN=&1AJ=&1BJ=&1CJ=&1DJ=&1AA=&1BA=&1CA=&1DA=&1GA=&1HA=&1IA=&1JA=&1GF=&1HF=&1IF=&1JF=&1AP=&1BP=&1CP=&1DP=&1AK=&1BK=&1CK=&1DK=&1AF=&1BF=&1CF=&1DF=&1AG=&1BG=&1CG=&1DG=&1AX=&1BX=&1CX=&1DX=&1AS=25000&1BS=25000&1CS=&1DS=&1AT=&1BT=&1AZ=&1BZ=&1CZ=&1DZ=&1AO=&1BO=&1CO=&1DO=&1AL=&1BL=&1CL=&1DL=&1AM=&1BM=&1CM=&1DM=&1AD=&1BD=&1CD=&1DD=&1AW=&1BW=&1CW=&1DW=&1AR=&1BR=&1CR=&1DR=&1AU=&1BU=&1CU=&1DU=&2DH=&2CH=&2UU=&2VV=&2WW=&2XX=&2YY=&2ZZ=&2DC=&2FU=&2TS=&2GO=&2TR=&2TT=&2TU=&2TV=&2TW=&2CG=&2BH=&2CA=&2AB=&2CK=&2AA=&2AL=&2AM=&2AN=&2AQ=&2AR=&2DM=&2VM=&2VN=&2VO=&2VP=&2VQ=&3VG=&3VH=&4BE=&4BK=&4XD=&4BA=&4BL=&4BB=&4BC=&4BD=&4XA=&4XB=&4XC=&0XX=&6DE=&6GI=&6GJ=&6EL=&6EM=&6GP=&6GU=&6DD=&6RS=&6RT=&6RU=&APS=&APT=&APU=&BPS=&CPS=&DPS=&BPT=&CPT=&DPT=&BPU=&CPU=&DPU=&6QS=&6QT=&6QU=&7UD=&7UF=&7UH=&7XS=&7XT=&7XU=&7XW=&7XY=&7VA=&7VC=&7AC=&7AE=&7AG=&7DB=&7DL=&7VV=&7VT=&7VX=&7CD=&7CE=&7GA=&7GE=&7GB=&7GF=&7GC=&7GG=&7EA=&7EB=&7EC=&7ED=&7EF=&7EG=&7GZ=&7UK=&7VO=&7TD=&7WN=&7WO=&7WM=&7WP=&7CB=&7AA=&7AO=&7AD=&7AF=&7AH=&7AK=&7AL=&7AP=&7AM=&7AN=&7AQ=&7AR=&7AV=&7AX=&7AS=&7AY=&7AZ=&7BB=&7BC=&7BM=&7BD=&7BE=&7BF=&7BH=&7BK=&7BL=&7WJ=&7WI=&7WL=&8UT=&8TF=&8TI=&8TK=) retourne 343, soit exactement le double.

**Comment by maukoquiroga** [comment]
Merci @PhunkyBob ! @benjello en as-tu une idée ? cc @openfisca/france-contrib-ipp

**Comment by benjello** [comment]
@claireleroy pourrais-tu vérifier cela ?
Merci !

**Comment by claireleroy** [comment]
Merci @PhunkyBob ! Effectivement je pense qu'il y a une erreur dans le code de la réduction...

```
plafond1 = P.seuil1 * nb_adult + P.seuil_maj_enf * 2 * (nb_parts - nb_adult)
plafond2 = P.seuil2 * nb_adult + P.seuil_maj_enf * 2 * (nb_parts - nb_adult)
reduction1 = P.taux * ir_apres_plaf_qf_et_decote
reduction2 = (P.taux * ir_apres_plaf_qf_et_decote * (plafond2 - rfr)) / ((plafond2 - plafond1) * nb_adult)
```

Dans la dernière ligne de code, la multiplication par `nb_adult` est de trop car les variables `plafond1` et `plafond2` intègrent déjà la dimension familiale des plafonds. Je peux ouvrir une merge request pour corriger cela.

**Comment by claireleroy** [comment]
@PhunkyBob J'ai ajouté le cas-type que tu utilises dans les tests du coup (`tests/calculateur_impots/yaml`) !

**Comment by PhunkyBob** [comment]
Merci !

**Comment by maukoquiroga** [comment]
Merci !!!
