### ISSUE TITLE
"impot_revenu.tspr.abatpro.max" pas à jour

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1391]
Bonjour,

La variable [impot_revenu.tspr.abatpro.max](https://fr.openfisca.org/legislation/impot_revenu.tspr.abatpro.max) est définie comme étant 

```
From 01/01/2017 | 12,305
```
Or en 2018, l'abattement maximum est de 12502 EUR (cf. [site des impôts](https://www.impots.gouv.fr/portail/particulier/questions/comment-puis-je-beneficier-de-la-deduction-forfaitaire-de-10))

Il faudrait modifier le fichier
https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/impot_revenu/tspr/abatpro/max.yaml

pour lui rajouter : 
```
2018-01-01:
    value: 12502.0
```

**Comment by maukoquiroga** [comment]
Bonjour @PhunkyBob et merci pour votre contribution !

Pensez-vous pouvoir créer une [_pull request_](https://github.com/openfisca/openfisca-france/edit/master/openfisca_france/parameters/impot_revenu/tspr/abatpro/max.yaml) avec la revalorisation ci-décrite ?

**Comment by PhunkyBob** [comment]
Je n'ai malheureusement aucun moyen de tester une éventuelle modification que je pourrais faire.

**Comment by maukoquiroga** [comment]
Les tests sont toujours bienvenus, mais pas rédhibitoires pour proposer une contribution : d'autres contributeurs (moi, par exemple), au moment d'en faire la _review_, pourront vous montrer comment ajouter des scénarios de test, s'il en faut.

**Comment by PhunkyBob** [comment]
Le fichier est à jour.
