### ISSUE TITLE
Calcul du nombre de part pour un veuf avec enfant en garde alternée

### ISSUE THREAD

**Issue by PhunkyBob** [openfisca/openfisca-france#1418]
Bonjour,

Je pense qu'il y a une erreur de calcul du nombre de part (nbptr) dans un cas un peu tordu : 
Un adulte a un enfant d'une précédente union. Séparé, il partage la garde de l'enfant avec son ancien conjoint.
Il se remarie et son nouveau conjoint décède.
Cet adulte est donc : 
- veuf
- avec un enfant en garde alternée

### Qu'ai-je fait ?
```
{
    "individus": {
        "Adulte 1": {
            "statut_marital": {
                "month:2018-01:12": "veuf"
            }
        },
        "Enfant 1": {
            "age": {
                "2018": 10
            },
            "garde_alternee": {
                "2018-01": true
            }
        }
    },
    "foyers_fiscaux": {
        "foyer_fiscal_1": {
            "declarants": [
                "Adulte 1"
            ],
            "personnes_a_charge": [
                "Enfant 1"
            ],
            "nbptr": {
                "2018": null
            }
        }
    }
}
```

### À quoi m'attendais-je ?
D'après le simulateur des impôts, il suffit d'avoir une personne en garde alternée pour bénéficier de la part de veuvage supplémentaire : 
```
https://www3.impots.gouv.fr/simulateur/cgi-bin/calc-2019.cgi?pre_situation_residence=M&pre_situation_famille=V&0DA=1970&0CH=1&0H0=2010
```
retourne : "nombre de parts :  2.25".

### Que s'est-il passé en réalité ?
OpenFisca retourne 1.25, soit la part de veuvage en moins.

```
            "nbptr": {
                "2018": 1.25
            }
```

### Voici des informations qui peuvent aider à reproduire le problème :
Dans la fonction "nbptr"
https://fr.openfisca.org/legislation/nbptr?q=nbptr
la ligne 
```
nb_parts_veuf = 1 + quotient_familial.veuf * has_pac + enf + n2 + n3 + n5 + n6
```
devrait être à mon avis quelque chose comme 
```
nb_parts_veuf = 1 + quotient_familial.veuf * (has_pac | has_alt) + enf + n2 + n3 + n5 + n6
```

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [x] Autre : utilisateur occasionnel d'OpenFisca.

**Comment by benjello** [comment]
Good catch @PhunkyBob !
Si ce n'est pas indiscret comment êtes-vous arrivé à ce cas un peu tordu ?

Et bien sûr n'hésitez pas à proposer une demande de fusion (pull request) !

**Comment by PhunkyBob** [comment]
> Si ce n'est pas indiscret comment êtes-vous arrivé à ce cas un peu tordu ?

En lisant un article qui donnait un tableau des nombre de parts en fonction des situations, j'ai remarqué qu'il n'y avait aucun cas où on était à la fois veuf et avec des enfants en garde alternée, alors que pour moi, ce n'est pas incompatible. J'ai voulu savoir quel était le calcul et je suis tombé sur 2 résultats différents entre OF et le site des impôts.


> Et bien sûr n'hésitez pas à proposer une demande de fusion (pull request) !

Comme je ne suis que simple utilisateur d'OF (j'utilise l'API publique), je n'ai aucun moyen de faire des modifications en local et les tester.

**Comment by benjello** [comment]
@PhunkyBob : il est toujours possible de faire la modification et d'ajouter un test, les tests seront automatiquement lancés lors du processus d'intégration continue.

**Comment by PhunkyBob** [comment]
Je ne me sens pas assez chanceux pour faire des modifications à l'aveugle + ajouter un test rédigé à l'aveugle sur cette modification, le tout dans un langage que je ne connais pas assez.
