### ISSUE TITLE
Take monthly work time variations into account for `alleg_fillon`

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#142]
As shown on Paie's [Fillon simulator prototype](http://paie.sgmap.fr/fillon/) ([long-lived link](https://github.com/sgmap/allegement-fillon/blob/a0d839ed5116abcb9cee014fb79c68dd430f3c63/index.html)), the “réduction Fillon” (`alleg_fillon`) is impacted by all variations in the volume of hours worked in a month. AFAIK, this is not currently taken into account by OpenFisca.

Here are some of the elements that need be handled:
- [ ] IJSS (assurance maladie)
- [ ] days off (jours de congé)
- [ ] unpaid days off (absence non payée)
- [ ] additional hours (heures supplémentaires)
- …

You can find a rather complete reference on the [URSSAF website](http://www.urssaf.fr/employeurs/comite_dentreprise/vos_salaries_-_les_mesures_daide_a_lemploi/reduction_dite_fillon_04.html).

**Comment by MattiSG** [comment]
Issue ayant plus de 2 ans, pas de travail actif, je ferme.
Si @laem a avancé sur le sujet, ne pas hésiter à commenter.

**Comment by laem** [comment]
C'est finalement passer d'une simulation à un logiciel de paie, c'est toujours hors-champ.
