### ISSUE TITLE
Duplication de paramètres sur le plafonnement du quotient familial ? 

### ISSUE THREAD

**Issue by magemax** [openfisca/openfisca-france#1421]
ce fichier https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/impot_revenu/plafond_qf/veuf.yaml   semble reprendre https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/impot_revenu/plafond_qf/reduc_postplafond_veuf.yaml    

Cependant je ne vois aucune reference dans le code au premier fichier.  Sont ce mes yeux ou ce fichier pourrait il être supprimé? il y a aussi dans le même folder le general.yaml qui semble avoir le même problème : identique (avec plus d'histo) que maries_ou_pacses.yaml,  mais general.yaml est inutilisé dans le code. 

Aussi, veuf.yaml semble construit à partir d'un barême IPP dont je ne suis pas sûr du bien-fondé (j'ai l'impression que le rôle de ce paramètre avant 2012 n'est pas le même qu'après 2012, mais je ne suis pas sûr à 100%).

Tous ces paramètres apparaissent dans l'historique de l'article 197 du CGI

**Comment by benjello** [comment]
@claireleroy : pourrais-tu jeter un oiel stp. le but étant de faire le nettoyage qui permettrait une meilleur convergence à terme avec les barèmes IPP. Donc conservé plutôt le barème IPP mais en le complétant / enrichissant s'il n'y a pas de problèmes et / ou en adaptant openfisca si besoin.

**Comment by claireleroy** [comment]
@benjello @magemax je regarde cela aujourd'hui :)

**Comment by claireleroy** [comment]
Si je comprends bien, la réduction supplémentaire accordée aux veufs ayant des personnes à charge a été crée à partir de l'imposition des revenus 2012 (voir [article 4 de la LF pour 2012](https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=921EEB18EFE352A3B3548DCECAB9C8C1.tplgfr33s_3?cidTexte=JORFTEXT000026856853&idArticle=&categorieLien=id)). 

Je suis donc d'accord avec @magemax, le barème IPP correspondant et `veuf.yaml` qui en découle ont un souci. Ce barème ne devrait commencer qu'en 2012. Le barème `reduc_postplafond_veuf.yaml` est quant à lui correct. 

Je propose donc : 
- de supprimer `veuf.yaml` (non utilisé dans tous les cas comme souligné par @magemax)
- et que j'aille corriger côté barèmes IPP le barème en question (et du coup cela ne devrait pas avoir d'effets négatifs sur la convergence des barèmes non @benjello ?)

**Comment by benjello** [comment]
Go @claireleroy.

**Comment by sandcha** [comment]
Au cas où @claireleroy, que ce soit dans `veuf.yaml` ou dans les [barèmes IPP](https://www.ipp.eu/baremes-ipp/impot-sur-le-revenu/calcul_impot_revenu/plaf_qf/) les valeurs `Veuf avec un ou plusieurs enfants à charge` de 2012 aux périodes plus tardives semblent êtres celles de `Plafond des avantages procurés par demi-part de QF > Général`.

**Comment by claireleroy** [comment]
@sandcha Oui effectivement, je pense que c'est une erreur j'ai corrigé dans les barèmes IPP. @magemax je peux te laisser t'occuper de la suppression sur Openfisca-france ?
