### ISSUE TITLE
DateCol: overall max and min 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#147]
Today default is 1970-01-01
And we test dates to be between 1870-1-1 and 2099-12-31.
Should we have a -infinity and a +infinity that are larger ?
Think inheritance, pension, ...
And I need those for default date for contrat_de_travail_arrivee contrat_de_travail_depart

**Comment by benjello** [comment]
Might be moved to openfisca-core ...

**Comment by MattiSG** [comment]
Definitely a validation question for openfisca/openfisca-core, but I'm not opening an issue there until there's a use case :wink:
