### ISSUE TITLE
Fiche de paie

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#148]
TODO-list pour finir la fiche de paie 

Cotisations et assimilées manquantes
- [x] formation CDD
- [x] forfait social
- [ ] taxe handicapés
- [x] ticket repas
- [x] versement transport (data from http://www.urssaf.fr/employeurs/baremes/baremes/versement_transport_01.html)
- [x] GMP

Gestion des contrats de travail et durée

Identifier les règles d'arrrondi
- [x] Sur les assiettes
- [ ] Sur les montants

Refactoring des assiettes (mutualiser)
- [ ] assiette allégement de charges : ne reste plus que la gestion des heures supplémentaires en historique  
- [ ] assiette cotisations sociales : ne reste plus que la gestion des heures supplémentaires en historique
- [x] assiette csg/crds salaires
- [ ] assiette forfait social

Gestion de la temporalité du calcul sur la fiche de paie 
- [x] allègement Fillon
- [ ] _toutes_ les cotisations sociales
- [x] taxe sur les salaires

**Comment by MattiSG** [comment]
@benjello Cette liste est-elle à jour ?

**Comment by benjello** [comment]
Maintenant oui

**Comment by MattiSG** [comment]
Cette liste ne sera probablement jamais exhaustive, puisque la législation continue à évoluer. Le bon espace de représentation pour une liste de ce type est plutôt un wiki ou autre document partagé. Une issue de ce type ne serait jamais fermée.

Je la ferme donc, son contenu peut au besoin être exporté dans tout autre format de représentation plus adapté  :)
