### ISSUE TITLE
Récupération des salaires à des dates différentes selon les individus

### ISSUE THREAD

**Issue by lauradelmas8** [openfisca/openfisca-france#1482]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

J'aimerais développer le simulateur sur la partie "chômage". J'aimerais dans un premier temps calculer le salaire de référence des individus, qui correspondant à la somme des 12 derniers mois de salaires perçus précédent la date à laquelle mon contrat a été rompu (mon dernier jour de salaire). 

Le problème est qu'avec Chloé et Brice, on arrive pas bien à stipuler ces 12 derniers mois par rapport à la date de fin de contrat sachant que cette date est différente pour tous les individus. 

J'espère que c'est assez clair, et que vous pourrez m'aider. 

Je vous mets le lien de mon travail en cours [ici](https://github.com/openfisca/openfisca-france/blob/assurance-chomage/openfisca_france/model/revenus/remplacement/chomage.py)
(C'est encore très brouillon)

Merci beaucoup. 

Je m'identifie plus en tant que :

- [ ] Économiste : je réalise des simulations avec des données.

**Comment by pzuldp** [comment]
je crois que le lien est 
https://github.com/openfisca/openfisca-france/blob/assurance-chomage/openfisca_france/model/revenus/remplacement/chomage.py ?

**Comment by benjello** [comment]
@lauradelmas8 : pourrais-tu préciser la législation ?
Y a-t-il une condition sur la date du dernier contrat ? Par exemple est-ce que cela a un sens de calculer un salaire de référence pour quelqu'un qui a arrêté de travailler depuis 5 ans / 10 ans ?
Notamment les douze derniers mois précédant la date de fin de mon contrat sont-ils limité dans le temps sous une autre forme ?
La somme contient-elle les période non travaillées (salaire nul) ?
Je cherche à limiter l'étendu temporelle à parcourir sachant qu'elle va dépendre de l'individu.

**Comment by benjello** [comment]
@lauradelmas8 : pourrais-tu également ajouter un test qui doit passer pour le salaire_de_reference ?

**Comment by lauradelmas8** [comment]
> je crois que le lien est
> https://github.com/openfisca/openfisca-france/blob/assurance-chomage/openfisca_france/model/revenus/remplacement/chomage.py ?

**Comment by lauradelmas8** [comment]
@pzuldp  oui c'est bien cela, je me suis trompée. Merci.

**Comment by benjello** [comment]
@lauradelmas8 j'avais corrigé le lien. Tu as fermé le ticket. Est-ce volontaire ?

**Comment by lauradelmas8** [comment]
@benjello 

Point législation : 
Pour être éligible à l'ARE (assurance chômage), il faut en résumé en 2012 (l'année qui m'intéresse mais seulement les paramètres changent pour aujourd'hui) : 
-ne pas avoir atteint l'âge légal de la retraite (sauf si elle n'est pas à taux plein) 
-résider en France
-être involontairement privé d'emploi 
-Avoir travaillé 4 mois dans les 18 derniers mois précédent le dernier jour travaillé (date de fin du contrat de travail) pour les moins de 50 ans et avoir travaillé 4 mois dans les 28 derniers mois pour les plus de 50 ans. 

Montant de l'ARE:
L'allocation journalière correspond au montant le plus élevé entre : 
-40,4% du Salaire Journalier de Référence (SJR) + 11,17 €
-57,4% du SJR  
L'allocation maximum ne peut pas dépasser 75% du SJR, et l'allocation minimale ne peut pas être inférieure à 19,53€. 

Le salaire journalier de référence (SJR) est calculé de la manière suivante:
SJR = salaire de référence / nombre de jours travaillés x 1,4
Le salaire de référence correspond à la somme des salaires des 12 mois civils précédant le dernier jour de travail payé.
Le nombre de jours travaillés maximum retenu sur la période de référence est de 261 jours.
Exemple : si vous avez travaillé du 1er janvier 2019 au 31 décembre 2019, c'est-à-dire 261 jours, et avez perçu 25 000 € de rémunération brute, votre salaire journalier de référence est : 25 000 / (261 x 1,4) = 68,42 €.
La somme peut contenir des périodes nulles de revenus car c'est vraiment les 12 mois civils précédant la fin du contrat, d'autant plus qu'on devra diviser cette somme par le nombre de jours travaillés. 

Un individu touchera la même allocation journalière qu'il soit à son 10ème jour de chômage ou 100ème jour (sauf s'il cumule des revenus d'activité réduite). 

Durée d'indemnisation : 
La durée d'indemnisation est égale à la durée d'affiliation (1 jour cotisé = 1 jour indemnisé). Elle ne peut pas être inférieure à 122 jours et supérieure à 730 jours pour les moins de 50 ans et 1095 jours pour les plus de 50 ans. 

Si un individu a arrêté de travailler depuis 5/10 ans, il ne pourra pas toucher les allocations chômage (2 ou 3 ans de durée selon l'âge), donc il n'y a pas de sens à calculer le salaire de référence. 

Si jamais tu as besoin d'autres clarifications, n'hésite pas.

**Comment by lauradelmas8** [comment]
@benjello 
Alors j'ai pas du tout fait exprès de fermer le ticket..

**Comment by benjello** [comment]
@lauradelmas8 : j'ai peut-être pas tout compris mais y a-t-il une limite sur la date du dernier emploi ? Puis-je remonter indéfiniment si je vérifie les uatres conditions. Si je n'ai pas fait valoir mes droits au chômage pendant 10 ans, puis je toucher l'ARE.

**Comment by lauradelmas8** [comment]
En fait, sachant qu'on ne peut toucher qu'au plus 3 ans l'ARE, si j'ai arrêté de travailler il y a 10 ans et que j'avais bien travaillé le temps requis avant pour toucher 3 ans d'allocations, je ne touche plus depuis 7 ans l'ARE. Mais si je décide de ne pas faire valoir de suite mes droits aux allocations chômage, je peux. Seulement, j'ai un délai de 12 mois après la fin de votre contrat de travail pour m'inscrire à Pôle emploi et les faire valoir. Ce délai peut être allongé pour différents motifs survenus pendant ces 12 mois comme une maladie, un accident ou encore une période de stage ou de formation.

**Comment by benjello** [comment]
Je ferme car c'est traité dans #1481.
