### ISSUE TITLE
Importer les références législatives des barèmes IPP

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#152]
Bonjour je suis en train de mettre à jour les paramètre de la loi de finance 2015 qui est parue le 30 décembre 2014.

Pour mettre à jour je prends le texte de loi et vérifie les montants qui changent en faisant des recherches de montants dans le param.xml . Seulement parfois il y a des problèmes d'incertitudes sur quel article correspond à un paramètre, et on perd du temps à chercher à quel paramètre correspond un article de loi. 

Mettre l'article de loi quelque part dans le param.xml permettrait de : gagner du temps pour les mises à jour de paramètres, diminuer le risque d'erreur.

Si on me propose une syntaxe pour inclure le code concerné (e.g code des impôts, décrets, etc), et l'article ( e.g 197bis) dans le xml, je veux bien m'y coller pour l'ensemble des paramètres que je modifierai/actualiserai dans openfisca.

A terme ça pourrait éventuellement servir à proposer aux utilisateurs d'obtenir les sources législatives exactes correspondant à chaque prestation avec le lien sur légifrance ?

Bon année à tous !

**Comment by benjello** [comment]
On devrait arriver à cela quand on parsera les barèmes IPP qui contiennent les références législatives.

**Comment by MattiSG** [comment]
@benjello Du coup, cela est-il le cas maintenant que #566 a été intégré ?

**Comment by benjello** [comment]
Non: les références législatives sont bien parsées et se retrouvent dans les yaml issus des barèmes IPP (excel) mais rien n'est remonté au niveau du XML.
L'idéal serait de définir le nouveau format des paramètres puis d'y intégrer ces références.

**Comment by Morendil** [comment]
Je ferme en faveur de #1164
