### ISSUE TITLE
[CSG] Problèmes observés sur les paramètres liés à la CSG

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1536]
Hello hello !
Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
En travaillant sur le chantier d'harmonisation OpenFisca (https://github.com/openfisca/openfisca-france/issues/1519), j'ai observé plusieurs problèmes ou questionnements. Comme je n'ai pas le temps de m'y plonger, je les note tous ici pour garder une trace.

### Que s'est-il passé ?
Au cours de l'harmonisation, on plonge dans le .yaml de chaque paramètre. Puis on va dans le code pour changer le chemin (vers le nouveau chemin 'harmonisé') de chaque paramètre. En faisant cela, j'ai observé:

1- On a des paramètres qui ne sont pas du tout utilisés dans OpenFisca-France  (nulle part dans le code). Souvent ceux-ci sont en doublons (et seul l'un des doublons est dans le code): 
-- csg.remplacement.allocations_chomage
-- csg.remplacement.retraite
-- csg.remplacement.indemnites_journaliere

2- Certains ne sont pas en doublons, et ne sont pas utilisés dans OpenFisca-France. **Cela veut dire que, même si les paramètres existent (et sont à jour), ils ne sont PAS DU TOUT pris en compte dans le code !**
-- csg.preretraite
-- csg.indemnites_journalieres

3- Dans model/.../prelevements_sociaux/contributions_sociales/remplacement.py:31 , il semble y avoir une faute de frappe dans le code (mais je n'ai pas les connaissances métiers pour le confirmer):

**_Avant harmonisation:_**
_seuil_exoneration = seuils.seuil_rfr1 + (nbptr - 1) * seuils.demi_part_suppl
seuil_reduction = seuils.seuil_de_rfr_2 + (nbptr - 1) * seuils.demi_part_suppl_

Sauf que dans les vieux params,  seuils.demi_part_suppl == seuil.rfr2_demi_part_suppl --> pas de demi-part pour RFR1 ! 

**_D'où, après modif:_**
_seuil_exoneration = seuils.seuil_rfr1 + (nbptr - 1) * seuils.rfr2_demi_part_suppl
seuil_reduction = seuils.seuil_rfr2 + (nbptr - 1) * seuils.rfr2_demi_part_suppl_
 
**_Question: ne serait-ce pas plutôt:_**
_seuil_exoneration = seuils.seuil_rfr1 + (nbptr - 1) * seuils.rfr1_demi_part_suppl
seuil_reduction = seuils.seuil_rfr2 + (nbptr - 1) * seuils.rfr2_demi_part_suppl_   
(Sachant que le rfr1_demi_part_suppl existe côté IPP, et donc dans OFF aussi après harmonisation )
  
4- Avec l'harmonisation, on a de nouveaux paramètres (obtenus côté IPP), qui sont désormais présents dans le repo mais pas dans le code. Faut-il les lister ? Ou la date de last_review suffit à donner cette information ?

### Contexte
Je m'identifie plus en tant que :
- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.

**Comment by benjello** [comment]
@SophieIPP : pourrais-tu jeter un oeil stp ?
cc @bfabre01 @clallemand @pzuldp
