### ISSUE TITLE
indemnités de sécurité sociale

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#155]
Finir l'intégration des indemnités de sécurité sociale:e, AT/MP etc. 
- [x] assiette cotisation sociale,
- [x] assiette CRDS et CSG,
- [ ] intégration dans les salaires imposables
- [ ] gestion des IJ maladie AT/MP etc

**Comment by MattiSG** [comment]
@benjello Des avancées ?  :)

**Comment by MattiSG** [comment]
Issue ayant plus de 2 ans, pas de travail actif, je ferme.
Si @laem a avancé sur le sujet, ne pas hésiter à commenter.
