### ISSUE TITLE
Harmonisation IPP [1/10] - Prélèvements Sociaux

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1597]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section Prélèvements Sociaux** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici: https://www.ipp.eu/baremes-ipp/prelevements-sociaux/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Initialisation: https://github.com/openfisca/openfisca-france/pull/1746
Voici les dossiers en cours de traitement / à traiter: 

1 - Plafond de la Sécurité Sociale
- [x] En cours d'harmonisation (Branche: harmonisation_pss)
- [x] PR harmonisation en cours
- [x] Harmonisation merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1610 )
- [ ] Formules en cours de vérification (Branche: check )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

2 - Contributions Sociales
- [x] En cours d'harmonisation (Branche: harmonisation_csg_crds)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1541 , https://github.com/openfisca/openfisca-france/pull/1595 , https://github.com/openfisca/openfisca-france/pull/1640 , https://github.com/openfisca/openfisca-france/pull/1732 , https://github.com/openfisca/openfisca-france/pull/1743 )
- [x] Harmonisation merged !
- [x] Formules en cours de vérification (Branche: check_harmonisation_contributions_sociales )
- [x] PR check en cours
- [x] Check merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1595 )

3 - Cotisations de Sécurité sociale (SS) du régime général
- [x] En cours d'harmonisation (Branches: harmonisation_cotisations_securite_sociale_regime_general et harmonisation_regime_general_mmid et après la PR cotsoc: harmonisation_cotisations_post_costsoc)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1547 et https://github.com/openfisca/openfisca-france/pull/1553 et https://github.com/openfisca/openfisca-france/pull/1578 , et après la PR cotsoc : https://github.com/openfisca/openfisca-france/pull/1623 , et https://github.com/openfisca/openfisca-france/pull/1759)
- [x] Harmonisation merged !
- [x] Formules et paramètres en cours de vérification (Branche: check_harmonisation_cotisations_regime_general )
- [x] PR check en cours : *Ont été mergés les checks relatifs aux cotisations salariés seulement*. Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1633 . 
- [ ] Check merged ! 

4 - Cotisations au régime de l'assurance chômage
- [x] En cours d'harmonisation (Branche: harmonisation_regime_assurance_chomage)
- [x] PR harmonisation en cours
- [x] Harmonisation merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1613 et https://github.com/openfisca/openfisca-france/pull/1627 et  https://github.com/openfisca/openfisca-france/pull/1740 et https://github.com/openfisca/openfisca-france/pull/1757 )
- [x] Formules en cours de vérification (Branche: check )
- [x] PR check en cours (Lien vers la PR: )
- [x] Check merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1627 )

5 - Régimes complémentaires de retraite (secteur privé)
- [x] En cours d'harmonisation (Branche: harmonisation_and_check_cotsoc_retraites_complementaire)
- [x] PR harmonisation en cours
- [x] Harmonisation merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1619 et https://github.com/openfisca/openfisca-france/pull/1764)
- [x] Formules en cours de vérification
- [x] PR check en cours
- [x] Check merged ! (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1619)

6 - Cotisations du secteur public
- [x] En cours d'harmonisation (Branche: harmonisation-cotsoc-public)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1622 et https://github.com/openfisca/openfisca-france/pull/1656 et https://github.com/openfisca/openfisca-france/pull/1758 )
- [x] Harmonisation merged !
- [x] Formules en cours de vérification
- [x] PR check en cours : *n'ont été checkées et mergées que les cotisations salariales et une partie des cotisations employeurs* (voir le détail des PR pour le détail). Le lien des PR mergées : https://github.com/openfisca/openfisca-france/pull/1608 et https://github.com/openfisca/openfisca-france/pull/1622
- [x] Check merged !

7 - Autres taxes et participations assises sur les salaires
- [x] En cours d'harmonisation (Branche: harmonisation)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1615 , https://github.com/openfisca/openfisca-france/pull/1755)
- [x] Harmonisation merged !
- [x] Formules en cours de vérification (Branche: check )
- [x] PR check en cours (Lien vers la PR: )
- [x] Check merged !

8 - Contributions assises spécifiquement sur les accessoires du salaire
- [x] En cours d'harmonisation (Branche: harmonisation)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1756 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

9 - Cotisations et taxes des indépendants artisans-commerçants
- [x] En cours d'harmonisation (Branche: harmonisation)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1761)
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

10 - Cotisations et taxes des professions libérales
- [x] En cours d'harmonisation (Branche: harmonisation)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1762 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

11 - Réductions de cotisations sociales
- [x] En cours d'harmonisation (Branche: harmonisation_reduction_cotisations_sociales2)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1549 et https://github.com/openfisca/openfisca-france/pull/1763 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

**Comment by pzuldp** [comment]
Bonjour, je vois que quelqu'un.e s'occupe déjà de "cotisation sociale au régime de l'assurance chômage", mais je ne vois pas de branche "harmonisation_regime_assurance_chomage". Est-elle en cours ? qui est dessus ?

**Comment by Sasha-Laniece** [comment]
Hello @pzuldp  c'est moi ! J'ai commencé ce matin et je viens de la pusher.
Pour le moment j'ai juste déplacé tous les fichiers à harmoniser mais je n'ai rien harmonisé encore, je pensais finir demain matin

**Comment by pzuldp** [comment]
ok  @Sasha-Laniece ! pour info je n'avais pas vu cette grande issue vendredi dernier (ni pris encore le temps de lire le guide de contrib, désolé), et j'ai commencé une branche `check_regime_assurance_chomage` (pour vérifier les formules : je peux la re-vérifier quand t'auras mergé l'harmonisation des paramètres).

**Comment by clallemand** [comment]
Bonjour, est ce que ça pose un problème si on fait une seule branche / PR pour à la fois harmoniser et checker un barème ? Car dans la perspective de supprimer le preprocessing (comme discuté sur Slack) les deux sont un peu liés : après avoir modifié l'arborescence, on modifie directement la formule (et donc on la check) et non le preprocessing.

**Comment by Sasha-Laniece** [comment]
> Bonjour, est ce que ça pose un problème si on fait une seule branche / PR pour à la fois harmoniser et checker un barème ? Car dans la perspective de supprimer le preprocessing (comme discuté sur Slack) les deux sont un peu liés : après avoir modifié l'arborescence, on modifie directement la formule (et donc on la check) et non le preprocessing.

Hello ! Non, si tu fais les deux, c-à-d:
- harmoniser, i.e. 
  -- modifier l'arborescence 
  -- mettre les paramètres/barèmes sous leur nouvelle forme avec les metadonnées récupérées côté IPP
  -- ajouter les éventuels paramètres/barèmes de l'IPP qui manqueraient côté OF 

- et checker, i.e. 
  -- vérifier que les formules sont encore justes et les modifier si besoin
  -- (ajouter les metadata - pas encore d'actualité)

Alors une branche devrait suffire. Mais attention, il faut bien traiter TOUS les paramètres d'un dossier, et pas uniquement ceux qui sont dans les formules. 
Et il faudra bien tout préciser sur cette issue.

**Comment by Sasha-Laniece** [comment]
Dans l'harmonisation de cotisations_securite_sociale_regime_general (cf #1623 ) il a été décidé de ne pas créer de barèmes (ou rassembler des barèmes communs) dans un premier temps par souci de vitesse. 
Cela peut être un futur chantier (pour cet hiver?)

**Comment by Sasha-Laniece** [comment]
Harmonisation du dossier réalisée !
