### ISSUE TITLE
Harmonisation IPP [7/10] - Retraite

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1601]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section Retraite** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici: https://www.ipp.eu/baremes-ipp/regimes-de-retraites/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Voici les dossiers en cours de traitement / à traiter: 

1 - Secteur privé
  1.1 - Régime général (CNAV)
  - [ ] En cours d'harmonisation (Branche: harmonisation_)
  - [ ] PR harmonisation en cours (Lien vers la PR: )
  - [ ] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !
  
  1.2 - Régimes complémentaires
  - [ ] En cours d'harmonisation (Branche: harmonisation_)
  - [ ] PR harmonisation en cours (Lien vers la PR: )
  - [ ] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !

2 - Secteur public
- [ ] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: )
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

3 - Indépendants
- [ ] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: )
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

**Comment by benjello** [comment]
Pas besoin de ces barèmes pour openfisca-france.
Je ferme donc @Sasha-Laniece.
