### ISSUE TITLE
Harmonisation IPP [10/10] - Tarifs réglementés de l'énergie

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1606]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section Tarifs réglementés de l'énergie** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici:  https://www.ipp.eu/baremes-ipp/tarifs-reglementes-energie/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Voici les dossiers en cours de traitement / à traiter: 

1 - Tarifs réglementés EDF
- [ ] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: )
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

2 - Tarifs réglementés GDF
- [ ] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: )
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

3 - Prix du fioul domestique
- [ ] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: )
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

**Comment by benjello** [comment]
Pas besoin de ces barèmes pour openfisca-france.
Je ferme donc @Sasha-Laniece.
