### ISSUE TITLE
Restructurer la configuration CircleCI

### ISSUE THREAD

**Issue by HAEKADI** [openfisca/openfisca-france#1643]
Sur la [configuration](https://github.com/openfisca/openfisca-france/blob/master/.circleci/config.yml) `CircleCI`, je constate deux choses :

1. Le job `build` exécute deux tâches à la fois : 

- Installer les dépendances
- Exécuter les tests

Je suggère donc de séparer ce job en 2 voire 3 jobs :

- `build`: qui installe les dépendances
- `test-python`: qui exécute les tests Python
- `test-yaml`: qui exécute les tests yaml

Ceci permettra d'avoir une logique claire d'exécution dans le workflow.

2. Les jobs `lint_yaml_files` et `lint_python_files` dépendent du `build` dans le workflow, ce dernier est très long, vu le temps d'exécution des tests. 

Je propose alors d'enlever cette dépendance et d'exécuter le linting avant le testing. L'objectif étant de donner un retour rapide à l'utilisateur qui, en cas d'erreur sur le linting, peut directement le corriger sans pour autant devoir attendre l'exécution de tous les tests.

**Comment by benjello** [comment]
Merci @HAEKADI d'optimiser les tests !
Cependant je ne suis pas sûr que séquencer le retour du lint et des tests soit optimal pour le développeur.
En effet, quand on code une variable, on la teste en local. 
Les tests viennent essentiellement vérifier qu'il n'y a pas d'effet de bord.
Donc les tests et le linting sont souvent orthogonaux.
Cela peut donc être contre-productif d'obliger le contributeur à corriger les problèmes de linting avant d'avoir accès aux résultats des tests qui nécessiteront un nouveau push alors qu'il pourrait avoir tout en une seule passe (et que les deux étapes sont de toute façon nécessaire).
Par ailleurs le linting est rapide et possible en local.

**Comment by MattiSG** [comment]
Merci pour cette proposition @HAEKADI !

> Je propose alors d'enlever cette dépendance et d'exécuter le linting avant le testing.

Je lis deux choses différentes ici :

1. Retirer la dépendance du linting au `build`.
2. Exécuter le linting avant les tests fonctionnels.

Je suis d'avis de ne simplement pas les ordonnancer, et d'exécuter en parallèle. Pour moi on aurait donc l'organisation suivante :

- `build`, `lint-python` et `lint-yaml` en parallèle.
- `test-python`, `test-yaml` et `test-api` dépendant de `build`.
- `check-version-and-changelog` dépendant du résultat positif de tous les autres éléments, afin d'éviter la coche rouge systématique actuelle.

**Comment by MattiSG** [comment]
Je serais également en faveur d'effectuer une seule tâche `lint` qui vérifierait à la fois les fichiers Python et YAML. D'un point de vue contributeur, je ne suis pas sûr que la différence soit signifiante.

**Comment by HAEKADI** [comment]
Très bien, merci @MattiSG et @benjello ! 
Par contre,  le job `lint` doit dépendre du `build` vu qu'il dépend de l'environnement et de `flake8` en particulier.
