### ISSUE TITLE
salaire_net_a_payer to salsuperbrut always gives 0

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#165]
http://api-test.openfisca.fr/api/1/formula/salsuperbrut?salaire_de_base=1445.38 gives 1983.50.
But http://api-test.openfisca.fr/api/1/formula/salsuperbrut?salaire_net_a_payer=1127.25 gives 0.

How can I get superbrut from net?

**Comment by benjello** [comment]
You have to use salnet as a variable for salaire net. Net à payer and salaire net are actually different. Salaire net is salaire brut - cotisations salariales - CSG - CRDS and salaire net à payer also include (negatively) a few perks your employer may have paid for you (tickets restaurant etc)

For now you can invert salnet ant sali (salaire imposable)

**Comment by MattiSG** [comment]
Thanks a lot for these details!

However, if I try to get `salsuperbrut` (or `salbrut`, or `salaire_de_base`, for what it's worth) and I provide `salnet`, it does not seem to work any better: http://api-test.openfisca.fr/api/1/formula/salsuperbrut?salnet=1445.38 also gives 0  :(

**Comment by benjello** [comment]
@cbenz could you check with Matti (when he will be back) how he could use inversion_revenus in the API
