### ISSUE TITLE
Erreur d'application d'un abattement fiscal sur les AL pour apprentis et stagiaires 

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1660]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais on vient de rencontrer un problème. cc @mtifarine @frtomas 

### Qu'a-t-on fait ?

Des contributeurs ont identifié que la règle de calcul d'`al_revenu_assimile_salaire` intègre un abattement pour les apprentis et les stagiaires : 
https://github.com/openfisca/openfisca-france/blob/0f49b6fe467d0ac6d892a153ae0cafda31fc7e20/openfisca_france/model/prestations/aides_logement.py#L558-L562

### À quoi peut-on s'attendre ?

À ce que des exonérations fiscales soient appliquées au calcul de l'impôt. 
Et à ce que les ressources prises en compte pour les AL soient imposables.

### Que s'est-il passé en réalité ?

La règle d'AL `al_revenu_assimile_salaire` applique des abattements fiscaux sur rémunérations. 
Les exonérations apprenti et stagiaire ne semblent pas figurer dans les règles fiscales d'OpenFisca-france.

### Voici des informations qui peuvent aider :

🔗 [Comment est imposé le salaire d'un apprenti ? / service-public](https://www.service-public.fr/particuliers/vosdroits/F11249)
🔗 [Article 81 bis du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000029236245) (vérifier qu'il s'agit bien de la référence principale)

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [x] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by MattiSG** [comment]
Le revert référencé (https://github.com/openfisca/openfisca-france/commit/110c0ecca5ddbae5961d6a98ee8271903354ba18) a été inclus dans la #1553, qui a été ouverte par @Sasha-Laniece et validée par @eraviart. Ce revert n'a malheureusement pas été inclus dans le changelog.

Je crois que les personnes impliquées doivent donc discuter directement pour déterminer les raisons de ce revert et la marche à suivre pour inclure à la fois les modifications de #1567 et #1553.

N'hésitez pas à me solliciter si la discussion doit être facilitée.
