### ISSUE TITLE
Intégrer les ressources de mes-aides dans le calcul du montant imposable

### ISSUE THREAD

**Issue by nanocom** [openfisca/openfisca-france#167]
Il faudrait plugger différents types de ressources que nous avons créées pour mes-aides (IJSS, revenus de stage & stage de formation pro, bourses, gains exceptionnels, pensions d'invalidité, ) pour rendre notamment la formule br_pf plus juste.
Dans quelles formules les intégrer : tspr ? sal_pen_net ? rev_sal ? salcho_imp ?

**Comment by benjello** [comment]
Quelle est l'urgence ? Ce n'est pas très évident à faire (faut bien vérifier).

**Comment by jdesboeufs** [comment]
Aucune urgence du côté Mes-Aides.

**Comment by MattiSG** [comment]
A priori, cela a été fait depuis un moment.
