### ISSUE TITLE
Move currency to legislation

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#173]
Should not be better to have the current currency as a legislation parameter than a capitalized variable in country **init** file ?

**Comment by MattiSG** [comment]
If that wasn't a rhetorical question but an actual software quality question, the answer is definitely yes… as long as there's not a single inference made on the currency beyond what's in the legislation.
The idea is that setting it as a parameter means, in terms of software architecture, that you may change it independently from all other parameters. If that's the case, then indeed, parameterise as much as possible.

- - - - 

Brings one question to my mind though: OpenFisca aims at storing historical data too. Would that mean currencies are year-dependent?

**Comment by benjello** [comment]
Yes: franc, euro

**Comment by MattiSG** [comment]
Then that's a pretty solid argument for storing them in some other way than a runtime constant, indeed.

**Comment by MattiSG** [comment]
This is cross-countries, moved to https://github.com/openfisca/openfisca-core/issues/477.
