### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [openfisca/openfisca-france#1791]
Apologies I don't speak French 😞 So was unable to figure out the issue template. Again sorry for not following that

It would be helpful to include the license file in packages. In particular it can be added to [`setup.py` with the `license_files` metadata]( https://stackoverflow.com/a/66443941 ). This should work with `sdist`s, `whl`s, etc. Should add this helpful to make sure users of these packages get the license file. Similarly downstream packagers can also distribute the license file to their users.

**Comment by benoit-cty** [comment]
Hi @jakirkham, thanks for reporting this. To be sure I understand well:
- We already include the licence in the package in setup.py this way:
```
   data_files = [
        (
            "share/openfisca/openfisca-france",
            ["CHANGELOG.md", "LICENSE.AGPL.txt", "README.md"],
            ),
        ],
```
- I've included a copy in the conda-forge recipe named "LICENSE".

What you suggest is to remove the two above and replace them by `license_files = ('LICENSE.AGPL.txt',),` in `setup.py`.

In the recipe I have to put `license_file: ../LICENSE.AGPL.txt`.

Am I right ?

**Comment by jakirkham** [comment]
Yeah exactly.

Then the recipe would have `license_file: LICENSE.AGPL.txt`.

**Comment by benoit-cty** [comment]
I've added it to my conda PR:
- setup.py : https://github.com/openfisca/openfisca-france/blob/0b5301d721deb48a34db9d6cd64add6c45e90cb8/setup.py#L29
- meta.yaml : https://github.com/openfisca/openfisca-france/blob/0b5301d721deb48a34db9d6cd64add6c45e90cb8/.conda/meta.yaml#L72

I took the option to publish automatically to a conda channel _openfisca_ with Github Action and use conda feedstock for conda-forge. I really don't know if it's a good option, is there guideline about this ?

**Comment by jakirkham** [comment]
Thanks for working on this! 😄

Not following exactly what the packaging goal or constraints are here, so not sure.
