### ISSUE TITLE
Doublon sur les paramètres des retenues pour pension

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1799]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai exploré les paramètres des cotisations retraite de la fonction publique

### À quoi m'attendais-je ?

Pas de doublons

### Que s'est-il passé en réalité ?

Il y a des doublons

### Voici des informations qui peuvent aider à reproduire le problème :

[prelevements_sociaux/cotisations_secteur_public/retraite/pension/salarie/pension.yaml](
https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/pension/salarie/pension.yaml) et [prelevements_sociaux/cotisations_secteur_public/rp/retenues.yaml](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/rp/retenues.yaml)
sont identiques.

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.

cc @Sasha-Laniece

**Comment by Sasha-Laniece** [comment]
Bien vu !

Ici on a un problème "classique": on a des barèmes côté OpenFisca VS des paramètres côté IPP. Je crois qu'au début de l'harmonisation je laissais les 2 (car je ne savais pas comment vous alliez adapter vos formules), puis j'ai choisi par défaut les barèmes (car les enlever demanderai un énorme changement des formules).

Du coup je te propose une PR sur le sujet en début de semaine prochaine !
