### ISSUE TITLE
AttributeError sur test-on-windows de branche master

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1860]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai été sur la [page d'accueil du dépôt](https://github.com/openfisca/openfisca-france) et je me suis rendue compte que la CI était en [erreur sur test-on-windows](https://github.com/openfisca/openfisca-france/runs/6986847197?check_suite_focus=true).

### À quoi m'attendais-je ?

J'ai pensé qu'il s'agissait d'un écart de temps entre la publication du paquet`conda` et le test (risque connu à la mise en place récente de ce check) ou d'une erreur sur la dernière PR.

### Que s'est-il passé en réalité ?

Le problème est [survenu sur plusieurs merges](https://github.com/openfisca/openfisca-france/actions?query=branch%3Amaster) 🙀 dont [un que j'avais effectué ](https://github.com/openfisca/openfisca-france/actions/runs/2227600149) 😅.

### Voici des informations qui peuvent aider à reproduire le problème ou compléter le contexte :

Même s'il semble que l'erreur ait évolué entre temps (pas toujours le même fichier mais source à confirmer) et si elle n'est pas survenue sur le paquet `pip`, il s'agit d'une erreur propre au modèle (`AttributeError`, pas un problème logistique type temps de publication des paquets) et elle ne semble pas avoir été vue ou discutée.

Cette issue couvre donc peut-être deux problématiques : 
* L'`AttributeError` sur `test-on-windows`.
* Un manque de visibilité de l'erreur au moment du merge de PR. Ceci dans un contexte où le test dépend de la publication du paquet conda donc ne peut pas être simplement activé sur une PR en cours (Trouver une solution sur PR ? Ou diffuser l'information plus largement lorsque l'erreur survient ?).

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [x] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by sandcha** [comment]
@benoit-cty Tu auras peut-être une idée d'amélioration du process actuel :)

**Comment by benoit-cty** [comment]
Non reproduit en local, sous Windows 10 avec Anaconda 4.10 sur _master_ 116.13.2 :
````
conda create --name openfisca-fix-windows python=3.7
conda activate openfisca-fix-windows 
conda config --add channels conda-forge && conda config --set channel_priority strict
conda install -c openfisca -c conda-forge openfisca-france-dev 
openfisca test --country-package openfisca_france tests 
````
=>2242 passed !

Je propose d'ajouter le check de longeur de chemin dans la CI même si ce n'est pas l'erreur ici.

**Comment by benoit-cty** [comment]
Voir aussi https://github.com/openfisca/openfisca-france/issues/1883
