### ISSUE TITLE
PR mergée avec des tests qui échouent

### ISSUE THREAD

**Issue by benoit-cty** [openfisca/openfisca-france#1906]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

* La PR a été validée.
* J'ai fait le rebase et le push force.
* Pendant que les tests tournaient sur Github, j'ai choisi l'option auto-merge : "Automatically merge when all requirements are met.".

### À quoi m'attendais-je ?

Que tous les tests doivent passer avec que la PR ne soit mergée.

### Que s'est-il passé en réalité ?

La PR a été mergée alors qu'un test YAML a échoué : https://github.com/openfisca/openfisca-france/actions/runs/3327950026/jobs/5503396637#step:6:79

### Voici des informations qui peuvent aider à reproduire le problème :

* La PR : https://github.com/openfisca/openfisca-france/pull/1872
* Les tests de la PR : https://github.com/openfisca/openfisca-france/actions?query=branch%3Aprime-partage-valeur

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by sandcha** [comment]
Dans les Settings d'openfisca-france, voici ce que nous avons concernant l'automerge : 
<img width="796" alt="Capture d’écran 2022-10-27 à 12 14 18" src="https://user-images.githubusercontent.com/6567910/198259360-66598a60-6437-4a59-aafd-f7d1242a91e9.png">

Les checks de la branche doivent normalement être pris en compte. C'est aussi ce que dit la [documentation GitHub donnée en lien dans le screenshot](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request).

**Comment by sandcha** [comment]
Sur les PR, il ne semble qu'on ne voie l'automerge que dans l'onglet description. Par exemple, pour la [PR PPV](https://github.com/openfisca/openfisca-france/pull/1872), nous avons ceci qui illustre bien le problème : 
<img width="869" alt="Capture d’écran 2022-10-27 à 12 35 04" src="https://user-images.githubusercontent.com/6567910/198262850-6b69a3d3-d080-4451-b8e4-9c0a45fe9eb1.png">

**Comment by MattiSG** [comment]
Bonjour,

Ceci n'a pas à voir avec l'auto-merge, mais avec les test obligatoires (“required checks”). Les `test-yaml` n'étaient pas dans les “required status checks”, ce qui signifie que n'importe quel‧le contributeurice aurait aussi pu intégrer une telle PR sans être bloqué‧e.

J'ai donc rendu obligatoire les status checks suivants :

<img width="262" alt="Capture d’écran 2022-11-03 à 16 35 37" src="https://user-images.githubusercontent.com/222463/199734934-76d53740-c3ee-4e3b-ba25-66c88aa657b0.png">

…ce qui correspond au workflow de test :

<img width="606" alt="image" src="https://user-images.githubusercontent.com/222463/199735001-0138f197-c8f1-424a-829c-92c6a1336d71.png">

Je vais donc réactiver la fonctionnalité auto-merge et fermer cette issue 🙂
