### ISSUE TITLE
Paramètres sur le tabac étant tantôt des taux tantôt des montants

### ISSUE THREAD

**Issue by eraviart** [openfisca/openfisca-france#1921]
Dans `openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_specifique/`, les différents paramètres ne sont plus des taux, mais des montants en € à partir du 1er janvier 2015.

Il faudrait sans doute créer des paramètres différents pour les montants à partir de 2015.

Il faudrait peut-être aussi regarder du côté d'openfisca-france-indirect-taxation.

**Comment by Sasha-Laniece** [comment]
PR de correction ici : https://github.com/openfisca/openfisca-france/pull/1922
