### ISSUE TITLE
Passage à `null` des réductions d'impôts sous conditions de revenu en 2019 et intégration dans la décote

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1932]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
En cherchant à harmoniser les répertoires des barèmes IPP et OpenFisca dans cette PR: https://github.com/openfisca/openfisca-france/pull/1931 j'ai observé la chose suivante: 

Côté IPP, les plafonds utilisés pour les réductions sous conditions de revenu passent à `null` en 2019. Cela casse nos tests.
Il semble que ce dispositif a été intégré dans la décote en 2019 ([cf. reference ici](https://guideimpots.com/reduire-impot/428-reduction-fortaitaire-impot-condition-revenu.php) )

Comme cette PR ne concernait que de l'harmonsation pure, pour l'instant donc je n'ai pas implémenté ce passage à `null` pour les 4 paramètres du sous-dossier `calcul_impot_revenu.plaf_qf.reduction_ss_condition_revenus` : 
  - taux
  - plafond_rfr_celib
  - plafond_rfr_couple
  - majoration_plafond_par_demi_parts_supp

Il faudrait coder cette prise en compte dans la décote ([cf. ref. ici](https://guideimpots.com/calculer-impot/13-decote-de-impot-sur-revenu.php) ) et ensuite éteindre le calcul de `class reduction_ss_condition_revenus`

@benjello @clallemand @NolwennLoisel si vous avez des idées.

**Comment by clallemand** [comment]
Salut Sasha, je ne suis pas certaine de comprendre ton point. La suppression de ce dispositif a bien été pris en compte puisque la variable possède une `end_date` et que le calcul de la décote a bien été mis à jour à partir de 2020. 
En fait le problème n'est pas que ce n'est pas codé... Mais qu'il y a une différence d'un an entre l'année d'entrée en vigueur selon les barèmes et selon openfisca. Donc c'est plutôt cette incohénrence là qu'il faut gérer (et donc trancher sur l'année de revenus de l'entrée en vigueur). Il y a un des deux qui est faux.
Et effectivement il faut rajouter le null pour les paramètres pour l'année de suppression.

**Comment by clallemand** [comment]
Pour la décote se sont les paramètres qui ont changé : le taux et les seuils qui font que la décote engloble en gros les personnes qui avant étaient bénéficiaires de la réduction sous conditions de revenus.

**Comment by Sasha-Laniece** [comment]
Merci ! Effectivement je n'ai pas l'impression d'avoir un an de décalage sur les dates des `values` (entre IPP et OFF), mais c'est probablement le cas pour les `references` du coup on perdrait tout au nettoyage automatique

(Pour rappel, si les valeurs des `references` ne correspondent à aucune `value` elles sont supprimées automatiquement du yaml)

**Comment by clallemand** [comment]
est ce qu'il y a un endroit où je peux regarder le problème concernant les références ? Ce sera plus facile pour bien comprendre le problème.

**Comment by Sasha-Laniece** [comment]
Je dirais probablement ici: `openfisca/openfisca_baremes_ipp/parameters/impot_revenu/calcul_impot_revenu/plaf_qf.yaml`

Mais comme on a plusieurs paramètres dans le fichier, et que les références sont des lois et pas des articles, c'est difficile de savoir quelle référence va à quel paramètre (et donc à quelle `value` de ce paramètre)

**Comment by Sasha-Laniece** [comment]
> Effectivement, je n'avais pas vu le `end_date` !
> 
> En revanche pour le calcul de la decote je ne vois pas la mise à jour en 2020 : https://github.com/openfisca/openfisca-france/blob/harm_IR_calcul_impot_revenu_pv/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py#L1391
> 
> Je regarde pour l'entrée en vigueur, c'est le sujet que j'ai soulevé sur Slack (peut-etre qu'en faire une issue serait mieux d'ailleurs)

J'ai fait la modification ici: https://github.com/openfisca/openfisca-france/pull/1933/commits/b31422a1c587f4a6b982fe586547ce386625ddf3
