### ISSUE TITLE
Doublons sur 'ecodev' / 'compte_epargne_codev' ? (Réductions impôt)

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1936]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
J'harmonise le dossier `parameters.impot_revenu.calcul_reductions_impots`

### Que s'est-il passé ?

J'ai l'impression d'avoir un doublon dans les paramètres et dans les calculs.

On a en effet, d'une part, le calcul d'un *montant* (taux*case < plaf):
parametres : `parameters.impot_revenu.calcul_reductions_impots.ecodev`
formule (en 2009) : `prelevements_obligatoires.impot_revenu.reductions_impot_plafonnees`

Et d'autre part le calcul d'*une assiette* (case < plaf):
parametres : `parameters.impot_revenu.calcul_revenus_imposables.charges_deductibles.compte_epargne_codev`
formule (en 2007): `prelevements_obligatoires.impot_revenu.charges_deductibles` 

### Proposition

Pour moi, afin d'éviter les doublons, il faudrait rassembler ces calculs.

Je ferais d'une part le calcul de l'assiette en 2007 ET 2009 (le nom de la case dans la déclaration d'impôt a changé) avec:
parametres : 
    - `parameters.impot_revenu.calcul_revenus_imposables.charges_deductibles.compte_epargne_codev.plafond`
    - `parameters.impot_revenu.calcul_revenus_imposables.charges_deductibles.compte_epargne_codev.plafond_pct.rng`
formule de l'assiette : `prelevements_obligatoires.impot_revenu.charges_deductibles` 

Et d'autre part le calcul du montant avec:
parametres : `parameters.impot_revenu.calcul_reductions_impots.compte_epargne_codev.taux`
formule du montant : prelevements_obligatoires.impot_revenu.reductions_impot_plafonnees` (et on appelle ici l'assiette calculée ci-dessus)

### Contexte

On remarquera que côté barèmes IPP on a aussi des doublons:

`.openfisca/openfisca_baremes_ipp/parameters/impot_revenu/calcul_reductions_impots/codev.yaml` contient:
    - taux
    - plafond_par_personne
    - plafond_en_revenu_net_global

ET
`.openfisca/openfisca_baremes_ipp/parameters/impot_revenu/calcul_revenus_imposables/charg_deduc.yaml` contient:
    - plafond_en_revenu_net_global
    - plafond

### Autres
Une PR récente (mergée) sur les réductions d'impôt:  https://github.com/openfisca/openfisca-france/pull/1876

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [x] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by Sasha-Laniece** [comment]
Je ping ici : @NolwennLoisel @lukas-puschnig @clallemand et @benjello car j'ai l'impression que vous aviez bien plongé le nez dans ces dispositifs pour la #1876

**Comment by NolwennLoisel** [comment]
Salut Sasha ! On n'a pas trop regardé ce dispositif dans le détail puisqu'on s'est concentrés principalement sur les dispositifs les plus récents, mais de ce que je comprends c'est un dispositif qui a changé de forme : il est passé de déduction d'impôt en 2007 à réduction d'impôt en 2009. Donc en effet il y a des paramètres identiques. Pour ce qui est du calcul je pense qu'il a été séparé en deux puisque le dispositif ayant évolué de déduction à réduction, il n'intervient plus à la même étape du calcul de l'impôt et n'est plus de même nature. Donc si on se place à l'échelle du dispositif qui porte sur les avantages fiscaux des comptes d'épargne codéveloppement il y a doublon, mais si on se place à l'échelle du type de dispositif on a deux parties distinctes, je ne sais pas quelle conceptualisation d'un dispositif on veut privilégier (je ne sais pas si je suis très claire)

**Comment by benjello** [comment]
@Sasha-Laniece @NolwennLoisel : il vaut mieux garder une seule source pour les paramètres et indiquer en note que l'on passe de crédit d'impôt à réduction d'impôt (ou dans l'autre sens).
Et il faut placer les paramètres avec les réductions ou crédit d'impôt selon sa plus récente catégorisation.

**Comment by Sasha-Laniece** [comment]
> Salut Sasha ! On n'a pas trop regardé ce dispositif dans le détail puisqu'on s'est concentrés principalement sur les dispositifs les plus récents, mais de ce que je comprends c'est un dispositif qui a changé de forme : il est passé de déduction d'impôt en 2007 à réduction d'impôt en 2009. Donc en effet il y a des paramètres identiques. Pour ce qui est du calcul je pense qu'il a été séparé en deux puisque le dispositif ayant évolué de déduction à réduction, il n'intervient plus à la même étape du calcul de l'impôt et n'est plus de même nature. Donc si on se place à l'échelle du dispositif qui porte sur les avantages fiscaux des comptes d'épargne codéveloppement il y a doublon, mais si on se place à l'échelle du type de dispositif on a deux parties distinctes, je ne sais pas quelle conceptualisation d'un dispositif on veut privilégier (je ne sais pas si je suis très claire)

Merci c'est beaucoup plus clair !!

**Comment by Sasha-Laniece** [comment]
> @Sasha-Laniece @NolwennLoisel : il vaut mieux garder une seule source pour les paramètres et indiquer en note que l'on passe de crédit d'impôt à réduction d'impôt (ou dans l'autre sens). Et il faut placer les paramètres avec les réductions ou crédit d'impôt selon sa plus récente catégorisation.

Ok je fais ça et je te ping quand c'est fait si tu veux y jeter un oeil

**Comment by benjello** [comment]
@Sasha-Laniece @NolwennLoisel c'est charges dédcutibles et réductions d'impôts (et non crédit d'impôt).

**Comment by Sasha-Laniece** [comment]
Pour info c'est mis en place ici: https://github.com/openfisca/openfisca-france/pull/1935
@benjello
