### ISSUE TITLE
Mettre à jour l'indice minimal de traitement dans la fonction publique

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#1949]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai consulté le paramètre de l'[indice minimal de traitement dans la fonction publique](https://github.com/openfisca/openfisca-france/blob/68f257c3a8e68c2924476093c34d2bc8b5bc6460/openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/IM_min.yaml#L1)

### À quoi m'attendais-je ?

Qu'il soit à jour 

### Que s'est-il passé en réalité ?

Il ne l'est pas [manifestement](https://www.service-public.fr/particuliers/actualites/A15184)

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by pzuldp** [comment]
done in #1959
