### ISSUE TITLE
`cerfa_field` manquant dans la variable f7oc

### ISSUE THREAD

**Issue by benoit-cty** [openfisca/openfisca-france#1996]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

Lancer les tests de OpenFisca-France-Data avec la dernière version d'OpenFisca.

### À quoi m'attendais-je ?

Les tests passent.

### Que s'est-il passé en réalité ?

Tests cassés car dans [https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/p[…]ments_obligatoires/impot_revenu/variables_reductions_credits.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py#L10477) il manque `cerfa_field`

[variables_reductions_credits.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py)
class f7oc(Variable):
<https://github.com/[openfisca/openfisca-france](https://github.com/openfisca/openfisca-france)|openfisca/openfisca-france>openfisca/openfisca-france

Fait ici : [https://github.com/openfisca/openfisca-france/commit/380c96e1c48bfc05a4c37218f0d328a7e1fed373#diff-b31f49de84f1666571a6[…]6ece4e1133fca5a1a637bL8384](https://github.com/openfisca/openfisca-france/commit/380c96e1c48bfc05a4c37218f0d328a7e1fed373#diff-b31f49de84f1666571a620f4973fe7024297f7380b76ece4e1133fca5a1a637bL8384) c'est un accident ou il y a une raison ?

![image](https://user-images.githubusercontent.com/6603048/213476586-4021e79b-02b9-43ce-b412-340e11fa6e52.png)

### Voici des informations qui peuvent aider à reproduire le problème :

`make install && make test`

### Contexte

Je m'identifie plus en tant que :

- [X] Contributeur·e : je contribue à OpenFisca France.
- [X] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by clallemand** [comment]
@NolwennLoisel, @lukas-puschnig c'est un accident non ?

**Comment by lukas-puschnig** [comment]
> @NolwennLoisel, @lukas-puschnig c'est un accident non ?

Hello, j'en ai parlé avec @benoit-cty  pendant la journée de contribution OF, effectivement ca nous semble une erreur !
