### ISSUE TITLE
Doit on garder les tests liés au PLF 2016

### ISSUE THREAD

**Issue by clallemand** [openfisca/openfisca-france#2043]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai rajouté une valeur `null` à [un paramètre ](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/seuil.yaml)de la décote (calcul de l'ir) qui est remplacé par d'autres paramètres à partir des revenus 2014 (voir la référence législative dans le fichier de paramètre). 

### À quoi m'attendais-je ?

Je m'attendais à ce que les tests passent, puisque la seule formule de calcul dans laquelle le paramètre est appelé change bien à partir de 2014 ([fichier de calcul de l'ir ](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py), ligne 1390)

### Que s'est-il passé en réalité ?

Le test `tests/reforms/test_plf2016.py` [ne passe pas ](https://github.com/openfisca/openfisca-france/actions/runs/4282968482/jobs/7457948892).

Je me pose la question de la pertinence de garder ce test ainsi que les autres tests concernant les PLF dans ce dépôt.

J'aimerais donc avoir votre avis sur la pertinence d'un tel test.
Si le test est jugé utile je voudrais avoir la confirmation qu'il est bien faux, au niveau des formules et que ce n'est pas moi qui me suis trompée dans la modification du paramètre.

### Voici des informations qui peuvent aider à reproduire le problème :

 liée à la PR [2041](https://github.com/openfisca/openfisca-france/pull/2041)

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [x] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by benjello** [comment]
C'était pour avoir des exemples de réforme qui étaient testés de bout en bout.
Tu peux virer celui-ci qui n'est pas très parlant ni utile.

**Comment by clallemand** [comment]
merci !
