### ISSUE TITLE
Paramètre "Pente du RSA" à passer à null ?

### ISSUE THREAD

**Issue by DorineLam** [openfisca/openfisca-france#2062]
Le paramètre suivant ["Pente du RSA"](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france%2Fparameters%2Fprestations_sociales%2Fsolidarite_insertion%2Fminima_sociaux%2Frsa%2Frsa_m%2Fpente.yaml) semble obsolète et pourtant il est à 0 et non à null. 
Est-ce que c'est normal ? 

je ne l'ai pas trouvé dans les dernières formules du RSA.

**Comment by DorineLam** [comment]
@clallemand je me demande si ce n'est pas le même cas de figure que le paramètre de l'IR qui était à 0...

**Comment by clallemand** [comment]
Oui c'est ça effectivement, j'ai commencé une branche (https://github.com/openfisca/openfisca-france/tree/correction_pente_rsa_null) mais je suis confrontée à un problème avec la formule des enfants à charge...
