### ISSUE TITLE
Test déconjugalisation AAH

### ISSUE THREAD

**Issue by sylvainipp** [openfisca/openfisca-france#2110]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
J'ai effectué une revalorisation du smic.

### À quoi m'attendais-je ?
A ce que les tests passent.

### Que s'est-il passé en réalité ?
Il existe un test anticipé sur la déconjugalisation de l'AAH comparant août et novembre (en attendant de nouveaux tests qui pourraient bientôt arriver de la MSA si j'ai bien compris). Or, la base ressource de l'AAH est modifiée avec le SMIC. Ce test va donc possiblement devenir faux une ou plusieurs fois, et il faudra bien penser à le remplir avec de véritable données une fois que celles-ci seront disponibles.

### Voici des informations qui peuvent aider à reproduire le problème :
Le test est dans test/formulas/aah/aah_couple (les deux derniers).
La revalorisation du SMIC (et le changement afférent du test) est ici : https://github.com/openfisca/openfisca-france/pull/2097

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by benjello** [comment]
@sylvainipp et  @openfisca/france-contrib-msa  est-ce qu'il est désormais possible d'avancer là-dessus ?

**Comment by sylvainipp** [comment]
A ma connaissance les craintes que j'exprimais sur la possibilité d'une modification du montant du SMIC ou de l'AAH ne se sont pas réalisées. Après, l'idéal serait d'avoir un test sur données réelles, et je ne sais pas où les trouver.
