### ISSUE TITLE
Intégration de la variable `prelevement_forfaitaire_unique_ir` dans `irpp` ou `irpp_economique`

### ISSUE THREAD

**Issue by clallemand** [openfisca/openfisca-france#2161]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai calculé des montants d'impôts sur le revenu pour des contribuables avec des revenus du capital

### À quoi m'attendais-je ?

Je m'attendais à trouver la partie ir du PFU comme composante de la variable `irpp`, étant donné que c'est une imposition au titre de l'impôt sur le revenu.

### Que s'est-il passé en réalité ?

Cette variable n'est pas comprise. Ainsi l'imposition des revenus qui sont soumis au PFU n'est pas comprise dans la variable d'impôt sur le revenu. D'après ma compréhension de la législation il s'agit pourtant bien d'un composant de l'IR, mais je voudrais avoir la confirmation de la part de personnes connaissant bien cette partie là de l'IR.

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by clallemand** [comment]
@NolwennLoisel , @sylvainipp , @bfabre01 pourriez vous m'éclairer sur ce point ? Merci d'avance !

**Comment by bfabre01** [comment]
Bonjour @clallemand , en effet, ça n'est pas dans `irpp`, alors que ce prélèvement est au titre de l'IR, comme d'ailleurs aussi les taxations forfaitaires sur les plus-values, qui elles sont incluses dans `irpp` via la variable `iai`.

De mémoire, il s'agissait d'une convention dans l'arborescence du code, qui datait du prélèvement forfaitaire libératoire (PFL), qui existait avant le PFU. Le PFL est "libératoire de l'IR", d'où le fait de l'avoir sorti de l'IR. Mais en fait, on peut autant dire que c'est libératoire de l'IR et que c'est au titre de l'IR.

Bref, je suis d'accord que la situation n'est pas claire. Soit on dit que irpp c'est l'impôt au titre du barème et toutes les taxations forfaitaires sont dans des variables à part, soit on met dans irpp toutes les taxations forfaitaires.

Je suis plus pour la seconde solution. Par clarté et aussi pour un autre point, qui là relève de l'erreur et pas de la convention : le PFU est sujet à un prélèvement à la source (le "prélèvement forfaitaire non libératoire"), avec régularisation suite à la déclaration de revenus. Ces sommes versées en guise d'avance sont à déclarer en 2CK. Cette case est dans `acomptes_ir`, utilisé pour `irpp_economique`. Donc, `irpp_economique` ne comprend pas le PFU mais tient compte des avances versées au titre du PFU.

Bref, merci pour ta remarque et bonne idée de rectifier ça (que la variable `irpp` contienne le PFU). Par contre, si on fait ça pour le PFU, il faut aussi faire cette intégration pour le PLF.

**Comment by clallemand** [comment]
Ok merci pour ton retour, je me lance donc dans cette correction pour le PFU et le PFL !

**Comment by sylvainipp** [comment]
Il y a un problème similaire qui se pose avec le prélèvement libératoire de l'IR sur les revenus des micro-entrepreneurs soumis à ce régime (variable microsocial). Pour l'instant, il est seulement dans impot_direct, et pas en amont dans irpp comme il pourrait l'être pour harmoniser avec le PFU.

**Comment by clallemand** [comment]
Après des recherches complémentaires il semblerait que le prélèvement forfaitaire unique ne soit pas comptabilisé dans l'impôt sur le revenu dans les statistiques de la DGFIP. De ce fait je pense finalement que la situation actuelle est la plus appropriée. @sylvainipp, @bfabre01 qu'en pensez vous ?

**Comment by sylvainipp** [comment]
Le principal me semble être de préserver de l'homogénéité entre les différents dispositifs, de toute façon il est clair que toutes les impositions "au titre de ..." ne pourront pas être rangés dans une case sans contestation possible. Peut-être pourrait-on cependant définir une variable d'IRPP au sens large (éventuellement en réutilisant `irpp_economique`) où on rajouterait ces dispositifs dérogatoires, en laissant la variable `irpp `comme maintenant.

**Comment by bfabre01** [comment]
@clallemand : sur les statistiques de la DGFiP, ça dépend. Des fois c'est pris en compte, des fois non. Ça dépend des fichiers. La question est plus ce que l'on a envie d'avoir nous. En réalité, la situation actuelle nous convient très bien. Car elle permet de mieux distinguer le PFU et le PFL du reste de l'IR, en assemblant ces variables en aval seulement, via la variable `impots_directs`.

La seule chose à avoir en tête dans l'état actuel du code, c'est que, comme évoqué plus haut, la variable `irpp` retranche les acomptes de l'IR, dont ceux associés au PLF/PFU, alors qu'elle ne contient pas le PFU/PFL lui-même. Donc, pour une simulation qui utilise ces cases d'acomptes (cases utilisées dans la variable `acomptes_ir`), il faut utiliser `irpp_economique`, et pas `irpp`.

Après, une solution bien plus simple serait de supprimer `irpp_economique`, et de remplacer `irpp` par ce qu'est aujourd'hui `irpp_economique`. Comme ça, il n'y a plus d'erreur possible. Et concrètement, avoir l'irpp après retranchement des acomptes, ça n'aje pense pas d'intérêt pour une analyse de l'imposition ou un chiffrage d'impact de réforme. C'est juste une variable de gestion sur le calendrier de paiement des individus. Si un individu a un impôt de 1000 euros, mais a déjà payé 800 en mensualisé, ce qu'on veut dans Openfisca (il me semble), c'est seulement le 1000 euros, pas le fait que la personne a déjà versé 800 euros au moment de l'émission de son avis d’imposition et que la DGFiP lui dit qu'il ne lui reste que 200 euros à payer.

**Comment by sylvainipp** [comment]
L'option pour l'imposition au barème codée par @Lolajossipp dans [2197](https://github.com/openfisca/openfisca-france/pull/2197) relance un peu la discussion pour moi, avec des revenus qui peuvent ou pas atterrir _dans l'IR_ (au sens openfisca) selon le choix effectué, avec dans tous les cas une imposition _au titre de l'IR_. Après, le sens dans lequel ça joue n'est pas très clair, mais le champs de notre variable peut donc varier hors changement réel de revenus, avec seulement un choix de taxation différent.

**Comment by Lolajossipp** [comment]
Bonjour, il faudrait réfléchir aussi au moment du calcul de `impots_directs` où l'on intègre la `contribution_exceptionnelle_hauts_revenus`. Pour l'instant elle est intégrée au niveau de `irpp` mais uniquement si `iai` est non nulle. Dans le cas d'un individu qui a un `iai` nul car il n'a que revenus éligibles au pfu (et il choisit le pfu) sa potentielle cehr ne sera pas comptée dans `impots_directs` alors qu'elle devrait.

**Comment by clallemand** [comment]
Cette correction me semble très bien, merci pour ce travail !
