### ISSUE TITLE
Ajout de la cotisation prévoyance IRCEM pour assistants maternels

### ISSUE THREAD

**Issue by Zbluu** [openfisca/openfisca-france#2195]
Hello hello !

Je suis le fan numéro un d'OpenFisca (en vrai j'adore, merci à toute l'équipe pour ce magnifique outil), mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
Je cherche à récupérer toutes les cotisations qu'on retrouve sur la fiche de paie des assistants maternels.
Grâce à OpenFisca France j'ai réussi à récupérer le CRDS, CGS, Vieillesse et retraite complémentaire via les nombreux paramètres.
Mais il m'en manque un : la cotisation de prévoyance (IRCEM). 

### À quoi m'attendais-je ?
Je m'attendais à trouver le taux de cette cotisation sur l'explorateur de la législation (https://legislation.fr.openfisca.org/), via un parameter.

### Que s'est-il passé en réalité ?
J'ai essayé de rechercher plusieurs mots clés comme "prevoyance" ou "IRCEM", mais tous les résultats sur lesquels je suis tombé ne sont pas ce que je recherche.
Comme je sais quel est le taux actuel (1.04%), j'ai fait un petit script récupérant toutes les données de tous les paramètres d'OpenFisca france et j'ai cherché parmis ces données si je ne retrouvais pas une valeur de 0.0104, mais sans succès.
Par conséquent, j'en ai déduit que ce paramètre n'est pas présent dans OpenFisca France.

### Voici des informations qui peuvent aider à reproduire le problème :
-

### Contexte
J'aimerais avoir la confirmation que ce paramètre n'existe pas. Si c'est le cas, je suis prêt à faire un PR (avec vos conseils) pour l'ajouter si vous pensez qu'il a sa place ici !

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [x] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by sylvainipp** [comment]
Bonjour ! Merci pour cette remarque ! Je n'ai pas vérifié dans le détail, mais il me semble que comme l'IRCEM fait partie de l'Agirc-Arrco cette cotisation pourrait être la cotisation patronale présente dans parameters/prelevements_sociaux/autres_taxes_participation_assises_salaires/prevoyance/prevoyance_obligatoire ... auquel cas son taux ne serait pas à jour et mériterait donc une PR (qui nécessiterait notamment de retrouver le document législatif associé, ce qui nous confirmerait bien que les cotisations correspondent).

**Comment by Zbluu** [comment]
Bonjour, merci pour votre réponse !

J'ai fait quelques recherches, voici ce que j'ai trouvé :
Pour le parameters/prelevements_sociaux/autres_taxes_participation_assises_salaires/prevoyance/prevoyance_obligatoire, d'après [l'article Legifrance attaché](https://www.legifrance.gouv.fr/conv_coll/id/KALITEXT000036732007/), le taux de 1,5% semblerait toujours en vigueur, et ça à l'air différent de ce que je recherche.

Je cherche en fait à récupérer le taux de la cotisation prévoyance de la "Convention collective nationale des particuliers employeurs et de l'emploi à domicile". Ce taux est fixé à 1,04% (pour la part salarié) par cette [convention de Legifrance](https://www.legifrance.gouv.fr/conv_coll/id/KALISCTA000045749093/?idConteneur=KALICONT000044594539&origin=list).
Ce taux est en vigueur depuis le 1er janvier 2022, et avant ça, d'après quelques sources, il était à 1,15% (je n'ai pas réussi à remonter plus loin afin d'avoir la date exacte de la mise en vigueur de ce précédent taux).

Parmi tous les parameters, je n'en trouve aucun qui a un taux de 1,04% ou 1,15%. J'ai l'impression qu'il n'existe juste pas dans OpenFisca France.

**Comment by sylvainipp** [comment]
Si le paramètre est spécifique aux particuliers employeurs et employés à domicile, alors il est probable qu'il ne soit en effet pas dans openfisca. Cependant, il est possible qu'il y ait des valeurs définies à un niveau plus agrégé qui posent des niveaux minimaux de cotisations prévoyance au niveau agirc-arrco ou droit du travail par exemple. Dans ce cas, il faudra faire attention à ne pas cumuler les deux taux si celui-ci est bien rajouté, et à faire une substitution dans le cas où l'emploi est soumis à cette convention collective. Le taux agirc-arrco que j'évoquais dans le commentaire précédent ne semble cependant pas dans ce cas, il est supérieur au taux de cotisation patronal en vigueur dans la convention collective et n'est donc pas un minimum.

**Comment by Zbluu** [comment]
C'est noté, merci pour ces infos.
D'après ce que je comprends de la [Convention collective nationale des particuliers employeurs et de l'emploi à domicile](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000044594539), la mise en place de cette cotisation de prévoyance est bien unique à cette convention, "au regard des spécificités du secteur (en particulier la multiplicité d'employeurs)", et est gérée par l'APNI.
Et je n'ai pas trouvé de valeurs définies à un niveau plus agrégé, mais je suis loin d'être expert en droit.

J'ai donc demandé confirmation au syndicat de la Convention collective nationale des particuliers employeurs et de l'emploi à domicile ainsi qu'à l'agirc-arrco. 
Je ferai un retour dès que possible

**Comment by benjello** [comment]
@Zbluu : avez-vous eu un retour ?
Merci.

@sylvainipp : merci pour les réponse. Je te laisse fermer ce ticket dans un temps raisonnable si pas de retour de @Zbluu.
