### ISSUE TITLE
Paramètres inutilisés : limites des plafonds de ressources pour la réduction du loyer de solidarité 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#2200]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai regardé les paramètres de la réduction du loyer de solidarité des allocations logement.

### À quoi m'attendais-je ?

Ne voir que des paramètres utilisés dans les formules

### Que s'est-il passé en réalité ?

Il existe des [limites des plafonds de ressources pour la réduction du loyer de solidarité](openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/limite_plafond_ressources) qui ne me semblent pas utilisés dans le code des formules.   

### Contexte

Je réalise l'homogénéisation des [barèmes IPP](https://www.ipp.eu/baremes-ipp/) et des paramètres d'`openfisca-france`.
Ils ne sont pas présents dans 

@mtifarine : tu as édité ces fichiers pourrais-tu m'en dire plus ?   
cc @openfisca/france-contrib-msa

@clallemand : tu connais bien les aides au logement saurais-tu m'en dire plus ?

Merci !

**Comment by clallemand** [comment]
Salut @benjello, de ce que je comprends et me souviens : 
- la loi définit dans un premier temps une limite de plafonds pour le RLS et dans un deuxième temps les plafonds effectifs qui sont donc ceux utilisés et qui sont inférieurs à la limite
- Cette série de paramètres sont les limites de plafond c'est donc logique qu'ils ne soient pas appelés dans des calculs
- Quand je regarde l'historique de ce fichier je constate qu'ils ont été créés par @Sasha-Laniece dans [ce commit](https://github.com/openfisca/openfisca-france/commit/a47fb3e64151367e82f4b6f9f211d369433a59d9) car les limites de plafonds et les plafonds étaient mélangés dans les mêmes paramètres

**Comment by clallemand** [comment]
Et j'ai l'impression que le mélange plafond / limite de plafond vient de l'harmonisation dans [ce commit](https://github.com/openfisca/openfisca-france/commit/175c05eceeaf0dea96a21ee8849bd8860d1b119a). Mais sur le [site des barèmes ipp](https://www.ipp.eu/baremes-ipp/prestations-sociales/1/al_rls/) je ne trouve pas les limites de plafond donc je ne comprends pas trop d'où ils viennent, à moins qu'il y a eu une correction côté ipp depuis.

**Comment by benjello** [comment]
Oui, ils ne sont pas dans les barèmes IPP et ne sont pas utilisés dans les formules donc je me posais la question de la pertinence de ces paramètres. Doit-on les garder ? Pourquoi cette limite aux plafonds ? 

Merci @clallemand de me faire part tes lumières sur la question.

**Comment by clallemand** [comment]
Je n'ai pas l'impression qu'il soit très nécessaire de les garder mais je ne connais pas la raison exacte de leur existence

**Comment by benjello** [comment]
Je vais donc les virer. Merci @clallemand
