### ISSUE TITLE
Liens dans la documentation HS (502)

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openfisca/openfisca-france#2228]
Bonjour,
dans la page de présentation GitHub, il y a de nombreux liens HS, je ne suis pas arrivé à comprendre le périmètre du projet car j’aimerai plus de docs avant de faire les installations chez moi. Dans le paragraphe : 

L’ensemble des endpoints sont décrits dans la [documentation Swagger](https://legislation.fr.openfisca.org/swagger).

[L'explorateur de législation](https://legislation.fr.openfisca.org/swagger) contient la liste des paramètres et variables disponibles.

les deux liens donnent :  502 Bad Gateway

**Comment by sylvainipp** [comment]
Bonjour et merci pour la remarque ! J'ai l'impression que le problème est résolu, est-ce bien la même chose pour vous ? Si oui, l'issue pourra être fermée a priori.

**Comment by pmlaroche-agoralogie** [comment]
je confirme, tout semble opérationel.
