### ISSUE TITLE
Calcul RSA : neutralisation des ressources chômage appliquée à tort

### ISSUE THREAD

**Issue by varrailhonlaurane** [openfisca/openfisca-france#2257]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?
Cas de calcul du montant du RSA, avec un début de formation sur le mois de la déclaration trimestrielle et une allocation chômage (ASS) se terminant en M-1.

### À quoi m'attendais-je ?
A avoir un montant de RSA réduit du montant de l'ASS (chômage)

### Que s'est-il passé en réalité ?
Les montants de l'ASS sur M-1, M-2 et M-3 ont été neutralisés, et j'ai obtenu un montant de RSA sans déduction des ressources chômage.

### Voici des informations qui peuvent aider à reproduire le problème :
![image](https://github.com/openfisca/openfisca-france/assets/161829718/006b57f0-a391-482c-98b3-ee28d6588900)

### Contexte
Etant donné que la rémunération de formation est associée, comme un salaire, à un revenu de substitution.

Voici quelques sources trouvées pendant l'analyse : 
- https://www.aude.fr/sites/default/files/media/downloads/REGLEMENT%20DPTL%20RSA%20%20-%20version%20session%20d%C3%A9c%202019%20sans%20annexes.pdf (page 29)
- https://www.lebonplan.org/8-rsa-et-principe-de-neutralisation-2/
- Un contact CAF nous a confirmé l'écart entre le résultat obtenu de notre côté et la théorie

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [X] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by sylvainipp** [comment]
Merci beaucoup pour cette issue ! Juste pour mémoire, l'ASS prise en compte avant [#2259](https://github.com/openfisca/openfisca-france/pull/2259) était celle du mois du calcul, et pas la moyenne des trois mois précédents. Cette issue est issue de [cette conversation](https://app.slack.com/client/T3KNPBDCN/C47KV33QF).

La prise en compte de l'Aspa est pour l'instant similaire à celle de l'ASS (prise en compte de la valeur au mois M et pas de la moyenne M-1, M-2 et M-3), serait-il possible de savoir s'il s'agit là aussi d'un bug ? Si c'est le cas, je pourrais régler plus facilement les deux d'un coup.

**Comment by varrailhonlaurane** [comment]
Bonjour,

Merci pour le retour aussi rapide. Désolée pour le délai, j'étais en congés la semaine dernière. 

Pour l'ASPA, je ne saurais pas m'engager, mais j'ai trouvé cette information là : https://www.service-public.fr/particuliers/actualites/A15712#:~:text=L%27Aspa%20n%27est%20pas%20attribu%C3%A9e%20automatiquement.%20Vous%20devez%20en%20faire%20la%20demande%20%C3%A0%20la%20caisse%20de%20retraite%20dont%20vous%20d%C3%A9pendez%2C%20elle%20%C3%A9valuera%20vos%20ressources%20au%20cours%20des%203%C2%A0derniers%20mois.

Il semblerait que ce soit également sur les 3 derniers mois (comme toutes les ressources prises en compte pour le calcul du RSA), mais je ne sais le dire avec certitude car je ne suis pas côté CAF.

Je vois qu'un correctif est préparé pour l'ASS, il y a t'il des échéances à respecter avant d'envisager une possible nouvelle version l'embarquant ? Travaillant que depuis récemment avec OpenFisca, je n'ai aucune idée des process / délais habituels sur ce genre d'anomalie.

Merci encore pour tout.

**Comment by sylvainipp** [comment]
Bonjour,
La nouvelle version devrait arriver assez rapidement (une semaine en moyenne, le temps qu'une autre personne vérifie les changements) une fois qu'on abandonne l'idée de chercher une éventuelle erreur dans la prise en compte de l'ASPA dans le calcul du RSA (qui était le problème que je soulevais de manière assez peu claire : l'ASPA était prise en compte de la même manière que l'ASS dans le calcul du RSA). Je vais me contenter d'un commentaire dans le code pour l'instant afin de mettre à disposition plus rapidement la bonne version de la prise en compte de l'ASS dans le calcul du RSA. Merci encore d'avoir soulevé cette erreur !

**Comment by varrailhonlaurane** [comment]
Super, c'est rapide ! Merci du retour.
