### ISSUE TITLE
Prélèvements sociaux (CSG - CRDS - solidarite) sur les revenus fonciers

### ISSUE THREAD

**Issue by JulienPalard** [openfisca/openfisca-france#2313]
Hello hello !

Je suis le fan numéro 278 d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

Simuler mon impot sur les revenus 2023.

### À quoi m'attendais-je ?

Je m'attendais à aussi simuler les prélèvement sociaux sur les revenus fonciers.

### Que s'est-il passé en réalité ?

J'arrive à calculer mon IR net, tout marche sans surprise (bravo) et tous les résultats sont juste (♥).

J'arrive juste pas à aller plus loin : à inclure les prélèvements sociaux (que je vois sur mon avis fourni par impots.gouv.fr). 

### Voici des informations qui peuvent aider à reproduire le problème :

Sur mon avis d'impôt 2024 sur les revenus 2023 je vois des prélèvements sociaux sur des revenus fonciers, j'ai deux colonnes "CSG - CRDS" et "PREL SOL", la première à 9.70% et la seconde à 7.50%.

J'ai abusé de grep dans openfisca-france pour essayer de retrouver ça, mais rien n'y a fait...

Suis-je passé à côté ?

Est-ce simplement hors scope ?

Ou autre ?

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [x] Autre : Citoyen lambda qui simule son propre impôt avec OpenFisca pour le plaisir.

**Comment by sylvainipp** [comment]
Bonjour,
Ces valeurs sont normalement calculées, dans `csg `à 9.2 %, dans `crds `à 0.5 % (ce qui donne le 9.7 % de csg-crds) et dans `prelevements_sociaux_revenus_capital_hors_csg_crds` pour le prélèvement de solidarité. Les trois sont agrégées dans `prelevements_sociaux_revenus_capital`. Pourrais-je savoir quelle est la variable de départ qui pose problème s'il y a un type de revenu foncier qui n'est pas bien pris en compte ?

**Comment by JulienPalard** [comment]
OK je vois les classes `csg` et `crds`, elles ne sont juste pas prises en compte dans `impot_revenu_restant_a_payer`, ce qui est peut-être normal.

Actuellement si je compare ma simulation à impots.gouv.fr j'ai :

- `impot_revenu_restant_a_payer` qui est juste, il correspond à la ligne « Total de l'impôt sur le revenu net »
- Les prélèvements sociaux sont, sur mon avis, juste après le « Total de l'impôt sur le revenu net », donc en accord avec le fait que dans la simulation ils ne sont pas pris en compte dans `impot_revenu_restant_a_payer`.
- Sur mon avis les prélèvements sociaux ne semblent concerner que les « Revenus fonciers nets ⁴⁵ », c'est `f4ba`.
- Dans la simulation, `assiette_csg_revenus_capital` semble prendre, en plus de `f4ba` via `rev_cat_rfon`, du `revenus_capitaux_prelevement_forfaitaire_unique_ir`. J'obtiens donc un montant de csg/crds un peu plus gros dans la simulation que sur l'avis.

Attention, je ne maîtrise pas **du tout** le sujet, j'ai ouvert le ticket dans le but de remonter quelque chose qui me semble être une anomalie mais j'avoue être moins sûr de mon coup avec ce ticket qu'avec https://github.com/openfisca/openfisca-france/issues/2310 :D

**Comment by benjello** [comment]
@JulienPalard : la réponse vous satisfait-elle ? Peut-on fermer ce ticket ?
Merci.

**Comment by JulienPalard** [comment]
Oui merci à tous pour vos réponses dans tous mes tiquets :)
