### ISSUE TITLE
exoneration_cotisations_employeur_apprenti exists even if apprenti=false

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#234]
`exoneration_cotisations_employeur_apprenti` returns an amount greater than 0 even if `apprenti` is not given.

Example: [without `apprenti`](http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_apprenti?effectif_entreprise=1&type_sal=prive_non_cadre&salaire_de_base=1445.38) (597,29 €), [with `apprenti=true`](http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_apprenti?effectif_entreprise=1&type_sal=prive_non_cadre&salaire_de_base=1445.38) (592,33 €).

**Comment by benjello** [comment]
I am on it

**Comment by benjello** [comment]
Not reproductible. BTW apprenti doesn't get any salaire_de_base but have a fixed remuneration_pprenti depending oon their age and apprentissage_debut_contrat.
Do you have some default value forced into openfisca API ?

**Comment by MattiSG** [comment]
WTF. I can't reproduce either.

@fpagnoux did you deploy a new version?

**Comment by MattiSG** [comment]
> have a fixed remuneration_apprenti depending oon their age and apprentissage_debut_contrat

Is the output formula different too?
This works: http://openfisca.sgmap.fr/api/2/formula/sal?salaire_de_base=700&apprenti=true
This doesn't: http://openfisca.sgmap.fr/api/2/formula/sal?remuneration_apprenti=700&apprenti=true&apprentissage_contrat_debut=2015-03-01

**Comment by fpagnoux** [comment]
I deployed a new version of OpenFisca on SGMAP side, based on branch next

**Comment by MattiSG** [comment]
The timeline was:
- I opened the issue at 18:49.
- @fpagnoux deployed at 19:01.
- @benjello tried to reproduce at 19:07.
…so we just had a race condition  ;)
