### ISSUE TITLE
Ajout d'un fichier publiccode.yml pour être promu via code.gouv.fr

### ISSUE THREAD

**Issue by bzg** [openfisca/openfisca-france#2347]
Votre dépôt est référencé comme "Awesome" dans https://code.gouv.fr/fr/awesome/.

Pour ce référencement, la mission logiciels libres a créé un fichier `publiccode.yml` avec des metadonnées sur le dépôt, fichier que vous trouverez dans [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist).

D'ici octobre, nous mettrons à jour https://code.gouv.fr/sources et nous listerons les dépôt Awesome en allant chercher les métadonnées directement depuis un fichier publiccode.yml à la racine du dépôt.

Pourriez-vous rappatrier le `publiccode.yml` de [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist) et l'ajouter à votre dépôt ?

Si besoin, je peux proposer de faire la PR, vous me dites :)  Merci !

PS: https://github.com/publiccodeyml/publiccode.yml donne plus d'info sur le standard `publiccode.yml`.

**Comment by sandcha** [comment]
Merci @bzg ! Comme nous l'évoquons ensemble IRL, l'objet principal de cette issue est de référencer `openfisca-france` comme logiciel produit par l'administration à fort potentiel de réutilisation (aussi utile pour un référencement européen). La contrainte est que la roadmap est censée être dans les mains de l'administration. Ce n'est pas notre cas et pas le cas des communs en général. Nous ne sommes donc hors périmètre d'[Awsome](https://code.gouv.fr/fr/awesome/).

Nous fermons donc cette issue.
Et si ce référencement ne nous concerne pas directement, on se souvient qu'openfisca reste référencé dans le [SILL](https://code.gouv.fr/sill/). 😊

**Comment by bzg** [comment]
Merci beaucoup d'avoir pris le temps de te poser pour réfléchir à tout ça :)
