### ISSUE TITLE
salsuperbrut is lower than salaire_de_base

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#237]
Example: http://openfisca.sgmap.fr/api/2/formula/salsuperbrut?effectif_entreprise=1&type_sal=prive_non_cadre&salaire_de_base=1445.38&allegement_fillon_mode_recouvrement=progressif

Last verified version where this did not happen was 81554034a883d4a1dcb235f37f1ccdeb0ad6617c.

@benjello This is pretty urgent. Any ideas?

**Comment by benjello** [comment]
I am on it

**Comment by benjello** [comment]
Got it. Fix coming in few minutes.

**Comment by MattiSG** [comment]
:heart:

**Comment by benjello** [comment]
Fixing collateral effects but it is coming ;-)
