### ISSUE TITLE
exoneration_cotisations_employeur_jei does not take into account jei_date_demande

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#238]
The following queries:

- http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_jei?jei_date_demande=2015-01-01&jeune_entreprise_innovante=true&salaire_de_base=1400
- http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_jei?jei_date_demande=2014-01-01&jeune_entreprise_innovante=true&salaire_de_base=1400
- http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_jei?jei_date_demande=2013-01-01&jeune_entreprise_innovante=true&salaire_de_base=1400

…all give the same results, while JEI is degressive over years.

**Comment by benjello** [comment]
entreprise_creation is important too. The entreprise should be less than 8 years old

**Comment by MattiSG** [comment]
> entreprise_creation is important too

Am I using it wrong? This condition doesn't seem to be taken into account either:
http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_jei?jei_date_demande=2014-01-01&jeune_entreprise_innovante=true&salaire_de_base=1400&&entreprise_creation=2005-01-01

**Comment by benjello** [comment]
Too old try entreprise_creation 2013

**Comment by MattiSG** [comment]
> Too old

Yes, that was the point  ;)  `exoneration_cotisations_employeur_jei` is > 0 when entreprise_creation is < 2015 - 8.

**Comment by benjello** [comment]
exoneration_cotisations_employeur_jei doesn't smoothly disappear: it just goes abruptly zero after 8 years (but exo d'IS not simulated is halved after 1 year)
http://www.apce.com/pid1653/jeune-entreprise-innovante.html?pid=1653&pagination=2

**Comment by benjello** [comment]
Do not force jeune_entreprise_innovante to True just fill entreprise_date_creation and jei_date_demande

**Comment by benjello** [comment]
http://openfisca.sgmap.fr/api/2/formula/exoneration_cotisations_employeur_jei?jei_date_demande=2014-01-01&salaire_de_base=1400&&entreprise_creation=2005-01-01

**Comment by MattiSG** [comment]
Ok, got it! Thanks for the details  :)
