### ISSUE TITLE
Ajouter les cotisations syndicales et la mutuelle obligatoire

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#240]
Implement the following missing cotisations:
- [x] [cotisation syndicales](http://www.service-public.fr/professionnels-entreprises/actualites/007298.html)
- [ ] mutuelle obligatoire

**Comment by benjello** [comment]
La mutuelle obligatoire doit être mise en place en [2016] (http://www.service-public.fr/professionnels-entreprises/actualites/007383.html)

**Comment by benjello** [comment]
@laem: the mutuelle obligatoire is still missing

**Comment by MattiSG** [comment]
Ouvrir une autre issue spécifiquement sur la mutuelle obligatoire si le besoin s'en fait sentir.
