### ISSUE TITLE
Fix taux_invalidite

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#249]
Should be a percentage ("taux") and thus 50% should be referenced as .5.
I can change the code but changes are also needed in mes-aides.fr tests.
@MattiSG @fpagnoux  @cbenz @jdesboeufs how should we proceed ?

**Comment by MattiSG** [comment]
Is there anything more to do than updating the mes-aides API and the existing tests to divide all amounts by 100?

**Comment by benjello** [comment]
And some little changes in [aspa-asi] (https://github.com/benjello/openfisca-france/blob/dependance/openfisca_france/model/prestations/minima_sociaux/asi_aspa.py)

**Comment by benjello** [comment]
I can deal with the openfisca-france side

**Comment by MattiSG** [comment]
Including ASPA-ASI?

**Comment by benjello** [comment]
Yep (the condition on taux_invalidite is commented out for the time being)

**Comment by MattiSG** [comment]
Ok, either I or @fpagnoux will handle updating mes-aides. Can this wait for next week?

**Comment by benjello** [comment]
Yes it can

**Comment by benjello** [comment]
@fpagnoux: Should I close this issue ?

**Comment by MattiSG** [comment]
@benjello Have the tests been updated? If yes, you may close. Otherwise, better wait until @fpagnoux comes back (off until next Monday).

**Comment by fpagnoux** [comment]
This has been fixed by :
https://github.com/openfisca/openfisca-france/pull/262
https://github.com/sgmap/mes-aides-api/pull/22

The issue can be closed.
