### ISSUE TITLE
inversion superbrut

### ISSUE THREAD

**Issue by julien-lambert** [openfisca/openfisca-france#253]
Bonjour,

Je souhaiterais inverser les revues imposables d’un individu et calculer les cotisations sociales et le superbrut.
j’ai remarqué un test dans le repository, mais cela ne fonctionne pas (Probablement à cause des non-linéarités induites par les seuils cice, fillon etc… )
En revanche, cela fonctionne bien sur le démonstrateur en ligne, je suppose donc que openfisca est en mesure de calculer cela simplement et rapidement.

Pourriez, vous m’aidez svp ou m’envoyer un exemple minimal. En input, j’ai les données individu_demo,log,rev,conj,ded de piketty cad 80000 lignes.

l’idée et d’en un premier temps d’obtenir la totalité des contributions et allocations et le revenu primaire pour cet échantillon

En vous remerciant par avance,

Cordialement,

Julien

Ps: je n’utilise pas l’API, mais le code installé en local

**Comment by benjello** [comment]
@julien-lambert: contactez-moi par email (coordonnées sur ma page github)
