### ISSUE TITLE
rsa_eligibilite_tns

### ISSUE THREAD

**Issue by SophieIPP** [openfisca/openfisca-france#266]
@fpagnoux : I think rsa_eligibilite_tns is bugging because it is True when all variables are at their default value. And it shouldn't. Please consider the additional test which can be found here https://github.com/SophieIPP/openfisca-france/blob/rsa/openfisca_france/tests/formulas_mes_aides/rsa_eligibilite_tns.yaml
Please use my branch rsa https://github.com/SophieIPP/openfisca-france/tree/rsa since I alphabetically sorted all the classes in rsa ;-)

**Comment by fpagnoux** [comment]
Hi @SophieIPP 
`rsa_eligibilite_tns` checks a few conditions on RSA eligibility based the user's income as an independent worker. It returns true when the user doesn't break these conditions. 
This functions is then called by `rsa_eligibilite`, which checks other condition and gives back a global RSA eligibility. 
In the case where all variables are at their default value, which means 0 income, `rsa_eligibilite_tns` gives `true` as the user respects the condition. You can find the same behavior with other classes, such as `cmu_c`.

Does this behavior causes bug on your side ? If so, can you tell me more about what is the problem exactly ?

**Comment by SophieIPP** [comment]
@fpagnoux : Indeed, it works, and there is no bug. But it is just very unclear for the person who did not code it :) It makes that person believe that, the way rsa_eligibilite is coded, you need to be a TNS to be eligible !
So it would be better if rsa_eligibilite_tns was replaced by a class which default value is 0, and change rsa_eligibilite accordingly.

**Comment by fpagnoux** [comment]
Ok, I understand better, thanks :)
I'll try to work on a fixup this week

**Comment by fpagnoux** [comment]
I sent you a pull request, let me know if it suits you.

**Comment by SophieIPP** [comment]
It sounds good - I'll check this with more details tomorrow morning :)

Thanks !!

**Comment by SophieIPP** [comment]
It seems all good to me !
