### ISSUE TITLE
Allègement de cotisation famille pour les salaires < 1.6 SMIC

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#267]
Doit-on la retirer des allègements de cotisations et réduire la cotisation famille ?

**Comment by laem** [comment]
> Doit-on la retirer des allègements de cotisations et réduire la cotisation famille ?

@benjello Je viens de tomber sur ce sujet de la réduction de la cotisation famille. J'ai l'impression qu'elle n'est pas implémentée (pas pu trouver dans le code) mais ton commentaire me met le doute :question: 

Pour répondre à ta question, [cette page](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/la-cotisation-dallocations-famil/la-reduction-du-taux-de-la-cotis/comment-declarer-la-cotisation-d.html) précise bien que le principe est le même que pour la réduction fillon, donc je serais pour la calculer comme un allègement et ne pas changer la formule famille originale.

**Comment by laem** [comment]
Et je pourrais m'en charger, ça impacte pas mal de coût du travail.

**Comment by MalkIPP** [comment]
Je confirme, c'est clairement une exonération de cotisation.
J'ouvre une nouvelle issue pour les autres exonérations qui manquent (Juppé, Aubry I et Aubry II) ?

**Comment by benjello** [comment]
Yep

Le jeu. 14 janv. 2016 16:14, Guillot <notifications@github.com> a écrit :

> Je confirme, c'est clairement une exonération de cotisation.
> J'ouvre une nouvelle issue pour les autres exonérations qui manquent
> (Juppé, Aubry I et Aubry II) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/267#issuecomment-171668811>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by laem** [comment]
@benjello Tu me confirmes qu'elle n'est pas implémentée aujourd'hui ?

**Comment by benjello** [comment]
Je vais vérifier.

Le jeu. 14 janv. 2016 16:38, Mael <notifications@github.com> a écrit :

> @benjello <https://github.com/benjello> Tu me confirmes qu'elle n'est pas
> implémentée aujourd'hui ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/267#issuecomment-171676252>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by benjello** [comment]
En recoupant:
 - [rapport du Sénat] (http://www.senat.fr/rap/a13-701/a13-70116.html)
 - [barèmes IPP] (https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-yaml-clean/blob/master/baremes-ipp-prelevements-sociaux-social-security-contributions/fillon.yaml)
 - [le fichier de paramètres d'openfisca] (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/param/param.xml#L858-L871)

je conclue que ces allègements sont bien présents. Ils augmentent l'allègement Fillon.
Si vous êtez d'accord avec moi, je me permet de rajouter que s'il faut la séparer en deux morceaux (voire en plus),  je mettrais cela dans une extension feuille de paie ultra détaillée.

**Comment by benjello** [comment]
@laem, je te laisse fermer cette issue si tu es satisfait.

**Comment by laem** [comment]
Je ne comprends pas ce qui te fait penser que la réduction des allocations familliales est déjà inclue dans le calcul Fillon (qui d'ailleurs a vu ses taux [changer](https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-reduction-generale.html) en 2016). 

Ce sont pour moi deux dispositifs bien séparés (l'urssaf [précise](https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-reduction-generale/les-regles-relatives-au-cumul.html) même que les deux peuvent être cumulés) même si reversés de façon similaire et ayant les mêmes conditions d'éligibilité ([lien](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/la-cotisation-dallocations-famil/la-reduction-du-taux-de-la-cotis.html), et même si l'allègement général prend en compte cette réduction des alloc famille pour le calcul de son taux.  

En avril 2016, cette réduction s'étend à 3.5x le SMIC. 

Le document du Sénat est très intéressant !

**Comment by benjello** [comment]
Dans le document du Sénat, tu vois que les 1.80 % des cotisations AF viennent s'ajouter aux autres taux entrant dans le calcul du taux maximal des exonérations Fillon.
Ce qui m'a mis la puce à l'oreille est le fait que je vois mal imposé les AF à 1.80 % à partir de 1.6 SMIC et zéro avant. Si tu désires que l'on fasse des tests pour nous en convaincre, il faudrait trouver une circulaire ACOSS qui précise le calcul avec des exemples si jamais elle est sortie et/ou sortira.
Ou trouver une fiche de paie ou un expert ;-)

**Comment by laem** [comment]
Justement, par exemple pour 1.6xSMIC, la réduction de 1.8% vient se *soustraire* au taux Fillon : étant donné que la cotis allocs a été allégée de 1.8% en 2015, il faut alléger l'allègement Fillon est réduite de 1.8%.
![selection_248](https://cloud.githubusercontent.com/assets/1177762/12351384/6362c392-bb7d-11e5-950b-0a0baa6246dc.png)

**Comment by laem** [comment]
Justement, par exemple pour 1.6xSMIC, la réduction de 1.8% vient se *soustraire* au taux Fillon : étant donné que la cotis allocs a été allégée de 1.8% en 2015, il faut alléger l'allègement Fillon de 1.8%.
![selection_248](https://cloud.githubusercontent.com/assets/1177762/12351384/6362c392-bb7d-11e5-950b-0a0baa6246dc.png)

**Comment by laem** [comment]
Et en effet ça donne envie de rester en dessous de 1.6xSMIC... Peut-être que l'élargissement à 3.5xSMIC d'avril est un moyen de déplacer ce problème ?

**Comment by benjello** [comment]
Message écrit juste avant le tien ;-)
Tu soulèves un bon point ;-) J'ai regardé trop vite.
Le truc qui me titille c'est la discontinuité du taux à 1.6 SMIC mais comme ils étendent à 3.5 SMIC après. On va regarder avec Antoine incessamment pour mettre à jour les barèmes IPP. Mais si tu trouves des cas-types cela nous permettrait de faire des tests.

Merci pour ta perspicacité et désolé pour mes réponses peu approfondies (j'essaie de répondre rapidement mais je n'ai pas lu assez attentivement ... désolé).

**Comment by laem** [comment]
Pas de souci, on avance ! J'attends votre retour.

**Comment by benjello** [comment]
Confirmation auprès de sources sûres.
La réduction était bien de 1,8 point jusqu’à 1,6 smic en 2015. Elle est étendue aux salaires entre 1,6 et 3,5 smic à partir d’avril 2016. Et oui ça fait une marche d’escalier assez importante.
