### ISSUE TITLE
Indemnité de fin de contrat

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#268]
A introduire.

**Comment by laem** [comment]
Tu veux parler du CDD c'est bien cela ?

**Comment by benjello** [comment]
Oui et il doit y en avoir également dans d'autres cas.

Le lun. 11 janv. 2016 10:37, Mael <notifications@github.com> a écrit :

> Tu veux parler du CDD c'est bien cela ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/268#issuecomment-170487815>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by laem** [comment]
@benjello Je me lance sur ça, d'abord sur le cas des CDD. 
Je suis pour calculer cette prime de 10% du salaire total du contrat **par défaut**, et introduire s'il le faut par la suite des varibles d'exception de type "ebauche en CDI à l'issue du contrat" ou "rupture à l'initiative du salarié", voir carrément "indemnité non due".

**Comment by benjello** [comment]
OK, on part sur cela et on ajustera si nécessaire.
