### ISSUE TITLE
Exonerations apprenti

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#270]
Vérifier que les apprentis sont bien exonérés 
 [ ] du versement transport pour les entreprises de moins de 11 salariés
 [ ] Fnal
http://www.urssaf.fr/employeurs/comite_dentreprise/vos_salaries_-_les_mesures_daide_a_lemploi/contrat_dapprentissage_04.html
test 26240

**Comment by MattiSG** [comment]
Pas de problème connu, pas de travail depuis 2 ans, je ferme.
