### ISSUE TITLE
br_pf is calculated at wrong period scale

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#279]
br_pf should be a yearly period as it is base on N-2 fiscal income (that figures on feuille d'impôt). 

Currently it is based on a monthly period, such that a calculate_add('br_pf', '2015') will give a 12 times higher number than expected.

br_pf is not supposed to vary from month to month, but from year to year, a monthly period is thus not appropriated.

**Comment by benjello** [comment]
You are not suppose to do a calculate_add on br_pf since br_pf is the yearly amount consider at the period.
And it does not depend only on n-2 revenues since if your previous months revenus vary your br_pf can change. @fpagnoux which is close to your office can explain that to you

**Comment by adrienpacifico** [comment]
Thanx @benjello, you can close this.
br_pf is the yearly tax base for benefits and is based on N-2 income, but is re-evaluated monthly. As an exemple, in case of death of a spouse only the N-2 remaining spouse income will be taken into account by the end of next month.
