### ISSUE TITLE
état des variables de salaires

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#280]
J'ai cru comprendre que `sali` avait disparu.

Cependant elle reste utilisée par :
* les variables `ass_base_ressources_conjoint` et `ass_base_ressources_i` (voir http://legislation.openfisca.fr/variables/sali)
* la réforme `inversion_revenus`

Je n'ai pas trouvé d'autre utilisation de `sali`.

À mon avis pour les deux cas mentionnée il faut simplement mettre à jour le code pour utiliser `salaire_imposable`. @benjello Est-ce exact ?

Je demande aussi à @jdesboeufs et @fpagnoux pour prévenir que ce renommage aurait un impact sur mes-aides.

merci

**Comment by iDevelopper** [comment]
Je ne comprend pas bien quelle différence vous faites entre sali(master) et salaire_de_base(next).

Je pensais que c’était juste un changement de nom de variable mais que dans les deux cas, il s’agissait du montant à saisir dans les cases cerfa 1AJ, 1BJ, 1CJ, 1DJ… C’est à dire les revenus d’activité avant l’abattement de 10% ou la déduction des frais réels.

Ce n’est pas le cas ?

**Comment by benjello** [comment]
@iDevelopper : Le salaire de base est le salaire "brut". Le salaire imposable est le salaire à saisir dans les cases cerfa 1AJ etc. Comme nous travaillons au détail de la fiche de paie et qu'il n'est pas si facile de remonter du salaire_imposable vers le salaire_de_base dans le cas le plus général, nous avons préféré à nous tenir à ce qui est du strict ressort de la législation sociale et fiscale. Après chacun est libre de construire son inverseur de salaire imposable voir de contribuer à celui que nous essayons de faire et de l'intégrer comme "add-on" à son système socio-fiscal (avec un objet Reform).

Pour @cbenz: il faut virer sali et passer à salaire_imposable dans les prestations. Pour inversion je ne sais pas, je me tâte: je serais pour garder un sali qui deviendrait salaire_imposable_pour_inversion. Explicit is better than implicit.

**Comment by iDevelopper** [comment]
Alors je pense que les deux variables doivent pouvoir être saisies et donc faire partie de columns_tree. Le commun des mortels qui va utiliser ce simulateur a l'habitude de renseigner un salaire imposable, pour le calcul de l'impôt

**Comment by iDevelopper** [comment]
salaire_de_base dans l'entité "ind" et salaire_imposable dans l'entité "foy"

**Comment by cbenz** [comment]
@benjello OK, je vote pour le nom `salaire_imposable_pour_inversion` et je suis d'accord pour dire que ce serait embêtant de garder `salaire_imposable` dans `inversion_revenus`, car on ne pourrait plus calculer à nouveau `salaire_imposable` à partir de `salaire_de_base` (on retomberait sur la valeur saisie en entrée).

@iDevelopper On pourrait en effet envisager de présenter les 2 variables `salaire_imposable_pour_inversion` et `salaire_de_base` dans les UI via `columns_tree`, à poursuivre.
Sache que le passage à `salaire_de_base` dans l'UI-test était considéré comme un quick-fix.

**Comment by cbenz** [comment]
Du coup @benjello pour finir le boulot sur `inversion_revenus`, peux-tu me conseiller sur ce qu'il faut faire concernant les autres variables inversées, à savoir `chobrut` et `rstbrut` (en profiterait-on pour les renommer aussi ?)

**Comment by cbenz** [comment]
@benjello Je vois que la variable [sali](http://legislation.openfisca.fr/variables/sali) n'est plus utilisée depuis la dernière PR #285 a été mergée.

Est-ce que je peux supprimer la variable sali du [code source](https://github.com/openfisca/openfisca-france/blob/7f271621a8ec5091c4035aba3df6162a9fd68762/openfisca_france/model/revenus/activite/salarie.py#L40) et affecter ses attributs (`cerfa_field` et `val_type`) à [salaire_imposable](http://legislation.openfisca.fr/variables/salaire_imposable) ?

**Comment by benjello** [comment]
Elle sert à inversion_revenu peut-être faut-il la cantonner à la réforme.
Mais oui il faut affecter cerfa_field et val_type à salaire_imposable

**Comment by benjello** [comment]
sali peut être renommée salaire_imposable_pour_inversion ou être remplacé par salaire_imposable, je ne me suis pas encore fait une religion mais je vais y venir en août.

**Comment by cbenz** [comment]
Done ! Attention c'est long il fallait renommer `sali` dans beaucoup de tests...

openfisca/openfisca-france@209e2c6fbb14424ff24193695211b3cd4337ea49
openfisca/openfisca-web-api@d7252c0edc7f14f26cc899e8a1fc246b9478201c

J'ai mis `salaire_imposable_pour_inversion` dans https://github.com/openfisca/openfisca-france/blob/3e5dfd22255d0c8ac9d8f89122366e449646d92f/openfisca_france/reforms/inversion_revenus.py#L54

**Comment by benjello** [comment]
@cbenz merci !
