### ISSUE TITLE
Decomposition validator

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#281]
Je constate que les appels `simulate` utilisant les décompositions renvoient un résultat différent d'un `calculate`.

Pour rappel, je pense écrire un validateur de décomposition qui, pour chaque nœud "sommé" dont le nom correspond aussi à une variable calculée, s'assure que les valeurs sont égales.

**Comment by benjello** [comment]
+1

**Comment by iDevelopper** [comment]
Sur api.openfisca.fr alors ? Puisque decomposition renvoie une erreur sur
api-test.openfisca.fr.

Si je fais un test sur la variable irpp, ça me donne la même valeur dans les
deux cas.

Sur quelle variable avez vous constaté une différence ?

J’ose : peut-on se tutoyer ?

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-france
<reply+001b32b27c56633366b02ec03545c54fe241f62b8dbea1df92cf0000000111acdc699
2a169ce05851ff6@reply.github.com>
Date :  jeudi 2 juillet 2015 13:03
À :  openfisca/openfisca-france <openfisca-france@noreply.github.com>
Objet :  [openfisca-france] validateur de décomposition (#281)


Je constate que les appels simulate utilisant les décompositions renvoient
un résultat différent d'un calculate.

Pour rappel, je pense écrire un validateur de décomposition qui, pour chaque
nœud "sommé" dont le nom correspond aussi à une variable calculée, s'assure
que les valeurs sont égales.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-france/issues/281> .

**Comment by cbenz** [comment]
@iDevelopper Osons le tutoiement !

La façon la plus simple de constater une différence sur http://ui-test.openfisca.fr/ est de :
* partir du test case par défaut (au besoin cliquer sur "actions" puis "réinitialiser")
* affecter un salaire de base de 15000 €
* constater sur l'UI-test que le revenu disponible est de 14182 €
* cliquer sur "actions" puis "trace"
* constater sur l'outil de trace que le revenu disponible est de 14609 € (dernière ligne tout en bas)

De même pour `irpp` : si j'élève le `salaire_de_base` à 25000 €, sur le graphique "waterfall" j'ai un IRPP de 1208 € tandis que sur l'outil de trace c'est 1408 €.

:warning: Il faut réouvrir l'outil de trace depuis l'UI à chaque changement de cas type pour prendre en compte les changements.

**Comment by iDevelopper** [comment]
Oui je suis d’accord avec toi que sur http://ui-test.openfisca.fr/ il y a
une différence (pas sur http://ui.openfisca.fr/
<http://ui-test.openfisca.fr/> )

Par contre, depuis mon simulateur iOS, je ne parviens toujours pas à avoir
un résultat avec le paramètre decomposition sur http:/api-test.openfisca.fr/
<http://ui-test.openfisca.fr/> , alors que cela fonctionne sur
http://api.openfisca.fr/ <http://ui-test.openfisca.fr/>

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-france
<reply+001b32b2ebc2cfcf03c6933e93ab38671c3d530da851c30292cf0000000111ad08259
2a169ce05851ff6@reply.github.com>
Date :  jeudi 2 juillet 2015 16:09
À :  openfisca/openfisca-france <openfisca-france@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-france] validateur de décomposition (#281)


@iDevelopper <https://github.com/iDevelopper>  Osons le tutoiement !

La façon la plus simple de constater une différence sur
http://ui-test.openfisca.fr/ est de :
* partir du test case par défaut (au besoin cliquer sur "actions" puis
"réinitialiser")
* affecter un salaire de base de 15000 €
* constater sur l'UI-test que le revenu disponible est de 14182 €
* cliquer sur "actions" puis "trace"
* constater sur l'outil de trace que le revenu disponible est de 14609 €
(dernière ligne tout en bas)
De même pour irpp : si j'élève le salaire_de_base à 25000 €, sur le
graphique "waterfall" j'ai un IRPP de 1208 € tandis que sur l'outil de trace
c'est 1408 €.

 Il faut réouvrir l'outil de trace depuis l'UI à chaque changement de cas
type pour prendre en compte les changements.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-france/issues/281#issuecomment-11804
5913> .

**Comment by cbenz** [comment]
D'accord, en fait on retombe sur l'issue openfisca/openfisca-web-api#32

**Comment by cbenz** [comment]
Note: a decomposition can be validated:

- formally, using the parsers, which is difficult task a priori
- in the context of a simulation, which is easy but not very valuable

The parsers may guess that a variable is a sum, until we introduce a more declarative `SumVariable` but that's just an idea yet.

> I just realized that this issue was in french :open_mouth:

**Comment by MattiSG** [comment]
Comme indiqué dans openfisca/openfisca-web-api#32, les décompositions ont été supprimées de l'API il y a deux ans.
