### ISSUE TITLE
Rename etu to etudiant

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#294]
all in the title

**Comment by benjello** [comment]
@cbenz : I am not able to add a new label renaming to this issue. Any hint ?

**Comment by cbenz** [comment]
@benjello you are in the OpenFisca owners, so you should see an "Edit" button right to the issue title, otherwise I'll investigate

**Comment by benjello** [comment]
@cbenz : didn't find a way to add labels ...

**Comment by cbenz** [comment]
I think I misunderstood the question!

This should answer: https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by benjello** [comment]
I actually already read it but I am not able to add a new label. I can only add existing  a labels but cannot create one (and I already done that in the past to create the existing ones ...) ! Very strange.

**Comment by benjello** [comment]
@fpagnoux didn't you plan to rename etu to etudiant or did it already (didn't find it in the git log though) ?

**Comment by benjello** [comment]
already done
