### ISSUE TITLE
choi and rsti

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#296]
For a given test-case with `choi` and/or `rsti`:

```
{
  "individus": [
    {
      "id": "Personne 1",
      "choi": 20000,
      "rsti": 20000
    }
  ],
  "familles": [
    {
      "id": "Famille 1",
      "parents": [
        "Personne 1"
      ]
    }
  ],
  "foyers_fiscaux": [
    {
      "id": "Déclaration d'impôt 1",
      "declarants": [
        "Personne 1"
      ]
    }
  ],
  "menages": [
    {
      "id": "Logement principal 1",
      "personne_de_reference": "Personne 1"
    }
  ]
}
```

The result does not include any tax.

Furthermore I see that [`choi`](http://legislation.openfisca.fr/variables/choi) and [`rsti`](http://legislation.openfisca.fr/variables/rsti) variables aren't used by any formula, they seem to be dead input variables.

@benjello Do you have any quick hint about it?

**Comment by benjello** [comment]
choi and rsti are inputs for inversion_revenus to produce cho and rst which are then used to compute the tax

**Comment by cbenz** [comment]
All right, so if I replace `choi` by `cho` and `rsti` by `rst`, it is OK.

Since the UI does not use the inversion_revenus reform no more, I will change the datatrees.

**Comment by benjello** [comment]
Should be ok ;-)

**Comment by cbenz** [comment]
Note to myself: 209e2c6fbb14424ff24193695211b3cd4337ea49

**Comment by benjello** [comment]
@cbenz : should we close this issue ?
