### ISSUE TITLE
Bad mix between axes and the other spouse income.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#297]
Seems that if you add an historical variable for parent2 in a scenario with axes, the results are wrong.

Exemple : https://gist.github.com/adrienpacifico/836a08f9e66429dedbc5
Json of an API call : https://gist.github.com/adrienpacifico/3cfb9f3b0632c2f89766

An other exemple when all the salaire_de_base are put in a monthly pattern in the simulation :
https://gist.github.com/adrienpacifico/725335bf0407ec63ecbf

For my case I have an output of 16438.58 for revdisp whatever is the initial income of the household.

**Comment by benjello** [comment]
@adrienpacifico : could you check if this is still relevant ? And close it if it is obsolete.
Thanks

**Comment by MattiSG** [comment]
2 years old, reproducibility questioned 8 months ago, no news, closing. Please reopen if reproducible.
