### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#298]
Revenus agricoles
- [x] Cases f5hd, f5id, f5jd à partir de 2008: these are in fact frag_fore (thanks @edarin)
- [ ] Cases f5hj, f5ij à partir de 2008
- [X]  Case f5jj: in `cncn_adef`

**Comment by edarin** [comment]
Mmm concerning the first point, isn't it related with the variable `frag_fore` which seems to work ?

**Comment by benjello** [comment]
Thanks @edarin !
We should have a strategy to deal with these names and changing cases with @pnbt sometime !

**Comment by edarin** [comment]
else we have f5jj under `cncn_adef` and actually I don't find this other ones even in the cerfa sheet ...

**Comment by benjello** [comment]
Could you be more precise on the different years you looked at ?
Thank you very much !

**Comment by edarin** [comment]
already 2012 and 2014

**Comment by edarin** [comment]
Sheets are on online on the governmental website only from 2010 and in these sheets the two first boxes don't appear

**Comment by benjello** [comment]
Thanks @edarin !

**Comment by edarin** [comment]
furthermore `5jj` is already in `cncn_adef`

**Comment by MattiSG** [comment]
Je ferme cette issue qui décrit du reste-à-modéliser sans cas d'usage ni porteur, ni activité depuis 8 mois. Ne pas hésiter à rouvrir des issues spécifiques à chaque case restante si de la force de travail est provisionnée pour.
