### ISSUE TITLE
Harmonize foy/declar menage/men etc in scenario and the rest of the code 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#30]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/103_

---

_Issue by **[Pyke75](https://github.com/Pyke75)** from Friday Dec 14, 2012 at 15:06 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/100_

---

**Comment by MattiSG** [comment]
Issue ayant plus de 4 ans, pas de travail actif, je ferme.
