### ISSUE TITLE
Very strange children's gains in 2008.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#300]
Although for other years from 2005 to 2015 looks ok, 2008 looks very unrealistic...

Notebook exemple : https://github.com/adrienpacifico/bug-openfisca/blob/master/Gain%20%C3%A0%20l'enfant%20artefact%202008.ipynb
![telechargement](https://cloud.githubusercontent.com/assets/6614121/9722296/e6c8ecc2-55aa-11e5-9839-27c2a9c51b4d.png)

**Comment by benjello** [comment]
Try to narrow down to a simpler example showing the problem. For example comparing 2007 and 2008 for one child. It is difficult to dig in such complicated setup.

**Comment by adrienpacifico** [comment]
I will ASAP, higher priority right now. But ping me if not done in one week.

**Comment by benjello** [comment]
@adrienpacifico : where are we on this issue ?

**Comment by adrienpacifico** [comment]
Désolé, pas eu le temps de me pencher dessus encore...

**Comment by adrienpacifico** [comment]
Mais je le garde en tête.

**Comment by MattiSG** [comment]
> ping me back if not done in one week

Knock, knock. 2 years later, future is knocking  :wink:  and it's closing this issue.
