### ISSUE TITLE
Éclater les catégories "autres" du datatrees

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#309]
Demande de @iDevelopper

> Les catégories « Autres » sont super chargées et mériteraient d’être éclatées en plusieurs autres catégories (par exemple dans la déclaration d’impôt, Réductions et crédits d’impôt, Déficits, etc…). Même choses pour « Autres » pour l’individu.

Contexte: il s'agit du fichier [datatrees.py](https://github.com/openfisca/openfisca-france/blob/a3f85b909ad8ff085ecc30a1b8397dc710d31a70/openfisca_france/model/datatrees.py#L161)

@benjello  Qu’en penses-tu ? Je demande pour le principe.

**Comment by benjello** [comment]
Oui sur le principe

**Comment by MattiSG** [comment]
Fixed via #428.
