### ISSUE TITLE
parent isolé en garde alternée

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#31]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/110_

----

_Issue by **[Pyke75](https://github.com/Pyke75)** from Monday Jan 28, 2013 at 14:21 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/107_

----

Vérifier si la législation n' pas changé en 2010.

**Comment by jdesboeufs** [comment]
La règle est la suivante : les parents peuvent choisir le partage des AF mais doivent déterminer qui perçoit les autres prestations pour l'enfant. En cas d'absence de choix, c'est la situation de départ qui persiste malgré la garde alternée.
