### ISSUE TITLE
Opt-in caching reforms for tests

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#310]
This [code section](https://github.com/openfisca/openfisca-france/blob/57ce751ede7d112efa6e050cc9475a79bd6df311/openfisca_france/tests/base.py#L54-L74) caches the reforms.

It slows down this single command line:

```
python openfisca_france/tests/test_yaml.py openfisca_france/tests/.../....yaml
```

Solution: cache reforms with opt-in from Makefile passing an environment variable.

**Comment by MattiSG** [comment]
Pas de travail depuis 2 ans, je ferme.
