### ISSUE TITLE
Fix plf2015 reform

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#311]
Reform [plf2015] (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/plf2015.py) should be fixed:
 - [ ] remove deprecated update_legislation (@cbenz what should be used instead ?)
 - [ ] reform year and decote parameters do not match exactly

**Comment by cbenz** [comment]
See openfisca/openfisca-core#344

**Comment by cbenz** [comment]
On my computer the tests pass.

**Comment by cbenz** [comment]
> reform year and decote parameters do not match exactly

@benjello Can you explain further (not hurry)?

**Comment by benjello** [comment]
I did fix that. Initially reform year was 2014 (actually Claire Bernard needed that, to compare the changes introduced by the reform vs business as usual for revenus 2014) and decote parameters where on 2013 and 2014. I swithched back to have everything on 2013. No more problem now.
