### ISSUE TITLE
Should "base_ipp" data files stay in openfisca-france repo?

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#313]
I found these quite old files which are pretty big (total of 2.2M) [here in the `base_IPP` directory](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/tests/ipp/base_IPP)

@benjello Should they stay in this repo? What's their purpose?

**Comment by benjello** [comment]
There are test computed with the old taxipp model to check the first version of openfisca. But we didn't maintain tem since then ...
Valuable tests but to rework when there is time !
We may should put them somewhere else ...

**Comment by cbenz** [comment]
OK thanks!

I won't package them but I let them in the Git source tree since they test the formulas.
