### ISSUE TITLE
Should I delete this file?

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#314]
Sorry for this dumb question,

Since this commit 205a2d03f8065e34cfacba5bd4520f6f0ba90368 the file [section_1_traitements_salaires_ppe_pensions_rentes.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/input_variables/section_1_traitements_salaires_ppe_pensions_rentes.py) contains only comments.

@benjello Should I delete it? Or keep the contents in an issue?

**Comment by benjello** [comment]
You can put the content somewhere in a issue. And assign me !
