### ISSUE TITLE
Bring back section_1_traitements_salaires_ppe_pensions_rentes data

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#315]
Following #314, I removed the file containing only comments, and put its contents in [this gist](https://gist.github.com/cbenz/1268d6203686dd3f05e9)

**Comment by benjello** [comment]
section_1_traitements_salaires_ppe_pensions_rentes

**Comment by benjello** [comment]
@edarin @pnbt : il y a des variables manquantes dans openfisca qui ont été recensées [ici](https://gist.github.com/cbenz/1268d6203686dd3f05e9)

**Comment by edarin** [comment]
et encore il me semble qu'il n'ya pas les nouvelles cases crées depuis non ?

**Comment by benjello** [comment]
Non c'est un vieux truc.
C'est dur de suivre le rythme de l'administration fiscale ...
Disposer des codes M pour les années précédentes pourrait être vachement utile ! 
N'est-ce pas @pnbt @cbenz  ;-) ?

**Comment by MattiSG** [comment]
Issue datant d'il y a 2 ans, explicitement décrite comme obsolète il y a 8 mois, je ferme.
