### ISSUE TITLE
Remove all callers of deprecated update_legislation()

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#317]
See openfisca/openfisca-core#344

[`update_legislation`](https://github.com/openfisca/openfisca-core/blob/18f72180529470664c79e228ed0ad544a42de6f5/openfisca_core/reforms.py#L188) is deprecated. Before deleting it, all callers must be removed or replaced by equivalent.

Used by, in particular:
- [ ] [plf2015.py](https://github.com/openfisca/openfisca-france/blob/c363f2fff502a5519e1685b61de4c60371d5f4aa/openfisca_france/reforms/plf2015.py)
- [ ] [test_parametric_reform.py](https://github.com/openfisca/openfisca-france/blob/c363f2fff502a5519e1685b61de4c60371d5f4aa/openfisca_france/tests/reforms/test_parametric_reform.py)
- [ ] [test_allegement_fillon.py](https://github.com/openfisca/openfisca-france/blob/c363f2fff502a5519e1685b61de4c60371d5f4aa/openfisca_france/tests/test_allegement_fillon.py)

**Comment by benjello** [comment]
@cbenz : we do keep update_legislation. Should we close this issue ? 
At least, we should be more specific at the next steps.

**Comment by MattiSG** [comment]
Removing this needs offering an alternative. This issue could be reopened if there is active work on it, but this is not currently the case. Closing.
