### ISSUE TITLE
Nombre de parts, réductions et crédits d'impôt

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-france#319]
Est-il possible d'ajouter dans le JSON retourné par l'API simulate ces trois variables calculées (nbptr, reductions, credits_impot) ?

**Comment by benjello** [comment]
@iDevelopper puis-je fermer ce ticket ?

**Comment by iDevelopper** [comment]
Bah je ne sais pas, c'est possible ou pas ?

**Comment by benjello** [comment]
Avez-vous essayé ?
@cbenz on a besoin de toi ;-)

**Comment by iDevelopper** [comment]
Je regarde, dans api ou dans api-test ?

**Comment by iDevelopper** [comment]
J'ai fait un test, ces informations ne sont pas retournées et ce qui me dérange aussi depuis le début c'est l'absence de possibilité de saisir les revenus d'activités comme sur la déclaration d'IR (dans l'api test). Egalement, il m'est toujours retourné des montant de prestations sociales pour un montant de salaire de base de 50.000 €, ce qui ne me parait pas correspondre à la réalité

**Comment by iDevelopper** [comment]
Aussi le montant de l'impôt me semble faux

**Comment by iDevelopper** [comment]
![2015-11-11_16-38-48](https://cloud.githubusercontent.com/assets/1782450/11094963/0da2abd8-8893-11e5-9321-bb4d4e009106.png)

**Comment by cbenz** [comment]
> Est-il possible d'ajouter dans le JSON retourné par l'API simulate ces trois variables calculées (nbptr, reductions, credits_impot) ?

Suite au point de ce matin avec @edarin je peux dire qu'il n'est pas possible d'ajouter `nbptr` à l'API `simulate`, pour `reductions` et `credits_impot` je demande à @edarin.

En revanche tu peux d'abord appeler `simulate` pour avoir la décomposition du revenu disponible, et *ensuite* appeler `calculate` avec la liste des variables souhaitées en plus.

**Comment by MattiSG** [comment]
@cbenz Pourquoi n'est-il pas possible de demander le calcul de certaines variables ? Qu'y a-t-il de spécifique à `nbptr` pour qu'on ne puisse pas recevoir sa valeur ?

**Comment by cbenz** [comment]
C'était en relation avec l'endpoint `simulate`, pas `calculate`. `simulate` nécessite d'ajouter chaque nouvelle variable à [`decomp.xml`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/decompositions/decomp.xml).

Dans ce cas je ne sais plus *pourquoi* `nbptr` n'était pas ajoutable en l'état, mais sûrement que c'était ne question de périodes.

**Comment by MattiSG** [comment]
Ok, merci ! La réponse à apporter à @iDevelopper est donc : utiliser l'[endpoint `calculate`](https://doc.openfisca.fr/openfisca-web-api/endpoints.html) !

**Comment by cbenz** [comment]
Suite à cette réponse je ferme cette issue.
