### ISSUE TITLE
Conditions de majoration du RSA

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#32]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/112_

---

_Issue by **[Pyke75](https://github.com/Pyke75)** from Thursday Feb 28, 2013 at 15:50 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/109_

---

La condition de présence d'enfant de moins de trois ans n'est pas toujours nécessaire
http://vosdroits.service-public.fr/F502.xhtml

**Comment by MattiSG** [comment]
Le RSA majoré avait été implémenté, et est maintenant déprécié, cf #646.

**Comment by benjello** [comment]
@MattiSG : on veut pouvoir calculer le rsa majoré en historique, il ne sera jamais déprécié ;-)

**Comment by MattiSG** [comment]
Oui, mais personne ne travaille plus sur ce sujet.
