### ISSUE TITLE
Brainstorm: distinction between extension and reforms

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#323]
Shouldn't we make a distinction between extensions and reforms ?

A tax benefit_system is composed by a  **root** tax_benefit_system that may be completed by some **extensions**.

A **reform** is a specific extension of a specific **reference** tax_benefit_sysem.

Scenarios (test-case or survey) should deal with a vanilla tax_benefit_system or a **reform** tax_benefit_system coming with it **reference**  

What do you think @cbenz @eraviart ?
ps: @adrienpacifico you should follow this discussion

**Comment by adrienpacifico** [comment]
@benjello 
Can you provide exemples for what is reform and what is extensions ?

I can see extensions such as CMU, bourses de colleges, aide au retour à l'emploi, etc. And reforms such as Trannoy-Wasmer, plf, etc. Is it that ?

In that case what should determine the  hard coded tax/benefits from extensions ?

**Comment by cbenz** [comment]
For the moment extensions are nothing ;-)

If we rename reforms to extensions, political reforms will be extensions indeed.
But there will be perhaps extensions that do not correspond to political reforms (I have no example).

The term "extension" expresses in a better way the technical concept

**Comment by benjello** [comment]
mes-aides introduces an extension that is not a politcal reforms
openfisca-france-data introduces an extension that is not a politcal reforms
pl2015 etc are reforms.

**Comment by cbenz** [comment]
We are now OK for talking about extensions, I close the issue.
