### ISSUE TITLE
Écrire automatiquement des tests d’impôt sur le revenu via le simulateur officiel

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#325]
An automatic way of testing of have been made by @bixiou during summer 2014. As far as I know there is no test for IR 2015 and might not be reliable. What should be done, some test based on the DGFip simulator, or an automatic that uses @bixiou script ?

Shouldn't we organise a procedure to be up-to-date every year after 'Loi de finance' has been voted (december) and DgFip simulator is online ?

**Comment by benjello** [comment]
I do not know where we stand on this. May be @eraviart  know what is the shape of @bixiou scripts for now.

**Comment by adrienpacifico** [comment]
@cbenz @eraviart on peut connaitre votre position par rapport à ça ? On repasse à la méthode manuelle ou vous créez pleins de test automatiquement ?

**Comment by MattiSG** [comment]
Issue datant d'il y a plus de 18 mois, pas de travail sur le sujet, je ferme.
