### ISSUE TITLE
Use a DatedFormula for CEHR

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#334]
La contribution exceptionnelle sur les hauts revenus est introduite pour les revenus 2011

**Comment by adrienpacifico** [comment]
you can assign me on this if you want to.

**Comment by adrienpacifico** [comment]
Tu peux m'assigner à cette issue si tu veux.

**Comment by benjello** [comment]
Go ahead. En attendant j'essaie de t'ajouter au groupe pour que tu sois un vrai assignee ;-)

**Comment by benjello** [comment]
@adrienpacifico : comptes-tu toujours régler ce problème ?

**Comment by adrienpacifico** [comment]
Oui, pour Noël.

2015-12-19 22:35 GMT+01:00 Mahdi Ben Jelloul <notifications@github.com>:

> @adrienpacifico <https://github.com/adrienpacifico> : comptes-tu toujours
> régler ce problème ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/334#issuecomment-166028057>
> .
>



-- 
Adrien Pacifico
PhD Student at Aix-Marseille school of economics (AMSE)
IDEP, GREQAM, EHESS

**Comment by cbenz** [comment]
@adrienpacifico close?
