### ISSUE TITLE
Corriger le plafonnement des niches fiscales

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#335]
Le plafonnement des niches fiscales sensé intervenir dans le calcul de l'impôt net à partir des revenus 2008 n'est pas effectif (ni dans les barèmes, ni dans le calcul). 
Cf. "Barèmes IPP - Impôt Revenu.xls", onglet_plaf_nich pour plus de précision (lien pour un exemple de calcul notamment).

**Comment by benjello** [comment]
Thx. @adrienpacifico cela peut expliquer des écarts.

**Comment by adrienpacifico** [comment]
>Thx. @adrienpacifico cela peut expliquer des écarts.

Des écarts où ? Tout les tests de @bixiou passent non ?

**Comment by benjello** [comment]
Encore faudrait-il qu'il y ait plus de 10000 euros de niches.
Et je crois qu'ils ont été "momentanément" retirés: @cbenz @eraviart confirmez-vous ?

**Comment by MattiSG** [comment]
Pas de test, pas de cas d'usage, pas de travail actif depuis plus d'un an, je ferme.
