### ISSUE TITLE
Ceiling of the tax loopholes

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#336]
Le plafonnement des niches fiscales sensé intervenir dans le calcul de l'impôt net à partir des revenus 2008 n'est pas effectif (ni dans les barèmes, ni dans le calcul). 
Cf. "Barèmes IPP - Impôt Revenu.xls", onglet plaf_nich pour plus de précision (lien pour un exemple de calcul notamment).

**Comment by benjello** [comment]
Remove duplicated issue
