### ISSUE TITLE
Social contribution on capital gains

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#337]
In the param.xml file, the CSG rate csg.capital.glob and csg.capital.deduc stop in 2013 but there is a mistake : they where not supressed, I think.

**Comment by adrienpacifico** [comment]
Dans le param.xml file si un paramètre fini il est toujours utilisé tel quel après sa date de fin. On est censé l'actualiser chaque année, c'est donc sûrement que personne l'a fait depuis.

Les lignes dont tu parles n'ont pas été actualisées depuis avril 2014, si c'est dans la loi de finance c'est donc sur les revenus 2013.

(git blame -L 189,200  param/param.xml)

**Comment by benjello** [comment]
@MalkIPP: on a le droit de parler en français sur openfisca-france ;-)

**Comment by MalkIPP** [comment]
oui effectivement, merci @adrienpacifico. Il me semblait que le problème était général, effectivement. 

Ceci dit, il me semble que c'est l'occasion d'ouvrir une issue plus large sur la fin de vie des paramètres plaidant pour la définition d'un intervalle ouvert. Qu'en penses tu @benjello ?

**Comment by benjello** [comment]
Pour l'instant ils vivent éternellement. Comme on a accès à des DatedFormula qui permettent de gérer l'extinction de certaine "variables".  Mais oui on gagnerait à avoir un script qui nous avertisse sur les paramètres de la législation utilisés au delà de la date de péremption @cbenz @eraviart

**Comment by adrienpacifico** [comment]
@benjello J'aillais répondre plus ou moins la même chose. Avoir une date de fin me semble souhaitable, car ça permet de savoir ce qui a réellement été actualisé ou pas. @MalkIPP les dated_formula, elles, n'ont pas besoin d'une date de fin.

Il faudrait un warning sur tout les paramètres antérieur à la période de simulation (avec une option pour ne pas l'avoir) dès qu'une simulation fait appel à un paramètre antérieur à la la date de simulation. Ça donnerait une bonne incitation à l'utilisateur d'actualiser ces paramètres !

@MalkIPP @benjello @cbenz @eraviart  Cela pose cependant la question de l'actualisation des paramètres, je sais que vous avez un projet IPP_to_code depuis plus d'un an et demi et que vous comptez dessus, mais en attendant on a pas de workflow pour actualiser la législation. L'équipe mes aides le fait très bien et de manière réactive pour le volet social, peut être faudrait-il répartir un peu les tâches entre nous pour vérifier les paramètres obsolètes sur le reste ? Quid des tests ?!

Après si les taux sont bons et que tu peux les prolonger @MalkIPP tu pourrais faire une PR donnant la bonne date :-).

**Comment by MattiSG** [comment]
> Avoir une date de fin me semble souhaitable, car ça permet de savoir ce qui a réellement été actualisé ou pas.

Attention, il faut bien comprendre ce qu'on veut représenter avec ça. Que se passe-t-il si la législation ne définit pas de date de fin ? Que doit-on mettre si on ne connaît pas la date de début d'application et qu'on n'a pas 2h d'archéologie législative à mettre au moment de l'ajout d'un paramètre ?

Le plus important est de coller au plus près à la législation elle-même. Je ne sais pas comment sont édictées ces valeurs, mais il ne faut pas ajouter de « date de fin » comme un moyen d'obtenir un rappel automatisé de vérifier si la loi a changé à une certaine date (j'ai déjà vu faire cela). Les dates de fin et de début ne devraient être spécifiées que si l'on en est certains.

> L'équipe mes aides le fait très bien et de manière réactive pour le volet social

Mouais… C'est très artisanal et se repose sur la communauté qu'on est en train de construire. Ça ne tient qu'avec des personnes à temps plein sur une étendue réduite de la législation.

- - - -

Il y a un vrai sujet sur la mise à jour des paramètres et l'incitation à la vérification, mais le seul moyen de passer à l'échelle sera d'automatiser cette détection.

J'avais déjà évoqué une idée : si les URL sources des formules étaient correctement renseignées, et qu'un attribut similaire était appliqué aux paramètres, il deviendrait assez simple de construire un crawler qui, à intervalles réguliers, vérifie si le contenu pointé par l'URL a changé (ou toute autre action arbitraire sur la base de l'URL). Pointer vers la version consolidée d'un article sur Légifrance, par exemple. Ou utiliser le Git de la Loi pour être notifié lorsqu'un fichier (voire une ligne) est modifié…

**Comment by benjello** [comment]
Quelques remarques:
 - Pour détecter les paramètres mal prolongés je suis d'accord avec Matti, il ne faut pas casser tout le processus. Mais il serait utile d'avoir un script qui nous permette de savoir où commencer.
 - Les url ont été introduites par des étudiants au cours d'un stage, elles ne valent pas grand chose.
 - Le but ultime est de rediriger vers les textes de loi / utiliser le Git de la Loi.
 - Beaucoup de références législatives se trouvent dans les paramètres IPP que nous avons commencer à merger avec @eraviart. Cela pose un certain nombre de problèmes de renommage, de champ couvert et de validation. On y est presque et dès que l'on aura un peu de temps, on pourra faire participer tout un chacun au processus.
 - Ceux qui veulent aider dès aujourd'huien mode muddle through, qu'ils se manifestent ... la semaine    prochaine ;-)

**Comment by benjello** [comment]
Moved to #388
