### ISSUE TITLE
Les paramètres de la décote de 2002 à 2013 ne sont pas ceux de la législation

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#338]
Les paramètres de la législation ont semble-t-il été multiplié par deux pour simplifier (en fait pas vraiment ?) la formule de la décote sur cette période.

Je pense qu'il serait bien d'avoir les vrais montants tel que défini par la législation en paramètres, ça facilite les allers retours entre la loi et le code, et limite les erreurs...

On peut peut être d'ailleurs repasser la décote en formula plutôt qu'en dated_formula et rajouter un paramètre coefficient pour la décote.

Je veux bien être assigné mais sera fait sur du moyen terme.

**Comment by benjello** [comment]
@adrienpacifico : est-ce encore d'actualité ? Que veux-tu dire par "de la législation" ? 

Il me semble que les paramètres apparaissant dans les textes de loi sont ceux apparaissant dans les paramètres (fichier param.xml). Vérifier également sur les (barèmes IPP) [https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-xlsx].

Si tu veux te lancer là-dedans, il faut faire un bilan précis de l'existant et lister les actions que tu comptent entreprendre. Sinon cela attendra.

**Comment by adrienpacifico** [comment]
Si on peut laisser ouvert c'est cool, je ne suis pas pleinement content de la manière dont c'est codé, je m'en occuperai en listant clairement mes actions, mais ça attendra...

Non, ce n'est pas les mêmes paramètres dans la loi et le param.xml.
    <NODE code="decote" description="Décote">
      <CODE code="seuil" description="Seuil de la décôte" format="integer" type="monetary">
        <VALUE deb="2002-01-01" fin="2002-12-31" valeur="772" />

Seuil de l'article 197, 4) :  386 euros.
http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=19ED4A6F18EB16471BDE573C36A33C32.tpdila22v_3?idArticle=LEGIARTI000006308347&cidTexte=LEGITEXT000006069577&categorieLien=id&dateTexte=20031230

Les montants sont donc doublés dans le param.xml

Tu peux m'assigner, mais ça ne sera pas pour tout de suite.

**Comment by maukoquiroga** [comment]
Via #400 :

> Cool, merci pour ce travail ! ✨✨✨ Je vais fermer cette pull request ainsi que #338, mais n'hésitez pas à la re-ouvrir si vous pensez que cela a du sens.

Fixed by #918
