### ISSUE TITLE
loyer for families

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#34]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:59 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/162_

---

_Issue by **[AlexisEidelman](https://github.com/AlexisEidelman)** from Tuesday Apr 16, 2013 at 08:23 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/159_

---

So far in the model, household benefit are calculated using the "loyer" variable. 
It is assumed that each familiy pay the rent of its household (men) but in case of more than one family that rent should be shared into the families. 
You can think about house-sharing to be convinced. 

By the way, if I'm not wrong, there is a special legislation in that case.

**Comment by MattiSG** [comment]
Issue ayant plus de 3 ans, pas de travail actif, je ferme.
