### ISSUE TITLE
Support non consecutive parameter values

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#343]
Some parameters may have non consecutive values. For example, the parameter [majoration excceptionnelle](https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-yaml-clean/blob/master/baremes-ipp-impot-revenu-income-tax/majo-excep.yaml) coming from bareme-ipp does not have consecutive dates. But we do want to test for consecutive dates for almost all parameters

What should be done:
- add white list of parameters with non consecutive values ?
- add a new tag when declaring this type of parameters (might be useful for later visualization) ?
- other solution ?

@eraviart @cbenz, i need your input on this.

**Comment by cbenz** [comment]
Like we said on the phone, add a "non-consecutive" lag to a parameter.

**Comment by benjello** [comment]
@cbenz you mean tag ?

**Comment by cbenz** [comment]
yes :)

**Comment by benjello** [comment]
@eraviart : these non-consecutive parameters are produced by parsing the IPP baremes. I do not want to add a "non-consecutive" tag every time I parse them. Could we add a white list allowing some parameters to be non consecutive when parse the excel files or when we merge them to produce parameters.xml ?
You can test the non-consecutive problems by using the [baremes-ipp branch] (https://github.com/openfisca/openfisca-france/tree/baremes-ipp) and running test_legislation

**Comment by MattiSG** [comment]
This issue should be moved to openfisca/openfisca-core, but I'm not even sure it's legit. What happens today if a parameter has non-consecutive values? Is there a check explicitly preventing that?

**Comment by MattiSG** [comment]
This won't happen, as continuity is now an expected behaviour of variables since https://github.com/openfisca/openfisca-core/issues/371 and of parameters. You will need to introduce a differently-named parameter for such special cases, for the sake of readability and ease of write.
