### ISSUE TITLE
Supprimer le paramètre `finpfl`

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#345]
Le paramètre finpfl est toujours dans le code alors que c'est une variable de réforme qui devrait être retirée de l'arbre de paramètre de la législation comme les autres variable #344.
Il faudrait passer en revue les points où finpfl apparaît pour voir si on peut le retirer du code et le mettre dans une réforme.

**Comment by MattiSG** [comment]
Défini dans https://github.com/openfisca/openfisca-france/blob/39f762d4c8a3f86a7688211d7acd9c07c6a01cdf/openfisca_france/parameters/impot_revenu.xml#L158, initialisé dans https://github.com/openfisca/openfisca-france/blob/97a8ba675d1bbdd5c3f1dfbf63fa62c416fdc628/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py#L602, utilisé nulle part. Peut être supprimé.

**Comment by Morendil** [comment]
Je ne trouve aucune mention du paramètre `finpfl` à l'heure actuelle. Vérification faite il a été supprimé par ba1101eeebed6d4ed55fe5db85adacfea1338b2f de @claireleroy dans #1034. Merci! Je ferme donc l'issue.
