### ISSUE TITLE
L'`api` est incluse à tort dans le `rsa` en 2009

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#35]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:59 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/184_

---

_Issue by **[bouvard](https://github.com/bouvard)** from Tuesday May 14, 2013 at 10:00 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/181_

---

there is too much API in 2009, API is included in rsa in june 2009. Perhaps it's due to "annualisation" of api.

**Comment by maukoquiroga** [comment]
Hi @benjello , @MalkIPP and @LouisePaulDelvaux , is this issue still relevant ? I'm trying to see if there's still work to be done here or if we can close it.

**Comment by maukoquiroga** [comment]
Bonjour @benjello, je vais fermer cette issue car il me semble qu'elle n'est plus d'actualité. N'hésites pas à la re-ouvrir si ce n'est pas le cas.
