### ISSUE TITLE
Get rid of build_column and reference_input_variable functions

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#350]
Replace all `build_column` and `reference_input_variable` functions by the decorator "@variable" (or such).

And `Reform.input_variable`

Related to openfisca/openfisca-core#355

**Comment by cbenz** [comment]
- [x] `reference_input_variable ` is removed everywhere https://github.com/openfisca/openfisca-core/commit/87568e7d3c0440779292c335c99bfa0c1e5fd25f
- [ ] `build_columns` remains

**Comment by fpagnoux** [comment]
I used a script to get rid of most the `reference_input_variable`, but it dont think it's reusable for `build_columns`
Maybe parsers can help ?

**Comment by cbenz** [comment]
Can you please publish the script on a gist for example? 
Le 9 déc. 2015 4:11 PM, Florian Pagnoux <notifications@github.com> a écrit :I used a script to get rid of most the reference_input_variable, but it dont think it's reusable for build_columns
Maybe parsers can help ?

**Comment by fpagnoux** [comment]
https://gist.github.com/fpagnoux/94c292506aff71d85f61
It's dirty parsing...

**Comment by cbenz** [comment]
Thanks!

After having searched for a "graal" tool to express code transformations, perhaps using the [parsers](https://github.com/openfisca/openfisca-parsers), I ended up using dirty regexes in Atom.

**Comment by benjello** [comment]
@cbenz : should we close this issue ?

**Comment by cbenz** [comment]
No because some `build_column` functions remain. I'm on it :)

**Comment by cbenz** [comment]
> After having searched for a "graal" tool to express code transformations, perhaps using the parsers, I ended up using dirty regexes in Atom.

I finally found the [RedBaron](https://redbaron.readthedocs.org/en/latest/) Python library, wrote a [transformation script](https://github.com/openfisca/openfisca-france/commit/4e579efe4a66d025176e2a72de484884b6120426) (WIP) and here is a [sample transformed file](https://github.com/openfisca/openfisca-france/blob/bf1565b842ba71a896344adc9eabb06cde8d7c6e/openfisca_france/model/revenus/activite/non_salarie.py) (and the [original file](https://github.com/openfisca/openfisca-france/blob/a2953ef97938a999e5b53952c445d0687aad88a1/openfisca_france/model/revenus/activite/non_salarie.py)).

To be continued...

**Comment by fpagnoux** [comment]
@cbenz @benjello 
All builds columns have been removed, can we close it ?

**Comment by benjello** [comment]
Yep
