### ISSUE TITLE
Corriger le calcul du Libre choix du mode de garde

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#351]
Les seuils des plafonds de ressources du complément du libre choix du mode de garde sont exprimés en pourcentage du plafond maximal. A corriger et utiliser les valeurs disponibles dans les barèmes-ipp.

**Comment by benjello** [comment]
@fpagnoux : aviez vous regarder le complément de libre choix du mode de garde pour mes-aides ?
Cela vous intéresse ?

**Comment by MattiSG** [comment]
@benjello On capture la PreParE (ancienne CLCA), mais on ne capture pas à ma connaissance le CLMG, et on ne calcule aucune des deux prestations.
On est a priori intéressés par toute nouvelle prestation.

**Comment by Morendil** [comment]
Vérification faite le calcul actuellement effectué dans `prestations/prestations_familiales/paje.py` ne semble plus se référer à un plafond exprimé en pourcentage, je ferme donc cette issue.
