### ISSUE TITLE
End date of a taux

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#353]
In this bareme :

```xml
<BAREME code="apprentissage_add" >
  <TRANCHE code="tranche0">
    <SEUIL>
      <VALUE deb="2004-01-01" fin="X" valeur="0" />
    </SEUIL>
    <TAUX>
      <VALUE deb="2006-01-01" fin="X" valeur="0.0018" />
      <VALUE deb="2005-01-01" fin="2005-12-31" valeur="0.0012" />
    </TAUX>
  </TRANCHE>
</BAREME>
```

If `X < 2013-12-31`, the computed taux will be 0 (null)
If `X >= 2013-12-31`, the computed taux will be the last taux, here 0.0018, even if period > X.

 This seems to happen because of the `fin` attribute of the root param.xml node,  `2013-12-31`

**Comment by laem** [comment]
This should at least be documented

**Comment by cbenz** [comment]
See #366
