### ISSUE TITLE
Remplacer les rôles `chef` et `part` par une liste de parents

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#357]
With @fpagnoux we wonder if the two roles "chef" and "part" are relevant.

Is there any formula that treats the "chef" differently that the "part"?

Or should there be "parent1" and "parent2" role?

In test cases we have only a "parents" key associated to a list of 1 or 2 persons.

**Comment by benjello** [comment]
No we should use parent1 and parent2, it is more politically correct. So if you want to change that everywhere, be my guest.

**Comment by cbenz** [comment]
Thanks, I start a pull-request

**Comment by fpagnoux** [comment]
Closing this issue, as `chef` doesn't exist anymore, and there is a more up-to-date and better documented issue about this topic: https://github.com/openfisca/openfisca-core/issues/560
