### ISSUE TITLE
Fetch specific test from Ludwig - mes-aides

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#359]
When a YAML test from mes-aides fails like:

```
FAIL: openfisca_france.tests.test_yaml.test('/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54661ad9f36fa43e77898968.yaml', 'Ressources incluses', u'2014-11', {'output_variables': OrderedDict([('cmu_c', {Period((u'month', Instant((2014, 11, 1)), 1)): array([False], dtype=bool)})]), 'output_variables_name_to_ignore': set([]), 'name': 'Ressources incluses', 'scenario': <openfisca_france.scenarios.Scenario object at 0x7fa119aae1d0>, 'keywords': ['base ressources', 'cmu-c/acs'], 'absolute_error_margin': 0.007, 'description': u"Test sur les ressources incluses dans la base ressource cmu-c/acs.\nPour une personne seule : plafond de 8645 euros sur l'ann\xe9e glissante.\nIci, le demandeur a d\xe9clar\xe9 444 euros sur l'ann\xe9e glissante pour les 20 types de ressources \xe0 prendre en compte dans la base ressource.\n444 * 20 = 8880 euros > plafond de 8645 euros, donc pas de droit \xe0 la CMU-C."}, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/test_yaml.py", line 189, in check_calculate_output
    relative_error_margin = test.get('relative_error_margin'),
  File "/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/test_yaml.py", line 121, in assert_near_calculate_output
    abs(target_value - value), absolute_error_margin)
AssertionError: cmu_c@2014-11: [ True] differs from [False] with an absolute margin [ True] > 0.007
```
 we know the name `test_mes_aides_54661ad9f36fa43e77898968.yaml`. Perhaps that the test has been updated in [Ludwig](https://mes-aides.gouv.fr/tests/54661ad9f36fa43e77898968/show).

It would be useful to have something like:

```
julia scripts/download_mes_aides_tests.jl 54661ad9f36fa43e77898968
```

See https://github.com/sgmap/ludwig-api and https://github.com/openfisca/OpenFiscaFrance.jl/#test

**Comment by MattiSG** [comment]
The most useful thing would be to automate imports, really. `git diff` does a pretty good job at identifying if the test has been updated. The main issue is drag-and-dropping the downloaded folder over the previous one.

**Comment by cbenz** [comment]
wip 848edb0c513b184f7cd9719494c291406e7512a8

**Comment by cbenz** [comment]
Implemented in master: [download_mes_aides_tests.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/scripts/download_mes_aides_tests.py)

@fpagnoux Can you test it? There is a doc at the beginning of the script.

**Comment by fpagnoux** [comment]
I'm looking at it

**Comment by fpagnoux** [comment]
Everything is working for me, thanks a lot for this, it should solve a lot of problems !

**Comment by cbenz** [comment]
Cool ! 
Le 24 nov. 2015 1:59 PM, Florian Pagnoux <notifications@github.com> a écrit :Everything is working for me, thanks a lot for this, it should solve a lot of problems !

**Comment by cbenz** [comment]
So I close the issue
