### ISSUE TITLE
Reorganise capital gains

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#36]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:59 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/194_

---

_Issue by **[benjello](https://github.com/benjello)** from Tuesday May 21, 2013 at 16:38 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/191_

---

Using revenus du patrimoine et revenus de placements as in here:
http://vosdroits.service-public.fr/F2329.xhtml

**Comment by MattiSG** [comment]
Issue ayant plus de 3 ans, pas de travail actif, je ferme.
