### ISSUE TITLE
Refactor legislation XML file

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#366]
# Examples

- we know the parameter does not exist after `2014-12-31`:

```xml
<CODE code="taux">
  <VALUE deb="1991-02-01" fin="1993-06-30" valeur=".011" />
  <VALUE deb="1993-07-01" fin="2014-12-31" valeur=".024" />
</CODE>
```

- we don't know whether the parameter stops or its last value will change after `1993-06-30`:

```xml
<CODE code="taux">
  <VALUE deb="1991-02-01" fin="1993-06-30" valeur=".011" />
  <VALUE deb="1993-07-01" fin="unknown" valeur=".024" />
</CODE>
```

- we have verified that from `1993-07-01` to `2014-12-31` the value is `0.024` but we'd like the value to propagate in the future:

```xml
<CODE code="taux">
  <VALUE deb="1991-02-01" fin="1993-06-30" valeur=".011" />
  <VALUE deb="1993-07-01" fin="2014-12-31" valeur=".024" />
  <VALUE deb="2015-01-01" fin="unknown" valeur=".024" fuzzy="true" />
</CODE>
```

**Comment by MattiSG** [comment]
Why not simply remove the `fin` attribute when it's `unknown`?

I don't understand what happens when there is no `fuzzy` and the `fin` is `unknown`.

**Comment by benjello** [comment]
@cbenz: what is the sechedule for splitting the xml files and reworking the dates ?

**Comment by fpagnoux** [comment]
For Paris, it would be very nice if we could split the xml file before the vacation :)

**Comment by cbenz** [comment]
I just merged the `multiple-param-xml` branch in `master` in core and france.

@benjello You can now work on the `baremes-ipp` branch I think.

My next step is to implement the subject of the current issue.

**Comment by benjello** [comment]
Thanks. I will work on baremes-ipp tomorrow morning

Le mar. 15 déc. 2015 19:45, Christophe Benz <notifications@github.com> a
écrit :

> I just merged the multiple-param-xml branch in master in core and france.
>
> @benjello <https://github.com/benjello> You can now work on the
> baremes-ipp branch I think.
>
> My next step is to implement the subject of the current issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/366#issuecomment-164851972>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by benjello** [comment]
@eraviart I merged master branch containing baremes-ipp. You can deal with dates formatting.

**Comment by cbenz** [comment]
Done by @eraviart
