### ISSUE TITLE
Aide embauche premier salarié

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#368]
On est en train de réfléchir à inclure l'aide pour l'embauche d'un premier salarié dans le simulateur de coût d'embauche. 
@benjello  Est-ce que tu penses qu'on peut tout simplement l'inclure dans la variable [salsuperbrut](http://legislation.openfisca.fr/variables/salsuperbrut) ? 
La description de cette variable est `Salaires superbruts/coût du travail`. Cette prime est déterminante dans le coût du travail (500 euros tous les 3 mois), mais pas forcément à inclure dans un super brut car il faut en faire la demande, et qu'elle est délivrée sous conditions. 
D'ailleurs, si on décide de ne pas l'inclure, et donc par exemple de créer une variable `cout_du_travail` différente de `salsuperbrut`, je pense qu'il faudrait aussi y mettre le CICE, qui lui aussi est accessible sous conditions et imputé de façon complexe. 
https://www.service-public.fr/professionnels-entreprises/actualites/008168

**Comment by laem** [comment]
Après réflexion, je serais pour garder dans `salsuperbrut` les allégements de cotisations sociales (par exemple l'allègement Fillon), et de mettre dans une nouvelle variable `cout_du_travail` toutes les réductions de cotisations sociales qui ne sont pas immédiates, donc notamment le CICE et la prime premier salarié.

**Comment by benjello** [comment]
Je réfléchis ... Et je te réponds ASAP.

Le jeu. 3 déc. 2015 14:22, Mael <notifications@github.com> a écrit :

> Après réflexion, je serais pour garder dans salsuperbrut les allégements
> de cotisations sociales (par exemple l'allègement Fillon), et de mettre
> dans une nouvelle variable cout_du_travail toutes les réductions de
> cotisations sociales qui ne sont pas immédiates, donc notamment le CICE et
> la prime premier salarié.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/368#issuecomment-161638132>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by benjello** [comment]
J'ai fait ma petite enquête et il n'y a pas de terme consacré. Et ta solution me parait très correcte si elle est bien documentée. Si tu pouvais en passant renommer salsuperbrut en salaire_super_brut ce serait parfait.

**Comment by benjello** [comment]
@cbenz Cette presentation va modifier le waterfall et les décompositions. N'hésite surtout pas à ouvrir les bons tickets aux bons endroit pour que l'on règle cela.

**Comment by benjello** [comment]
@laem @cbenz : shouldn't we close this issue ?

**Comment by MattiSG** [comment]
Definitely  :wink:
