### ISSUE TITLE
alloc in foy

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#37]
_Issue by **[benjello](https://github.com/benjello)** from Saturday Mar 01, 2014 at 00:09 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/211_

---

_Issue by **[AlexisEidelman](https://github.com/AlexisEidelman)** from Thursday May 30, 2013 at 15:32 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/212_

---

I try to clean the get value function. 
Doing this I figured out that there is might be a problem with actual code and alloc in irpp. 
It's not a big deal as it's still virtual for now, but is was coded as it was simpler than it is in real. 
I mean in some case, a familiy is on two declaration (non married couple) so what af should we put ? There is also more complicated case. My point is just that there is no order between fam and foy so a legislation should be explicit on that point. 

I change the code by commenting these line and let af = 0 instead.

**Comment by MattiSG** [comment]
Issue ayant plus de 3 ans, pas de travail actif, je ferme.
