### ISSUE TITLE
Add flake8 to CI

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#372]
`make flake8` should always return no error.

---

_Edité par @maukoquiroga_

Relates to #1057 
Relates to  #1060 

Pour continuer l'entreprise initié par @cbenz, je propose une stratégie incrémental :

- [x] Linter seulement les fichier modifiés
- [x] Annoncer sur Slack
- [x] Linter les fichiers `revenus`
- [x] Linter les fichiers `prestations`
- [x] Linter les fichiers `prélèvements obligatoires`
- [x] Linter les fichiers `patrimoine`
- [x] Linter les fichiers `consommation`
- [x] Linter les fichiers `caractéristiques socio-démographiques`
- [ ] Linter le reste de fichiers
- [ ] Ajouter une explication de comment auto-linter dans le `README.md`

**Comment by fpagnoux** [comment]
I guess adding it to `make test` would help to enforce this

**Comment by cbenz** [comment]
New branch [`flake8`](https://github.com/openfisca/openfisca-france/tree/flake8) WIP

**Comment by benjello** [comment]
Good job

**Comment by cbenz** [comment]
I'm gonna do this task incrementally, keeping different commits in the `flake8` branch and merging in `master` on the fly. Otherwise, rebases are a real burden.

**Comment by benjello** [comment]
We have to think about the baremes-ipp merging process too. It might  be better to fix that before starting to merge things that we will need to merge again ...

**Comment by cbenz** [comment]
OK, so I pause this issue

**Comment by Morendil** [comment]
Corrigé par #1135

**Comment by maukoquiroga** [comment]
Bonjour @Morendil, cette issue est encore en cours, merci pour le heads up : il faut que je mette à jour la description.

**Comment by Morendil** [comment]
@maukoquiroga "Le reste des fichiers" c'était bien #1153 ? Peut-on fermer bientôt ?
