### ISSUE TITLE
nosetests fails on branch master

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#380]
Quand je lance nosetests sur ma machine j'ai 3 erreurs et 40 failures sur la branche master.

Le dernier build travis passé était il y a 27 jours.

Ne peut-on pas avoir la branche master qui soit toujours opérationnelle avec les tests qui passent, quitte à créer une branch dev destinée à avoir des tests qui ne passent pas ?

Bonne année à tous,

Adrien

**Comment by MattiSG** [comment]
:+1:

**Comment by fpagnoux** [comment]
master est censée être toujours opérationnelle est faire passer les tests.
Visiblement c'est un update du core qui a tout fait sauté.

Il y a sans doute à faire pour améliorer la gestion des dépendance entre les différents packages, et tant qu'on est pas protégé par des tests automatiques, éviter de merger des updates sur core sans vérifier que tout passe sur France.

**Comment by adrienpacifico** [comment]
Ou aller backward dès que le cas ce présente ? À court terme ça m'arrangerait bien si c'était fait !

**Comment by MattiSG** [comment]
@adrienpacifico si tu es bloqué, jette un œil à https://github.com/sgmap/openfisca qui explicite les dépendances entre les différents composants d'OpenFisca. Mais ça n'est peut-être pas à la toute dernière version de tout ce que tu veux…

**Comment by adrienpacifico** [comment]
@MattiSG  :+1:  Cool ! Je crois que c'est exactement ce qu'il me fallait (pas encore essayé, mais cool d'avoir les références inter-versions) ! 
Merci

@benjello Pourquoi on ne fait pas comme ça sur notre branche (tout dans un seul repo en gérant les dépendances) ?

**Comment by cbenz** [comment]
Je confirme que la branche master doit rester en permanence dans un état où les tests passent. Il y a eu entorse à la règle grandement due aux vacances. Sorry !

**Comment by cbenz** [comment]
@adrienpacifico De plus, toute branche `master` d'un dépôt doit fonctionner avec la branche `master` de tous les dépôts.

Cela garantit que si tu fais `git pull` sur tous les dépôts chacun sur la branche `master` cela fonctionne.

Sinon c'est une erreur de notre part. Pour y remédier on peut en effet dire qu'on "revert" les commits malheureux immédiatement.

Face aux changements de Core et France, même si ceux-ci restent cohérents entre eux, ton code lui peut casser. C'est pour cela qu'on peut mettre en place le "semantic versionning" où on indique via le numéro de version majeur/mineur si un changement est susceptible de casser le code appelant. Mais il faut réinstaller le paquet avec `pip` après chaque `git pull` (d'où le script [`update.sh`](https://github.com/sgmap/openfisca/blob/master/update.sh) j'imagine).

Ou alors on dit que tant qu'on utilise `git` on est en mode développement "à la pointe du progrès" et si on veut plus de stabilité alors on utilise OpenFisca via `pip install`, et on exprime dans le code utilisateur une dépendance avec numéro de version du paquet `pip`.

À documenter prochainement.

**Comment by adrienpacifico** [comment]
Merci @cbenz !

> De plus, toute branche `master` d'un dépôt doit fonctionner avec la branche `master` de tous les dépôts.

* Ce n'est pas tout le temps le cas... Il y a beaucoup d'interdépendances et ça peut être compliqué de faire avancer la branche master dans ces conditions (?)

* Quid si l'on crée un repo dans son coin, il faut pouvoir facilement coller à un écosystème en particulier jusqu'à ce que ça ne fonctionne plus. Un `git checkout 'bon commit à trouver"` sur les 4/5 projets d'openfisca peut vite devenir un vrai casse tête vu le nombre de combinaisons possibles, et la date du commit n'aide pas forcément (je m'y prend peut être mal). Bon on peut être prudent et créer 4/5 branches sur chaque dépôt pour chaque travail à réaliser (fastidieux).

>Face aux changements de Core et France, même si ceux-ci restent cohérents entre eux, ton code lui peut casser. C'est pour cela qu'on peut mettre en place le "semantic versionning" où on indique via le numéro de version majeur/mineur si un changement est susceptible de casser le code appelant. Mais il faut réinstaller le paquet avec pip après chaque git pull (d'où le script update.sh j'imagine).

Dis comme ça semble un peu lourd et overkill pour les gens qui sont dans le bidouillage/contribution light.

Idée comme ça, en fait, pour mon utilisation, il faudrait juste un dictionnaire qui lie chaque commit d'openfisca-france au sha de core, data, web, etc.

```
of_france_links_by_sha = {of_france_sha1 : 
                                          {"of_core_sha" :3bde6, "of_data_sha" : e4f36d, "of_web_sha" : re6y9k, etc.},
                         of_france_sha2 : 
                                          {"of_core_sha" :3vkl7e, "of_data_sha" : 69m7o8, "of_web_sha" : ab54bf, etc.},
                         etc.. 

                         }
```
Après si l'on veut aller à une version précise il suffirait de créer un petit script qui checkout l'ensemble des repo qui sont dans une ligne du dictionnaire pour ne plus avoir à changer toutes les versions tout en permettant de faire des retours en arrière etc.



>Pour y remédier on peut en effet dire qu'on "revert" les commits malheureux immédiatement.

:+1: 

>Ou alors on dit que tant qu'on utilise git on est en mode développement "à la pointe du progrès" et si on veut plus de stabilité alors on utilise OpenFisca via pip install, et on exprime dans le code utilisateur une dépendance avec numéro de version du paquet pip.

Si on a les labels de version pip dans le git tree ça résout un des problèmes sans utiliser pip.
Par contre, l'install pip n'impliquerait-elle pas si on veut contribuer d'installer la version pip et de cloner les différents dépôts (impliquant les conflicts de versions, etc.) en augmentant le coût d'entrée du contributeur ? (quid du pip install -e openfisca ).

(Pour dire que je ne vois pas comment serait le workflow de l'utilisateur utilisant pip et voulant contribuer).

**Comment by MattiSG** [comment]
> Après si l'on veut aller à une version précise il suffirait de créer un petit script qui checkout l'ensemble des repo qui sont dans une ligne du dictionnaire

C'est _exactement_ ce que fait sgmap/openfisca avec Git  ;)

Chaque commit sur `master` correspond à un état stable connu d'une combinaison des quatre dépôts OpenFisca. Revenir à un état connu correspond à faire un `git checkout <identifiant> && ./update.sh`.

**Comment by adrienpacifico** [comment]
Ok, cool, je vais peut être tenter d'utiliser ça.

Du coup @cbenz , je n'ai pas bien compris pourquoi on fait pas ça pour l'ensemble des dépots openfisca ? @MattiSG ?

**Comment by cbenz** [comment]
@adrienpacifico Je ne comprends pas exactement ta question car je l'interprète de 2 manières :

-  tu suggères de couvrir des dépôts git supplémentaires dans `sgmap/openfisca`, comme par exemple `openfisca-web-ui` ?
- ou bien tu proposes d'utiliser cette manière de travailler comme la manière standard et l'ajouter dans la doc ?

Pour te resituer l'histoire de ce dépôt, il a été créé par mes-aides à une époque où la branche master était beaucoup plus souvent cassée car le Core évoluait énormément et les paquets `pip` n'existaient pas encore.
Côté mes-aides la réponse pragmatique a été de créer `sgmap/openfisca`. De mon côté j'ai creusé les releases de paquets `pip` et renforcé le contrôle aux pull-requests pour que les tests passent toujours.

Cela dit le dépôt `sgmap/openfisca` est bien fait et chacun peut s'en servir. Je peux creuser un peu plus afin de l'inclure dans la doc comme solution de dev par défaut.

Question quand même : si les branches `master` sont toujours cohérentes entre-elles et que les tests passent, alors est-ce utile dans ces conditions-là de conserver `sgmap/openfisca` ?

> (Pour dire que je ne vois pas comment serait le workflow de l'utilisateur utilisant pip et voulant contribuer).

En installant Core et France avec `pip` en effet on ne peut pas développer sur Core et France.
Pour cela il faut bien passer par `git` et profiter de `sgmap/openfisca` si on le souhaite. CQFD :-)

Disposer des numéros de version `pip` sous forme de tags `git` peut également aider à revenir à des versions stables du code. Là aussi une synchro cross-repo peut être pratique avec un meta-repo.
Cependant pour développer on repart plutôt de master plutôt que de la dernière version stable.

**Comment by MattiSG** [comment]
> si les branches master sont toujours cohérentes entre-elles et que les tests passent, alors est-ce utile dans ces conditions-là de conserver sgmap/openfisca ?

Je ne comprends pas ce que peut vouloir dire que les branches `master` soient « toujours cohérentes entre elles ». En l’absence de référence à un identifiant de commit stable, elles ne peuvent l’être que par coïncidence temporelle. En cas d’incompatibilité entre mon code client et une nouvelle version de l’un des modules, je ne peux pas revenir en arrière à une version stable d’OpenFisca.
(Ou sinon, il faut un engagement qui me semble complètement irréaliste : un commit de merge sur un module = un commit de merge sur les autres modules.)

L’interêt principal réside dans le fait que cette mise en œuvre nous permet d’avoir une branche par produit, et donc des versions de travail différentes d’OpenFisca, sans publier sur un registry public ou sur master à chaque fois. Je peux ainsi bénéficier de la garantie de cohérence des différents modules sur la version temporaire sur laquelle je développe.

> Disposer des numéros de version pip sous forme de tags git peut également aider à revenir à des versions stables du code. Là aussi une synchro cross-repo peut être pratique avec un meta-repo.

Je ne suis pas certain du besoin d’un meta-repo s’il y a des tags. En revanche, je ne suis pas non plus certain de l’intérêt du tag par rapport au meta-repo.

Si on prend du recul, le seul besoin est d’avoir une référence unique à un état spécifique de tous les modules qui composent OpenFisca, dans la mesure où ils sont interdépendants. La solution la plus courante dans ce genre de cas est la publication sur un registre public d’un paquet référençant un état de chacun des modules.

À défaut, s’il y a une stratégie de versionnement qui assure que tous les modules partagent un numéro de version unique (x.y.z d’un module est compatible avec x.y.z de tous les autres), je ne vois pas l’intérêt d’un meta-repo : chaque dépôt contient la référence qui est nécessaire pour déterminer la version des autres avec laquelle il est censé interagir. Dans ce cas, le coût administratif me semble démesuré : une modification sur un module implique un tagging sur tous les dépôts. Ce serait mitigeable avec `gitslave`, par exemple, mais au vu du nombre de modifs sur `openfisca-france`, on va à mon avis rapidement surtagger tous les autres dépôts.

Si le numéro de version n’est pas partagé, il faut effectivement un espace dans lequel inscrire quel numéro de version d’un module correspond à quels numéros de version des autres modules. Mais dans ce cas, quel est l’intérêt du tag ? S’il n’est pas sémantique, utiliser un SHA ou un tag est équivalent, et on évite alors le coût administratif du tag.

> Cependant pour développer on repart plutôt de master plutôt que de la dernière version stable.

Ce n’est pas censé être la même chose ?

- - - - - -

PS par souci de complétude : au niveau historique, ce n’est pas pour Mes Aides mais pour le Simulateur de Coût d’Embauche que j’ai créé ce dépôt  ;)

**Comment by cbenz** [comment]
@MattiSG Merci pour cette longue réponse.

Je suis pour intégrer le meta-repo dans le projet OpenFisca et l'ajouter à la doc dans le workflow "Install with git" !

Tout cela mêlé avec [Conda](https://github.com/openfisca/openfisca-gitbook/pull/6) risque de simplifier encore l'installation.

Précisions :

> les branches master sont toujours cohérentes entre-elles

Je voulais dire que les extrémités des branches `master` des différents dépôts fonctionnent bien ensemble à l'instant présent; si on veut remonter dans le passé on ne sait pas en effet reconstituer la "coïncidence temporelle", je suis d'accord.

Mon raisonnement était : le développeur fait `git pull` sur tous les dépôts OpenFisca sur `master` et dispose immédiatement d'une version qui marche. Puis il adapte son code à la nouvelle version si besoin est.

Mais j'avais sous-estimé le besoin de remonter dans le passé, soit lorsque le code utilisateur est cassé, soit lorsqu'on veut travailler avec des feature branches dans Core et France.

--

> >  Cependant pour développer on repart plutôt de master plutôt que de la dernière version stable.

> Ce n’est pas censé être la même chose ?

Si ! Je voulais dire : Cependant pour développer on repart plutôt de master plutôt que de la dernière version *publiée* sur `pip`.

--

Sinon je suis tout à fait d'accord que les SHA sont aussi efficaces que les tags pour stocker la coïncidence temporelle. Les tags sont utilisés pour les numéros de release `pip`.

Enfin, je me demande à quel moment vous faites un commit de synchro sur le meta-repo. J'imagine que c'est à chaque fois qu'on déploie une version ?

**Comment by MattiSG** [comment]
> Enfin, je me demande à quel moment vous faites un commit de synchro sur le meta-repo. J'imagine que c'est à chaque fois qu'on déploie une version ?


En upstream de openfisca/openfisca-france vers sgmap/openfisca-france, tu veux dire ?

Non, on fait les màj quand on a des modifs à faire. Si on passe par ce système, c’est justement pour ne pas subir les mises à jour systématiques et parfois incohérentes, du type de celle qui est à l’origine de cette issue.

Encore une fois, replaçons la solution dans le contexte du problème. La solution normalement employée par la communauté dans le genre de cas qui nous occupe est la publication de paquets stables sur un registre public, numérotés avec semver.

Le meta-repo est une implémentation alternative de l’explication de dépendances à plusieurs modules en même temps. Il s’agit donc toujours d’un moyen pour un produit client de pointer vers plusieurs références en même temps. De la même manière qu’on mettrait à jour volontairement un numéro de version dans un fichier de définition de dépendances plutôt que de le subir, on ne met à jour le meta-repo que lorsqu’un produit a un intérêt à incorporer les modifications.

Notre objectif ici n’est pas de maintenir des pointeurs vers l’ensemble des états stables d’OpenFisca (ne serait-ce que parce qu’il n’y a pas de changelog et que nous n’avons pas les ressources à investir dans de la rétro-ingénierie), mais de maintenir des pointeurs vers des états cohérents utilisés par nos produits à des moments donnés.
Chaque produit utilisant cette implémentation comme moyen de maintenir des états cohérents doit gérer les commits à chaque mise à jour.

Si vous voulez maintenir cet historique, pas de souci pour vous laisser la main sur `master` et utiliser de notre côté des branches nommées par produit  :)

**Comment by cbenz** [comment]
OK c'est plus clair merci.

- Je n'ai pas envie de maintenir l'ensemble des états stables d'OpenFisca moi non plus.
- Les releases `pip` sont trop rares pour servir de base aux développements. Elles pourraient être accélérées mais n'atteindront jamais a priori le rythme d'une release "patch" par commit.
- Donc il reste le meta-repo qui a bien du sens.

**Comment by cbenz** [comment]
Dès demain soit je revert les commits qui cassent les tests soit je corrige les tests. 
Je confirme que la branche master doit rester dans un état qui permette à tous les tests de passer. Il y a eu entorse ! 
Le 5 janv. 2016 8:00 PM, adrienpacifico <notifications@github.com> a écrit :Ou aller backward dès que le cas ce présente ? À court terme ça m'arrangerait bien si c'était fait !

**Comment by benjello** [comment]
@cbenz: quels sont les commit problématiques que je pourrais aider à résoudre ?

**Comment by cbenz** [comment]
Mazette, cet email est arrivé avec un retard de plusieurs jours. Ne pas en tenir compte.
