### ISSUE TITLE
Importer les références législatives des barèmes IPP

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#382]
- [ ] add references to legislation articles
- [ ] add references to XLS file and tab

**Comment by MattiSG** [comment]
Serait un correctif partiel de #152.

**Comment by MattiSG** [comment]
Importer sous la forme `url = `.

**Comment by benjello** [comment]
Les références ne sont pas forcément une URL. Il s'agit d'articles de loi, décrets, circulaires etc. Il y a généralement la date de parution au JO. Les onglets contiennent également des informations plus générales. Vous trouverez [ici](https://framagit.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-yaml-clean/blob/master/baremes-ipp-prelevements-sociaux-social-security-contributions/casa.yaml) un bon exemple.

**Comment by MattiSG** [comment]
Duplicate of #152.
