### ISSUE TITLE
PPE cassée

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#385]
simulation.calculate("ppe") ne fonctionne pas sur la branche master, il y a un problème de période (en lien avec le [commentaire d'@eraviart dans rsa.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/rsa.py#L641).

J'ai corrigé un petit peu en bricolant en local, cependant je ne retombe pas sur les valeurs du simulateur dgfip.

Je peux être assigné, mais ça ne sera pas pour tout de suite.

**Comment by adrienpacifico** [comment]
J'ai pushé mes modifs locales [ici](https://github.com/adrienpacifico/openfisca-france/commit/63cb75a5a96647da2055b4728a9a53ddfdad8217)

**Comment by benjello** [comment]
Merci @adrienpacifico

**Comment by adrienpacifico** [comment]
J'ai pushé mes modifs locales [ici](https://github.com/adrienpacifico/openfisca-france/commit/63cb75a5a96647da2055b4728a9a53ddfdad8217), les formules de rsa.py ont été changée car j'avais des erreurs d'appel circulaire, mais c'est peut être overkill.

**Comment by adrienpacifico** [comment]
@benjello c'est sur ton calendrier ou pas du tout ?

**Comment by benjello** [comment]
Je n'en ai pas un besoin urgent et j'ai pas le temps.

**Comment by MattiSG** [comment]
Personne n'ayant de besoin urgent ni de temps depuis plus d'un an, je ferme.
