### ISSUE TITLE
PPE needs testing

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#386]
Il n'y a aucun test sur la ppe > 0  dans les tests .yaml

Il faudrait s'en occuper, si les simulateurs de la dgfip disparaissent on n'aura plus de benchmark.

**Comment by benjello** [comment]
Il faudrait se remettre à ré-utiliser les tests dgfip (peut-être hors travis) pour tester ces points là également. Voir même récupérer ce qui avait été fait avec taxipp.
@cbenz @eraviart comment voyez-vous la réintégration des tests dgfip ?

**Comment by adrienpacifico** [comment]
Deux exemples de tests sur la ppe (qui ne passent pas) [ici](https://github.com/adrienpacifico/openfisca-france/commit/8e880743baa428005a0575d7f0c110466def32ee)

Quelle est la politique de commit pour les tests qui ne passent pas ?

**Comment by benjello** [comment]
Trouver la solution. Je serais d'avis qu'il faut les inclure mais les ignorer dans les tests travis car cela touche à des vieilles années. Ouvrir une issue et documenter l'erreur et les tests. Mais il faut surtout la résoudre !

**Comment by adrienpacifico** [comment]
@benjello  la bonne réponse m'avait été donné par christophe est est dans la doc [ici](http://doc.openfisca.fr/contribute/tests.html#ignored-tests)

**Comment by MattiSG** [comment]
Issue vieille de plus d'un an et demi, pas de porteur identifié, toutes les formules pourraient bénéficier de plus de tests, je ferme.
