### ISSUE TITLE
Fix fuzzy legislation values in the past

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#389]
In `param.xml` there are some `fuzzy` values. Some of them are in the past. They must be replaced by real values, in general coming from "IPP baremes".

> `fuzzy` values in the future may not by removed.

See https://github.com/openfisca/openfisca-core/issues/368 for background information.

**Comment by laem** [comment]
This issue is refering to **past** fuzzy values only right ?

**Comment by benjello** [comment]
Yes at least as I understood it ;-)

Le lun. 11 janv. 2016 10:33, Mael <notifications@github.com> a écrit :

> This issue is refering to *past* fuzzy values only right ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/389#issuecomment-170485642>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by cbenz** [comment]
@laem Yes, and I fixed the issue title

**Comment by cbenz** [comment]
Cancelled, since I did not introduce `fuzzy` values in the past finally.
