### ISSUE TITLE
Ristournes Juppé (I, II et III) (1995-2003)

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#392]
Ces allègements de cotisations sociales (patronales) sur les bas salaires introduits par Juppé en 1995 pour remplacer les allègements famille sont absents. 
Cf. les paramètres du [fichier excel](http://www.ipp.eu/wp-content/uploads/2015/04/baremes-ipp-prelevements-sociaux-social-security-contributions.xlsx), onglet ALLEG_GEN.

**Comment by Morendil** [comment]
Je ferme, le recensement des dispositifs législatifs à modéliser se fait désormais sur [le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
