### ISSUE TITLE
Allègement Aubry (2000-2003)

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#393]
Ces allègements de cotisations sociales (patronales) sur les bas salaires sont absents. Ils ont été introduits par Aubry pour les entreprises appliquant la réforme de réduction du temps de travail (passage au 35h).  
Cf. les paramètres du [fichier excel](http://www.ipp.eu/wp-content/uploads/2015/04/baremes-ipp-prelevements-sociaux-social-security-contributions.xlsx), onglets AUBRY I et AUBRY II.

**Comment by Morendil** [comment]
Je ferme, le recensement des dispositifs législatifs à modéliser se fait désormais sur [le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
