### ISSUE TITLE
Allègements de cotisations sociales transitoires (2003-2005) 

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#394]
Ces allègements de cotisations sociales (patronales) sur les bas salaires sont absents. Ils ont été introduits par la réforme Fillon pour permettre une convergence des barèmes d'allègement, différant suivant que les entreprises applique la RTT ou pas.

Cf. les paramètres du [fichier excel](http://www.ipp.eu/wp-content/uploads/2015/04/baremes-ipp-prelevements-sociaux-social-security-contributions.xlsx), onglet FILLON.

**Comment by Morendil** [comment]
Je ferme, le recensement des dispositifs législatifs à modéliser se fait désormais sur [le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
