### ISSUE TITLE
Corriger le calcul de l'allègement Fillon

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#395]
Modifier le calcul de la composante dépendant du salaire car elle a évolué au cours du temps selon 
les notes du barème IPP idoine

**Comment by MattiSG** [comment]
@benjello pour faciliter le traitement par d'autres contributeurs, pourrais-tu a minima mettre un lien vers les notes en question, voire les copier ici ? :slightly_smiling_face:

**Comment by Morendil** [comment]
Après vérification j'ai l'impression que nous conservons bien [un historique de l'évolution de ces taux](https://fr.openfisca.org/legislation/prelevements_sociaux.fillon.ensemble_des_entreprises.reduction_maximale.entreprises_de_moins_de_20_salaries). Je ferme donc l'issue sur l'hypothèse que cette carence est corrigée.

Je suis un peu familier de cet allègement pour avoir travaillé dessus cette année (#862) en confrontant les résultats à ceux obtenus avec https://github.com/betagouv/syso mais je n'avais pas pris connaissance de cette issue plus ancienne - @benjello si tu as un souvenir plus précis de ce qui te préoccupait, et qu'il te semble que ce n'est toujours pas adressé, je t'invite à réouvrir en apportant un complément d'information.

**Comment by benjello** [comment]
@Morendil : télécharger le fichier excel se trouvant ici https://www.ipp.eu/outils/baremes-ipp/prelevements-sociaux/ puis aller à l'onglet fillon.

**Comment by Morendil** [comment]
C'est fait, je te confirme que notre historique est correct (même si l'explorer affiche des valeurs arrondies à la troisième décimale ce qui donne l'impression de valeurs incorrectes à première vue), en tout cas pour la plage de dates prise en charge par OpenFisca (à partir de 2005).
