### ISSUE TITLE
Documenter qu'il faut tester systématiquement les changements

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#396]
Les tests d'openfisca-france sont un peu disparates : certaines prestations sont très bien testées (notamment grâce aux tests mes aides), d'autres ne le sont pas du tout.

Des choses telles que [PR#384](https://github.com/openfisca/openfisca-france/pull/384) ou [Issue#385](https://github.com/openfisca/openfisca-france/issues/385)/[Issue#386](https://github.com/openfisca/openfisca-france/issues/386) ne devraient pas être possible.

Il est peut être nécessaire de définir une stratégie de test systématique, voici quelques points qui pourraient améliorer les choses ? :
- Faire un script qui vérifie qu'une formule est testée d'une manière ou d'une autre pour une valeur différente de zéro.

Certaines formules sont testés de fait car une autre formule appelante est testée, il faudrait s'assurer que 1) toutes les formules sont testées ; 2) Qu'elles sont toutes testées pour une valeur différente de zéro.
- Imposer que toute nouvelle prestation codée fasse l'objet d'un test avec la pull request qui l'accompagne. Ça permettrait d'éviter toute future déconvenue.
- Faire un script qui permette de lister les années non testées pour une prestation spécifique afin de pouvoir efficacement enrichir les tests pour les années non testées.

**Comment by MattiSG** [comment]
- [ ] Systématiquement exécuter tous les tests en CI (depends on #397).
- [ ] Documenter l'ajout de tests comme partie du processus de rédaction d'une formule.
