### ISSUE TITLE
Faire passer tous les tests

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#397]
Y-a-t-il des directives pour les tests qui ne passent pas ?
@Benjello semble dire que non ( voir [#386](https://github.com/openfisca/openfisca-france/issues/386) )

Ce que l'on pourrait faire est :
- Si la formule ne change pas d'année en année, qu'un certains nombre de tests passent, mais que des cas particuliers ne passent pas, on pourrait commenter ces cas particuliers au sein du yaml, commiter les tests commentés, ouvrir une issue référençant l'ensemble des lignes ne passant pas.
- Si la formule n'est pas testée (ou que c'est une dated_formula non testée pour ses années), créer un fichier nonpassing_test_formulaname.yaml qui serait exclu des tests travis de par son nom ; ouvrir une issue.

**Comment by cbenz** [comment]
Remettons les choses dans le contexte d'un dev logiciel classique.

On ajoute un test :

- avant ou après (le débat n'est pas là) qu'une fonctionnalité ait été ajoutée. Dans ce cas c'est dans `master`.

- pour mettre en lumière un bug du logiciel. Dans ce cas on commite le test dans une feature branch, et dans cette même branche on continue à fixer le bug. Ensuite on merge la feature branch dans `master` introduisant une nouvelle fonctionnalité et les tests qui vont avec.

Donc on ne devrait pas à avoir à ignorer des tests.

Nous on est dans un cas où on avait des tests historiques qui ont été cassés par de nouvelles fonctionnalités. On aurait pu, par ordre de préférence, les corriger, les supprimer, les commenter ou les ignorer.

**Comment by cbenz** [comment]
Suite à ce pavé de texte, on peut en déduire qu'on choisit d'ignorer les tests qui ne passent pas, et qu'on les garde pour ne pas les oublier. Il faudrait dans l'idéal se rappeler qu'ils existent régulièrement et voir si on peut les corriger au fil de l'eau. Pourquoi pas faire une issue par test ignoré mais tout dépend de la granularité, on peut regrouper par domaine de la législation.

Pour les tests YAML je suis plutôt pour créer un répertoire `ignored` pour les fichiers entièrement ignorés.

Pour le suivi qualité des formules testées, c'est en effet un script qu'on peut faire, avec l'aide des parsers. Cela permettrait de tester les formules à des valeurs limites. C'est un vrai sujet qui n'est a priori pas simple car il faut détecter dans le code source les fameuses limites.

**Comment by cbenz** [comment]
Je crois que j'ai répondu pour l'issue https://github.com/openfisca/openfisca-france/issues/396

**Comment by MattiSG** [comment]
De mon expérience, mieux vaut supprimer les tests non exécutés systématiquement. C'est du code, avec donc ses coûts habituels de maintenance, mais mort donc ces coûts sont inutiles, et ils ont pour effet de bord un faux sentiment de sécurité.
Tout étant dans le VCS, si on veut finalement récupérer du code de test précédent, on peut toujours le récupérer (penser à écrire un message de commit de bonne qualité).

**Comment by adrienpacifico** [comment]
@MattiSG J'ai un doute sur le laisser dans le vcs.
1. On risque de les oubliers
2. Pour mon utilisation l'urgence est d'avoir le maximum de prestations testées, et donc le maximum de tests. Oublier des tests déjà existant n'est peut être pas super. Voir un dossier `ignored` rappelle à tout le monde assez souvent qu'il y a ces tests qui sont à réintégrer ?

**Comment by MattiSG** [comment]
> 1. On risque de les oublier

De mon expérience, ce n'est pas voir des tests non exécutés qui motive à les mettre à jour et les faire tourner, mais se prendre une énorme claque parce qu'un truc foire et qu'on pensait que c'était testé  :wink:  et à ce moment-là, on écrit des tests, peu importe qu'il y ait déjà un squelette ou non.

Faites comme vous voulez.
Je dis simplement qu'un test n'a de valeur qu'à partir du moment où il renvoie "vert" ou "rouge" (en fait, il a même une valeur décroissante avec sa stabilité, [cf. 1.5](http://pythontesting.net/strategy/why-most-unit-testing-is-waste/)).
En revanche, maintenir du code a un coût non nul, ne serait-ce que le coût cognitif de sa prise en compte dans une hiérarchie de dossiers. Donc, un test qui n'est pas exécuté est juste un coût.
J'enlève donc systématiquement de mes codebases les tests non exécutés, au même titre que du code mort ou du code mis en commentaire. Maintenant, je ne suis pas mainteneur ici  :wink:

**Comment by cbenz** [comment]
@MattiSG Je suis d'accord avec ça, c'est le plus propre. On peut aussi s'appuyer sur une branche git come "dead-tests" et pourquoi pas créer une issue pour les garder en tête. Après les réflexions d'hier je pense qu'il faut oser faire ça.

**Comment by adrienpacifico** [comment]
:+1:  , @cbenz pour moi ça ne répond pas à #396 , et j'aimerai bien que quelqu'un rentre dans la discussion. Ou alors je crée une issue pour chaque prestation qui ne me semble pas testée ?

**Comment by MattiSG** [comment]
- [ ] Supprimer les tests ayant un `ignore`.
- [ ] Retirer le support pour `ignore`.
- [ ] Retirer le support pour le préfixe `IGNORE_` et commenter les lignes correspondantes.
- [ ] Systématiquement exécuter tous les tests en CI.

Si le besoin apparaît de créer des "spécifications", c'est-à-dire si des contributeurs souhaitent contribuer des tests sans être capables de contribuer leur implémentation :

1. Passer par des branches _long-lived_. Le coût de mise à jour sera ainsi payé en une seule fois quand un contributeur capable de coder les formules nécessaires sera disponible.
2. Alternative : reprendre le concept de _ignore_, avec un attribut _spec_ ou similaire. Mais cette fois, les tests sont systématiquement exécutés et un résultat d'échec est attendu, et la CI échoue si une erreur est levée (garantit la mise à jour de ces tests) ou si les tests passent (augmente la couverture des effets de bord).
