### ISSUE TITLE
fix invalides in build survey

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#40]
_Issue by **[benjello](https://github.com/benjello)** from Saturday Mar 01, 2014 at 00:14 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/256_

---

_Issue by **[benjello](https://github.com/benjello)** from Thursday Jun 27, 2013 at 12:04 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/257_

---

**Comment by MattiSG** [comment]
Issue ayant plus de 3 ans, en attente de validation de fermeture, je ferme.
