### ISSUE TITLE
Éclaircir pourquoi certains tests ne sont pas exécutés en CI

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#402]
```
$ nosetests openfisca_france/tests/reforms/test_plf2015.py
```

Cette commande fait casser le test chez moi sur la branche master, j'en déduis qu'il n'est pas exécuté puisque les tests Travis passent... Et donc probablement qu'aucune réforme n'est testée.

CC @cbenz

**Comment by benjello** [comment]
Pour savoir quels sont les tests exécutés par travis il faut regarder le [Makefile] (https://github.com/openfisca/openfisca-france/blob/master/Makefile)

**Comment by adrienpacifico** [comment]
Et le fait que des tests ne soient pas exécuté n'est pas une issue ?

**Comment by benjello** [comment]
Tu peux en ouvrir pour chaque test non exécuté si tu veux.

**Comment by cbenz** [comment]
@adrienpacifico Oui c'est une issue, mais à résoudre à long ou moyen terme.

**Comment by adrienpacifico** [comment]
* Il y a un répertoire test. 
* Des tests sont volontairement exclus des tests travis par le makefile (j'étais persuadé qu'ils étaient exécuté).
* Il y a donc plein de choses qui sont cassées dans openfisca, c'est implicite et non référencé dans la [doc](http://doc.openfisca.fr/contribute/tests.html)

Je ne vois pas en quoi proposer des tests, pour ne pas les tester n'est pas un problème, sachant que tout porte à croire que ceux-ci sont testés.

Soit il faut retirer ces tests du projet, soit le placer dans un dossier explicitement nommé non_tested_test, soit les réintégrer dans le travis.

Je ne saisi pas s'il y a de l'ironie dans  : 

> Tu peux en ouvrir pour chaque test non exécuté si tu veux.

Mais pour moi c'est un vrai problème, qui mérite d'être traité.

Les tests json ne sont plus executable uniquement car les imports ont changé, etc. On laisse du code vieillir sans l'entretenir, dans quel but ?

**Comment by benjello** [comment]
Adrien : on ne va pas faire un nouveau répertoire car comme tu le dis toi-même les tests non exécutés sont listés dans le Makefile. 

S'ils n'ont pas été traités c'est que l'urgence à l'époque n'était pas à la migration de ces tests. Maintenant si tu veux prendre part au travail de maintenance, nettoie ces tests cela sera très utile.

**Comment by adrienpacifico** [comment]
Ok, je m'occuperai de voir les tests json qui cassent, peut être les réformes ; mais je ne comprends pas que l'on ne soit pas plus explicite sur ce point, le makefile n'est pas forcément ce que l'on va aller voir en premier...

**Comment by cbenz** [comment]
@adrienpacifico je suis d'accord, cela prête à confusion.
Ces tests ignorés devaient être temporaires mais continuent d'exister.

Un pas en avant vers plus de qualité serait de créer un répertoire `ignored_tests` au même niveau que `tests` et déplacer les tests ignorés dedans. Puis de modifier le [`Makefile`](https://github.com/openfisca/openfisca-france/blob/ea869ad3c98e633ed3de84fa8618a045b5ebe4f9/Makefile#L1) pour ignorer ce répertoire plutôt que les tests un à un.

Pour la doc : https://github.com/openfisca/openfisca-gitbook/commit/0ccd24e81533f43db20b111d652962d6e8765ef7

**Comment by adrienpacifico** [comment]
@cbenz Je suis prêt à m'en occuper s'il le faut. Ça expliciterait qu'ils ne sont pas inclus et permettrait un travail accessible et facile pour un nouveau contributeur (réintégrer les tests dans `ignored_tests` ou les transformer en yaml ?).

**Comment by cbenz** [comment]
@adrienpacifico Dans ce cas fais une proposition dans une branche dans ton fork.

En revanche ne déplace que des tests Python et pas YAML. Certains tests YAML sont marqués par `ignore: true` ([exemple](https://github.com/openfisca/openfisca-france/blob/ea869ad3c98e633ed3de84fa8618a045b5ebe4f9/openfisca_france/tests/formulas/irpp.yaml#L297)) et doivent rester là où ils sont.

Si tu arrives en plus à transformer certains tests Python en YAML on est preneurs.

merci

**Comment by MattiSG** [comment]
Merci @adrienpacifico de proposer de t'en charger en tous cas, ce serait vraiment une belle avancée que de résoudre ce point !! :smiley:

**Comment by adrienpacifico** [comment]
Merci Christophe,

> @adrienpacifico Dans ce cas fais une proposition dans une branche dans ton fork.

Je ne comprends pas exactement ce que tu veux dire. Mon workflow habituel est de créer une branche sur mon fork, puis de créer une PR sur master a partir de ma branche (et je ne connais pas d'autre moyen de faire).

>En revanche ne déplace que des tests Python et pas YAML. Certains tests YAML sont marqués par `ignore: true` ([exemple](https://github.com/openfisca/openfisca-france/blob/ea869ad3c98e633ed3de84fa8618a045b5ebe4f9/openfisca_france/tests/formulas/irpp.yaml#L297)) et doivent rester là où ils sont.

Ok, j'ai posé une question avec #397 , et vient de faire #400 qui commentent des codes avec du `#` en début de ligne. Est-ce que `ignore: true` est la bonne façon de faire quand on trouve un test qui ne passe pas, dans quel cas faut-il le mettre ? 

Dans la doc section contribute, il n'est pas précisé que l'on peut créer des tests (alors que c'est peut être un premier marchepied accessible), et il n'y a pas de guidelines sur la création de ceux-ci.

Ces remarques peuvent peut-être s'inscrire dans l'issue #396 qui n'a pas vraiment déclenché de réactions...

**Comment by cbenz** [comment]
OK pour ton workflow qui est le bon, je voulais rien dire de plus :)

Je réponds sur les issues respectives.

Quand à la doc si tu le souhaites, tu peux être contributeur également : https://github.com/openfisca/openfisca-gitbook à forker

**Comment by cbenz** [comment]
https://github.com/openfisca/openfisca-gitbook/commit/c8eea9b97843d8d9e82d7fc1c149f95526aba960

**Comment by MattiSG** [comment]
Documenté dans https://github.com/openfisca/openfisca-gitbook/commit/c8eea9b97843d8d9e82d7fc1c149f95526aba960.
