### ISSUE TITLE
Make parameters merge script reentrant

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#407]
This follows a discussion with @benjello, @MalkIPP and @laem.

The script [`merge_ipp_tax_and_benefit_tables_with_parameters.py`](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/scripts/merge_ipp_tax_and_benefit_tables_with_parameters.py) is not reentrant (if I modify for instance [`isf.xml`](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/parameters/isf.xml) and re-execute the script, the modifications should be kept).

This would prevent the projets like Mes aides to contribute in XLS files.

Note: for now it is possible to contribute in `param.xml` which is read by the script, but it constrains the contributor to know the mapping (`param-to-parameters.yaml`) and apply it backwards, to find the old parameter name starting from a formula.

@eraviart Would it be difficult to make the script reentrant?

**Comment by cbenz** [comment]
After a discussion with @eraviart, it's not a good idea to make a script reentrant, based on the experience of [`generate_columns_tree.py`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/scripts/generate_columns_tree.py) which generates [`datatrees.py`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/datatrees.py) while keeping the modifications of the latter.

Instead of making the script reentrant, we can modify `param.xml` to reflect the new structure of `parameters.xml` and delete the mapping rules declared in `param-to-parameters.yaml` accordingly.

**Comment by benjello** [comment]
You mean reentrant by hand ;-)
