### ISSUE TITLE
Make preprocessing more explicit

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#409]
Instead of defining a [`preprocessing` method](https://github.com/openfisca/openfisca-france/blob/ea869ad3c98e633ed3de84fa8618a045b5ebe4f9/openfisca_france/__init__.py#L78) and [letting the Core call it](https://github.com/openfisca/openfisca-core/blob/4f9fe592ae8378131f9799ff0d114e66c07ec288/openfisca_core/taxbenefitsystems.py#L141), which is hard to guess by someone who reads the source code of a formula, call "generator" functions directly from formulas.

Example:

``` python
def function(self, simulation, period):
    param1 = simulation.legislation_at(period.start).x.y.z
    generated_param = generate_param(param1)
```

(this is just the idea)

**Comment by laem** [comment]
The situation today for the `cotsoc` part, is that a preprocessing file rewrites the whole param hierarchy, and makes understanding and contributing a mess. But it is necessary at the moment, for the params have multiple categories expressed through tree levels (*cotisation patronale* / *cotisation salarié*, *cotisations privé* / *cotisation fonctionnaire*, *cadre / non-cadre*).

Some of these categories are OpenFisca input variables (*cadre/non-cadre/public*, *taille entreprise* which duplicates baremes) and could be filtered dynamically if correclty expressed in the param file. 
Others correspond to *sum variables* (e.g. `class cotisations_employeur`), or non-existing variables that may still have an interest for categorizing params (e.g. `cotisations URSSAF`) that may be implemented with tags, letting us flatten the param file.

**Comment by cbenz** [comment]
> the hierarchical view can be useful : should the most used one be kept (but with tags), or should we implement a view system to explorer params with one of a list of tag trees ?

We could represent the main hierarchy by splitting parameters in many XML files in the `parameters` directory. This is more categories/domains than a tree.

```
parameters/bouclier_fiscal.xml
parameters/isf.xml
[...]
```

Inside each XML file there would be a flat list of `<CODE>` or `<BAREME>`, without any `<NODE>`, whose names would be in "dot notation", like:

```xml
# parameters/isf.xml

<BAREME code="bareme" description="Impôt de solidarité" type="monetary">
  <TRANCHE code="tranche0">
    <SEUIL>
      <VALUE deb="2015-01-01" fuzzy="true" valeur="0" />
      <VALUE deb="2001-01-01" fin="2014-12-31" valeur="0" />
    </SEUIL>
    <TAUX>
      <VALUE deb="2015-01-01" fuzzy="true" valeur="0" />
      <VALUE deb="2001-01-01" fin="2014-12-31" valeur="0" />
    </TAUX>
  </TRANCHE>
  [...]
</BAREME>
<CODE code="decote.base" description="Base montant décote" format="float">
  <VALUE deb="2015-01-01" fuzzy="true" valeur="17500" />
  <VALUE deb="2013-01-01" fin="2014-12-31" valeur="17500" />
</CODE>
<CODE code="decote.max" description="Plafond de la décote" format="float" type="monetary">
  <VALUE deb="2015-01-01" fuzzy="true" valeur="1400000" />
  <VALUE deb="2013-01-01" fin="2014-12-31" valeur="1400000" />
</CODE>
<CODE code="decote.min" description="Plancher de la décote" format="float" type="monetary">
  <VALUE deb="2015-01-01" fuzzy="true" valeur="1300000" />
  <VALUE deb="2013-01-01" fin="2014-12-31" valeur="1300000" />
</CODE>
<CODE code="decote.taux" description="Taux de la décote" format="percent">
  <VALUE deb="2015-01-01" fuzzy="true" valeur="0.0125" />
  <VALUE deb="2013-01-01" fin="2014-12-31" valeur="0.0125" />
</CODE>
```

(Or we could do YAML...)

> No need to prefix by `isf.` since it's the name of the file.

Tags could be added like that:

```xml
<CODE code="decote.base" description="Base montant décote" format="float" tags="contributif, patronal">
  <VALUE deb="2015-01-01" fuzzy="true" valeur="17500" />
  <VALUE deb="2013-01-01" fin="2014-12-31" valeur="17500" />
</CODE>
```

--

> how to call flat params from formulas ?

A Python API for accessing a flat parameters file could be like:

```python
def function(self, simulation, period):
    value = simulation.legislation_at(period.start, 'isf.decote.base')
    # or
    value = simulation.legislation_at(period.start, 'isf', 'decote.base')
```

The notation `simulation.legislation_at(period.start).isf.decote.base` is not useful anymore since we don't need to store sub-nodes in variable anymore, like:

```python
def function(self, simulation, period):
    decote = simulation.legislation_at(period.start).isf.decote
    # [...] some code
    base = decote.base
    # [...] some code
```

Also, having names in dot-notation allows to *grep* those names, which is useful when we see them in the formula source.

**Comment by MattiSG** [comment]
This discussion did not reach any consensus. It is interesting as history and food for thought, but it is not actionable, and today's take at the same problem would probably be different. Closing.
