### ISSUE TITLE
Merge barèmes IPP / split param.xml / clean them

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#410]
This is a description of the work of @benjello and @eraviart, and the discussions of yesterday. 

_Barèmes IPP_ are XLSX files corresponding to sections of the legislation's parameters. Each file has tabs that can be mapped to nodes in param.xml : 

![selection_008](https://cloud.githubusercontent.com/assets/1177762/12444744/b81b18f8-bf60-11e5-9b3b-0006d189ef45.png)

The idea is to merge these _barèmes_ into OpenFisca's parameters. All of this happens in branch baremes-ipp until #407 is fixed. 
1. IPP is now using a [gitlab repository](https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-xlsx) to store these xlsx files and use issues. 
   Writing in tables is easier than handling XML for economists (it is after all a graphical interface to another XML format), but the main drawback is that there is no diff possible (there may be after dezipping the file, but it would be polluted)...
2. Another gitlab repository converts these XLSX files to raw YAML, and then cleaner YAML files. These are diffable, and modifications can be validated in the XLSX directory with merge requests. 
3. A new XML file is created for each section of the legislation (e.g. _prélèvements sociaux_ or _prestations sociales_), whose content is a merge of both worlds. 
   - it has OpenFisca's param format (`<BAREME>`, `<NODE>`, `<VALUE>`...)
   - names and paths are updated to be clearer.
   - it has _barèmes IPP_ 's hierarchy

OpenFisca's param names are mapped to new names in this [file](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/param/param-to-parameters.yaml)
_Barèmes IPP_ tables are transformed into OpenFisca XML nodes with this huge [script](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/param/ipp_tax_and_benefit_tables_to_parameters.py)
This [script](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/scripts/merge_ipp_tax_and_benefit_tables_with_parameters.py) is run to create the new, splitted, parameter files, e.g. [_prélèvements sociaux_](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/parameters/prelevements_sociaux.xml)
# What remains to do

To complete the first merge :
- Complete the two files above to handle all the tables of _barèmes IPP_. 
- Rewrite formula calls to new parameters

Afterwards, 
- IPP will make changes to XLS files, whose changes will be integrated with the same process
- OpenFisca contributors will change the new parameter files, and use the issue / PR label `parameter` so that IPP can reflect changes in their tables. See #407
- A new version of _legislation explorer_ will make it possible for everyone to contribute in the same place : 
  - signal parameter (or formula) problems directly on the website (relatively easy)
  - browse parameters with a new interface that could replace viewing the XLSX _barèmes IPP_ (relatively easy)
  - edit parameters directly in this interface (forms to edit XML param nodes; should create PRs with github's API)
# Flat params ?

I'm convinced that parameters should be made flat, which would in particular make it easier to develop the editing interface. 
Discussion in #409

**Comment by MattiSG** [comment]
Great! Thanks for the heads up, and looking forward to the finalisation of this!  :)

**Comment by cbenz** [comment]
Well done! I referenced this meta-issue from the documentation: https://github.com/openfisca/openfisca-gitbook/commit/c1296e3e4ed175464f58a9a70564c279287bb640

**Comment by MalkIPP** [comment]
Thank you very much for this very clear summary of yesterday. Ok for the `parameter` label of PR.

**Comment by benjello** [comment]
@laem @cbenz : I have done some work on [baremes-ipp] (https://github.com/openfisca/openfisca-france/pull/428) this week-end. I completed some baremes migration. I am increasingly convinced that mael tagging startegy to tag te baremes (privé, cadre, effectif d'entreprise etc) to sort the by employee-employer type is wort pursuing. And I think we should do that at the migration step rather than rewriting param.xml (wich is messy for the baremes) and the re-parsing it. @laem what do you think ? SHould we start this ?

**Comment by benjello** [comment]
With @pierrehvz we are progressing into the migration of the baremes-ipp to the new parameters directory containing the various xml files of the legislation resulting form the merge between openfisca param.xml files and the baremes-ipp yaml files.

More or less regularly, i try to merge the baremes-ipp branch with master for both core and france repo.
The [last merge is not succeeding](https://travis-ci.org/benjello/openfisca-france) and i would appreciate if @fpagnoux could have a look at it (both branches on my personals repos ([here](https://github.com/benjello/openfisca-core/tree/baremes-ipp) and [here](https://github.com/benjello/openfisca-france/tree/baremes-ipp).

And then we could definitively discuss the next step with @laem for the yaml parameters files (and @cbenz) and @eraviart for the data brewer etc

**Comment by fpagnoux** [comment]
Just looking at the error log doesn't give me any idea. I could investigate more but we have many things going on here. @cbenz do you have time to have a look at it ?

**Comment by benjello** [comment]
It is a problem with loading the parameters i wasn't abe to solve by my own
...

On Mon, Jul 11, 2016 at 12:11 PM Florian Pagnoux <notifications@github.com>
wrote:

> Just looking at the error log doesn't give me any idea. I could
> investigate more but we have many things going on here. @cbenz
> <https://github.com/cbenz> do you have time to have a look at it ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/410#issuecomment-231694747>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHxd-devo8QLhEL7WWee3El9BI9RucKks5qUhbHgaJpZM4HIeHd>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by benjello** [comment]
And if we could merge it we could proceed to a next step with @pierrehvz ;-)

**Comment by laem** [comment]
I'll try to look at the error. 
@benjello Concerning the work on YAML parameters, I've stopped developing the branch... because I wanted to go further this summer *. But the current work is still a progress to me (some details and review  

* currently on a different repo, moving forward at the same time with parameters expressivity and the Web UI to display them

**Comment by benjello** [comment]
@laem : could you have a look at it today or should I bug my hero @cbenz ;-)
Thanks

**Comment by laem** [comment]
@benjello ça me semble se passer [ici](https://github.com/benjello/openfisca-core/blob/baremes-ipp/openfisca_core/legislationsxml.py#L866) -> problème d'import des fichiers XML, mais je n'ai pas de certitudes...

**Comment by benjello** [comment]
Oui clairement c'est un problèmes dans l'import des fichiers XML entre la nouvelle api de @fpagnoux et les modifs qui ont été introduites pour gérer les fichiers multiples générés par le merge du param.xml et des barèmes IPP. Mias je n'ai pas réussi à m'en dépêtrer. Et c'est un peu un goulot d'étranglement de notre côté ...
Encore désolé pour mon impuissance.

**Comment by fpagnoux** [comment]
`add_legislation_params()` take only the xml path as a parameter, not the tuple`('xml_path', 'path_in_legislation_tree')`

See https://github.com/benjello/openfisca-france/pull/4.

It become urgent to write documentation on the TBS construction, I'll try to find some time to do it.

**Comment by benjello** [comment]
Thnak you @fpagnoux

**Comment by MattiSG** [comment]
The most important part of this merge was done via #566, and will be changed again with https://github.com/openfisca/openfisca-core/issues/437. The documentation has massively changed in a year, so what's left to be done cannot be deducted from the stuff described here. Closing.

Thanks again for having taken the time to write down what happened, this has strong historical value 🙂
