### ISSUE TITLE
Use numpy 1.10 on Travis

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#416]
Following https://github.com/openfisca/openfisca-france/issues/413#issuecomment-173860874

I'd like to make sure that Travis uses numpy 1.10

**Comment by cbenz** [comment]
I hesitate between 2 ways:

- use [Travis cache](https://docs.travis-ci.com/user/caching/) to remember 
- use [Miniconda](http://conda.pydata.org/docs/travis.html) (see [this gist](https://gist.github.com/dan-blanchard/7045057) too)

See https://github.com/openfisca/openfisca-france-indirect-taxation/issues/106

**Comment by laem** [comment]
My conda setup is really neat :smile:

**Comment by benjello** [comment]
@laem : 
 - Do you use anaconda or miniconda ?
 - On which OS ?

**Comment by laem** [comment]
http://doc.openfisca.fr/install-with-conda.html

**Comment by cbenz** [comment]
Breaking news: NumPy is now shipped with wheels for GNU/Linux OSes.

**Comment by benjello** [comment]
@cbenz : can we close this issue ?

**Comment by cbenz** [comment]
Yes!
