### ISSUE TITLE
Fix remaining numpy errors

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#417]
Due to Travis config which initialized the test env with numpy 1.6, we didn't spot all the errors provoked by the switch to numpy 1.10

Here are them: https://travis-ci.org/openfisca/openfisca-france/builds/104059088

See https://github.com/openfisca/openfisca-france/issues/416

**Comment by cbenz** [comment]
See https://github.com/openfisca/openfisca-france/pull/414

**Comment by cbenz** [comment]
By the way prefer the idiomatic notation:

```python
timedelta64(value, 'Y')

# like in
(anciennete_contrat[age_condition] == timedelta64(anciennete, 'Y')) * part_de_smic
```
rather than:

```python
np.array([value], dtype = 'timedelta64[Y]')

# like in
(anciennete_contrat[age_condition] == np.array([anciennete], dtype = 'timedelta64[Y]')) * part_de_smic
```

**Comment by benjello** [comment]
@cbenz : aren't we done with this issue ?

**Comment by cbenz** [comment]
Not yet some still remain, but not many. Should be fixed very soon. 
Le 31 janv. 2016 12:38, Mahdi Ben Jelloul <notifications@github.com> a écrit :@cbenz : aren't we done with this issue ?

**Comment by cbenz** [comment]
See https://github.com/openfisca/openfisca-france/commit/895fa68d71ed20ddc3bd4dced804090804ea84f5
