### ISSUE TITLE
Revalorisation des revenus de références des aides au logement

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#423]
Modification des indices "revenu de références" dans le calcul des AL :
http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000031886273&dateTexte=&categorieLien=id

Texte initial:
http://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=5989302CB1DD2AEC17D0E4C5E9247FA5.tpdila20v_1?cidTexte=JORFTEXT000000838203&idArticle=LEGIARTI000030084305&dateTexte=19780723&categorieLien=cid

via @HelaG

**Comment by fpagnoux** [comment]
Les paramètres des AL sont les premiers dans ce fichier : https://github.com/sgmap/openfisca-france/blob/prod/openfisca_france/param/param.xml.

Mais comme c'est les AL et que le mode de calcul est super complexe, la mise à jour est peut être pas triviale.

**Comment by benjello** [comment]
Généralement, le ministère publie une brochure. en comparant la brochure d'une année sur l'autre, on voit ce qui change tant au niveau des paramètres que des "formes fonctionnelles" (rare)

**Comment by Morendil** [comment]
Vérification faite ces taux semblent bien avoir été mis à jour, [ici par exemple](https://fr.openfisca.org/legislation/prestations.aides_logement.R0.taux_seul) pour la valeur de 4 562€. Je ferme cette issue sur l'hypothèse que les valeurs ont été intégrées.
