### ISSUE TITLE
Revalorisation barèmes fonction publique

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#425]
Je ne sais pas si ces éléments ont déjà été pris en compte, mais à tout hasard, voici la liste des changements en matière de cotisations sociales intervenus à compter du 1er janvier 2016 qui impactent les rémunérations des agents publics.

> - Le plafond de la Sécurité Sociale : 3 218 € au lieu de 3 170 €
> - Pour les agents titulaires et titulaires détachés sur contrat :
>   - Retenue pension civile : 9,94 % au lieu de 9,54 %
> - Pour les agents non titulaires
>   - Cotisation vieillesse dans la limite du plafond de SS
>     - Part salariale : 6,90 % au lieu de 6,85 %
>   - Cotisation vieillesse sur la totalité
>     - Part salariale : 0,35 % au lieu de 0,30 %
>   - Cotisation IRCANTEC de la tranche A - dans la limite du plafond
>     - Part salariale : 2,72 % au lieu de 2,64 %
>   - Cotisation IRCANTEC de la tranche B – au-delà du plafond
>     - Part salariale : 6,75 % au lieu de 6,58 %

**Comment by benjello** [comment]
Merci @MattiSG

**Comment by benjello** [comment]
Pour info: une stagiaire va bosser un peu sur les cotisations du public une partie du mois d'avril.

**Comment by benjello** [comment]
@pierrehvz : pourrais-tu jeter un oeil à ces barèmes ? Si tout est à jour on peut fermer. Merci !
@LisaDeg, si tu te rappelles l'avoir fait et que tu peux guider @pierrehvz, ce serait cool.

Merci à vous deux

**Comment by MattiSG** [comment]
Pas de référence législative, pas réussi à trouver facilement les paramètres impactés pour vérifier si les changements ont été pris en compte, aucune réponse des personnes qui étaient censées avoir pris ce sujet, je ferme.
