### ISSUE TITLE
Paramétrisation du seuil effort construction 

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#432]
Voir https://github.com/openfisca/openfisca-france/pull/430#issuecomment-184314779
Il a changé dans le temps.

**Comment by benjello** [comment]
@laem could we close this issue ?

**Comment by laem** [comment]
Pour être cohérent dans le temps, il faut implémenter [ça](https://github.com/openfisca/openfisca-france/pull/430#issuecomment-184311239).
