### ISSUE TITLE
Location of extensions might be confusing

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#436]
In the model directory we essentially have node of the legislation.
Having extension there might be confusing for non coders.
I understand that it naturally sits there from a coding point of view but can't we think of another location.
Sorry for this late thought.

**Comment by fpagnoux** [comment]
You don't think the README.md would me clear enough for these users ? 
What locations would seem better from your point of view ?  `openfisca_france` ?

**Comment by benjello** [comment]
Not so many people actually reads the README.md ...
`openfisca_france` looks like a good place.  Is it too burdersome for you.
