### ISSUE TITLE
RSA finit fin 2015

### ISSUE THREAD

**Issue by MorganRx** [openfisca/openfisca-france#449]
la fonction [RSA] (https://github.com/openfisca/openfisca-france/blob/a9f151fc46f9a5d8a0be5990ad7eaa655f432571/openfisca_france/model/prestations/minima_sociaux/rsa.py#L251) n'a pas la bonne date de fin.

**Comment by fpagnoux** [comment]
As-tu une source ? D'après ma compréhension, le RSA est toujours en vigueur, simplement le mécanisme de "pente" a été supprimé.

**Comment by MorganRx** [comment]
On vient de voir ça avec @benjello, 
c’est ok pour le rsa_socle, 
mais la fonction que je pointe inclus le rsa_socle et le rsa activité qui reste pour l’instant actif alors qu’il devrait disparaitre au profit de la ppa.

**Comment by fpagnoux** [comment]
La fonction `rsa_base_ressources` inclut les ressources d'activité et hors activité, car toutes les ressources doivent être prises en compte.
Simplement, on ne leur applique plus de pente, ce que tu peux voir dans la fonction [`rsa_non_majore`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/rsa.py#L997), où il y a un changement de formule pour le 1er janvier 2016.

Je remarque au passage que le lien pointe sur une vielle version du fichier. Il y a eu beaucoup de renommage récemment, et je pense que c'est plus facile à comprendre avec les nouveaux noms.

**Comment by benjello** [comment]
Le lien est celui donné par l'explorateur de législation @cbenz

Le mar. 15 mars 2016 12:10, Florian Pagnoux <notifications@github.com> a
écrit :

> La fonction rsa_base_ressources inclut les ressources d'activité et hors
> activité, car toutes les ressources doivent être prises en compte.
> Simplement, on ne leur applique plus de pente, ce que tu peux voir dans la
> fonction rsa_non_majore
> <https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/rsa.py#L997>,
> où il y a un changement de formule pour le 1er janvier 2016.
>
> Je remarque au passage que le lien pointe sur une vielle version du
> fichier. Il y a eu beaucoup de renommage récemment, et je pense que c'est
> plus facile à comprendre avec les nouveaux noms.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub:
>
>
> https://github.com/openfisca/openfisca-france/issues/449#issuecomment-196767919
>
-- 
Mahdi Ben Jelloul

**Comment by fpagnoux** [comment]
Ah oui, l'explorateur de législation n'est clairement pas à jour...
@cbenz, comment se passent les mises à jours ?
