### ISSUE TITLE
Transformer aides_cd93 en une extension

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#450]
@fpagnoux : These reforms are still present in  `openfisca_france/reforms`. Diddn't you move them somewhere else ? Shouldn't we remove them ?

Thanks

**Comment by benjello** [comment]
@fpagnoux : only aides_cd93 are still present in `openfisca_france/reforms`. Should we remove the reform ? And close this issue ?

**Comment by fpagnoux** [comment]
We still use `aides_cd93` in `openfisca_france`. We can move it out if needed, but as the collaboration with 93 is not very active right now, we are not focusing on it right now.

**Comment by MattiSG** [comment]
Apparemment en cours par @fpagnoux sur https://github.com/sgmap/openfisca-cd93.

**Comment by MattiSG** [comment]
Cela semble avoir été fait : https://github.com/sgmap/mes-aides-ui/pull/519/files#diff-198d415a7731375052d9955427f9201cL15

@fpagnoux merci de fermer l'issue si c'est bien le cas, ou d'indiquer ce qu'il reste à faire si ce n'est pas le cas  :)

**Comment by MattiSG** [comment]
Confirmé IRL.
