### ISSUE TITLE
Support loading reforms in YAML tests

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#451]
I would like to write yaml test to test specific reform. Is there a way to do that ?

**Comment by laem** [comment]
In #441 I tested the reform with a yaml test. Is it what you want ?

**Comment by benjello** [comment]
Yep. But I do not understand well the logic. Why not having a reform key in the yaml file ?

**Comment by laem** [comment]
This might be interesting here : ee093a61f9a225913d4b712886bf393017d03486
For reforms that require additional packages.

**Comment by MattiSG** [comment]
- [ ] Add a `reforms` property that is an array of strings stating paths to reform modules that should be loaded in order to execute that test. The test runner is responsible for resolving the paths and using the cached versions of the reforms if possible.

**Comment by fpagnoux** [comment]
> Try to remove the cache altogether, measure and report impact.

There is today only _one_ YAML test that use a reform. So if we are _just_ talking about YAML tests, the cache is useless.

The current cache mechanism is however today common to YAML tests _and_ python tests. But if we look closely, we never call the same reform in two different python tests. So here again, useless.

The cache mechanism is also used in [france-data](https://github.com/openfisca/openfisca-france-data). There, one reform, `inversion_directe_salaires`, is called many times. This could justify caching but:
- As this does not concern `france`, such mechanism should not be in `france`
- If there is only one reform that need caching, we probably don't need such a generalist mechanism.

So I'm removing the cache system from `france`. @benjello tell me if I missed something important.
