### ISSUE TITLE
Problèmes avec l'ARS

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#456]
L'[ars](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/ars.py) (aide à la rentrée scolaire) a il me semble quelques problèmes.

Gros problème : 
1. Le versement de la prestation est annuel, alors qu'il est versé ponctuellement fin août : un simulation.caculate("ars", "2014-01") plante....

Petits problèmes : 
1. La date de condition est en octobre, alors qu'il semble --d'après les commentaires-- qu'elle doit être en septembre (voir fin août).
2. Les conditions de montant en fonction de l'age semblent être les bonnes, les conditions de versements (e.g au [15 septembre de l'année](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006156692&cidTexte=LEGITEXT000006073189) ) ne semblent pas être prises en compte (mais c'est peut être un raffinement qui n'est pas nécessaire).

Je n'ai pas trouvé le décret ou la loi précisant la date de versement de la prestation.

**Comment by benjello** [comment]
@fpagnoux

**Comment by benjello** [comment]
@fpagnoux : cela te semble-t-il devoir être revu ?

**Comment by benjello** [comment]
@fpagnoux: should I lower the priority of this issue ?

**Comment by MattiSG** [comment]
Le "gros problème" a a priori été résolu via #685, qui force l'explicitation des périodes de calcul.

Les "petits problèmes" ne sont pas actionnables, puisqu'il n'y a pas de référence législative. Ils pourront être traités lorsqu'un contributeur cherchera à valider la prestation. Je ferme cette issue.
