### ISSUE TITLE
Améliorer la description de la variable F6GH

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#457]
La variable [f6gh](http://legislation.openfisca.fr/variables/f6gh), a une description très limitée.
La case n'existe pas sur la 2042 de 2010 par exemple (je n'ai pas fait toute les années).

Correspond peut-être aux cases relatives aux pensions alimentaires déductible ?
- [ ] Trouver à quoi ça correspond.
- [ ] Donner une description plus informative

**Comment by benjello** [comment]
Regarder les déclarations de 2006 et/ou 2003

**Comment by Morendil** [comment]
Vérification faite cette variable est assortie d'une description ("Sommes à ajouter au revenu imposable") qui correspond bien au [formulaire](https://www.impots.gouv.fr/portail/files/formulaires/2042/2017/2042_1886.pdf) du moins sur l'un des millésimes consultés. Je ferme donc l'issue comme sans objet.

Cela dit, il s'agit peut-être ici d'un problème que j'ai par ailleurs relevé: les noms associés aux cases des formulaires peuvent être "réemployés" par l'administration fiscale d'une année sur l'autre, et le schéma de nommage adopté ne permet pas de les distinguer. Je ne suis personnellement pas favorable à les augmenter systématiquement avec l'année correspondante (par exemple `f6gh_ 2006`) comme cela a été fait occasionnellement, pour diverses raisons (travail trop important de conversion du stock, méfiance envers l'idée de faire peser sur des noms ce qui relève de la notion d'espaces de nommage, manque de lisibilité des noms résultants).

J'envisage de soulever prochainement la question de ces variables correspondant exclusivement à des cases du formulaire de déclaration d'impôt (`cerfa_field`), il me semble qu'il convient de les traiter différemment des variables standard du modèle.
