### ISSUE TITLE
ir_brut en trop dans ir_ss_qf

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#458]
ir_brut est calculé pour rien dans ir_ss_qf

https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py#L1061

**Comment by benjello** [comment]
J'accepte les PR. Tu peux la faire en ligne !

**Comment by adrienpacifico** [comment]
Fait : #459
