### ISSUE TITLE
Missmatch in allocation logement

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#46]
_Issue by **[benjello](https://github.com/benjello)** from Saturday Mar 01, 2014 at 00:18 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/289_

---

_Issue by **[benjello](https://github.com/benjello)** from Tuesday Sep 24, 2013 at 20:53 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/290_

---

l'agrégat al (ind) n'est pas égal (inférieur ?) à la somme de af, als, apl.
Bizarre

**Comment by MattiSG** [comment]
Réponse de @benjello 4 ans plus tard : "qu'entend-on par bizarre ?" :wink: je ferme, ne pas hésiter à rouvrir en décrivant plus précisément le problème.
