### ISSUE TITLE
Allocation de solidarité spécifique revalorisation 2016-04-01

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#460]
@HelaG, @fpagnoux : il doit y avoir une revalorisation de l'ASS au 1er avril 2016 mais je n'arrive pas à trouver l'info sur le web ni un décret. Seriez-vous mieux informés que moi ?

**Comment by HelaG** [comment]
On a eu les infos pour les PF (métropole et DOM), le RSA et la Prime.
Pas pour les autres presta…

connected to sgmap/mes-aides-api#82<https://github.com/sgmap/openfisca-france/pull/52>

De : Mahdi Ben Jelloul [mailto:notifications@github.com]
Envoyé : lundi 11 avril 2016 11:54
À : openfisca/openfisca-france
Cc : GHARIANI Hela
Objet : [openfisca/openfisca-france] Allocation de solidarité spécifique revalorisation 2016-04-01 (#460)


@HelaG<https://github.com/HelaG>, @fpagnoux<https://github.com/fpagnoux> : il doit y avoir une revalorisation de l'ASS au 1er avril 2016 mais je n'arrive pas à trouver l'info sur le web ni un décret. Seriez-vous mieux informés que moi ?

**Comment by benjello** [comment]
Merci @HelaG : je cherche aussi l'allocation temporaire d'attente (ATA) et l'allocation équivalent retraite (AER) ...

**Comment by benjello** [comment]
C'est bizarre, la revalorisation est censée arriver au 1er avril.

**Comment by benjello** [comment]
@fpagnoux @HelaG : on a également mis à jour les prestations au 1er avril [ici] (https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-xlsx) sio cela vous intéresse.

**Comment by HelaG** [comment]
Merci @benjello vous avez prévu de les ajouter à openfisca ?

**Comment by benjello** [comment]
On les ajoute aux barèmes qui idéalement devraient être moulinés pour aller alimenter automatiquement openfisca (la fameuse branche [baremes-ipp](https://github.com/openfisca/openfisca-france/tree/baremes-ipp) sur laquelle il faudrait progresser @laem @fpagnoux ). Mais ce n'est pas encore opérationnel. On n'a pas prévu de les mettre à jour rapidement (on comptait sur vous ;-)). Urgent @HelaG ?

**Comment by HelaG** [comment]
Pas d'urgence (la revalorisation a peu d'impact sur le résultat des simulations) mais on va le faire: sgmap/mes-aides-api#82 :)

**Comment by benjello** [comment]
@HelaG : Merci !

**Comment by MattiSG** [comment]
Fixed via #461.
