### ISSUE TITLE
Rework params : YAML

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#464]
Partons de la formule `participation_effort_construction` pour essayer d'améliorer la gestion des paramètres. 

Aujourd'hui, nous avons : 
- dans le param.xml

``` xml
<NODE code="construction_node" description="Effort à la construction">
          <BAREME code="construction_20" description="Effort à la construction (plus de 20 salariés)" option="main-d-oeuvre">
            <TRANCHE code="tranche0">
              <SEUIL>
                <VALUE deb="2015-01-01" fuzzy="true" valeur="0" />
                <VALUE deb="1992-01-01" fin="2014-12-31" valeur="0" />
              </SEUIL>
              <TAUX>
                <VALUE deb="2015-01-01" fuzzy="true" valeur="0.0045" />
                <VALUE deb="1992-01-01" fin="2014-12-31" valeur="0.0045" />
              </TAUX>
            </TRANCHE>
          </BAREME>
</NODE>
```
- dans le preprocessing.py [source](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py#L19)

``` py

commun['children']['construction'] = commun['children']['construction_node']['children']['construction_20']
del commun['children']['construction_node']
# [...]

# Rework commun to deal with public employees
    for var in ["apprentissage", "apprentissage_add", "assedic", "chomfg", "construction", "maladie", "formprof_09",
                "formprof_1019", "formprof_20", "vieillesse_deplafonnee", "vieillesse_plafonnee"]:
        del commun['children'][var]

    for var in ["apprentissage", "apprentissage_add", "formprof_09", "formprof_1019", "formprof_20", "chomfg",
                "construction", "assedic"]:
        del pat['children']['fonc']['children']['contract']['children'][var]

```
- dans la formule `participation_effort_construction` (simplifié)

``` py
bareme = apply_bareme(
            simulation,
            period,
            cotisation_type = 'employeur',
            bareme_name = 'construction',
            variable_name = self.__class__.__name__,
            )

        # TODO : seuil passé de 10 à 20 avec l'Ordonnance n° 2005-895 du 2 août 2005

        cotisation = (
            bareme * (effectif_entreprise >= 20) +
            self.zeros() * (effectif_entreprise < 20)
)
```

**En bref, c'est très confus.**

**Comment by benjello** [comment]
Ca sent le ménage de printemps du fichier `preprocesing.py`

**Comment by laem** [comment]
Quelques pistes : 
- utiliser les **variables directement dans les paramètres** pour remplacer les hiérarchies actuelles de nœuds. Notamment : 
    - Catégories (type_sal : cadre/non-cadre/public_etat...)
    - Entiers (effectif_entreprise, notamment pour les noeuds formprof, CSA, fillon...)
Lors de l'accès au paramètre dans la formule, ces variables filtrent les nœuds possibles automatiquement. 

- une formule pourrait automatiquement avoir accès à son paramètre si un paramètre du même nom existe : un nouveau noeud `<FORMULA>` ?

- [plus expérimental] les "sum variables", dont les variables sommées sont des éléments d'une catégorie. Ex : cotisations employeur / employé

**Comment by fpagnoux** [comment]
Est-ce que [ceci](http://doc.openfisca.fr/legislation-parameters/index.html) est toujours à jour ? Il n'y a plus de `root_start_date`, si ?
Aussi, est-ce que `<BAREME>` est documenté quelque part ?

**Comment by laem** [comment]
La section Query et son `root_end_date` est justement ce qui a été rendu obsolète par l'ajout de `fuzzy`.

**Comment by MattiSG** [comment]
Duplicate of #410 (voir https://github.com/openfisca/openfisca-france/issues/410#issuecomment-231732461). Le travail expérimental de @laem peut être vu sur https://github.com/sgmap/syso.

**Comment by laem** [comment]
L'exemple précis de cette issue peut être vu [ici](https://github.com/sgmap/syso/blob/master/r%C3%A8gles/r%C3%A9mun%C3%A9ration-travail/cotisations/participation-effort-construction.yaml)
Cette cotisation particulière est encore au stade du brouillon.
