### ISSUE TITLE
Créer un module spécifique pour la fonction publique

### ISSUE THREAD

**Issue by LisaDeg** [openfisca/openfisca-france#472]
The file [salarie.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/revenus/activite/salarie.py) should be splitted and all the variables which are specific to fonction publique should be placed in a separate file `agent_fonction_publique.py`.

**Comment by benjello** [comment]
[WIP](https://github.com/LisaDeg/openfisca-france/tree/remuneration_fonctionnaire)

**Comment by laem** [comment]
Excellent :+1:  !

**Comment by Morendil** [comment]
Je ferme pour refléter la décision sur #729.

Par ailleurs je note que le périmètre de cette issue n'était pas assez clair - le commentaire en anglais ci-dessus la limite à un simple refactoring (qui ne nécessite pas une issue distincte) mais dans les faits il s'agissait d'un travail plus ambitieux avec notamment l'intégration des grilles de la fonction publique.
