### ISSUE TITLE
How to test error raising in .yaml tests ?

### ISSUE THREAD

**Issue by LisaDeg** [openfisca/openfisca-france#473]
Need to add some tests in [indice_majore.yaml](https://github.com/LisaDeg/openfisca-france/blob/d8a58ddd6b153967acd291e58809363da2c0d3f7/openfisca_france/tests/formulas/indice_majore.yaml#L23-L43) to see if get_indice() raises the right error. How to test error raising ?

**Comment by benjello** [comment]
Precision: how to test error raising in yaml tests

**Comment by cbenz** [comment]
I'm not sure it's a good idea to test exceptions in YAML tests like (`ValueError` or `TypeError`), except for OpenFisca-level exceptions (`ParameterNotFound` for example).

`nosetests` uses [`assert_raises`](https://docs.python.org/2.7/library/unittest.html#unittest.TestCase.assertRaises) from Python unittest, but this function is not available in the YAML formalism.

@benjello What would be the typical use case for exception checking?

**Comment by benjello** [comment]
Imagine you have a "grille de la fonction publique" with 5 echelons for some and you ask for the 6th echelon. We should raise a `ParameterNotFound` (I discover this exceptions) and you may want to test that through yaml test.
We can also do that in morelegislation oriented tests and do not use the TAML formalism.
@LisaDeg will provide you examples.

**Comment by cbenz** [comment]
First I encourage you to write a Python test and then we'll iterate :)

**Comment by MattiSG** [comment]
Still waiting for Python examples after 10 months, closing. Feel free to reopen with specific examples :smiley:
