### ISSUE TITLE
Grilles fonction publique

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#475]
Contraintes sur l''utilisation des grilles FP:
 - partage avec CNRACL
 - diffusion sous forme de barèmes IPP
 - utilisation dans openfisca

Tentative de description du processus idéal:
 - [x] Définition du format de base avec la CNRACL à stocker avec les [barèmes IPP](https://framagit.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-xlsx) (mais pas de diffusion pour l'instant)
 - [x] Script pour produire le fichier csv à stocker dans les [assets d'openfisca-france](https://github.com/LisaDeg/openfisca-france/tree/remuneration_fonctionnaire/openfisca_france/assets/grilles_fonction_publique)
 - [x] Abandon de pandas et utilisation de [numpy](http://stackoverflow.com/questions/3518778/how-to-read-csv-into-record-array-in-numpy) et utilisation de l'indexation par des vecteurs de booléens

**Comment by benjello** [comment]
@LisaDeg should I close this ?

**Comment by LisaDeg** [comment]
Yes !
