### ISSUE TITLE
Document how to write (complex) yaml tests

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#477]
@LisaDeg didin't find that easy to write yaml test ?

@cbenz @fpagnoux @laem : is there a place where their syntax is described ? @LisaDeg is ready to write some doc if she is told where to do it and monitored (I will do my part of the job).

**Comment by laem** [comment]
I guess it could be a new page "Writing YAML tests" in http://doc.openfisca.fr/en/coding-the-legislation/index.html and a link to it in Contribute/Tests 
Writing a Markdown file in this directory should be a good start : https://github.com/openfisca/openfisca-gitbook/tree/master/en/coding-the-legislation

**Comment by cbenz** [comment]
The doc editor is [here](https://www.gitbook.com/book/openfisca/documentation/edit), it is more convinient than editing markdown by hand.

I'm going to add Lisa to the editors of the doc.

**Comment by adrienpacifico** [comment]
> The doc editor is [here](https://www.gitbook.com/book/openfisca/documentation/edit)

I've got a "Forbidden Can't access this page" error when I clic on the link, is it on purpose ? @cbenz  Could you open the gitbook ?

**Comment by cbenz** [comment]
I started this stub http://doc.openfisca.fr/en/coding-the-legislation/writing_tests.html
I choosed to add the page to "Coding the legislation" because YAML tests are part of the process.

@adrienpacifico Strange, though you are part of the team. I re-synced the members so could you try again?

**Comment by adrienpacifico** [comment]
It works, thx !

**Comment by cbenz** [comment]
I confirm just for the record:

- [GitHub OpenFisca documentation team members](https://github.com/orgs/openfisca/teams/documentation) can edit the `.md` files
- [GitBook OpenFisca team members](https://www.gitbook.com/@openfisca/settings/people) can edit the settings of the book

**Comment by cbenz** [comment]
@benjello @LisaDeg May I close this issue or do you have any specific questions about YAML tests that I could add to the doc?

**Comment by benjello** [comment]
@LisaDeg is not in front of her computer today. i will let this issue open till she is back. 
She encountered some problems with the syntax of the yaml tests (different periods, different roles in entities) that should be documented. @cbenz : if you think the issue should be opened somewhere else please let us know.

**Comment by benjello** [comment]
After discussing with @LisaDeg we should split the problem in several parts:
 - test the legislation
 - validate the entries possibly conditionally on the legislation

We may also write the condition on the variable when we declare them (positive int or float, less than 10, etc)

**Comment by benjello** [comment]
@LisaDeg should I close this ?

**Comment by LisaDeg** [comment]
Yes please!
