### ISSUE TITLE
ppe/rsa_act_i breaks run with survey data

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#48]
_Issue by **[benjello](https://github.com/benjello)** from Saturday Mar 01, 2014 at 00:22 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/315_

----

_Issue by **[benjello](https://github.com/benjello)** from Tuesday Feb 25, 2014 at 21:26 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/316_

----

rsa_act_i
NumPy boolean array indexing assignment cannot assign 21557 input values to the 21327 output values where the mask is true
ppe

Error could come from data or from implementation

**Comment by jdesboeufs** [comment]
Obsolète.
