### ISSUE TITLE
Obtenir la liste des zones d’indemnité de résidence pour la fonction publique

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#487]
`indemnite_residence` dépend actuellement de `zone_apl` _(EDIT : import du titre — @MattiSG)_
Les zones APL et les zones fonction publique ne sont pas les mêmes !
Mais je ne trouve pas de source pour la délimitation des zones fonction publique.
@jdesboeufs : tu es désormais le géographe de service, aurais-tu cela dans tes cartons ?

@laem @fpagnoux je vous rajoute au cas où.

@LisaDeg, @SophieIPP: une piste possible consiste à demander à la CNRACL.

**Comment by jdesboeufs** [comment]
Je n'ai pas ça dans mes cartons, ni la base APL, mais les deux m'intéressent fortement.
Je peux même en faire une API.

**Comment by scenaristeur** [comment]
C'est ça que vous cherchez ? http://www.fonction-publique.gouv.fr/indemnites-de-residence-et-supplement-familial-de-traitement

**Comment by benjello** [comment]
Oui mais sous forme numérique avec l'historique si possible.

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
