### ISSUE TITLE
Validity period of indemnite_fin_contrat

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#488]
Working ont he baremes-ipp branch, I have this [bug](https://travis-ci.org/benjello/openfisca-france) related to the legislation about indemnite_fin_contrat.
It does not have a value for the first month of 2002.
By looking at the [parameters](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/param/param.xml#L1093) it seems that it might be valid for this month.
@laem could you check that, please ?
 We then should change the start date BUT keep the date of the legislative reference in comment (we may use it elsewhere).

AFAICR we do not have this info in the IPP barèmes.

**Comment by benjello** [comment]
We should also change indemnite_fin_contrat to a DatedVariable

**Comment by laem** [comment]
@benjello 
Oui le 18 janvier 2002 est la date de la loi qui introduit l'indemnité de fin de contrat : 
[Article 125 ici](https://www.legifrance.gouv.fr/eli/loi/2002/1/17/2002-73/jo/texte)
Je ne sais donc pas si on peut l'étendre à janvier 2002, mais je suppose que si.
Elle est versée au salarié à la fin du contrat. Je comptais la mensualiser. Je n'ai aucune idée si un contrat commencé en fin 2001 peut avoir droit à cette prime.

**Comment by MattiSG** [comment]
Pas de conclusion, pas d'avancée en 9 mois, non reproductible puisque le lien original ne dirige pas vers le build qui a cassé. Je ferme cette issue. N'hésitez pas à la rouvrir si le problème apparaît à nouveau  :)
