### ISSUE TITLE
csg on revenu foncier

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#49]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:56 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/6_

---

_Issue by **[clems](https://github.com/clems)** from Wednesday Nov 23, 2011 at 18:17 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/3_

---

Les cotisations sociales sur les revenus au barèmes (csgcap_bar) agrège la csg sur les revenus du capital soumis au barème, mais aussi sur les revenus fonciers et les rentes viagères à titres onéreux. Il faudrait séparer les 3 variables par soucis d'harmonisation et de clarté.

**Comment by MattiSG** [comment]
Issue ayant plus de 5 ans, pas de travail actif, je ferme.
