### ISSUE TITLE
Should  aeeh stops at 2015-12-31 ?

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#491]
Il semblerait que non selon [ce lien](http://droit-finances.commentcamarche.net/faq/22211-aeeh-2016-montant-et-complement).

Qu'en pense mes-aides @fpagnoux ?

**Comment by fpagnoux** [comment]
No, it shouldn't.
We should remove the `stop` [here](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/aeeh.py#L61).

Good catch 👍

**Comment by benjello** [comment]
Fixed by #505
