### ISSUE TITLE
Temps partiel / proratisation

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#496]
Implémenté dans  #444 mais certains doutes subsistent. 

**Objectif de la PR** : Consolidation du calcul des prélèvements sociaux pour un temps partiel (données d'entrée dans le cas d'usage envisagé : heures par mois, durée légale de 151.67h par mois). 

**Notes** : 
- Je suis maintenant **confiant sur la proratisation du plafond de la sécurité sociale** : l'étape de proratisation pour mois incomplet est bien réalisé selon la règle des 30èmes.
- Voici une proposition pour le coefficient de proratisation, que nous utilisons pour le calcul du SMIC proratisé, surtout pour les aides, mais qui est en fait la méthode de calcul du salaire. 
  J'ai quelques **doutes sur le cas** mois incomplet - temps partiel - jours d'absence. Nous avons comme information d'entrée pour le temps partiel le nombre d'heures par semaine, il nous faudrait la répartition des heures. 
  Je ne comprends toujours pas l'implémentation actuelle des valeurs 2, 3, 4 du `contrat_de_travail`, que j'ai donc ignoré dans les formules...
- Seul un [test](https://github.com/openfisca/openfisca-france/commit/319ee16b7064926d170faa0ac23ea9e62a64cf82#commitcomment-16532690) ne passe pas, mais il a été mis à jour :white_check_mark:

**Comment by benjello** [comment]
@laem : que reste-t-il à faire ? Quels sont les questions précises auxquelles il faut des réponses ?

**Comment by laem** [comment]
@benjello Ton doc devrait me permettre d'y répondre...

**Comment by MattiSG** [comment]
Les questions décrites ici et encore ouvertes suite à #444 ne sont pas assez précises pour être actionnables. En l'absence de nouvel élément, je ferme cette issue : si des problèmes sont rencontrés, il feront l'objet d'un traitement au cas par cas.
