### ISSUE TITLE
aides logements - Calcul de R0

### ISSUE THREAD

**Issue by pierrehvz** [openfisca/openfisca-france#497]
Le calcul du revenu de référence R0 (variable: aide_logement_R0) s'appuie sur le niveau du RMI en N-2. Pour cela, les anciens paramètres ont intégré directement les valeurs du RMI au lieu de passer par une "simulation.legislation" comme ça a été fait pour les prestations familiales dans le même calcul. 
Je pense que cela pourrait être amélioré afin de pouvoir se débarrasser définitivement du "al." et donc être indépendant des anciens paramètres.
@benjello @fpagnoux

**Comment by benjello** [comment]
@pierrehvz: est-ce réglé finalement ou reste-t-il du taf. Si oui mettre des liens vers le code à modifier. Merci.

**Comment by pierrehvz** [comment]
Je regarde ça cet aprem et je te tiens au courant

**Comment by pierrehvz** [comment]
Je pense avoir corriger le "problème", les tests passent sans problème. Cela m'a permis de me remettre un peu dans les AF, j'ai remarqué qu'il restait qq merges à faire encore, je vais essayer de rendre ça plus propre cet aprem
