### ISSUE TITLE
assiette_cotisations_sociales_prive ne gère pas le temps partiel

### ISSUE THREAD

**Issue by bixiou** [openfisca/openfisca-france#504]
J'ai peur qu'il y ait un problème dans une variable appelée pour calculer presque toutes les cotisations sociales : [assiette_cotisations_sociales_prive](http://legislation.openfisca.fr/variables/assiette_cotisations_sociales_prive)
L'assiette est à 1457€ mensuels pour les bas revenus (< 500€/mois), ce qui conduit à des cotisations sociales forfaitaires de 206€ mensuels pour ces bas revenus, d'où un salaire_imposable négatif pour les revenus < 200€/mois.
Or, la formule de cette variable semble douteuse : 
`max_(assiette, smic_proratise * not_(apprenti)) * (assiette > 0)`
En gros, pour les bas revenus, le smic_proratise est appliqué comme assiette, d'où le montant forfaitaire. La condition "assiette > 0" est peut-être à revoir : ne serait-ce pas "assiette > xxx €" ?
Je laisse cette énigme à qui voudra bien se plonger dans les textes de loi.

**Comment by benjello** [comment]
Il certes faut que l'on détecte les salaires imposables négatifs (@fpagnoux, @laem, @cbenz il nous faut réfléchir à implémenter plus de warnings pour les valeurs aberrantes, ie pouvoir dire cette valeur est toujours positive etc)

Mais ton cas est également erronée. Par défaut, une personne est à plein temps donc elle ne peut toucher moins que le smic. Il faut que tu joues avec la variable `contrat_de_travail` et [les autres variables autour de la définition du travail effectué](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/revenus/activite/salarie.py).

N'hésite pas à continuer la discussion ici.

On peut imaginer également que le scénario de cas type détecte cette erreur et corrige en temps partiel etc.

**Comment by benjello** [comment]
@bixiou: si tu pouvais mettre un titre plus parlant, ce serait parfait ;-)

**Comment by bixiou** [comment]
Effectivement, ça serait pas mal de créer automatiquement une variable temps_plein, du genre
`temps_plein  = (ppe_tp_sa | ppe_tp_ns | (frac_sa + frac_ns >= 1)) * (salaire_de_base >= smic)`
avec smic = cotsoc.gen.smic_h_b * cotsoc.gen.nb_heure_travail_mensuel,
et de prendre en compte la valeur de cette variable dans le calcul des cotisations sociales et autre.

**Comment by laem** [comment]
Oui en effet, pour l'instant, les entrées numériques ne sont pas validées par des règles. Comme exemple extrême, si la complémentaire santé renseignée est de `-8000` on aura aussi un salaire net négatif. 
Je ne suis malheureusement pas familier avec les variables de ton dernier message qui propose la variable temps_plein :sweat_smile:

**Comment by bixiou** [comment]
Moi non plus à vrai dire, et c'est pour ça que je ne me risque pas à faire un commit. Je sors ma formule de cette variable : [ppe_coef_tp](http://legislation.openfisca.fr/variables/ppe_coef_tp)

**Comment by MattiSG** [comment]
La formule référencée a changé suite à #444, qui annonce traiter ce type de cas. Je ne suis pas certain que le problème spécifique décrit ici ait été corrigé, mais en tous cas la description qui en est faite est obsolète.

Je ferme cette issue, mais si le comportement apparaît toujours aujourd'hui, ne pas hésiter à la rouvrir.

**Comment by MattiSG** [comment]
La gestion du problème décrit ici a par ailleurs été encore simplifiée grâce à #661.
