### ISSUE TITLE
Error with plf2016 reforms

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#506]
When migrating plf2016 reforms I got this [error](https://travis-ci.org/benjello/openfisca-france)

I badly need those reforms. 

@fpagnoux @cbenz : could you give it a look ASAP please ?

**Comment by cbenz** [comment]
Perhaps `update_variables` is no more useful. I tried removing it but another error occured, I investigate :)

**Comment by cbenz** [comment]
No, it's a typo: `update_variable` and not `update_variables`. But again another error!

**Comment by cbenz** [comment]
Fixed. See branch https://github.com/openfisca/openfisca-france/tree/plf106_reform on upstream repo.

**Comment by fpagnoux** [comment]
Thanks @cbenz for dealing with that.
Do you have feedback on what was unclear or surprising with the new API ?

**Comment by benjello** [comment]
The reform class name and the reform key were supposed to be the same.

Le lun. 11 juil. 2016 09:02, Florian Pagnoux <notifications@github.com> a
écrit :

> Thanks @cbenz <https://github.com/cbenz> for dealing with that.
> Do you have feedback on what was unclear or surprising with the new API ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/506#issuecomment-231656559>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHxdyE-vYKlmEZLkQvYEtkH8bzdOPt9ks5qUeqdgaJpZM4JH6X2>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by benjello** [comment]
I tried to end the migration but there is [another pending bug](https://github.com/openfisca/openfisca-france/pull/511).

**Comment by benjello** [comment]
Fixed by https://github.com/benjello/openfisca-france/pull/4
