### ISSUE TITLE
Use numpy 1.11

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#508]
Since 1.11, numpy is released pre-compiled for linux and windows.

It would have a **huge** impact on instability to upgrade the numpy dependency, so that we don't have to  use conda / recompile numpy / find wheels on shady websites.

**Comment by benjello** [comment]
No objection if it is ok on travis (it is packaged for debian).

**Comment by cbenz** [comment]
I started the tests: https://github.com/openfisca/openfisca-france/tree/numpy-1.11

**Comment by cbenz** [comment]
We would remove conda and use wheels which are available for GNU/Linux too, now.

**Comment by fpagnoux** [comment]
Tests are ok 🎉 !

**Comment by laem** [comment]
I suggest we keep the conda install as an alternative installation method in the documentation

**Comment by fpagnoux** [comment]
If everything is good let's merge it, I could use it tomorrow with my windows contributor.

**Comment by benjello** [comment]
Go !

**Comment by cbenz** [comment]
@fpagnoux By the way I don't understand why `pip` did not download the last version (1.11) *by default*.

**Comment by fpagnoux** [comment]
I don't know why either, but anyway, I we *really* want numpy 1.11, we should explicit that dependency.
