### ISSUE TITLE
Use pip dependencies in travis tests 

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#509]
It seems that in travis CI, dependencies between openfisca modules are not resolved by pip, but by fetching the latest version on git. See [this example](https://github.com/openfisca/openfisca-web-api/blob/master/requirements.txt).

This is an unwanted behaviour, as we know rely on continous releasing, and it could make the CI testing results erroneous.

**Comment by MattiSG** [comment]
I think this was fixed in https://github.com/openfisca/openfisca-france/pull/713.
@fpagnoux If this is not the case, please reopen this issue.
