### ISSUE TITLE
Fix baremes-ipp branch after merge with master

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#513]
See https://github.com/openfisca/openfisca-france/issues/410
This is actually pretty urgent @laem @cbenz.
I thank you in advance ...

**Comment by laem** [comment]
This is solved by https://github.com/benjello/openfisca-france/pull/4 then ?

**Comment by benjello** [comment]
Yep

Le mar. 12 juil. 2016 09:33, Mael <notifications@github.com> a écrit :

> This is solved by benjello#4
> <https://github.com/benjello/openfisca-france/pull/4> then ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfisca/openfisca-france/issues/513#issuecomment-231960950>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHxd8SA_LDLHVT9CKBuzUG3crm3xqGOks5qU0NYgaJpZM4JJmN2>
> .
>
-- 
Mahdi Ben Jelloul
