### ISSUE TITLE
Nettoyer assets/versement_transport

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#515]
Garder le seul fichier utilisé, `taux.json`.
Ajouter l'option `depth` à `git clone` dans la documentation.

**Comment by benjello** [comment]
Il me faut de conserver les fichiers bruts de données (peut-être ailleurs) et l'évolution temporelle.

**Comment by laem** [comment]
@benjello l'historique des taux est déjà dans cet unique fichier.
L'ancien fichier sera toujours trouvable dans l'historique du dépôt.

**Comment by fpagnoux** [comment]
:+1:, le `git clone` est aujourd'hui très lent.

**Comment by benjello** [comment]
Peut-on savoir ce qui le ralentit particulièrement ?

**Comment by fpagnoux** [comment]
Au total le dépôt fait 45 Mo. C'est gros pour un repository git. Le dossier `versement_transport` en fait 13Mo.
On a beaucoup de données, donc l'obésité de notre dépôt peut être justifié, mais il faut éviter les doublons et compresser ce qui est nécéssaire, sinon avec une connexion pas terrible (Hackathon, SGMAP) c'est un vrai problème: ça peut prendre 20 minutes.

**Comment by MattiSG** [comment]
Fixed via #726 🎉
