### ISSUE TITLE
Renommer `impo`

### ISSUE THREAD

**Issue by bixiou** [openfisca/openfisca-france#518]
La variable impo somme tous les impôts directs. Or, elle n'inclut que irpp et taxe_habitation. Est-ce normal que les autres impôts directs en soient absents : ISF, taxe foncière, voire même CSG ?

**Comment by benjello** [comment]
Oui il faudrait ajouter ISF. On ne calcule pas la taxe foncière. 
On a mis la csg dans les contributions.
Il faut voir impo comme ce qui vient après cotisations et contributions sociales et prestations  pour donner le revenu disponible

**Comment by benjello** [comment]
- [ ] Rename impo to impots_directs

**Comment by MattiSG** [comment]
Fixed via https://github.com/openfisca/openfisca-france/pull/641.
