### ISSUE TITLE
complete isf_bouclier fiscal- csg-crds in imp1 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#52]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:57 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/56_

---

_Issue by **[sarahdi](https://github.com/sarahdi)** from Wednesday Jun 06, 2012 at 14:21 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/53_

---

those taxations should be included in imp1 to be reimbursed. 
also  "impots sur les plus-values/ et prélèvements libératoires" should be added.

**Comment by MattiSG** [comment]
Issue ayant plus de 4 ans, pas de travail actif, je ferme.
