### ISSUE TITLE
Calcul de la PPA - problème avec les dates d'entrée en vigueur

### ISSUE THREAD

**Issue by pierrehvz** [openfisca/openfisca-france#521]
La PPA est calculée en fonction des revenus du trimestre précédent.  Le montant touché au mois N est en fait la moyenne de ce qui aurait pu être perçu par l'agent durant les 3 derniers mois en fonction de ses conditions d'éligibilité pendant cette période.
Pour cela, les dates d'entrée en vigueur des paramètres openfisca ont été antidaté de 3 mois afin de calculer la variable "ppa_fictive" et ainsi, permettre le calcul de la PPA dès le 1er janvier 2016.
Dans les barèmes IPP, nous n'avons pas cette possibilité d'action sur les dates, ce qui bloque le processus de fusion des paramètres IPP/openfisca. 
Les deux solutions pour l'instant envisagées sont : 
- séparer le calcul par des _if_ en faisant appel aux paramètres du "RSA activité" avant le début du 2e trimestre de 2016 et ensuite à ceux de la PPA.
- séparer le calcul par des _if_ en jouant sur la période à l'aide des "simulation.legislation_at(period.start)" en avançant de 3mois la date de début.
@benjello

**Comment by benjello** [comment]
@fpagnoux qu'en penses-tu ?

**Comment by fpagnoux** [comment]
La PPA est un cauchemar à modéliser dans openfisca, principalement à cause du mécanisme de PPA fictive. 
Il y a une période "de référence", celle où on demande la PPA, et les trois mois précédents pour lesquels on calcule des "primes fictives". Ce n'est pas un concept qui nous est propre, ça vient de la notice officielle. 
Il faudrait, pour tous les paramètres législatifs utilisés, les calculer pour le mois de référence, on n'aurait plus besoin d'antidater. Je regarde si je peux faire un correctif rapidement.

**Comment by benjello** [comment]
Nous sommes conscient du cauchemar ;-)
Il faut juste trouver la façon la plus élégante de la calculer correctement sans avoir à dire que les paramètres existent trois mois plus tôt. Et tu es plus élégant que nous :-)

**Comment by fpagnoux** [comment]
Voir #522

**Comment by benjello** [comment]
@pierrehvz : si on a fini, il faut fermer cette issue; Sinon lister ce qu'il reste à faire. Merci !

**Comment by pierrehvz** [comment]
c'est noté, je regarde ça très vite

**Comment by pierrehvz** [comment]
Le problème est résolu puisque les paramètres ont bien été mergé et les erreurs de dates n'apparaissent plus. Merci
