### ISSUE TITLE
Error in ppa_eligibilite

### ISSUE THREAD

**Issue by pierrehvz** [openfisca/openfisca-france#523]
Lorsque je lance le robot Travis depuis la modification du calcul de la PPA, j'obtiens [l'erreur suivante](https://travis-ci.org/pierrehvz/openfisca-france/builds/147519217) Je n'arrive pas à la résoudre tout seul, je fais donc appel à votre savoir faire @fpagnoux @cbenz 
Merci

**Comment by benjello** [comment]
And we need you on #520 one too ...

**Comment by fpagnoux** [comment]
I understand what the problem is here, even though I don't get why it's appearing for your PR.

There is an incompatibility between `requested_period_last_value` and variables with extra parameters. This needs a patch on core. I'll try to handle it this week.

#520 is beyond my reach :(

**Comment by benjello** [comment]
Still pending [here](https://travis-ci.org/benjello/openfisca-france/builds/153309807)
@fpagnoux do you have found time to fix it ?
Thanks

**Comment by fpagnoux** [comment]
I'll do fix that by the end of the week !

**Comment by fpagnoux** [comment]
Working on it, I promise not to sleep until a PR is open 😎

**Comment by fpagnoux** [comment]
https://github.com/openfisca/openfisca-core/pull/406 should fixe the `ppa_eligibilite@familles (...) doesn't return a numpy array` error.

No idea about the other one though, as said before.

**Comment by benjello** [comment]
Thanks !
