### ISSUE TITLE
Cerfa field alias "7UH" declared 2 times

### ISSUE THREAD

**Issue by pnbt** [openfisca/openfisca-france#524]
Which one is the good one?
- https://github.com/openfisca/openfisca-france/blob/8efe43291f5cdc98bcd9e6ab5497a9fa38d1f374/openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py#L142
- https://github.com/openfisca/openfisca-france/blob/8efe43291f5cdc98bcd9e6ab5497a9fa38d1f374/openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py#L2668

Or should one of them be deleted?

thanks

**Comment by benjello** [comment]
Les cases de la feuille d'impôt changent de signification selon les années. Une même case peut signifier des choses différentes ...
Nous n'avons pas de véritable stratégie pour l'instant. 
A minima, Quand une case est utilisée plusieurs années on la nomme comme ici 7uh_2007.
Mais il semble ici qu'il y ait une erreur vu que les dates se recoupent. Ou plutôt que on a gardé 7uh pour les dons aux oeuvres ... quelque soit l'année.

Bref, je suis preneur d'une solution plus systématique.

**Comment by MattiSG** [comment]
Une `DatedFormula` ne pourrait pas faire l'affaire ici car il s'agit d'une entrée, c'est bien cela @benjello ?

**Comment by MattiSG** [comment]
L'ambiguité ne semble plus être présente dans l'explorateur de législation. Je ferme cette issue spécifique.

![capture d ecran 2017-04-11 a 16 51 04](https://cloud.githubusercontent.com/assets/222463/24915412/5adc0062-1ed7-11e7-918c-515d6d02eb63.png)
