### ISSUE TITLE
implement csg_taux_plein condition for retired

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#53]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:57 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/76_

---

_Issue by **[clems](https://github.com/clems)** from Wednesday Oct 10, 2012 at 21:27 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/73_

---

**Comment by MattiSG** [comment]
Issue ayant plus de 5 ans, pas de travail actif, je ferme.
