### ISSUE TITLE
Différences entre Simulateur et Trace

### ISSUE THREAD

**Issue by jeremsou** [openfisca/openfisca-france#530]
Bonjour à tous, 

J'utilise simultanément l'outil Trace et l'outil Simulateur et il s'avère que la variable de retour "revdisp" n'a pas la même valeur dans les deux outils malgré des variables d'entrées identiques.

Exemple : Un indiviudu, salaire de 20 000, dividendes de 5 000 et assurancevie de plus de 8 ans avec PFL de 5000.
Revenu disponible retourné par le simulateur = 22 892
Revenu disponible retourné par Trace = 24 488

La différence se trouve dans le RSA + aides exceptionnelles de fin d'année + minimas sociaux qui sont en plus dans l'outil Trace. Ces prestations sociales me paraissent fausses car elles sont toujours présentes malgré un revenu élevé.

Trace est l'outil qui permet d'utiliser l'API et c'est donc la valeur qui va ressortir pour les utilisateurs, ce problème est donc majeur.

Merci de m'aider à trouver une solution 👍

**Comment by cbenz** [comment]
Bonjour @jeremsou et bienvenue dans le projet !

L'outil trace utilise une version pas toujours à jour de l'API web d'OpenFisca. Ceci peut être amélioré en travaillant sur la mise à jour automatique (ce que je compte faire très prochainement).

En attendant je vais mettre à jour manuellement le serveur "openfisca.fr" qui héberge l'API web.

Ce problème impacte également http://legislation.openfisca.fr/, http://ui.openfisca.fr/ et toutes les applications JavaScript qui utilisent l'API web.

D'autre part, coïncidence heureuse, je suis en train de travailler depuis 2 jours sur une "trace" directement accessible depuis Python, en particulier depuis les notebooks Jupyter. Je posterai d'ici demain une démo. Ceci rendrait l'outil trace moins central, pour ceux qui travaillent depuis les notebooks tout du moins.

Merci encore et à bientôt

**Comment by jeremsou** [comment]
Bonjour @cbenz merci pour vos réponses !

La valeur exacte est donc celle du simulateur et non pas celle de l'api?

A bientot!

**Comment by cbenz** [comment]
Qu'entendez-vous par `simulateur` ? http://ui.openfisca.fr/ ?

**Comment by cbenz** [comment]
En vous relisant je comprends que c'est l'UI. Les 2 utilisent l'API web.

En revanche ce qui les distingue, c'est que l'UI utilise une décomposition du revenu disponible alternative qui, elle, peut être erronnée.

Je vais investiguer cela.

**Comment by cbenz** [comment]
ping @edarin également

**Comment by iDevelopper** [comment]
Il y a effectivement plusieurs problèmes, c'est pour cette raison que j'ai mis en stand by mon application iOS !

**Comment by jeremsou** [comment]
Oui par simulateur j'entends UI.

Quand j'utilise le lien de l'API : curl http://api.openfisca.fr/api/1/calculate, cela me renvoie bien la valeur de Trace et non celle de l'UI ?

La différence entre les deux est égales à ces 3 variables : RSA + aides exceptionnelles de fin d'année + minimas sociaux, je pense alors qu'il faudrait étudier cela en détail. J'ai l'impression que le problème vient de Trace car qu'importe le niveau de revenu le RSA est toujours présent ce qui n'est pas logique.

**Comment by iDevelopper** [comment]
#319: On en parlait déjà...

**Comment by fpagnoux** [comment]
Je ne connais pas l'UI d'openfisca, mais quels sont les paramètres donnés en entrée pour estimer les prestations sociales ?

Les minimas sociaux sont calculés à partir d'inputs souvent mensuels : mon RSA dépend de mon revenu des trois derniers mois, par exemple. Si je rentre dans Openfisca un "revenu du travail" annuel  de 100 000€ pour une année mais que je ne précise aucun salaire mensuel, un RSA sera sans doute calculé "à tort" car il n'y a pas de dépendance formelle entre la variable RSA et la variable "revenu du travail".

Il semble donc que l'UI calcule des prestations sociales sans capturer les variables nécessaires à l'obtention d'un résultat juste.

**Comment by iDevelopper** [comment]
Je ne vois pas de variables permettant de saisir des salaires mensuels. D'autre part je viens de refaire des tests sur le simulateur OpenFisca. Pour un revenu de 100 000€, pas de RSA. Depuis mon application si j'utilise /api/1/calculate, pas de RSA, si j'utilise /api/1/simulate, RSA = 666. Donc les deux api ne renvoient pas les mêmes résultats.

**Comment by edarin** [comment]
Pour l'instant api/1/simulate renvoit vers une autre manière d'utiliser les variables d'OpenFisca qui permet de calculer des agrégats de façon malléable. Mais ceci nécessite un xml "fait main" donc il est vrai qu'il y a des fautes dedans.

Nous réflechissons à la tournure que doit prendre OpenFisca: soit on résout les problèmes du xml et cela laisse donc l'opportunité à chaque utilisateur de créer ses agrégats, soit on raisonne à partir de api/1/calculate mais la décomposition sera a priori plus rigide.

De toute façon actuellement il faut se fier à /api/1/calculate et appeler toutes les variables qui vous intéressent.

**Comment by cbenz** [comment]
En effet, avec @edarin nous avons refait un état des lieux ce matin et l'API `simulate` qui utilise le fichier de [décomposition XML](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/decompositions/decomp.xml) donne pour l'instant des résultats faux.

Conséquence : l'[UI](http://ui.openfisca.fr/) est fausse.

En revanche l'API `calculate`, elle, n'utilisant pas les décompositions, est juste.

Tout cela implique pas mal de corrections que nous allons démarrer.

En attendant fiez-vous à `calculate` uniquement.

**Comment by cbenz** [comment]
@iDevelopper l'UI (démonstrateur) ne permet pas d'affecter des valeurs autrement que par année.

Cette UI est appellée démonstrateur car justement elle permet de faire quelques démos, mais est rapidement limitée. Je vais ajouter quelques "warnings" pour indiquer les limitations.

Pour aller plus loin on préconise maintenant les "notebooks" [Jupyter](http://jupyter.org/), à installer soit sur sa machine, soit utiliser en ligne (https://jupyter.openfisca.fr/) mais malheureusement en ce moment notre admin système travaille dessus et le service est désactivé.
