### ISSUE TITLE
Problème PEA f3vm et f3vt

### ISSUE THREAD

**Issue by jeremsou** [openfisca/openfisca-france#531]
Bonjour à tous,

Les calculs relatifs aux PEA sont très étranges. Tout d'abord le simulateur ne fonctionne pas lorsqu'on remplit la variable du PEA soit f3vm et f3vt.

Ensuite les chiffres de Trace ne sont pas justes. 
Exemple : PEA clôturé avant 2 ans comme seul revenu pour 50 000€
Le revenu disponible retourné est : 999,45 ce qui ne peut être vrai

Merci à tous

Jérémy

**Comment by cbenz** [comment]
Pareil, pour @edarin ?

**Comment by benjello** [comment]
La partie taxation du capital est fragile. elle change souvent et est peut testée.
@edarin : une bonne façon de faire est de retracer l'utilisation des variables f3vm et f3vt à partir de la feuille de calcul livrée avec la notice 2042 (et/ou 2042C) pour voir si n n'a pas oublié certaines choses.
Une autre piste est de comparer avec Inès.
Ne pas hésiter à revenir vers moi.

**Comment by jeremsou** [comment]
Bonjour Benjamin,

Veux-tu que je me renseigne sur la fiscalité du PEA et que je regarde si le code correspond à cette fiscalité ?
En revanche, qui est Inès ?

Bonnne journée

**Comment by benjello** [comment]
INES est le programme de microsimulation de l'INSEE-DARES. Il est écrit en SAS. Il es disponible [ici](https://framagit.org/openfisca/ines-libre).

**Comment by benjello** [comment]
@jeremsou : je veux bien que tu regarde ce qu'il manque dans openfisca pour tout ce qui concerne les PEA. Le plus simple est de recenser cela année par année en partant d'aujourd'hui et en remontant le temps.

**Comment by edarin** [comment]
@jeremsou  es-tu encore sur l'affaire ? 

Ou dois-je regarder de mon côté ?

**Comment by jeremsou** [comment]
@edarin@benjello Désolé pour le retard je n'avais pas vu vos réponses

J'ai refait un point tout à l'heure : UI et Trace ne marche toujours pas pour le PEA dont les deux variables sont f3vm et f3vt.

Je pars d'un exemple avec f3vm = 50 000
La première capture d'écran montre qu'il n'y a aucun résultat sur simulation
<img width="1280" alt="capture d ecran 2016-08-15 a 17 52 25" src="https://cloud.githubusercontent.com/assets/20839927/17668250/0ee646d6-6311-11e6-89ff-23618da736bd.png">

Quand j'essaye sur Trace j'ai toujours la valeur non cohérente : 999 de revenu disponible pour 50000 de produits de PEA.

J'ai plusieurs pistes :   
- f3vt : n'a pas de variable appelante, ce qui expliquerait qu'il n'y ait pas de retour lorsqu'on la met en variable d'entrée : le revenu disponible donne toujours 7998 qu'importe la valeur d'entrée
- f3vm : a des variables appelantes : div et div_ms, mais les résultats restent non cohérents et je n'ai toujours pas compris pourquoi..

**Comment by cbenz** [comment]
Merci @jeremsou pour ton message.

Tant que cette issue est "in-progress" (cf les labels dans la colonne de droite) c'est normal que l'UI et l'outil trace qui sont en production ne soient pas mis à jour.

Premièrement il faut trouver quelqu'un qui comprenne la législation, avant même de parler de l'implémenter dans OpenFisca. Personnellement ce n'est pas mon cas :-)
Les économistes qui travaillent sont sûrement plus au fait, mais toi aussi sembles bien comprendre ce sujet. Je sais que @edarin peut regarder cette partie de la législation mais cela va prendre du temps à bien comprendre.

Ensuite il s'agit d'écrire les formules dans OpenFisca, et là on doit faire attention à bien "brancher" les nouvelles cases aux bonnes formules, sans ne rien casser. Et pour cela nécessite de bien comprendre les formules qui appellent ces cases, et ainsi de suite. Cela prend également du temps :-)

Puis il faut écrire des tests qui prouvent que pour au moins quelques valeurs caractéristiques les calculs sont justes et le restent au fil des mises à jour.

Enfin, seulement, on peut déployer une nouvelle version sur les serveurs et en faire profiter l'UI.

Je vois bien que tu pointes un manque dans le projet mais toute aide est la bienvenue, pas forcément pour écrire du code source OpenFisca, mais pour décrire un calcul, pointer vers des documentations, etc. pour aider à avancer. Ce serait super.

J'en profite également pour m'assurer, quand tu parles de la "calculette", si tu ne confonds pas avec l'application de Bercy en langage M, qui n'est pas la même chose que OpenFisca.

Merci encore pour ton implication :-)

**Comment by jeremsou** [comment]
@cbenz Merci pour ta réponse

Je comprends bien la législation, en revanche je suis moins à l'aise pour toute la partie code, on peut donc essayer de se compléter à ce niveau-là :-)

**Comment by cbenz** [comment]
Génial @jeremsou, je pense qu'on trouvera un moyen de se transmettre le savoir, soit par écrit soit par coup de fil, avec surtout @edarin dans la boucle !

**Comment by edarin** [comment]
J'ai commencé à regarder le problème (et notamment à véritablement implanter f3vt qui n'était que créée mais pas utilisée ..).

Voici le début de la révision : #545
