### ISSUE TITLE
What is the variable "div" (and "div_ms") ?

### ISSUE THREAD

**Issue by edarin** [openfisca/openfisca-france#532]
Looking to answer to jeremsou, I found the variable [div ](http://legislation.openfisca.fr/variables/div) whcih seems to embrace taxable divididends. 

1) it has no label. what does it mean ?

2) it is never used in the code, never called. But should be count in the taxes ..

**Comment by benjello** [comment]
Yes div is the taxable dividend. div-ms are the dividend that enterthe minima sociaux. Might beobsolete though.

**Comment by edarin** [comment]
should `div` be added to the `rev_coll` ?

It is written as comments but not used.

**Comment by benjello** [comment]
You should check where these div and div_ms enters.
Inclusion of div in rev_coll is unsure. @fpagnoux should know more.

**Comment by fpagnoux** [comment]
I don't know much about rev_coll. Although this is in mes-aides perimeter, I don't think this calculation has a direct impact on us given the quantities we use as inputs.

**Comment by benjello** [comment]
Update for @edarin (and I switch to french)
div_ms rassemble les dividendes qui entrent dans la base ressource des minimas sociaux
Sont-il différents de div ? Je ne crois pas. Ce qui est important c'est qu'n les ramène au niveau de l'individu pour les sommer au niveau d'une famille qui est l'entité des minima sociaux.

Il faudrait trouver un meilleur nom que div et div_ms.
Je propose pour dividendes et dividendes_individus
Qu'en pensez-vous @edarin et @fpagnoux ?

**Comment by edarin** [comment]
Je ne saurais dire pourquoi mais:
- `div` contient en plus les plus et moins values des revenus des professions salariés et est appelé par rev_coll (enfin il l'appelé à la base en commentaire et je l'ai mis en dur) et donc utilisé par prestations_familiales et aides_logement
- `div_ms` lui ne les contient pas et sert à asi, aspa et rsa.

Donc la distinction précédente n'est pas pertinente.

**Comment by edarin** [comment]
En tout cas j'ai changé les labels afin de préciser : 

- "Dividendes imposés"
- "Dividende entrant en compte dans le calcul des minimas"
