### ISSUE TITLE
GitHub ou Framasoft?

### ISSUE THREAD

**Issue by lumbjohn** [openfisca/openfisca-france#534]
Bonjour,

Sur quel support doit-on travailler?
https://git.framasoft.org/openfisca/calculette-impots-python
ou
https://github.com/openfisca/openfisca-france/

Je pose cette question apres avoir vu le commentaire de @cbenz, @edarin et @jeremsou dans une issue sur F2TR et F2FA de la 2042.
En effet dans la version Framasoft on retrouve F2FA(https://git.framasoft.org/openfisca/calculette-impots-python/blob/master/calculette_impots/generated/formulas.py) dans la version Git(celle de /calculate d'Etalab au final) on retrouve F2TR.

On a du mal nous qui n'avons pas construit le soft à faire la différence.

**Comment by cbenz** [comment]
Bonjour @lumbjohn,

Ces 2 dépôts ne concernent pas le même logiciel.

https://git.framasoft.org/openfisca/calculette-impots-python est le code source du compilateur du code source du calculateur des impôts de Bercy écrit en langage M vers Python.

https://github.com/openfisca/openfisca-france/ est le code source d'OpenFisca en ce qui concerne les formules de la législation Française, concernant les impôts mais aussi les prestations sociales et autres choses. Ce projet a été écrit "à zéro".

Pour trancher : pour contribuer à OpenFisca c'est https://github.com/openfisca/openfisca-france/

Attention, le fichier [`formulas.py`](https://git.framasoft.org/openfisca/calculette-impots-python/blob/master/calculette_impots/generated/formulas.py) est la transformation en Python du code M, et vous devriez lire les formules directement en langage M sur ce dépôt-ci : https://framagit.org/openfisca/calculette-impots-m-source-code

J'admets qu'il y a de quoi s'y perdre un peu, mais on préfère garder des dépôts git séparés pour ne pas tout mélanger.

En espérant vous avoir bien aiguillé sinon n'hésitez pas à demander.

**Comment by lumbjohn** [comment]
Merci @cbenz
