### ISSUE TITLE
Why `rfr_n_1` still exist and is still called ?

### ISSUE THREAD

**Issue by edarin** [openfisca/openfisca-france#538]
Working on [`f2fa`](https://github.com/openfisca/openfisca-france/pull/537/files), I found the variable `taxe_habitation` which calls `rfr_n_1` and not  `rfr` at the previous period.

Furthermore I don't understand what is this [variable](https://legislation.openfisca.fr/variables/rfr_n_1) ? It is neither an entry nor a calculated variable

Wtf ?

**Comment by benjello** [comment]
This should be fixed. It come from a previous version where we weren't handling variable's period.

**Comment by benjello** [comment]
@edarin : would you fix it ?

**Comment by edarin** [comment]
perfect!
