### ISSUE TITLE
How to handle end date of DatedVariable ?

### ISSUE THREAD

**Issue by edarin** [openfisca/openfisca-france#539]
I found at least a variable - `rev_cap_lib` - but I think that there is plenty of it that has a end date in 2015-12-01 without -in my opinion- any reason apart from the fact that we're in 2015.

I have the feeling that for this kind of case normally it should not have any end date. And that this mistake is quite frequent.

Furthermore I think that this issue is also acute for some parameters which should have an end date `fuzzy = true` (already experienced for `assvie`)

**Comment by laem** [comment]
The fuzzy attribute has been introduced in response to the previous state of OpenFisca, where this bug occured : https://github.com/openfisca/openfisca-france/issues/353.

**Comment by laem** [comment]
(I believe that all the parameters that were outdated at the time of the pull request (e.g. 2015-12-01 ?) where left as is. All the "running" parameters had their last date kept, but were "fuzzied")

**Comment by benjello** [comment]
@laem : you do believe right ;-)

**Comment by edarin** [comment]
if I understand good, some parameters have to be updated with the fuzzy attribute then ?

And for the DatedVariables which end in 2015-12-31, should they be extended ?

**Comment by benjello** [comment]
Yes some parameters should be updated with fuzzy (but their value should be checked)
And some DatedVariables should be extended too after checking that the case de la feuille d'impôt exists if the variable is of that type.

**Comment by MattiSG** [comment]
This question is not specific to France and was moved to openfisca/openfisca-core#437.
