### ISSUE TITLE
chomage_imposable devrait s'appeller "autres_revenus_imposable"

### ISSUE THREAD

**Issue by pnbt** [openfisca/openfisca-france#542]
Il correspond a la case 1AP, et inclut les préretraites. Etes vous OK pour que je change le nom du label? J'imagine que changer le nom de la variable vas casser pas mal de trucs...

**Comment by benjello** [comment]
Les preretraites c'est économiquement du chômage indemnisé et c'est traité fiscalement comme cela. Donc pas de changement du nom de variables mais oui au changement de label pour qu'il colle à celui de la déclaration d'impôt.

**Comment by pnbt** [comment]
Ok, merci pour la clarification!

**Comment by benjello** [comment]
@pnbt : can i close this issue ?

**Comment by benjello** [comment]
@pnbt : can i close this issue ?

**Comment by pnbt** [comment]
Ok!
