### ISSUE TITLE
Cerfa fields get converted to string at some point

### ISSUE THREAD

**Issue by pnbt** [openfisca/openfisca-france#543]
Example:
```
ipdb> column.cerfa_field
u"{0: u'6PS', 1: u'6PT', 2: u'6PU'}"
```

This should be a string like `u'1AJ'` or a dict, not a string representing a dict.

**Comment by benjello** [comment]
And Cerfa fields are sometimes reused for different things across years ...

**Comment by pnbt** [comment]
Yes! There are only 5 bugs of a cerfa field which is in two variables, do you know what is the one that actually matches CERFA?

nbN <> caseN
nbF <> caseF
nbG <> caseG
nbH  <> caseH
f8tk <> f8ti


PS: Less important since it seems to be old dated formulas:

f7uh_2007 -- f7uh
f8wc__2008 -- f8wc
f8td_2002_2005 -- f8td
f3vv_end_2010 -- f3vv

**Comment by benjello** [comment]
They are actually two "case"  N, F, G and H: some are integers and others are booleans.
For example G [here](http://www.impots.gouv.fr/portal/deploiement/p1/fichedescriptiveformulaire_8343/fichedescriptiveformulaire_8343.pdf)

It is a real mess !

**Comment by benjello** [comment]
I am ok since it should fix part of these failing [tests](https://travis-ci.org/openfisca/openfisca-france-data).
