### ISSUE TITLE
Nouveau calcul aide au logement

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#546]
Les aides au logement sont dégressives avec [le loyer pour les loyers au dessus d'un certain seuil](https://www.caf.fr/ma-caf/caf-de-la-haute-savoie/partenaires/aides-au-logement-nouveau-calcul-a-compter-de-juillet-2016) à partir de juillet 2016.
Il ne me semble pas que cela ait été implémenté dans openfisca:  @fpagnoux @pierrehvz  pouvrriez-vous confirmer ou infirmer ?

**Comment by pierrehvz** [comment]
En effet, cette mesure n'est pas prise en compte dans openfisca.
J'ai trouvé une bonne [documentation](https://www.anil.org/documentation-experte/analyses-juridiques-jurisprudence/analyses-juridiques/analyses-juridiques-2015/encadrement-de-levolution-et-du-niveau-des-loyers-dans-les-zones-tendues/) sur le site de l'ANIL

**Comment by benjello** [comment]
@fpagnoux : est-ce dans les tuyaux de votre côté ? Avez-vous des tests ?

**Comment by benjello** [comment]
@fpagnoux goûte un repos bien mérité.. 
@HelaG @MattiSG sauriez-vous me renseigner ?

**Comment by HelaG** [comment]
@benjello non, pas de nouveaux tests là-dessus.

**Comment by benjello** [comment]
@HelaG : est-ce implémenté ?

**Comment by MattiSG** [comment]
> est-ce implémenté ?

Pas à ma connaissance, non.

**Comment by MattiSG** [comment]
Peut-être @michelbl pourrait-il se pencher sur le sujet… ?

**Comment by michelbl** [comment]
Avec plaisir, mais je suis en vacances jusqu'au 2 novembre...

**Comment by benjello** [comment]
Personne n'est volontaire (dixit l'inspecteur des travaux à finir)  ?
@michelbl @fpagnoux ?

**Comment by fpagnoux** [comment]
@michelbl est-ce que tu veux te saisir de la mise à jour pour te faire une expérience dans la rédaction des formules ?

Côtés mes-aides, on sait qu'on doit le faire mais il faut qu'on trouve le temps.

**Comment by MattiSG** [comment]
Fixed via #651.
