### ISSUE TITLE
Bug with bouclier fiscal

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#55]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/98_

---

_Issue by **[benjello](https://github.com/benjello)** from Friday Dec 07, 2012 at 09:32 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/95_

---

In 2009 maxrev = 50000 nmen 101, 1 person there is some bouclier fiscal at 500 euros

**Comment by MattiSG** [comment]
Issue ayant plus de 5 ans, pas de travail actif, pas de test, je ferme.
