### ISSUE TITLE
Erreurs d'irpp pour des salaire_imposable entre 15000 et 20000 euros

### ISSUE THREAD

**Issue by pnbt** [openfisca/openfisca-france#553]
<img width="412" alt="screen shot 2016-08-25 at 10 30 45 am" src="https://cloud.githubusercontent.com/assets/6332247/17962055/3b893694-6aaf-11e6-8ce3-130cb5792ebd.png">
Comparé a la calculette en ligne, on a des erreurs entre 100 et 300 euros, cf graph ci joint
(x=salaire_imposable, y=erreur)

**Comment by edarin** [comment]
yeurk

**Comment by benjello** [comment]
Sur quelle année ?
Les deux dernières années sont très surement bugguées car l'essentiel des mises à jour des paramètres ont été faites sur la branche baremes-ipp.
Cependant on a un bug bloquant en ce moment https://github.com/openfisca/openfisca-france/issues/523 ...

**Comment by pnbt** [comment]
2014. Ok!

**Comment by benjello** [comment]
Mais je veux bien l'année hein ;-)

**Comment by edarin** [comment]
Il s'agit de 2014.

**Comment by benjello** [comment]
revenus 2014 ?
My guess: réduction d'impôt exceptionnelle (350 euros), décôte et montant du plafond de l'abattement des revenus.

**Comment by edarin** [comment]
oui. du coup malcalculé de notre part ?

**Comment by benjello** [comment]
Oui mais normalement corrigé dans la branche baremes-ipp. Mais on ne peut l'utiliser because https://github.com/openfisca/openfisca-france/issues/523.
Do you feel the pressure @fpagnoux ,-)

**Comment by benjello** [comment]
@pnbt @edarin : la branches baremes-ipp est de nouveau très [fonctionnelle](https://travis-ci.org/benjello/openfisca-france/builds/156558301), je suis preneur des erreurs que vous pourriez détecter ainsi.

**Comment by pnbt** [comment]
Ok, apres avoir amelioré le systeme de test, j'ai pu voir que l'erreur viens d'une conversion d'année de mon coté: openfisca considère la période, et le calculateur l'année de calcul. Je ferme le bug, les vrais ecarts sont en fait de l'ordre de 3 euros max :-) 
<img width="416" alt="screen shot 2016-09-01 at 11 29 46 am" src="https://cloud.githubusercontent.com/assets/6332247/18163103/a1b37daa-7039-11e6-8e54-36fc14b2a301.png">

**Comment by benjello** [comment]
On pourrait essayer de voir les règles pour réduire les erreurs à moins de 1 euro non ?
Faudrait  comprendre comment on fait les arrondis.
Je ne rouvre pas le ticket pour l'instant.
