### ISSUE TITLE
Lister les variables calculables en fonction des données saisies

### ISSUE THREAD

**Issue by prevostc** [openfisca/openfisca-france#556]
Est-il possible de lister les variables calculables par rapport aux données disponibles ?

Par exemple, pour calculer le montant d'aide au logement (APL), il faut saisir des informations relatives au logement, à la composition familiale, la situation professionnelle, et aux revenus. (source: [site de la caf](https://wwwd.caf.fr/wps/portal/caffr/aidesetservices/lesservicesenligne/estimervosdroits/lelogement/!ut/p/a1/lZDNDoIwEISfxQcwnVp_4NiAQKkK_qDCxTRGTaNUg8bntyQeDIkY97bJN7M7QwqyJYVRT31SD3016lLvxXCXJjSM5BIhxj0HIkLKomjNkPQskFsAX4ajVe_grW8BftzfkKKB-KkP4SKWrjugoaRNwAm8wAID35_Nhf2R_QLwBlpC5jbF6MNhljDwMKWOjD0K9ElmrlVp-1zWXseqPHtGHfm-bpnk1UEb_dDqou-HqumVUO5CLCYyDoYMNt8_Xrcy20KLbl7upive6bwA5ZjMGA!!/dl5/d5/L3dDcEEvd0NvQk1rQkEvNE8weENPd2cvWjZfUE8xR0hLUzBHMEUyODBJSDBQM0hIVjMwTzIvWjdfUE8xR0hLUzBHTzFBOTBJUkxLSkY2MzAwRzA!/))

Il serait donc pratique d'avoir comme sortie "aide_logement" lorsque je précise que je détient ces informations.

Le comportement actuel semble être d'utiliser des variables par défaut. 
Par exemple, si je demande de calculer le RSA sans préciser de salaire, alors j'ai bien un RSA qui est calculé (~500€ par mois, ce qui doit correspondre à un salaire de zéro). 
Dans le cas du RSA, si l'utilisateur ne m'a pas encore fournis son salaire, je voudrais savoir qu'il ne sera pas pertinent de lui afficher son aide RSA.

Je pourrais implémenter de mon côté une sorte de mapping entre les données disponibles et les aides mais dans ce cas on a un problème de responsabilité des systèmes car openfisca ne serait plus le seul "sachant" concernant la manière de calculer les différentes aides.

**Comment by laem** [comment]
En utilisant l'API des variables, [ici](https://api.openfisca.fr/api/1/variables/), il est possible de : 
- partir d'une sélection de variables intéressantes (dont `aide_logement`)
- traverser le graphe des `calls` de ces variables 
- vérifier si toutes ses variables d'entrées sont renseignées
Le problème, c'est que ça fera beaucoup de variables à renseigner : les défauts sont parfois bien utiles.
