### ISSUE TITLE
Fix travis.yml for baremes-ipp branch

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#557]
See [here](https://travis-ci.org/openfisca/openfisca-france/builds/155321720).
It would be nice to understand what is wrong so i can increase my knowledge and thus my utility.

**Comment by fpagnoux** [comment]
`  error: can't copy 'openfisca_france/i18n/fr/LC_MESSAGES/openfisca-france.mo': doesn't exist or not a regular file`-> on essaye d'installer openfisca-france sans compiler les fichiers d'internationalisation.

**Comment by fpagnoux** [comment]
I think I can fix it.

**Comment by benjello** [comment]
Yes ! Thanks  @fpagnoux

**Comment by fpagnoux** [comment]
@cbenz do you understand why travis tries to run `python setup.py bdist` here ? I can install easily from my computer without compiling the .mo files. Why is travis doing differently ?

**Comment by cbenz** [comment]
I'm looking at it

**Comment by fpagnoux** [comment]
Yes I meant bdist_wheel.

**Comment by fpagnoux** [comment]
I pushed a fix, it seems to install everything correctly, but tests are not passing afterwards for another reason related to parameters.

**Comment by cbenz** [comment]
I think that `--editable` was missing, so Travis triggered a "normal" install (via `bdist_wheel`) and `compile_catalog` was not run (it is run in deploy-to-pypi step).

**Comment by cbenz** [comment]
I tried merging with openfisca-france/master and the [tests](https://travis-ci.org/openfisca/openfisca-france/builds/155341507) seem to run.

**Comment by benjello** [comment]
run but do not pass ;-)

**Comment by benjello** [comment]
Closing since the remaining errors are related to something else
