### ISSUE TITLE
Add 1at and 2bt in the calculation of taxable income

### ISSUE THREAD

**Issue by edarin** [openfisca/openfisca-france#558]
I'm working on the variable 1at mentioned in the issue #529.
It is "Pensions de retraite en capital taxables à 7,5%" created for the income of 2011.
C'est un impôt forfaitaire libératoire de l'impôt sur le revenu.

I was wondering if we should add this variable to the pension part of OpenFisca (for example the script `remplacement.py`) or has this variable another status ?

I checked the INES file : 
it is added in the pgm `Impo` apart with others "prélèvement libératoires", [this way](https://framagit.org/openfisca/ines-libre/blob/master/pgm/3Mod%C3%A8le/Fisc/6_Impot.sas) : 

`/***************************
        IX. Prélèvements libératoires
        *****************************/

```
    impot=impot8
            +CEHR
            + &prel_lib_t2.*sum(0,_1at,_1bt)*(1-&abat10_bis.)
            /*Prestations de retraite versées sous forme de capital, 
            soumises à un prélèvement libératoire de l'impôt sur le revenu à partir de 2011 (CGI art 163 bis II) */
            + _4bh /* taxe sur les loyers élevés des logements de petite surface */;`
```

**Comment by benjello** [comment]
On est autorisé à parler en français quand on traite des questions de législation et/ou de compatbilité nationale etc  typiquement françaises
Pour rédpondre à ta question, je mettrai ces revenus avec les revenus du capital soumis à prélèvement libératoire

**Comment by edarin** [comment]
le problème c'est que rev_cap_lib rentre en compte dans plusieurs autres calculs d'entités. et notamment rev_cap ce que n'est pas 1at si je ne m'abuse ..

**Comment by benjello** [comment]
C'est de l'épargne retraite. Donc un revenu du capital. C'est soumis à un prélèvement libératoire.
Certes cela ne doit pas entré dans les bases ressources de certaines prestations mais pour la construction du revenu disponible du ménage je ne vois pas pourquoi cela n'entrerai pas dans les revenus.

Et bien entendu il faut ajouter ce prélèvement aux autres éventuellement avec les autres prélèvements libératoires.

**Comment by edarin** [comment]
et en ce qui concerne les prélèvements sociaux, sur cette case s'applique les taux liés au retraite ou aux revenu du capital ?

**Comment by benjello** [comment]
Je ne sais pas s'ils sont exonérés ou pas de prélèvement sociaux. A déterminer. INES est un bon point de départ.

**Comment by edarin** [comment]
un élément de réponse : http://bofip.impots.gouv.fr/bofip/4620-PGP.html#4620-PGP_Revenus_constituant_des_rev_40

**Comment by benjello** [comment]
Quelle ligne faut-il lire ?

**Comment by edarin** [comment]
paragraphe 60 ?

**Comment by benjello** [comment]
Cela ressemble plus aux pension de retraite à titre onéreux ...

**Comment by MattiSG** [comment]
Issue ayant été utilisé comme une discussion, ayant mené à un consensus, le porteur a trouvé sa réponse il y a 8 mois, je ferme.
