### ISSUE TITLE
rsa_act

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#56]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/106_

----

_Issue by **[benjello](https://github.com/benjello)** from Tuesday Dec 18, 2012 at 11:04 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/103_

----

Some ras_act are negative. rsa is attributated to famille

**Comment by jdesboeufs** [comment]
Obsolète.
