### ISSUE TITLE
Remplacer exposition_accident par taux_accident_travail

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#560]
Variable [exposition_accident](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/revenus/activite/salarie.py#L135) should be removed and [taux_accident_travail](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py#L711) amended

**Comment by laem** [comment]
AT/MP will be added to the simu embauche very soon, by selecting a code risque from this list. 
You can see them here : https://github.com/laem/taux-collectifs-cotisation-atmp
OpenFisca should be able to suggest this list to let the user choose it. I'm not sure how to do it.

**Comment by benjello** [comment]
Nice ! We should get the historic values.  How did you got that ? A csv from some official source or did you parse the arrêté ?

**Comment by laem** [comment]
Yes I parsed it (copy past html table to libre office calc ;-) )

**Comment by MattiSG** [comment]
@laem ce serait génial d'intégrer les taux AT/MP dans OpenFisca ! Penses-tu pouvoir ouvrir une PR en ce sens ? :smiley:

**Comment by laem** [comment]
@MattiSG Le simulateur utilise aujourd'hui ces taux pour proposer un `select` dans l'interface, donc en utilisant directement le JSON. Ils ne sont donc pas utilisés à travers l'API OpenFisca (et ce cas d'usage n'existera probablement pas). 
Je ne vois donc pas l'intérêt de les intégrer dans openfisca-france, mais pouprquoi pas les bouger dans un répertoire sur quelque chose comme : openfisca/openfisca-france-données. 
D'ailleurs, @benjello openfisca-france-data mériterait une description ou un renommage.

**Comment by benjello** [comment]
Il faudrait au moins remplacer la valeur par défaut par celle présente dans [syso](https://github.com/betagouv/syso/pull/192/files)

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
