### ISSUE TITLE
Fournir des représentations graphiques de la législation

### ISSUE THREAD

**Issue by pnbt** [openfisca/openfisca-france#565]
We should have a template with all important graphs in notebooks. What are the most important for you? Do we already have implementations of some of them?
- Pauvreté
- Gini
- Kakwani
- Barèmes:
  But: visualiser des evolutions d'impots
  Comment: courbes d'evolution de l'impot / taux marginal d'imposition en fonction du salaire
  x = salaire
  y = impot
- Salary/Disp:
  But: visualiser le revenu disponible de toute une population en un graph
  Comment: Scatterplot d'un échantillon de la population avec:
  x = revenus
  y = revdisp

**Comment by benjello** [comment]
Ces graphes n'ont pas besoin de réformes. Ce sont jsute pour certains des visualisations nécessitant des distributions.

**Comment by pnbt** [comment]
Ok for name changing. Questions remains: 
- do we need more of them?
- do we have implementations? (otherwise I'll just reimplement them, no big deal)

**Comment by benjello** [comment]
la variable pauvre est calculée dans [openfisca-france-data](https://github.com/openfisca/openfisca-france-data) 
gini et kakwani sont calculés dans [openfisca-survey-manager](https://github.com/openfisca/openfisca-survey-manager)
On n'a pas de scatter plot (j'utilisais matplotlib)
Les courbes de taux marginaux taux moyen peuvent être calculées à partir de fonctions qui se trouvent dans [rates.py](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/rates.py)

**Comment by benjello** [comment]
Commencer par le dernier point. On fera les autres plus tard.

**Comment by pnbt** [comment]
Super ca marche

**Comment by MattiSG** [comment]
Issue déplacée dans https://github.com/openfisca/openfisca-doc/issues/33.
