### ISSUE TITLE
Problem in PPE for 2006 and 2007

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#57]
_Issue by **[benjello](https://github.com/benjello)** from Friday Feb 28, 2014 at 23:59 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/178_

---

_Issue by **[bouvard](https://github.com/bouvard)** from Tuesday Apr 30, 2013 at 13:45 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/175_

---

there isn't enought ppe for those years. It's not due to rsa_act

**Comment by MattiSG** [comment]
Issue ayant plus de 4 ans, pas de travail actif, je ferme.
