### ISSUE TITLE
Formula uses `period.this_year` but dependencies do not

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#570]
I have a small question coming from @JeanEricHyafil notebook:

Variable [`cotsoc_noncontrib`](https://legislation.openfisca.fr/variables/cotsoc_noncontrib) starts with `period.this_year` but its dependencies [`cotisations_employeur_non_contributives`](https://legislation.openfisca.fr/variables/cotisations_employeur_non_contributives) and [`cotisations_salariales_non_contributives`](https://legislation.openfisca.fr/variables/cotisations_salariales_non_contributives) do not.
However it is a sum so I don't see why it should change the period.

The point is that Jean-Éric would like to calculate `cotsoc_noncontrib` on a month, so we either remove `period.this_year` or use a `calculate_divide` in the caller.

@benjello Can you tell us your point of view?

**Comment by benjello** [comment]
Remove `period.this_year`.
And rename `cotosc_noncontrib` to cotisations_non_contributives ;-)

**Comment by cbenz** [comment]
See https://github.com/openfisca/openfisca-france/issues/570
