### ISSUE TITLE
FIx isf test

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#574]
The last [isf test](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/tests/formulas/isf.yaml#L40) is failing.
@pierrehvz i thought you had a problem with the computation. 
Now it pass but the value is wrong.

**Comment by pierrehvz** [comment]
Yes I had a margin error (approximately 40euros)
I am not sure to understand how the test can pass with a wrong value?

**Comment by benjello** [comment]
If i recall well the computation stopped. Now it hors on til the end but the result is wrong !
Where Did you get the values for your last test ?

**Comment by pierrehvz** [comment]
Ok, i don't remember that, I thought it was just a margin error.
All the values I entered comes from [here](http://patrimoine.lesechos.fr/outils-services/calcul/isf/isf.html)

**Comment by benjello** [comment]
Thankd

**Comment by benjello** [comment]
@edarin : do you have time to check that (but you should be on baremes--ipp branch).
And you can say **no** ;-)

**Comment by MattiSG** [comment]
This issue is not actionable: the referenced test gives a 404, and there is no context to reproduce it. It is 7 months old, closing.
