### ISSUE TITLE
Renommer une variable dans `af_base`

### ISSUE THREAD

**Issue by elsaperdrix** [openfisca/openfisca-france#575]
Plus de deux enfants should be deuxieme_enfant in [af_base](https://github.com/openfisca/openfisca-france/blob/4.1.11/openfisca_france/model/prestations/prestations_familiales/af.py#L109)

**Comment by adrienpacifico** [comment]
Un barème dont les enfants seraient les tranches ne serait-il pas adapté ?

**Comment by benjello** [comment]
Je crains que ce ne serait prendre un marteau pour écraser une mouche et que cela induise les gens en erreur.
L'usage étant limité à  cette prestation, cela me semble plus  confusant qu'autre chose. Les gens qui connaissent bien les allocations familiales ou même ceux qui veulent juste ce renseigner n'ont pas besoin de connaitre la notion de barème en taux marginal pour comprendre le calcul des allocations familiales.
