### ISSUE TITLE
Résultats différents avec mes-aides.gouv et simulateur CAF

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#587]
Bonjour,

Lorsque que j'utilise l'api web d'OpenFisca avec les paramètres suivants : 
`{
  "apiVersion": 1,
  "method": "/api/1/calculate",
  "params": {
    "scenarios": [
      {
        "test_case": {
          "individus": [
            {
              "date_naissance": 1989,
              "id": "Personne 1"
            }
          ],
          "familles": [
            {
              "id": "Famille 1",
              "parents": [
                "Personne 1"
              ]
            }
          ],
          "foyers_fiscaux": [
            {
              "id": "Déclaration d'impôt 1",
              "declarants": [
                "Personne 1"
              ]
            }
          ],
          "menages": [
            {
              "id": "Logement principal 1",
              "personne_de_reference": "Personne 1",
              "statut_occupation_logement": 4,
              "loyer": 600,
              "depcom" : 93100
            }
          ]
        },
        "period": "2016"
      }
    ],
    "variables": [
      "als"
    ]
  },`

Alors j'obtiens un résultat différents : 
`"als": {
            "2015": 817.920166015625,
            "2015-06": 68.16000366210938,
            "2015-07": 68.16000366210938,
            "2015-04": 68.16000366210938,
            "2015-05": 68.16000366210938,
            "2015-02": 68.16000366210938,
            "2015-03": 68.16000366210938,
            "2015-01": 68.16000366210938,
            "2015-08": 68.16000366210938,
            "2015-09": 68.16000366210938,
            "2015-11": 68.16000366210938,
            "2015-10": 68.16000366210938,
            "2015-12": 68.16000366210938
          }`

du résultat de mes-aides.gouv : 310€ d'aides au logement
avec les paramètres suivants : Né·e le 1 janvier 1989, Nationalité française, Locataire d’un logement non meublé, Loyer : 600 €, Code postal 93100, Aucune ressource déclarée

et du résultat de la CAF : 309€ d'aides au logement
avec les paramètres suivants : 
- Vous vivez seul(e).
- Votre code postal est 93100.
- Vous déclarez être né(e) le 01/01/1989.
- Vous louez seul(e) un studio, un appartement ou une maison non meublée.
- Vous payez un loyer de 600 euros par mois.
- Vous n’êtes pas bénéficiaire du Rsa.
- Aucun revenu déclaré
- Aucun autre revenu déclaré
- Aucune charge ni déduction déclarée

Je n'arrive pas à comprendre d'où vient ce delta. 

La question la plus importante pour moi est quelle méthode puis-je utiliser pour connaitre toutes les variables qui influencent le calcule d'une aide ? Autrement dis, comment faire pour connaitre toutes les variables qui rentres dans le calcule de l'als par exemple ?

D'avance merci,

**Comment by cbenz** [comment]
Bonjour @VicBeto !

> La question la plus importante pour moi est quelle méthode puis-je utiliser pour connaitre toutes les variables qui influencent le calcule d'une aide ? Autrement dis, comment faire pour connaitre toutes les variables qui rentres dans le calcule de l'als par exemple ?

C'est la question centrale qui est difficile car une formule comme `als` dépend de beaucoup de variables d'entrée. On arrive très vite à énormément de variables quand on parcourt les dépendances récursivement.

Tu peux regarder sur https://legislation.openfisca.fr/variables/als et naviguer dans les dépendances. Cela peut être long donc tu peux aussi visualiser `als` en ouvrant la [vue graphe](https://legislation.openfisca.fr/graph/) et en cherchant `als` dans le champ de recherche en haut de la page.

Si je reformule ta question, je dirais « Parmi l'ensemble de variables d'entrée intervenant dans le calcul d'une formule, lesquelles sont *importantes* ». Et ça c'est difficile à dire formellement. On le sait de façon empirique selon les formules calculées (l'impôt dépend beaucoup du salaire par exemple).

La suite au prochain numéro.

**Comment by benjello** [comment]
Voici un exemple [tiré des tests](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_542ec2805e3a9c02007e90c4.yaml) qui pourrait vous aider.

**Comment by VicBeto** [comment]
Merci pour votre aide.
Après plusieurs essais j'ai finit par noter que j'obtiens le même résultat que mes-aides.gouv et la CAF en précisant l’année ET le mois pour la variable "period". Cela fonctionne donc avec "2016**-10**".

@cbenz va pour la méthode empirique donc et à ce propose, @benjello y-a-t'il un moyen pour obtenir les informations envoyées en input par mes-aides.gouv lorsque je fais une simulation ?

**Comment by benjello** [comment]
@VicBeto : @fpagnoux vous répondra mieux que moi.

**Comment by cbenz** [comment]
Tu peux regarder dans l'inspecteur du navigateur la requête qui est faite à l'api Web d'openfisca au moment du calcul. Tu verras le JSON exact.

**Comment by fpagnoux** [comment]
@cbenz: 
Le problème n'est pas tant de trouver les variables importantes que de trouver les inputs qui correspondent à cas d'usage particulier.

Si je calcule des prestation sociales, le salaire net d'une personne, ou le RFR de la famille, sont probablement des entrées. Si je fais une simulation d'embauche, alors peut être que mon salaire net va plutôt être une sortie calculée à partir de mon salaire brut. De même, si je fais une simulation fiscale, le RFR peut être mon résultat.

Dès lors, parcourir le graphe pour trouver les entrées n'est pas si trivial, puisqu'il n'est pas évident de distinguer une étape dans le calcul d'une entrée potentiel. 

@VicBeto je peux vous envoyer des exemples de JSON envoyés à Openfisca par mes-aides. Quel est le périmètre qui vous intéresse ? Toutes prestations nationales ? Prestations locales comprises ?

**Comment by VicBeto** [comment]
@fpagnoux avec plaisir. Le JSON envoyé par mes-aides.gouv m'aiderait beaucoup ! Pour l'instant le périmètre national me suffit. Ça me permettrait de voir comment déclarer 3 mois de revenu dans la requête OpenFisca.

Et au sujet du rfr, est-ce possible d'obtenir le rfr en sortie à partir du salaire de base en entrée ?

**Comment by benjello** [comment]
@VicBeto : je ne vois pas pourquoi il ne serait pas possible d'obtenir le rfr. Mais notez que pour passer du salaire de base au salaire imposable au rfr, il est nécessaire de préciser nombre de variables (cadre ou pas cadre, taile de l'entreprise etc, composition du foyer fiscal et autres revenus). il existe certes des valeurs par défaut qui devrait vous conduire à un résultat non nul mais il faut en être conscient.

**Comment by fpagnoux** [comment]
@VicBeto :
Vous pouvez trouver deux exemples [ici](https://github.com/fpagnoux/openfisca-france/tree/examples-json/openfisca_france/examples-json)

Vous pourrez constater que beaucoup d'entrées sont fixées à 0. En effet, lorsque le demandeur déclare ne pas toucher une prestation au moment de sa simulation, nous forçons la valeur de celle-ci à 0 pour les mois M-1 à M-12 pour éviter qu'elles ne soit recalculées à tort par openfisca.

**Comment by MattiSG** [comment]
Duplicate of #727.
