### ISSUE TITLE
Relier un parent âgé au foyer fiscal

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#588]
Bonjour,

Comment doit-on relier un parent agé (+65ans) au foyer fiscal ?

Lorsque je le relie au foyer fiscal comme une personnes_a_charge, j'obtiens l'erreur : `"Une personne à charge d'un foyer fiscal doit avoir moins de 25 ans ou être handicapée"`

Par exemple dans le cas du calcul de l'als, une personne âgée compte comme une personne à charge.

**Comment by benjello** [comment]
Un parent âgé ne peut être une personne à charge que s'il a un taux d'incapacité (supérieur à  80 %)  [http://www.impots.gouv.fr/portal/dgi/public/popup?espId=1&typePage=cpr02&docOid=documentstandard_1544].

**Comment by VicBeto** [comment]
Merci pour ta réponse (toujours aussi rapide !!!),

J'ai bien vu ton lien. Il explique bien ce qu'est une personne à charge au sens des impôts mais la définition change (il me semble) pour les allocations logements. 

Cette page : https://www.service-public.fr/particuliers/vosdroits/F13132 donne la définition dans la perspective de l'alf : _"vous avez à votre charge un ascendant de plus de 65 ans (ou 60 ans, s'il est inapte au travail, ancien déporté ou ancien combattant) et ne disposant pas de ressources supérieures au plafond de l'allocation de solidarité aux personnes âgées (Aspa),"_

Mais l'alf inclue également les personne handicapées au sens des împots comme tu l'indiques : _"vous avez à votre charge un ascendant, descendant ou collatéral atteint d'une infirmité entraînant une incapacité permanente d'au moins 80 % ou qui est, compte tenu de son handicap, dans l'impossibilité reconnue par la commission des droits et de l'autonomie des personnes handicapées (CDAPH) de se procurer un emploi."_

Qu'en dis-tu ?

**Comment by VicBeto** [comment]
De plus le simulateur de la CAF prends bien en compte la personne âgée comme personne à charge :

![capture](https://cloud.githubusercontent.com/assets/22907505/19550442/afc84eb6-96a9-11e6-96a2-8e2df2b9a13f.JPG)

**Comment by fpagnoux** [comment]
J'imagine que la solution la plus actionnable à court terme est de de déclarer le parent âgé dans un foyer fiscal différent de celui du reste de la famille (tout en restant dans la même entité "Famille).

**Comment by fpagnoux** [comment]
À long terme, c'est quelque chose auquel nous devrions réfléchir, car il est dommage qu'un utilisateur qui souhaite seulement faire des simulations de prestations sociales ait à se soucier du foyer fiscal ;)

**Comment by benjello** [comment]
Oui il faut revoir les validateurs pour autoriser ces cas. Il faut peut-être revoir aussi la composition des entités. Je ne suis pas contre le fait d'être plus exhaustif. Au contraire !

**Comment by VicBeto** [comment]
@fpagnoux merci pour la piste de solution mais je n'ai pas réussit à la transposer dans le code.

Comment déclarer la famille et les deux foyers fiscaux comme vous le suggérez avec les individus suivants ? : 
`"individus": [
		     {"id" : "Parent","date_naissance": 1989},
		    {"id" : "enfant","date_naissance": 2012},
		    {"id" : "Grandparent","date_naissance": 1940}
		  ],`

**Comment by fpagnoux** [comment]
Je tenterais : 

```js
    "individus": [
        {"id" : "Parent","date_naissance": 1989},
        {"id" : "enfant","date_naissance": 2012},
        {"id" : "Grandparent","date_naissance": 1940}
        ],
    'familles': [
        {'enfants': ['enfant', 'Grandparent'], 'parents': ['Parent']},
        ],
    'foyers_fiscaux': [
        {'personnes_a_charge': ['enfant'], 'declarants': ['Parent']},
        {'declarants': ['Grandparent']}
        ],
```

Même si c'est un peu étrange de déclarer un parent comme enfant dans la famille 🤔

**Comment by benjello** [comment]
Pour du [json](https://doc.openfisca.fr/en/openfisca-web-api/json-data-structures.html)
Pour des [tests yaml](https://doc.openfisca.fr/en/coding-the-legislation/writing_yaml_tests.html)

**Comment by MattiSG** [comment]
Bonjour @VicBeto !

Les réponses que vous avez obtenues vous ont-elles permis de résoudre votre problème ? Si oui, merci de fermer cette issue :wink: Si non, n'hésitez pas à détailler plus avant votre besoin !

**Comment by MattiSG** [comment]
Pas de réponse en 10 jours, je suppose que le problème a été résolu. Si ce n'est pas le cas, merci de détailler le problème rencontré, on rouvrira l'issue :wink:
