### ISSUE TITLE
Fip in erf ? 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#59]
_Issue by **[benjello](https://github.com/benjello)** from Saturday Mar 01, 2014 at 00:20 GMT_
_Originally opened as https://github.com/openfisca/openfisca-core/issues/304_

---

_Issue by **[AlexisEidelman](https://github.com/AlexisEidelman)** from Monday Nov 11, 2013 at 10:30 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/305_

---

I'm not sure about what is done with fip people. If I got it well, they are incluced in the erf data as if there were "normal" people. But they're not. They don't live in the household. In particular that means they're not in the family. 

Example : 
  I'm a 6 years old child. I live with my mum, and I'm on my father'fiscal declaration. I'm once EE, once FIP. If you change my status and add me in the erf in my father household then I'm counted twice, and there is two allocation for me...

Everyone agree to change ?

**Comment by MattiSG** [comment]
Issue ayant plus de 4 ans, aucun consensus atteint, je ferme.
