### ISSUE TITLE
Some variables missing in https://legislation.openfisca.fr/variables 

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#590]
Some variables are missing in https://legislation.openfisca.fr/variables, even though they can be find in https://legislation.openfisca.fr/graph/ ! 

Example: 

`indemnites_journalieres`: Total des indemnités journalières
`allocation_aide_retour_emploi`: Allocation d'aide au retour à l'emploi
`ass`: Montant de l'ASS pour une famille
`ppa`: Prime Pour l'Activité

**Comment by cbenz** [comment]
@fpagnoux thanks! I'm gonna spend a day or two fixing several issues on Legislation Explorer, probably on monday and tuesday.

**Comment by benjello** [comment]
@fpagnoux @cbenz : seems fixed right ?
Please close it if done.

**Comment by fpagnoux** [comment]
👍
