### ISSUE TITLE
Utiliser un nom moins ambigu pour `allocation_aide_retour_emploi`

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#591]
We have both `chomage_net` and `allocation_aide_retour_emploi`. Isn't it the same thing ?

**Comment by benjello** [comment]
`allocation_aide_retour_emploi` c'est plutôt `chomage_brut`
Peut être que ce dernier est un peu plus vaste mais je ne sais pas précisément.
Et oui il faut en éliminer un (plutôt le premier) où faire le lien (inclure le premier dans le second mais on crée des variables qui ne servent un peu à rien).

**Comment by benjello** [comment]
@fpagnoux: tu en penses quoi ?

**Comment by fpagnoux** [comment]
Je penses aussi qu'il faudrait supprimer `allocation_aide_retour_emploi`, et indiquer dans `chomage_*` qu'il s'agit bien des ARE (ou plus si la définition est plus large).

**Comment by benjello** [comment]
Qui s'y colle ? ;-)

**Comment by fpagnoux** [comment]
Je vais m'en occuper.

**Comment by Morendil** [comment]
Je ferme après avoir [consolidé sur le wiki](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le).
