### ISSUE TITLE
Déplacer les variables liées au logement du Ménage vers la Famille ?

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#593]
Aujourd'hui, les variables liées au logement comme `loyer` ou `statut_occupation_logement` sont toutes déclarées pour l'entité Ménage.
Le raisonnement étant, je crois, qu'un ménage désigne des personnes qui vivent toutes sous le même toit, est donc que c'est l'entité "naturelle" pour décrire le logement.

Dans la pratique, je constate que ce choix, du moins côté prestation sociales, n'a que des inconvénients. Par exemple, parmi les formules qui utilisent ces variables (sur tout le périmètre openfisca-france), toutes **sans exception** castent leur valeur vers l'entité famille.

En pratique, cela ne facilite pas la contribution. Les entités sont un facteur de complexité pour les nouveau contributeurs. Introduire les idées de Familles et d'Individu est nécessaire pour coder les textes de lois, mais la différence entre une Famille et un Ménage est une subtilité conceptuellement non nécessaire pour la grande majorité des contributeurs, qui ont pourtant bien besoin d'accéder à des informations de bases telles que le loyer.

Je propose donc, dans la PR à venir sur le refactor de la gestion des entités, de migrer toutes les variables au logement vers l'entité Famille. Est-ce que ça vous paraît acceptable ? Est-ce qu'il me manque un élément qui pousserait vers le maintien dans l'entité Ménage ?

Merci ! 

@benjello @cbenz

**Comment by benjello** [comment]
Pour moi ce n'est pas acceptable. 

Une des spécificités d'openfisca est de gérer plusieurs entités pour faire des simulations de l'ensemble du système.

Je peux comprendre que des contributeurs qui ne s'intéressent qu'à des prestations sociales se concentrent sur le champ mais cela dégradera le logiciel. Ainsi, avec des données d'enquêtes nous utilisons l'entité ménage pour appariement afin de déterminer les loyers. 

Je pense que représenter fidèlement les ménages est important aussi pour les co-locations.

Par ailleurs France toute les stats publiques se font au niveau ménage, on ventile selon les loyers des ménages etc.

Enfin, la notion de famille est plus faible: chaque prestations à en fait un périmètre qui s'approche de notre famille mais qui est en fait différent (foyer social caf est différent du foyer social rsa). On gère cela comme on peut pour l'instant mais c'es un autre bonne raison pour ne pas faire de famille une unité trop centrale. La véritable avancée ce serait la génération des entités (famille ou foyer sociaux) adéquates pour les prestations sociales selon les conditions législatives.    

J'espère avoir été convaincant ;-)

**Comment by fpagnoux** [comment]
Je lis dans ce que tu dis que l'entité Ménage a une réelle utilité pour les données d'enquête ;).

Je comprends que la gestion multi-entité soit quelque chose d'important dans certains cas d'usages, mais c'est un problème si cela constitue un obstacle supplémentaire pour d'autres. Nous multiplions les partenariats locaux, et nous essayons de faire monter en compétences la MSA, qui va utiliser openfisca dans le Portail National des Droits Sociaux, pour qu'ils puissent par ailleurs gérer à terme l'évolution des prestations sociales. 

Nous ne pouvons pas multiplier les contraintes (en plus du calcul vectoriel), et juste leur expliquer qu'ils doivent maîtriser une complexe manipulation d'entité chaque fois qu'ils veulent simplement savoir si une personne est locataire.

Vu que deux cas d'usages ont des contraintes antagonistes, on a plusieurs solutions :
- Soit tout reste dans Ménages, et chaque personne qui veut calculer un loyer doit faire une conversion d'entité, ou recourir à des variables obscures type `loyer_famille`. C'est la situation actuelle, dont je souhaite sortir pour les citées plus haut.
- Soit on passe dans Familles, et c'est au cas d'usage "données d'enquête" de s'adapter en ajustant ses entrées. Je comprends que ce n'est pas acceptable pour vous.
- Soit on investit dans un point de flexibilité qui permet de concilier les deux. Ce n'est pas évident. Peut être qu'une variable doit être assignée à une entité et pas au tax benefit system, de sorte que l'on puisse calculer un loyer pour un individu, une famille ou un ménage indifféremment. Ça bouleverse pas mal de chose, mais ça fait longtemps que le modèle du namespace plat (une liste interminable de variables sans hiérarchie ni relations) montre ses limites aussi.

**Comment by benjello** [comment]
L'entité Ménage n'as pas qu'une utilité pour les données d'enquête en soi: c'est une entité bien définie qui sert à calculer des paramètres importants. En effet, le niveau de vie, la pauvreté se conçoit ua niveau du ménage. Et cela peut servir même au niveau du design des prestations.

Ceci dit, je suis ouvert à une many to many où le loyer peut être relié à plusieurs entité.
On pourrait alors facilement accéder à famille.loyer ou individus.loyer ou menage.loyer.
Et ouvert aussi à une révision du namespace plat.

Et je réitère mon warning: attention famille n'a pas une définition constante pour les différentes prestations.

Je vois que je ne suis pas très utile. Mais je suis ouvert aux propositions si cela ne casse pas des points structurants.

**Comment by cbenz** [comment]
Désolé, j'interviens sur un sujet alors que je ne pratique pas le côté métier. En revanche il rejoint les travaux sur l'API Python et son "ergonomie".

Pour ma part je pense qu'on peut, tout en conservant la distinction des entités, itérer à partir de l'API Python actuelle vers une API plus simple. 

Les variables de type conversion comme [`statut_occupation_logement_famille`](https://legislation.openfisca.fr/variables/statut_occupation_logement_famille) vont disparaître après https://github.com/openfisca/openfisca-core/pull/402 (je travaille activement dessus).

D'autre part je pense qu'il faut distinguer la définition des variables (qui reçoivent une entité correspondant à la législation) de l'utilisation des variables, où là il s'agit plutôt d'une question d'API et de responsabilité du moteur.

Quand je vois des appels comme [ici](https://github.com/openfisca/openfisca-france/blob/c8e702afc6fe2d55580f2a9fb70cfaf594404eb4/openfisca_france/model/prestations/minima_sociaux/rsa.py#L561-L563) je me dis que c'est simplifiable niveau API :

```python
        loyer_holder = simulation.compute('loyer', period)
        loyer = self.cast_from_entity_to_roles(loyer_holder)
        loyer = self.filter_role(loyer, role = CHEF)
```

@fpagnoux Ces exemples sont-ils représentatifs ?

**Comment by fpagnoux** [comment]
Oui, il est clair qu'il y a une première étape qui peut être atteinte en simplifiant la conversion d'une quantité d'une entité à une autre.
Mais conceptuellement, même avec une API claire, introduire l'idée de manipulation d'entité quand on veut juste le loyer payé par une famille, cela reste couteux.

**Comment by benjello** [comment]
@fpagnoux : peut-on fermer cette issue maintenant que la syntaxe est allégée ?

**Comment by MattiSG** [comment]
@fpagnoux #402 a-t-elle résolu ce problème pour toi ?

**Comment by fpagnoux** [comment]
Je ferme l'issue, le déplacement évoqué n'étant plus à l'ordre du jour, car pas acceptable pour les utilisateurs au profil économiste.
