### ISSUE TITLE
Multi-period entry in yaml tests

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#601]
Il would be nice to be able to several period to run tests which on variable values do not change accross different years like those appearing [here](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/tests/formulas/irpp.yaml).    

What do you think @cbenz @fpagnoux @laem @pnbt @edarin ?

**Comment by benjello** [comment]
Actually my example is badly chose. A better one is [here](https://github.com/openfisca/openfisca-tunisia/blob/master/openfisca_tunisia/tests/formulas/irpp.yaml) where the same case apply for many years.

But we should think about extending the irrp french tests

**Comment by MattiSG** [comment]
5 months old brainstorming which didn't get any feedback, and which is not specific to France.
If you have a use case for this, please open an RFC in openfisca/openfisca-core, that is an issue which presents your need, a rationale explaining how it would benefit the community as a whole, and a syntax proposition  :)
