### ISSUE TITLE
"autres" ?

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#604]
Bonjour,

A quoi sert "autres" dans "menages" ?

Merci,

**Comment by benjello** [comment]
Un ménage rassemble les individus vivant sous un même toit. Tous les individus ne sont pas forcément conjoint ou enfants de la personne de référence.

**Comment by VicBeto** [comment]
donc par exemple des grands parents, des colocs, etc. ?
Est-ce que un individu "autres" est considéré à charge ?

**Comment by benjello** [comment]
Pour être considéré "à charge", il faut renseigner le rôle dans famille et foyer fiscal.

**Comment by benjello** [comment]
@VicBeto je referme ce ticket, n'hésitez pas à le rouvrir si nécessaire.
