### ISSUE TITLE
Réparer la casa pour les retraités

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#607]
A corriger:
- [ ] [formule casa (gestion des parts](https://github.com/openfisca/openfisca-france/blob/361b60db0c08baf2daaafb1bfeeafeaed86fdadd/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py#L249) 
 - [ ]  [inclusion dans le calcul de la retraite nette](https://github.com/openfisca/openfisca-france/blob/361b60db0c08baf2daaafb1bfeeafeaed86fdadd/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py#L294)

**Comment by MattiSG** [comment]
Cette issue n'est pas actionnable et a plus de 5 mois. En l'absence de référence législative et de détails sur le problème rencontré, je ferme. Ne pas hésiter à rouvrir en ajoutant ces éléments :slightly_smiling_face:
