### ISSUE TITLE
Changement de label dans baremes-ipp

### ISSUE THREAD

**Issue by abozio** [openfisca/openfisca-france#608]
Les labels des paramètres de la décote [ont été modifié](https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-xlsx/commit/e78c20aefce3c82a03115654c921f143a7d87b51) car ils pointaient tous les deux vers le même noeud de l'arbre. 

@benjello: vérifie bien que cela soit répercuté sur la branche baremes-ipp.

**Comment by MattiSG** [comment]
La branche baremes-ipp a été intégrée dans #566 une semaine après l'ouverture de cette issue. Sans nouvelles depuis 5 mois, je suppose qu'il n'y a pas eu de problème associé.
