### ISSUE TITLE
entreprise_assujettie_is and class entreprise_assujettie_tva have strange default value

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#609]
It is set to False. A better default value would be True.
What do you think @laem ?

**Comment by laem** [comment]
Absolutely !
`entreprise_assujettie_tva` is a complicated matter, but False is definitely an exception.
It could even be a formula with the simple rule : if (entreprise_est_association_non_lucrative) then False.

**Comment by benjello** [comment]
Since it do not show up anywhere, I would like remove it completely.
Any objection @laem ?

**Comment by laem** [comment]
Honestly I don't know how to implement the link between assujettie_TVA and assujettie_taxe_salaires. And it's not a binary relation anyway so yes, entreprise_assujettie_tva is not really useful at the moment.

**Comment by laem** [comment]
No objection for this removal.

**Comment by benjello** [comment]
entreprise_assujettie_tva  removed by #635
