### ISSUE TITLE
revenus_locatifs et f4ba sont (presque) redondants

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#615]
Les revenus locatifs d'un individus sont également les revenus fonciers déclarés à la case 4ba de la déclarations d'impôt.
Or `f4ba` est utilisé pour calculer l'impôt et `revenus_locatifs` pour le RSA sans assurer de cohérence entre ces deux variables.

Dans une optique où les données proviennent des déclarations d'impôt, il pourrait être judicieux d'assigner la valeur de `f4ba` aux `revenus_locatifs` pour les seuls déclarants. Cela laisse aussi la liberté à l'utilisateur de forcer la valeur `revenus_locatifs` au niveau individuel.

Mais l'inverse se défend aussi. Il peut être plus naturel de mettre des revenus au niveau individuel puis agréger.

Enfin, `revenus_locatifs` devraient changé en `revenus_fonciers_individuel` ou assimilé.  

@fpagnoux qu'en penses-tu ?

**Comment by fpagnoux** [comment]
Oui, hélas on n'a pas de gestion de cohérence pour ces cas-là.

Je partirais plutôt sur la deuxième solution: utiliser comme inputs "naturels" les variables qui ont un un nom clair et une signification "du point de vue de la personne" plutôt que du point de vue du formulaire cerfa.

Qu'est-ce que les revenus fonciers comprennent en dehors des revenus locatifs ?

**Comment by benjello** [comment]
Si vous avez un correspondant à la CNAF, peut-être faudrait-il lui demander ce qu'ils considèrent être des revenus locatifs et quels justificatifs ils demandent ?

**Comment by fpagnoux** [comment]
Ils donnent des détails [en bas de la page 57](http://www.gisti.org/IMG/pdf/circ_2012-27-06_cnaf-suivi-legislatif-rsa.pdf).

**Comment by benjello** [comment]
Les déinitions pour les impôts [des revenus fonciers imposables](http://www2.impots.gouv.fr/documentation/2016/brochure_ir/files/assets/common/downloads/publication.pdf)

**Comment by Morendil** [comment]
Corrigée par #677
