### ISSUE TITLE
Location of reform cache helpers

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#617]
Shouldn't the reform helpers `get_cached_composed_reform` and `get_cached_reform` moved to a better place since they are not tax_benefit_system dependent and I use them for many different tax_benefit_system. 
I think of:
 - openfisca_france.reforms
 - openfisca_core.reforms (my favorite)

@cbenz @fpagnoux: comments and suggestions needed here !

**Comment by benjello** [comment]
@fpagnoux : j'aimerais régler aussi cela assez rapidement. Des suggestions sur la bonne pratique à adopter !
Merci !

**Comment by fpagnoux** [comment]
`openfisca_core.reforms` is ok for me.

**Comment by fpagnoux** [comment]
Si je comprends bien, ça sert à cacher un certain nombre de réformes pour un tax benefit system ? 

Je ne pense pas que le stocker en static dans `reform_by_full_key` soit super par contre.

**Comment by fpagnoux** [comment]
Par contre la fonction dépends de `reform_list` qui lui est associé à un `tax_benefit_system` particulier.

**Comment by benjello** [comment]
Oui, le but est de mutualiser la fonction qui se retrouve partout. Par contre je ne comprends pas les enjeux de ta première réserve. Si tu as le temps, je veux bien que tu éclaires ma lanterne. Merci.

**Comment by benjello** [comment]
En relisant à tête plus reposée, il ressort qu'il faut refactorer cela un peu plsu en profondeur.
Je ferai cela avec @cbenz dès qu'il aura un peu de temps.
Merci @fpagnoux .

**Comment by cbenz** [comment]
Cette fonction doit être considérée comme de la "cuisine" qui sert à accélérer les tests déjà longs en temps d'exécution.

Le fait de stocker dans `reform_by_full_key` est tolérable dans le contexte des tests unitaires, mais pas dans celui d'un module appartenant à France ou à Core.

Pour info 2 endroits stockent des réformes ainsi : `openfisca_france.tests.base` et `openfisca_web_api.model`.

@benjello Si tu souhaites utiliser cette technique ailleurs je t'invite à tester dans mettre en cache dans un premier temps, et uniquement si nécessaire à dupliquer les fonctions plutôt que capitaliser là-dessus.

**Comment by benjello** [comment]
@cbenz : j'ai besoin de réformes partout (indirectètaxation, tunisia etc) ;-)
Je ne comprends pas bien l'argument qui justifie de mettre les réformes en cache pour accélérer les tests 
mais estime que cela n'est pas nécessaires quand on utilise _vraiment_ les réformes.

**Comment by cbenz** [comment]
Je viens de relire mon post et m'aperçois d'une erreur de frappe qui modifie le sens de ma pensée. Je voulais dire :

@benjello Si tu souhaites utiliser cette technique ailleurs je t'invite à tester *~d~sans* mettre en cache dans un premier temps, et uniquement si nécessaire à dupliquer les fonctions plutôt que capitaliser là-dessus.

>  Je ne comprends pas bien l'argument qui justifie de mettre les réformes en cache pour accélérer les tests ...

C'est parce que beaucoup de tests utilisent la même réforme et que la recréer pour chacun serait coûteux. Après une rapide recherche pour les tests il faudrait utiliser les [fonctions nosetests d'initialisation de module](http://nose.readthedocs.io/en/latest/writing_tests.html#test-modules).

> ... mais estime que cela n'est pas nécessaires quand on utilise vraiment les réformes.

En effet ! Il te suffit d'oublier cette histoire de cache dans ton cas d'utilisation.
