### ISSUE TITLE
Increase SMIC value in 2017-01

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#636]
New value: 9,76

**Comment by fpagnoux** [comment]
No `legifrance` source yet. See [here](http://www.editions-tissot.fr/actualite/droit-du-travail-article.aspx?secteur=PME&id_art=8149&titre=Montant+du+SMIC+2017)

**Comment by laem** [comment]
https://www.service-public.fr/particuliers/actualites/A11216
https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=731576D53F2A8524C6E62A66679B7808.tpdila14v_2?idArticle=LEGIARTI000033709196&cidTexte=LEGITEXT000033709190&dateTexte=20170104
