### ISSUE TITLE
Activité d'un étudiant demandeur d'emploi

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#642]
Bonjour,

Quelles sont les variables qui doivent décrire un déclarant à la fois étudiant et demandeur d'emploi ou à la fois retraité et demandeur d'emploi ?

Je pense notamment à la variable "activite" qui ne peut prendre **qu'une valeur à la fois** parmi 
0 = Actif occupé
1 = Chômeur
2 = Étudiant, élève
3 = Retraité
4 = Autre inactif

**Comment by benjello** [comment]
Je ne suis pas sûr que l'on puisse être demandeur d'emploi inscrit à Pôle emploi et étudiant (sauf cas très particuliers de travail à temps partiel antérieur) et encore moins retraité et inscrit à Pôle emploi (aucun cas ne me vient à l'esprit).

Pourriez-vous me décrire les cas que vous avez en tête ?

Merci !

**Comment by VicBeto** [comment]
Je pense que vous avez raison. Après réflexion les cas que j'avais imaginé ne sont pas possible.
