### ISSUE TITLE
Use entities data to generate test case parsers dynamically

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#643]
The [`entities.py`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/entities.py) module contains data about entities and roles of persons. It should be the single source of truth for these data.

But at some other places roles are hard-coded like in the [test case validator](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/scenarios.py#L127) where we see `foyers_fiscaux = ` or `declarants =`, etc..

I think they could be generated dynamically, based on the `entities.py` data, then moved to the Core as they will become generic.

This could be useful for Tunisia and Senegal and reduce the boilerplate when initiating a new country.

I don't intend to start doing it for the moment, this issue is for the record.

**Comment by MattiSG** [comment]
This is a generic issue, moved to openfisca/openfisca-core#485.
