### ISSUE TITLE
Mettre à jour les valeurs des prestations sociales pour les DOM en 2017

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#647]
http://circulaires.legifrance.gouv.fr/pdf/2016/12/cir_41638.pdf

**Comment by MattiSG** [comment]
Contient les valeurs des DOM et Mayotte pour :

- [ ] `paje`
- [ ] `af`
- [ ] `paje_clca`
- [ ] `ars`
- Allocation journalière de présence parentale.

**Comment by Morendil** [comment]
Je ferme après consolidation [sur le wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
