### ISSUE TITLE
ppe_base devrait être une variable de Foyer et non d'Individu

### ISSUE THREAD

**Issue by eraviart** [openfisca/openfisca-france#65]
Actuellement la prestation ppe_base concerne les personnes alors qu'elle concerne les foyers fiscaux (crédit d'impôt individuel)

**Comment by maukoquiroga** [comment]
Hello @benjello et @eraviart, j'ai l'impression que ceci a déjà été résolu, mais dites moi si ce n'est pas le cas. Sinon, on peut fermer l'issue ?
