### ISSUE TITLE
Calcule de la PPA sur un an

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#650]
Bonjour à tous,

Pour le calcule de la PPA, j'obtiens une erreur 500 avec l'appel suivant : 
`{
  "scenarios": [
    {
      "test_case": {
        "familles": [
          {
            "parents": ["individu0"]
          }
        ],
        "foyers_fiscaux": [
          {
            "declarants": ["individu0"]
          }
        ],
        "individus": [
          {
            "id": "individu0",
            "date_naissance" : 1989,
            "statut_marital" : 2,
            "salaire_de_base" : 0
          }
        ],
        "menages": [
          {
            "personne_de_reference": "individu0",
            "depcom" : 93100,
            "loyer" : 600,
            "statut_occupation_logement" : 4
          }
        ]
      },
      "period": "2016"
    }
  ],
  "variables": ["ppa"]
}`

Savez-vous d'où pourrais venir l'erreur ?

Merci !

**Comment by fpagnoux** [comment]
Même problème que #649

**Comment by MattiSG** [comment]
Duplicate of #649.
