### ISSUE TITLE
Format des périodes et instants

### ISSUE THREAD

**Issue by VicBeto** [openfisca/openfisca-france#675]
Bonjour,

Nous avons dans les retours de simulations de l'api web des résultats de ce type : "month:2016" : 2500, year:2015-12 ou year=>2015-12. 

ex : 
`"aide_logement": {
                "month:2016": 2500,
                "2016-10": 230,
                "2016-12": 230
            },`

En allant regarder la [doc](https://doc.openfisca.fr/en/periodsinstants.html), nous n'avons pas trouvé la signification de ces syntaxes. 

Où pourrait-on trouver la liste des format de périodes et instants possibles et leur signification ?

D'avance merci pour votre retour,
A+

**Comment by benjello** [comment]
Bonjour @VicBeto, 

Je ne peux pas te répondre précisément côté API web mais côté Python tout est dans [openfisca_core.periods](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/periods.py).

 @fpagnoux ou @cbenz: pourriez-vous compléter ma réponse ? 

Bonne journée

**Comment by cbenz** [comment]
Je suis surpris par ces résultats.
Pouvez-vous joindre à cette issue le JSON complet d'appel à l'API ?

Merci !

**Comment by xtrembaker** [comment]
Bonjour,

Je travaille avec @VicBeto et je suis le développeur qui met en place l'API Openfisca 
Voici le JSON envoyé (avec les valeurs de retour) :

`{
	"apiVersion": 1,
	"method": "\/api\/1\/calculate",
	"params": {
		"intermediate_variables": false,
		"labels": true,
		"scenarios": [{
			"test_case": {
				"familles": [{
					"parents": ["13000000-0000-0000-0000-000000000001", "189c1317-84aa-4c4b-b742-0743ba6c09a7"],
					"enfants": [],
					"proprietaire_proche_famille": false,
					"aide_logement": {
						"2016-12": 230,
						"2016-10": 230,
						"2016-01:12": 2500
					},
					"id": 0
				}],
				"foyers_fiscaux": [{
					"declarants": ["13000000-0000-0000-0000-000000000001", "189c1317-84aa-4c4b-b742-0743ba6c09a7"],
					"personnes_a_charge": [],
					"id": 0
				}],
				"individus": [{
					"date_naissance": "1990-01-01",
					"id": "13000000-0000-0000-0000-000000000001",
					"handicap": false,
					"inapte_travail": false,
					"etudiant": true,
					"enfant_a_charge": false,
					"enfant_place": false,
					"tns_micro_entreprise_type_activite": null,
					"tns_auto_entrepreneur_type_activite": null,
					"tns_autres_revenus_type_activite": null,
					"tns_avec_employe": false,
					"salaire_de_base": {
						"2016-12": 1700,
						"2016-10": 1700,
						"2016-01:12": 20000
					}
				}, {
					"date_naissance": null,
					"id": "189c1317-84aa-4c4b-b742-0743ba6c09a7",
					"handicap": null,
					"inapte_travail": null,
					"etudiant": false,
					"enfant_a_charge": null,
					"enfant_place": false,
					"tns_micro_entreprise_type_activite": null,
					"tns_auto_entrepreneur_type_activite": null,
					"tns_autres_revenus_type_activite": null,
					"tns_avec_employe": null,
					"salaire_de_base": {
						"2016-12": 1700,
						"2016-10": 1700,
						"2016-01:12": 20000
					}
				}],
				"menages": [{
					"personne_de_reference": "13000000-0000-0000-0000-000000000001",
					"enfants": [],
					"statut_occupation_logement": 5,
					"loyer": 1000,
					"charges_locatives": 50,
					"depcom": "93061",
					"conjoint": "189c1317-84aa-4c4b-b742-0743ba6c09a7",
					"id": 0
				}]
			},
			"period": "2016-12"
		}],
		"variables": ["af", "cf", "asf", "paje", "rsa", "aide_logement", "als", "alf", "apl", "ppa", "aah", "asi", "acs", "cmu_c", "bourse_college", "bourse_lycee", "ass", "aspa"]
	},
	"suggestions": {
		"scenarios": [{
			"test_case": {
				"individus": {
					"13000000-0000-0000-0000-000000000001": {
						"statut_marital": "5"
					},
					"189c1317-84aa-4c4b-b742-0743ba6c09a7": {
						"statut_marital": "5",
						"date_naissance": "1976-01-01"
					}
				}
			}
		}]
	},
	"url": "http:\/\/api.openfisca.fr\/api\/1\/calculate",
	"value": [{
		"familles": [{
			"id": 0,
			"parents": ["13000000-0000-0000-0000-000000000001", "189c1317-84aa-4c4b-b742-0743ba6c09a7"],
			"proprietaire_proche_famille": false,
			"aide_logement": {
				"month:2016": 2500,
				"2016-10": 230,
				"2016-12": 230
			},
			"cmu_c": {
				"2016-12": false
			},
			"ass": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-10": 0,
				"2016-02": 0,
				"2016-12": 0,
				"2016-03": 0,
				"2016-08": 0,
				"2015-12": 0,
				"2016-09": 0,
				"2016-11": 0
			},
			"ppa": {
				"2016-12": 0
			},
			"bourse_college": {
				"2016-12": 0
			},
			"aspa": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": -0,
				"2016-06": -0,
				"2016-05": -0,
				"2016-04": -0,
				"2016-10": -0,
				"2016-02": 0,
				"2016-12": -0,
				"2016-03": 0,
				"2016-08": -0,
				"2015-12": 0,
				"2016-09": -0,
				"2016-11": -0
			},
			"af": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-10": 0,
				"2016-02": 0,
				"2016-12": 0,
				"2016-03": 0,
				"2016-08": 0,
				"2015-12": 0,
				"2016-09": 0,
				"2016-11": 0
			},
			"alf": {
				"2016-12": 0
			},
			"paje": {
				"2016-12": 0
			},
			"cf": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-10": 0,
				"2016-02": 0,
				"2016-12": 0,
				"2016-03": 0,
				"2016-08": 0,
				"2015-12": 0,
				"2016-09": 0,
				"2016-11": 0
			},
			"rsa": {
				"2016-09": 0,
				"2016-10": 0,
				"2016-11": 0,
				"2016-12": 0,
				"2016-08": 0
			},
			"acs": {
				"2016-12": 0
			},
			"asf": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-10": 0,
				"2016-02": 0,
				"2016-12": 0,
				"2016-03": 0,
				"2016-08": 0,
				"2015-12": 0,
				"2016-09": 0,
				"2016-11": 0
			},
			"apl": {
				"2016-11": 0,
				"2016-12": 0
			},
			"asi": {
				"2016-01": 0,
				"year:2015-12": 0,
				"2016-07": -0,
				"2016-06": -0,
				"2016-05": -0,
				"2016-04": -0,
				"2016-10": -0,
				"2016-02": 0,
				"2016-12": -0,
				"2016-03": 0,
				"2016-08": -0,
				"2015-12": 0,
				"2016-09": -0,
				"2016-11": -0
			},
			"bourse_lycee": {
				"2016-12": 0
			},
			"als": {
				"2016-11": 0,
				"2016-12": 0
			}
		}],
		"foyers_fiscaux": [{
			"id": 0,
			"declarants": ["13000000-0000-0000-0000-000000000001", "189c1317-84aa-4c4b-b742-0743ba6c09a7"]
		}],
		"individus": [{
			"id": "13000000-0000-0000-0000-000000000001",
			"inapte_travail": false,
			"salaire_de_base": {
				"2016-12": 1700,
				"2016-10": 1700,
				"month:2016": 20000
			},
			"enfant_place": false,
			"statut_marital": 5,
			"tns_avec_employe": false,
			"handicap": false,
			"etudiant": true,
			"enfant_a_charge": false,
			"date_naissance": "1990-01-01",
			"aah": {
				"year:2015-08": 0,
				"2016-01:3": 0,
				"year:2015-09": 0,
				"2016-04:3": 0,
				"year:2015-02": 0,
				"year:2015-03": 0,
				"year:2015-04": 0,
				"year:2015-05": 0,
				"year:2014-12": 0,
				"2015-11:3": 0,
				"2016-03:3": 0,
				"2016-05:3": 0,
				"2015-11": 0,
				"2015-10": 0,
				"2015-10:3": 0,
				"2015-12": 0,
				"2015-09:3": 0,
				"2015-12:3": 0,
				"2016-07:3": 0,
				"2016-06:3": 0,
				"2016-10": 0,
				"2016-11": 0,
				"2016-12": 0,
				"year:2015-12": 0,
				"2015": 0,
				"2015-06": 0,
				"2015-07": 0,
				"2015-04": 0,
				"2015-05": 0,
				"2015-02": 0,
				"2015-03": 0,
				"2015-01": 0,
				"2014-12": 0,
				"2016-09:3": 0,
				"year:2015-11": 0,
				"year:2015-10": 0,
				"2016-08:3": 0,
				"2015-08": 0,
				"2015-09": 0,
				"year:2015-06": 0,
				"year:2015-07": 0,
				"2016-02:3": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-03": 0,
				"2016-02": 0,
				"2016-01": 0,
				"2016-09": 0,
				"2016-08": 0
			}
		}, {
			"id": "189c1317-84aa-4c4b-b742-0743ba6c09a7",
			"salaire_de_base": {
				"2016-12": 1700,
				"2016-10": 1700,
				"month:2016": 20000
			},
			"enfant_place": false,
			"statut_marital": 5,
			"etudiant": false,
			"date_naissance": "1976-01-01",
			"aah": {
				"year:2015-08": 0,
				"2016-01:3": 0,
				"year:2015-09": 0,
				"2016-04:3": 0,
				"year:2015-02": 0,
				"year:2015-03": 0,
				"year:2015-04": 0,
				"year:2015-05": 0,
				"year:2014-12": 0,
				"2015-11:3": 0,
				"2016-03:3": 0,
				"2016-05:3": 0,
				"2015-11": 0,
				"2015-10": 0,
				"2015-10:3": 0,
				"2015-12": 0,
				"2015-09:3": 0,
				"2015-12:3": 0,
				"2016-07:3": 0,
				"2016-06:3": 0,
				"2016-10": 0,
				"2016-11": 0,
				"2016-12": 0,
				"year:2015-12": 0,
				"2015": 0,
				"2015-06": 0,
				"2015-07": 0,
				"2015-04": 0,
				"2015-05": 0,
				"2015-02": 0,
				"2015-03": 0,
				"2015-01": 0,
				"2014-12": 0,
				"2016-09:3": 0,
				"year:2015-11": 0,
				"year:2015-10": 0,
				"2016-08:3": 0,
				"2015-08": 0,
				"2015-09": 0,
				"year:2015-06": 0,
				"year:2015-07": 0,
				"2016-02:3": 0,
				"2016-07": 0,
				"2016-06": 0,
				"2016-05": 0,
				"2016-04": 0,
				"2016-03": 0,
				"2016-02": 0,
				"2016-01": 0,
				"2016-09": 0,
				"2016-08": 0
			}
		}],
		"menages": [{
			"id": 0,
			"personne_de_reference": "13000000-0000-0000-0000-000000000001",
			"conjoint": "189c1317-84aa-4c4b-b742-0743ba6c09a7",
			"depcom": "93061",
			"loyer": 1000,
			"statut_occupation_logement": 5,
			"charges_locatives": 50
		}]
	}]
}`

Comme vous pouvez le constater, il y a plusieurs formats de clé retournés pour les dates, et j'aurai besoin d'une liste exhaustives et des différentes signification (ex : Que signifie le format "month:2016" ?).

En vous remerciant par avance

**Comment by cbenz** [comment]
Merci pour votre complément d'information ! 👍 

Je reviens vers vous dès que j'ai pu trouver une réponse.

**Comment by MattiSG** [comment]
Il me semble que tout est documenté [ici](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/periods.py#L290-L332) et que les formats désignent :

- `AAAA` : les douze mois de `01/AAAA` à `12/AAAA`.
- `AAAA-MM` : le mois `MM/AAAA`.
- `month:AAAA` : le mois `01/AAAA`.
- `year:AAAA-MM` : les douze mois de `MM/AAAA` à `MM-1/AAAA+1`.

**Comment by VicBeto** [comment]
Merci pour votre réponse rapide et précise.

**Comment by MattiSG** [comment]
Je vous laisse vérifier mon interprétation et fermer l'issue si le comportement correspond bien — si je ferme l'issue moi-même vous ne pourrez pas la rouvrir.

**Comment by VicBeto** [comment]
bien noté merci

**Comment by MattiSG** [comment]
Bonjour @VicBeto, les informations que je vous avais données correspondent-elles bien à ce que vous avez observé ?

**Comment by xtrembaker** [comment]
Bonjour,

Je réponds à la place de @VicBeto puisqu'il ne fait plus partie de notre équipe.
Les informations que vous nous aviez données sont correctes et nous vous remercions encore pour votre aide.

**Comment by MattiSG** [comment]
Parfait, merci !
