### ISSUE TITLE
Améliorer le changelog

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#683]
J'ouvre cette issue suite à une discussion avec un utilisateur d'openfisca qui effectue des simulations de prestations sociales type mes-aides, via l'api, sans aujourd'hui contribuer.

En discutant avec lui, je me rends compte que le CHANGELOG de `openfisca-france` n'est compréhensible que par des contributeurs qui ont déjà une certaine vue d’ensemble de ce qu’il y a sur openfisca.

Pour les intéressé.e.s, voyons-nous une fois que @MattiSG  sera revenu, pour trouver des pistes d’améliorations.

Quelques idées que j’ai eu après la discussion :

- Ecrire le changelog en français, puisque c’est la langue de travail sur `openfisca-france`
- Taguer les changements, par exemple Aides-sociales, Impots, Cotisations
- Indiquer si les changements impactent la legislation d’aujourd’hui, ou l'historique

**Comment by laem** [comment]
Une difficulté, c'est que dans le monde du simulateur d'embauche, il y a les cotisations sociales, les réductions de cotisations sociales, mais aussi des impôts sur les entreprises qui sont prélevés à la source sur le travail, et puis les aides à l'embauche. La réforme de l'impôt sur le revenu à la source va normalement le rapprocher (en termes de fonctionnement) de tous ces thèmes, en donnant une partie de la responsabilité à l'entreprise. Comme la CSG, qui représente bien la porosité de ces catégories : 
> Sa nature ne fait pas consensus : selon les services du gouvernement et le Conseil constitutionnel, c'est un impôt. En revanche, la Cour de cassation (instance suprême de l'ordre judiciaire) depuis 2001 et le Conseil d'État (instance suprême de l'ordre administratif) depuis 2015, suivant les décisions de la Cour de justice de l'Union européenne (CJUE), en reconnaissent désormais la nature duale d'impôt et de cotisation sociale. :grin: 

[wikipedia](https://fr.wikipedia.org/wiki/Contribution_sociale_g%C3%A9n%C3%A9ralis%C3%A9e)

Bref, je ne sais pas comment conclure, même si je suis d'accord sur le besoin de catégoriser les changements. Peut-être une liste plus importante de catégories à combiner ? ex. `aide`, `impôt`, `individu`, `entreprise`, `cotisation sociale (inclus réduction de cotisation)`

Une question d'ordre général : `aides sociales` est à préférer à `prestations sociales` (cf. la page d'accueil) ?

**Comment by benjello** [comment]
Je pense que le mieux est d'utiliser l'arborescence du répertoire `model` à une profondeur raisonnable.
Donc soit garder prestations sociales, soit aller plus profond soit garder les deux niveaux. Distinguer cotisations sociales de contributions sociales, etc.

**Comment by pndsagora** [comment]
D'un point de vue opérationnel, les informations minimales qui devraient figurer dans le changelog sont les suivantes :
- La typologie de la modification apportée (correctif / évolution)
- La nature de la modification (technique / fonctionnelle)
- Le périmètre de la modification (prestations sociales, fiscalité, aides aux entreprises). A voir si l'arborescence du répertoire model convient à l'usage.
-  Le détail des impacts (compatibilité  autres modules,  modification des résultats, etc...)

**Comment by MattiSG** [comment]
Première série de changements à appliquer (de manière non rétroactive) :

- [ ] Documenter que le changelog est rédigé dans la langue du pays, comme les discussions dans les _issues_.
- [ ] Le format du changelog est adapté pour que les niveaux des titres correspondent aux niveaux des bumps de version.
- [ ] Un lien est systématiquement ajouté vers la PR introduisant le changement.
- [ ] Expliciter la stratégie de versionnement et les modalités de lecture du changelog (rassurer sur la quantité de versions).
- [ ] Introduire une typologie des modifications : `Évolution du système socio-fiscal` (amélioration d'un calcul, même s'il était faux auparavant ; impacte les réutilisateurs intéressés par les calculs), `Amélioration technique` (performance, installation, DSL… ; impacte les réutilisateurs rédigeant des règles et/ou déployant leur propre instance), `Correction d'un crash` (impacte tous les réutilisateurs), `Changement mineur` (refactoring, métadonnées… ; aucun impact sur les réutilisateurs).

**Comment by MattiSG** [comment]
Autre série de changements :

- [ ] Expliciter les corrections apportées d'un point de vue fonctionnel.
- [ ] Indiquer les périodes de calcul concernées par la modification.

**Comment by MattiSG** [comment]
## Exemples

> ## 12.0.6
> Fix `rsa_activite`

→

> #### 12.0.6 — [#673](https://github.com/openfisca/openfisca-france/pull/673)
> - Correction de crash.
> - Périodes concernées : 2011  - 2015.
> - Zones impactées : `prestations/minima_sociaux/anciens_ms`.
> - `rsa_activite` : toute tentative de calcul levait une exception.

- - - -

> ## 12.0.0
> - Use core test_runner for yaml tests
> - Return yearly amount for acs, bourse_college, bourse_lycee instead of artificially divide it by 12 (breaking change).

→

> ## 12.0.0 — [#664](https://github.com/openfisca/openfisca-france/pull/664)
> - Évolution du système socio-fiscal
> - Périodes concernées : toutes.
> - Zones impactées :
>     - `prestations/minima_sociaux/cmu`
>     - `prestations/education`
> - Ces variables renvoient désormais un montant annuel et non mensuel :
>     - `acs`
>     - `bourse_college`
>     - `bourse_lycee`
> - _Les valeurs mensuelles précédentes étaient obtenues par une division par 12 et non par un calcul réel._
> - - - -
> - Amélioration technique.
> - Déplacement du test runner depuis `france` vers `core`.
> - _Il devient possible d'exécuter `openfisca-run-test` sur un fichier YAML. [Plus d'informations](http://openfisca.readthedocs.io/en/latest/openfisca-run-test.html)._

- - - -

@pndsagora @scenaristeur @adrienpacifico qu'en pensez-vous ? Cette proposition de format répondrait-elle à vos besoins ?

**Comment by pndsagora** [comment]
Je dois reconnaître que c'est bien mieux, et à priori, ce semble couvrir le besoin. 
Peut-être faudrait-il être un peu plus disert sur la partie amélioration technique et spécifier les impacts si il y en a ? 
Par ailleurs, peut-on étendre le principe aux modules Core, Web-Api et Parsers. Mais en anglais du coup ?

**Comment by MattiSG** [comment]
> spécifier les impacts si il y en a ?
Tout à fait ! Le fait est que dans ce cas, il n'y en a pas, la modification est transparente  :)

> étendre le principe aux modules Core, Web-Api et Parsers
Nous allons déjà tester ce format sur `france`, puisque c'est là que le besoin est le plus pressant. Nous itérerons à cet endroit, et dès que le format aura convergé vers une mise en forme stable qui satisfait les besoins, nous étendrons effectivement l'approche.

**Comment by pndsagora** [comment]
Donc si pas d'impact, préciser Impact : aucun. Ce sera clair.
Ok pour attendre une stabilisation du format sur `france` avant d'étendre aux autres modules. 
En attendant cette généralisation, je préconise d'essayer malgré tout d'appliquer les principes de clarification au maximum quelque soit le module.

**Comment by fpagnoux** [comment]
Il est clair que l'enjeu de clarifier le changelog est commun à tous les modules. En revanche, les règles concrètes adoptées ici ne sont pas transposables (les autres packages ne sont pas un système socio-fiscal).

**Comment by fpagnoux** [comment]
Je prends de documenter les nouvelles règles et de les faire appliquer 👮

**Comment by MattiSG** [comment]
> Donc si pas d'impact, préciser Impact : aucun. Ce sera clair.

Cette information est déjà transmise par le numéro de version, par le biais de [semver](http://semver.org) :

- S’il s’agit d’un patch, il n’y a aucun impact sur l’API publique.
- S’il s’agit d’un changement de numéro de version mineur, il peut y avoir un ajout dans l’API, mais aucune perte de compatibilité avec l’existant.
- Seul un changement de numéro de version majeur peut signaler un impact avec perte de rétrocompatibilité.

Il est important de détailler l’impact quand il existe. Mais définir « Impact : aucun » me semble ambigu : il va être difficile d’indiquer qu’un changement n’a « aucun impact »… tout dépend de l’usage visé. Et si l’impact est nul sur l’API publique, alors cette information est redondante avec le numéro de version.

**Comment by MattiSG** [comment]
Fixed via #691.
