### ISSUE TITLE
Calcul aides sociales: impact allocation dans le revenu

### ISSUE THREAD

**Issue by Hakimelbaraka** [openfisca/openfisca-france#693]
Bonjour à tous,
je travail avec une équipe et utilisons openfisca pour calculer le droit aux aides sociales à l'instar de ce que fait le site https://mes-aides.gouv.fr/foyer/demandeur1
nous nous interrogeons sur l'obligation ou pas de fournir les allocations dans les revenus pour le calcul des aides

nous avons l'impression que le calculateur reprend ce qu'on lui donne en entrée. Exemple si j'indique avoir 400€ mensuel de RSA openfisca va me le redonner dans la liste de mes aides
si l'on ne renseigne pas d'allocation parmi les revenus, cela va t-il donner un résultat erroné?

Florian Pagnou dans une conversation indiquais que "openfisca prendra des valeurs par défaut pour toutes les variables d'entrée que vous ne lui fournirez pas". Pour continuer sur mon exemple si je ne précise pas que j'ai 400€ de RSA, openfisca va considérer que la variable est à 0 si j'ai bien compris
Dis autrement, les allocations dans les revenus ont elles un impact sur la fiabilité des résultats?
j'espère être clair :slight_smile:

merci d'avance de votre aide

**Comment by fpagnoux** [comment]
Bonjour Hakim,

Sur mes-aides, pour ne pas se placer en porte à faux vis à vis des administrations, nous avons choisi de ne jamais recalculer le montant des prestations que l'utilisateur déclare. Si quelqu'un déclare toucher 500€ de RSA au mois de février, nous considérerons dans nos calculs qu'il touchera aussi 500€ au mois de mars, et n'afficherons pas le RSA dans la page de résultats.

L'implémentation de ce choix est faite côté mes-aides, et ne devrait pas avoir d'impact côté OpenFisca. 

Côté OpenFisca, si par exemple vous fournissez la valeur du RSA pour février, et que vous demandez la valeur du RSA pour mars, a priori il devrait refaire le calcul et ne pas vous renvoyer ce que vous avez donné en entrée. Si vous constatez un comportement anormal, merci de nous indiquer les `openfisca-france` et de `openfisca-web-api` que vous utilisez, ainsi qu'un exemple de requête JSON permettant de mettre en évidence le problème.

Par contre, si vous fournissez la valeur du RSA pour février, et que vous demandez la valeur du RSA pour février, oui, c'est bien la même valeur qui vous sera retourné.

**Comment by fpagnoux** [comment]
>Florian Pagnou dans une conversation indiquais que "openfisca prendra des valeurs par défaut pour toutes les variables d'entrée que vous ne lui fournirez pas". Pour continuer sur mon exemple si je ne précise pas que j'ai 400€ de RSA, openfisca va considérer que la variable est à 0 si j'ai bien compris


Pas exactement. Lorsqu'OpenFisca a besoin d'une valeur, il va d'abord voir s'il est capable de la calculer, et sinon prendre une valeur par défaut. Comme il existe une formule permettant de calculer le RSA, si vous ne le déclarez pas en entrée, alors le moteur va le recalculer s'il en a besoin. Si vous ne souhaitez pas que ce calcul ait lieu, il faut forcer les valeurs à 0 en envoyant explicitement la valeur 0 pour le RSA pour les mois qui vous concernent.

>Dis autrement, les allocations dans les revenus ont elles un impact sur la fiabilité des résultats?
j'espère être clair :slight_smile:

Il y a quelques interactions  : par exemple, CMU-C automatique et abattement spécifique pour les aides logement si vous touchez le RSA. Mais si vous ne fournissez rien, par défault OpenFisca va tout calculer et prendre en compte ces interractions.

**Comment by Hakimelbaraka** [comment]
merci pour ces précisions Florian,
toutes ces règles sont elles disponibles quelque part?
Nous avons souhaitons simplifier le parcours de notre service pour le rendre plus "sexy" tout en conservant la fiabilité des résultats, un support nous serait bien utile.

**Comment by MattiSG** [comment]
OpenFisca est un logiciel libre et communautaire. Toutes les informations sont disponibles en ligne, sur la [documentation](https://doc.openfisca.fr) et par les échanges sur GitHub que nous sommes en train d'avoir  :wink:

Nous cherchons en permanence à améliorer la documentation, mais il s'agit d'un effort commun et collectif. Nous ne pouvons pas fournir de support spécifique à chaque cas d'usage.

Vous êtes très bienvenus pour améliorer cette documentation, que ce soit directement dans le code sous la forme de commentaires, ou dans le [guide](https://github.com/openfisca/openfisca-gitbook) au fur et à mesure de votre découverte d'OpenFisca  🙂

Si vous avez eu une réponse aux questions que vous vous posiez, je vous laisse fermer cette issue  😉

**Comment by Hakimelbaraka** [comment]
oui merci de votre aide
