### ISSUE TITLE
Retirer la variable age_en_mois

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#694]
Utiliser âge, l'âge en mois est ici une survivance d'un passé très lointain.

**Comment by Morendil** [comment]
Cela me semble délicat, la variable est utilisée en entrée dans de très nombreux cas de tests issus de Mes-Aides et elle fait également l'objet de certains calculs (notamment pour la PAJE) qui évaluent finement l'avancée d'une grossesse, ici par exemple:

https://github.com/openfisca/openfisca-france/blob/c07c7089a492a19fafd2420e749c9678ececd316/openfisca_france/model/prestations/prestations_familiales/paje.py#L310

Un `grep` sur cette variable renvoie environ 1000 lignes, je ne suis pas certain que le jeu en vaut la chandelle.

Cette issue étant elle-même une survivance d'un passé pas si récent, je me permets de la fermer en proposant de ne la réouvrir qu'à condition de disposer de la bande passante nécessaire à réaliser les ajustements qui en découlent.
