### ISSUE TITLE
Éclater la variable activite en une série de booléens

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#701]
La variable [`activite`](https://legislation.openfisca.fr/activite) rend mutuellement exclusifs des statuts qui ne le sont pas dans la réalité : je peux cumuler Étudiant et Chômeur, ou Chômeur et Actif, ou Étudiant et Retraité…

Y aurait-il une contre-indication à la remplacer par une série de booléens ?

**Comment by benjello** [comment]
Chômeur et actif _occupé_ en même temps je pense que ce n'est vraiment pas possible ;-)
Et étudiant ici veut parfois dire étudiant comme activité principale (donc inscrit à la sécurité sociale étudiante) donc pas chômeur.
Mais oui on peut la remplacer par une série de booléens.

Bref quelle est la limitation rencontrée pour déterminer l'action à mener ?

**Comment by MattiSG** [comment]
> Chômeur et actif occupé en même temps je pense que ce n'est vraiment pas possible ;-)

Intermittent du spectacle, ou cumul d'activité (auto-entrepreneur + ARE).

> quelle est la limitation rencontrée pour déterminer l'action à mener ?

Aucune si personne n'a de grosse alerte à lever à la transformation en une série de booléens  🙂

**Comment by benjello** [comment]
Je ne suis pas d'accord: actif occupé = tu travailles (peut-être pas assez etc mais tu travailles).
Chômeur: tu n'as pas d'emploi et tu recherches un travail.

Tu peux donc travailler (auto-entrepreneur) et toucher des droits acquis au titre de l'ARE.
L'intermittent, il ne peut pas travailler et ne pas travailler ne même temps.

Je suis pour limiter l'inflation des variables s'il n'existe pas un besoin clairement identifié.
Et cela affecterait mes codes avec données d'enquête.

**Comment by MattiSG** [comment]
La question est ce que représente « chômeur ». S'il s'agit d'être inscrit comme demandeur d'emploi, on peut l'être et travailler en même temps. Si cela signifie « tu n'as pas d'emploi et tu recherches un travail », il manque la définition « tu as un emploi et tu recherches un travail ».
De même, je peux être étudiant et auto-entrepreneur, ou étudiant et stagiaire, ou étudiant et salarié, ou retraité et auto-entrepreneur, etc.

Le besoin est clairement identifié : https://github.com/sgmap/mes-aides-ui/issues/107.

**Comment by Morendil** [comment]
En doublon avec #1067, je ferme maintenant que le lien est référencé.
