### ISSUE TITLE
Erreur dans calcul RSA

### ISSUE THREAD

**Issue by pndsagora** [openfisca/openfisca-france#711]
Bonjour @fpagnoux 
Ci-dessous, un cas de simulation basique (1 personne, pas d'enfant, pas de domicile stable).
Section ressources : 
![image](https://cloud.githubusercontent.com/assets/25485070/24151510/4ae09e78-0e49-11e7-9e3e-abba06f103f8.png)
Je décoche vous percevrez un salaire etc...
Résultat : 
![image](https://cloud.githubusercontent.com/assets/25485070/24151566/71429062-0e49-11e7-9d3e-fe6fed826871.png)
Avec 45K de revenus sur trois mois, je suis éligible à la CMU et au RSA ?

**Comment by fpagnoux** [comment]
Bonjour,

Je ne reproduis pas le problème : 
![image](https://cloud.githubusercontent.com/assets/11834997/24199845/686002be-0f0b-11e7-87dc-97ee2e7e1478.png)


Par ailleurs, merci de privilégier https://github.com/sgmap/mes-aides-ui/ pour les problèmes constatés sur mes-aides.gouv.fr ;)

**Comment by MattiSG** [comment]
Bonjour @pndsagora, et merci pour votre contribution.

Les problèmes liés au services mes-aides.gouv.fr peuvent être plus efficacement remontés par l'interface fournie par ce service. En fin de simulation, vous pouvez indiquer un écart de résultat constaté.

Par ailleurs, si vous effectuez ce test dans un cadre professionnel, n'hésitez pas à écrire un email à contribuer@mes-aides.gouv.fr pour demander un accès permettant de créer des tests sur https://mes-aides.gouv.fr/tests/.

Si vous souhaitez signaler un écart de résultat dans OpenFisca-France, n'hésitez pas à ouvrir une PR avec un cas de test au format de test standard YAML ou Python 🙂
