### ISSUE TITLE
Garantir la cohérence des dépendances sur la CI

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#712]
Le script `travis-change-branch.sh` apporte de l'insécurité sur la CI, puisque les dépendances installées ne correspondent pas nécessairement à ce qui est indiqué dans le code à cause des inférences de branches (cf.[ce build](https://travis-ci.org/openfisca/openfisca-france/builds/213156509)).
Supprimer cette inférence pour rendre le comportement plus déterministe.

- [x] Vérifier `parsers`.
- [x] Vérifier `web-api`.

**Comment by fpagnoux** [comment]
Je viens d'ouvrir la PR #713 pour france, et j'ai vérifié qu'il n'y avait rien côté parsers et api, c'est bon.

Par contre, il serait utile de documenter la manière avec laquelle on peut faire tourner un build sur `france` en se basant sur une branche particulière de `core`.

Je n'ai pas trouvé de moyen simple de le faire : je ne sais pas aujourd'hui comment configurer le `setup.py` de `france` pour que `pip` installe la version de `core` d'une branche particulière (sans repasser par le `requirements.txt` et modifier le `.travis.yml`).

**Comment by fpagnoux** [comment]
Ok, I found a solution and I'll document it :duck:
