### ISSUE TITLE
Erreur 500 à l'appel de l'API

### ISSUE THREAD

**Issue by xtrembaker** [openfisca/openfisca-france#716]
Bonsoir,

Depuis ce soir (environ 19h), notre appel à l'API retourne une erreur 500, quelque soit le payload.
Ex de payload:

```json
{
  "intermediate_variables": false,
  "labels": true,
  "scenarios": [
    {
      "test_case": {
        "familles": [
          {
            "parents": [
              "30000000-0000-0000-0000-000000000001"
            ],
            "enfants": [],
            "proprietaire_proche_famille": false
          }
        ],
        "foyers_fiscaux": [
          {
            "declarants": [
              "30000000-0000-0000-0000-000000000001"
            ],
            "personnes_a_charge": []
          }
        ],
        "individus": [
          {
            "date_naissance": null,
            "id": "30000000-0000-0000-0000-000000000001",
            "handicap": false,
            "inapte_travail": false,
            "etudiant": false,
            "enfant_a_charge": false,
            "enfant_place": false,
            "taux_incapacite": null,
            "scolarite": "0",
            "tns_micro_entreprise_type_activite": null,
            "tns_auto_entrepreneur_type_activite": null,
            "tns_autres_revenus_type_activite": null,
            "tns_avec_employe": false
          }
        ],
        "menages": [
          {
            "personne_de_reference": "30000000-0000-0000-0000-000000000001",
            "enfants": [],
            "statut_occupation_logement": null,
            "loyer": null,
            "charges_locatives": null,
            "depcom": null
          }
        ]
      },
      "period": "2017-02"
    }
  ],
  "variables": [
    "af",
    "cf",
    "asf",
    "paje",
    "rsa",
    "aide_logement",
    "ppa",
    "aah",
    "asi",
    "acs",
    "cmu_c",
    "bourse_college",
    "bourse_lycee",
    "ass",
    "aspa"
  ]
}

```

----

EDIT: reformattage

**Comment by cbenz** [comment]
@xtrembaker Cela correspond à une mise en production. Normalement vous devriez voir l'erreur, mais en fait ce n'est pas le cas.

Pour info voici ce que voit le client :

```json
{"error": {"message": "An internal server error occurred", "code": 500, "hint": "See the HTTP server log to see the exception traceback."}}
```

Dans les logs du serveur, je vois cela :

```
 Module weberror.errormiddleware:171 in __call__
>>  app_iter = self.application(environ, sr_checker)
Module webob.dec:131 in __call__
>>  resp = self.call_func(req, *args, **self.kwargs)
Module webob.dec:196 in call_func
>>  return self.func(req, *args, **kwargs)
Module openfisca_web_api.application:37 in set_application_url
>>  return req.get_response(app)
Module webob.request:1316 in send
>>  application, catch_exc_info=False)
Module webob.request:1280 in call_application
>>  app_iter = application(self.environ, start_response)
Module openfisca_web_api.urls:115 in router
>>  return app(req.environ, start_response)
Module webob.dec:131 in __call__
>>  resp = self.call_func(req, *args, **self.kwargs)
Module webob.dec:196 in call_func
>>  return self.func(req, *args, **kwargs)
Module openfisca_web_api.controllers.calculate:360 in api1_calculate
>>  base_simulations = calculate_simulations(scenarios, data['variables'], trace = trace_simulations)
Module openfisca_web_api.controllers.calculate:82 in calculate_simulations
>>  simulation = scenario.new_simulation(trace = trace)
Module openfisca_core.scenarios:378 in new_simulation
>>  self.fill_simulation(simulation)
Module openfisca_core.scenarios:188 in fill_simulation
>>  set_input(variable_name, variable_period, array)
Module openfisca_core.scenarios:102 in set_input
>>  holder.set_input(period, value)
Module openfisca_core.holders:254 in set_input
>>  self.formula.set_input(period, array)
Module openfisca_core.formulas:85 in set_input
>>  self.holder.put_in_cache(array, period)
Module openfisca_core.holders:269 in put_in_cache
>>  ).encode('utf-8'))
ValueError: Unable to set a value for variable enfant_a_charge for month-long period 2017-02. enfant_a_charge is only defined for years. Please adapt your input. If you are the maintainer of enfant_a_charge, you can consider adding it a set_input attribute to enable automatic period casting.
```

La dernière ligne vous montre que la variable `enfant_a_charge` a été appelée sur `2017-02` alors qu'elle est définie sur une année.

Cela correspond à la mise à jour majeure du Core, tel que vous pouvez le voir dans ce [CHANGELOG](https://github.com/openfisca/openfisca-core/blob/master/CHANGELOG.md), en particulier la version 6 dans ce cas.

Je vous invite à consulter également la documentation correspondante : https://doc.openfisca.fr/coding-the-legislation/35_periods.html

D'autre part, nous allons faire en sorte que l'erreur soit bien affichée dans le JSON retourné par l'API Web.

**Comment by cbenz** [comment]
Pour compléter ma réponse, j'attire votre attention que la période globale à votre simulation est `2017-02` et que vous avez dans les inputs de l'individu : `"enfant_a_charge": false,`

Par défaut la période de la simulation est utilisée.

Pouvez-vous essayer en spécifiant explicitement `"enfant_a_charge": {"2017:" false},` ?

**Comment by xtrembaker** [comment]
Merci beaucoup pour votre réponse rapide, nous allons effectuer la modification.
Ce qui m'inquiète c'est que celà soit arriver alors que tout fonctionnait bien avant, n'avez-vous pas de logique de versionning pour éviter ce genre de désagrément ? Pour le moment nous sommes en phase de développement, mais si ça nous arrive une fois notre application déployée, celà sera beaucoup plus embêtant...

**Comment by fpagnoux** [comment]
Bonjour @xtrembaker, et merci de nous avoir signalé ce problème.

> n'avez-vous pas de logique de versionning pour éviter ce genre de désagrément ?

OpenFisca est un produit qui évolue beaucoup en ce moment, y compris de manière non rétro-compatible. Nous avons une politique de [semantic versioning](http://semver.org/) stricte sur tous les packages pour nous prémunir de ce genre de désagrément.

En revanche, il n'y a aujourd'hui aucune garantie de stabilité sur l'API publique de démonstration `api.openfisca.fr`. Les ré-utilisateurs d'OpenFisca qui ont des applications en production ont aujourd'hui [leur propre instance d'OpenFisca](https://doc.openfisca.fr/openfisca-web-api/install_an_api_instance.html), et peuvent ainsi [garder le contrôle sur la version servie](https://github.com/sgmap/mes-aides-ui/blob/master/openfisca/requirements.txt).

> je ne comprends pas pourquoi dans certains cas il faut passer un objet en précisant l'année....

Il y a sans doute un effort de documentation à faire sur ce point. OpenFisca gère des situations qui évoluent dans le temps. Quand on déclare une variable en entrée, on le fait toujours pour une période précise. 

Si on ne précise pas de période, par exemple en envoyant `"enfant_a_charge": false`, alors c'est la période globale (ici `2017-02`) qui est retenue. Or `enfant_a_charge` est une variable aujourd'hui liée à la déclaration d'impôts, donc annuelle. Nous avons rendu récemment le moteur plus strict, et il refuse aujourd'hui que l'on assigne une valeur mensuelle à une variable annuelle. D'où la nécessité de préciser le `2017`.

La valeur par défaut et le type n'ont pas d'impact sur ceci. Quels qu'ils soient, la structure de la déclaration d'un input dans le JSON est toujours la même:

```JSON
nom_de_la_variable: {
  "2017-01": 1000,
  "2017-02": 1000,
  "2017-03": "..."
  }
```
La syntaxe :
```json
nom_de_la_variable: 1000
```

n'est qu'un raccourci pour 

```json
nom_de_la_variable: {"2017-02": 1000}
```

**Comment by fpagnoux** [comment]
Côté OpenFisca, améliorations à apporter :
- [ ] Documenter la non-garantie de stabilité sur l'API de démonstration
- [ ] Transmettre les exceptions retournées par le core à l'API
- [ ] Documenter plus en détails la construction du JSON ([cette page](https://doc.openfisca.fr/openfisca-web-api/json-data-structures.html) est pleine de TODOs et contient des [éléments obsolètes](https://doc.openfisca.fr/openfisca-web-api/json-data-structures.html#periods))

J'ouvre les issues

**Comment by xtrembaker** [comment]
Bonjour @fpagnoux ,

Merci pour votre réponse précise. Nous avions effectivement envisagé d'embarquer votre solution en interne, je pense qu'à présent il n'y a plus débat.
En tout cas nous avons corrigé de notre côté, tout semble être rentré dans l'ordre.

Merci encore pour votre réactivité à tous !

**Comment by MattiSG** [comment]
J'ai l'impression que la question a bien été traitée, il y a du travail de consolidation de documentation à faire, mais cette _issue_ semble avoir été résolue.

@xtrembaker n'hésite pas à en ouvrir de nouvelles en cas de difficultés. Tu peux également envoyer un mail à contact@openfisca.fr pour décrire ton projet plus en détails, cela nous aidera à bien comprendre les usages actuels de l'API  :)
