### ISSUE TITLE
Ajouter la référence sur la neutralisation du RSA

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#720]
https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000006906133&dateTexte=&categorieLien=cid

Il n'est tenu compte ni des ressources ayant le caractère de revenus professionnels ou en tenant lieu mentionnées à l'article R. 262-12, ni des allocations aux travailleurs involontairement privés d'emploi mentionnées par les articles L. 5422-1, L. 5423-1 et L. 5423-8 du code du travail, lorsqu'il est justifié que la perception de ces revenus est interrompue de manière certaine et que l'intéressé ne peut prétendre à un revenu de substitution.

**Comment by monbocal** [comment]
+1 - j'ai eu le cas deux fois cette semaine

**Comment by Morendil** [comment]
@fpagnoux @monbocal ça me semble une excellente idée mais je ne comprends pas de quoi vous parliez dans cette issue et je n'ai pas la moindre idée de l'endroit où il faudrait ajouter cette référence. Une piste ?

**Comment by fpagnoux** [comment]
J'imagine qu'on parlait ce [cette variable](https://fr.openfisca.org/legislation/aide_logement_neutralisation_rsa?q=rsa%20neutralisation), qui semble depuis avoir été proprement référencée.

**Comment by Morendil** [comment]
Nickel ! Je fermerais bien cette issue (c'est pas l'envie qui manque) mais une prudence peut-être excessive m'amène à noter que la référence que tu cites dans le commentaire ci-dessous ne fait pas partie des deux références associées à cette variable, et je ne la trouve nulle part dans le modèle.

Penses-tu toujours que la référence ci-dessus est pertinente ? Si oui à quelle variable suggères-tu de l'associer ? Si non, n'hésite pas à fermer l'issue.

**Comment by Morendil** [comment]
Apparemment c'est OK, je ferme.
