### ISSUE TITLE
Différence de résultat entre l'API et mes-aides.gouv.fr

### ISSUE THREAD

**Issue by skurty** [openfisca/openfisca-france#723]
Bonjour,

j'ai essayé votre API mais je n'arrive pas à avoir exactement le même résultat que le site mes-aides.gouv.fr. Voici les informations renseignées sur mes-aides.gouv.fr :

> Date de naissance : 11/11/1988
> Nationalité : Française
> 
> 1 enfant :
> Date de naissance : 10/11/2015
> Figure sur la dernière déclaration d'impôt sur le revenu : oui
> Pas scolarisé
> 
> Vis seul-e
> Depuis moins de 18 mois
> Locataire
> Pas de colocation
> Pas de lien de parenté
> Type logement : Non meublé
> Chambre : oui
> 
> Loyer hors charges : 400 €
> Charges : 100 €
> Code postal : 92000
> Commune : Nanterre
> Salaire (janvier) : 1500 €
> Salaire (février) : 1500 €
> Salaire (décembre) : 1500 €
> Salaire (depuis avril 2016) : 18000 €
> 
> Ressources de Lilo : non
> 
> Pensions alimentaires : non
> 
> Résultats :
> 
> Aides au logement : 50 € / mois
> Allocation de soutien familial : 100 € / mois
> Prestation d’accueil du jeune enfant – Allocation de base : 190 € / mois
> Prime d’activité : 80 € / mois

Voici ce que j'envoie à votre API :

URL : https://api.openfisca.fr/api/1/calculate
Body :

`{"intermediate_variables":false,"labels":true,"scenarios":[{"test_case":{"familles":[{"parents":["01"],"enfants":["02"],"rsa_isolement_recent":true}],"foyers_fiscaux":[{"declarants":["01"],"personnes_a_charge":["02"]}],"individus":[{"date_naissance":"1988-11-11","id":"01","salaire_net":{"2015-01:12":18000,"2016-03:12":15000,"2017-03":1500,"2017-02":1500,"2017-01":1500}},{"date_naissance":"2015-11-10","id":"02","enfant_a_charge":{"2017":true}}],"menages":[{"personne_de_reference":"01","enfants":["02"],"statut_occupation_logement":4,"loyer":400,"charges_locatives":100,"depcom":"92050","logement_chambre":true}]},"period":"2017-03"}],"variables":["af","cf","asf","paje","rsa","aide_logement","ppa","aah","asi","acs","cmu_c","bourse_college","bourse_lycee","ass","aspa"]}`

Je reçois les mêmes types d'aides mais avec un montant différent pour l'aide au logement avec un montant de 292.71 € au lieu de 80 €.

Est-ce un problème au niveau des paramètres de ma requête, de votre API ou du site mes-aides.gouv.fr ?

Merci d'avance pour votre aide

**Comment by skurty** [comment]
Bonjour,

après investigation, j'ai remarqué que l'aide au logement utilisait l'aide_logement_base_ressources (https://legislation.openfisca.fr/aide_logement_base_ressources) qui elle-même utilisait le salaire_imposable. Sachant que le salaire_net est calculé à partir du salaire_imposable, je comprends pourquoi les résultats différaient.

Si j'envoie le salaire_imposable, cela règle le problème.

Mais j'ai une autre question liée à la retraite avec le même problème : 
- le rsa utilise la retraite_nette (rsa -> rsa_montant -> rsa_fictif -> rsa_base_ressources -> rsa_base_ressources_individu -> retraite_nette)
- l'aspa utilise la retraite_brute (aspa -> asi_aspa_base_ressources -> asi_aspi_base_ressources_individu -> retraite_brute)
- si j'envoie uniquement la retraite_brute, la retraite_nette est calculée et donc différente, je suis donc obligé d'envoyer le même montant en retraite brute et nette, est-ce normal ou y a-t-il une autre solution ?

Merci

**Comment by MattiSG** [comment]
Re-bonjour @skurty !

En premier lieu, je tiens à rappeler que l'OpenFisca n'a pas pour rôle de garantir que tous ses réutilisateurs donnent des calculs équivalents.

J'ai donné la démarche générale de l'investigation dans #727.

En ce qui concerne les différences de bases ressources, il n'est pas choquant que la base ressource du RSA utilise les ressources nettes et que l'ASPA utilise les ressources brutes. À moins qu'une référence législative n'indique que l'une ou l'autre de ces bases ressources est erronée, je ne crois pas qu'il y ait de problème.

Je ferme donc cette issue. Nous la rouvrirons si une référence législative est fournie. Si j'ai mal compris le problème, ne pas hésiter à commenter à nouveau en le reformulant ! :)
