### ISSUE TITLE
Pas de RSA pour une femme enceinte de moins de 24 ans ?

### ISSUE THREAD

**Issue by skurty** [openfisca/openfisca-france#725]
Bonjour,

j'ai actuellement un cas avec une personne de moins de 24 ans, enceinte et sans revenu, n'a pas le droit au RSA alors que mes-aides.gouv.fr indique un RSA de 620 € / mois.

Voici les paramètres envoyés à Openfisca :

`{"intermediate_variables":false,"labels":true,"scenarios":[{"test_case":{"familles":[{"parents":["01"],"enfants":[],"proprietaire_proche_famille":false,"rsa_isolement_recent":null}],"foyers_fiscaux":[{"declarants":["01"],"personnes_a_charge":[]}],"individus":[{"date_naissance":"1996-10-10","id":"01","activite":"1","ass_eligibilite_individu":"0","enceinte":true, "salaire_net": 0}],"menages":[{"personne_de_reference":"01","enfants":[],"statut_occupation_logement":7,"loyer":200,"charges_locatives":50,"depcom":"91377","logement_chambre":false}]},"period":"2017-03"}],"variables":["rsa","aide_logement","cmu_c"]}`

L'API me répond avec une aide au logement et une couverture maladie universelle mais pas de RSA.

rsa_eligibilite est toujours faux et rsa_enfant_a_charge est égale à 0.

En parcourant la documentation, je ne trouve pas où est géré le cas d'une personne isolée, enceinte et agée de moins de 24 ans.

Quels sont les paramètres à envoyer à l'API qui sont nécessaire pour faire fonctionner ce cas d'utilisation ?

Merci d'avance

**Comment by MattiSG** [comment]
Duplicate of #727.
