### ISSUE TITLE
RSA et aides au logement différents de mes-aides.gouv.fr

### ISSUE THREAD

**Issue by skurty** [openfisca/openfisca-france#727]
Bonjour,

j'ai un cas d'utilisation où la personne n'a pas le même montant de RSA et d'aides au logement que le site mes-aides.gouv.fr :
- date de naissance : 11/11/1985
- française
- enceinte, étudiante, handicapée
- pas boursière
- handicap à moins de 50%
- pas d'enfant
- vit seule
- location non meublée
- chambre
- loyer : 400
- charges : 50
- code postal : 69580 (sathonay-village)
- aucun revenu ou aide

Voici les paramètres que j'envoie à l'API :

`{"intermediate_variables":false,"labels":true,"scenarios":[{"test_case":{"familles":[{"parents":["691aa862-94ce-4e20-9d26-7610bb379342"],"enfants":[],"proprietaire_proche_famille":false,"rsa_isolement_recent":null}],"foyers_fiscaux":[{"declarants":["691aa862-94ce-4e20-9d26-7610bb379342"],"personnes_a_charge":[]}],"individus":[{"date_naissance":"1985-11-11","id":"691aa862-94ce-4e20-9d26-7610bb379342","handicap":true,"inapte_travail":false,"etudiant":false,"enfant_a_charge":{"2017":false},"enfant_place":false,"taux_incapacite":0.3,"scolarite":"0","tns_micro_entreprise_type_activite":null,"tns_auto_entrepreneur_type_activite":null,"tns_autres_revenus_type_activite":null,"tns_avec_employe":false,"activite":"2","garde_alternee":false,"ass_eligibilite_individu":"0","enceinte":true}],"menages":[{"personne_de_reference":"691aa862-94ce-4e20-9d26-7610bb379342","enfants":[],"statut_occupation_logement":4,"loyer":400,"charges_locatives":50,"depcom":"69293","logement_chambre":true}]},"period":"2017-03"}],"variables":["aide_logement", "rsa", "rsa_montant", "rsa_socle"]}`

Résultats de l'API :
- aide au logement : 247€/mois
- rsa : 470€/mois
- cmuc

Résultats de mes-aides.gouv.fr :
- aides au logement : 230€/mois
- rsa : 620€/mois
- cmuc

J'ai vu que le socle (https://legislation.openfisca.fr/rsa_socle) utilisait un taux mais qu'il se basait uniquement sur le nombre de personnes (parents + enfants), je ne vois donc pas comment le RSA pourrait dépasser le socle qui est de 535.17 €/mois (https://legislation.openfisca.fr/prestations.minima_sociaux.rsa.montant_de_base_du_rsa).

Auriez-vous une solution pour le calcul du RSA et de l'aide au logement qui différe légèrement ?

Merci

**Comment by skurty** [comment]
J'ai également un cas d'utilisation où un utilisateur étudiant et retraité sans revenu ne devrait avoir droit qu'à 100€ d'aide au logement et a droit à 272 € pour ces aides ainsi qu'au RSA.

Voici sa situation :
- date de naissance : 11/08/1985
- français
- étudiant ou retraité
- pas boursier
- pas d'enfant
- vit seul
- location non meublée
- loyer : 480
- charges : 60
- code postal : 69580 (sathonay-village)
- aucun revenu ou aide

Résultats de l'API :
- aide au logement : 272€/mois
- RSA : 470€/mois
- cmuc

Résultats de mes-aides.gouv.fr :
- aides au logement : 100€/mois
- cmuc

Pour le RSA, voici les valeurs des différentes variables :
- rsa : 470
- rsa_montant : 470
- rsa_socle : 0 pour le mois actuel et 535 pour les autres
- rsa_eligibilite : false pour le mois actuel et true pour les autres

Avec ces variables, comment se fait-il qu'il y ait un RSA ? Et pourquoi l'aide au logement est-elle différente ?

Merci de votre aide

**Comment by MattiSG** [comment]
Bonjour @Skurty !

Deux possibilités me viennent à l'esprit :

1. Un encodage différent de la situation décrite sur mes-aides.gouv.fr en une simulation OpenFisca entre ce qui est fait par [`sgmap/mes-aides-api`](https://github.com/sgmap/mes-aides-api) et la transcription que tu en as faite.
2. Un écart de version entre celle d'OpenFisca-France utilisée sur sur Mes Aides et celle utilisée sur api.openfisca.fr. On peut voir celle de Mes Aides sur son [`requirements.txt`](https://github.com/sgmap/mes-aides-ui/blob/220b720c74a5badb167d016a304d718f4acf90ac/openfisca/requirements.txt#L3), et celle d'api.openfisca.fr est a priori aujourd'hui déployée en continu, donc devrait être la version [la plus récente](https://github.com/openfisca/openfisca-france/blob/64cf5583e07f5e2ec119270cbaed833739afdbad/CHANGELOG.md#1611---632).

- Pour éliminer la première hypothèse : d'où provient la donnée source que tu envoies à OpenFisca ?
- Pour tester la seconde hypothèse, le mieux serait que tu [installes OpenFisca](https://doc.openfisca.fr/for_users.html) manuellement en précisant le numéro de version d'OpenFisca-France que tu souhaites installer, et en le faisant correspondre à ceux utilisés par Mes Aides.

Enfin, pour ce qui est de ce qui semble être des erreurs de résultats, je te conseille de jeter un œil à https://mes-aides.gouv.fr/tests/ afin de voir si les erreurs que tu as trouvées ne sont pas déjà connues.
Si ce n'est pas le cas, tu peux soit contacter l'équipe Mes Aides pour rajouter des tests dans l'interface graphique citée ci-dessus, soit ouvrir une PR sur OpenFisca-France en [ajoutant les tests](https://doc.openfisca.fr/coding-the-legislation/writing_yaml_tests.html) correspondant aux situations que tu as décrites ([exemples](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/tests/mes-aides.gouv.fr)) :smiley:

**Comment by skurty** [comment]
Bonjour @MattiSG,

merci de ta réponse. J'ai donc installé [sgmap/mes-aides-ui](https://github.com/sgmap/mes-aides-ui) en local pour récupérer les informations envoyées à openfisca.

En comparant les paramètres envoyés, j'ai trouvé un premier problème avec la variable "enceinte".

De mon côté, j'envoie :
`"enceinte": true`
et mes-aides-api envoie :
`"enceinte":{"2017-04":true,"2017-03":true,"2017-02":true,"2017-01":true}`
Le résultat n'est pas le même et en utilisant ce second format, j'obtiens bien le même montant de RSA que mes-aides.

C'est le même problème pour [cette issue](https://github.com/openfisca/openfisca-france/issues/725)

**Comment by MattiSG** [comment]
Merci pour ces détails !

Je ne comprends pas exactement ce que tu entends par « régler le format de cette variable », mais je peux dire qu'il s'agit d'une instance du problème décrit dans #460. Ce problème sera définitivement résolu lorsque #460 sera traitée.

D'ici là, il faut utiliser la solution décrite sur https://doc.openfisca.fr/coding-the-legislation/inferences.html#with-basefunction et rendre explicite l'intégralité des valeurs nécessaires pour la simulation, comme le fait Mes Aides : le RSA dépend des trois mois précédant la date de simulation, il faut donc étendre les valeurs sur ces trois mois. Ce n'est pas lié à la variable d'entrée mais à la formule elle-même, et il faut donc le faire pour _toutes_ les valeurs utilisées par le RSA.

Si cela résout ton problème, merci de fermer cette issue  🙂  Sinon, n'hésite pas à revenir vers nous en détaillant le problème rencontré !

**Comment by MattiSG** [comment]
Pas de réponse en 10 jours, je suppose que le problème a été résolu. Si ce n'est pas le cas, merci de détailler le problème rencontré, on rouvrira l'issue :wink:
