### ISSUE TITLE
Réintégrer les tests générés automatiquement via le simulateur des impôts

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#734]
- [x] Tenter de faire passer tous les tests supprimés et réintégrer ceux qui sont au vert.
- [x] Passer sur CircleCI si la performance est un frein.
- [ ] Supprimer des tests par partionnement de l'espace des résultats si la performance est un frein.
- [x] Créer une branche contenant les tests ne passant pas pour faciliter le travail de correction associé.
- [ ] Supprimer les scripts de génération de tests non maintenus.

Fait suite à #730.

**Comment by fpagnoux** [comment]
This could be useful: https://github.com/dlanger/nose-parallel

**Comment by fpagnoux** [comment]
Circle says it can do it on its own though: https://circleci.com/docs/1.0/setting-up-parallelism/

**Comment by benjello** [comment]
Ping me if some tests are failing. May be a neat and quick fix can expand there life expectancy.

**Comment by fpagnoux** [comment]
J'ai fait passé pas mal de tests en mettant par défaut une marge d'erreur relative de `O.1%`. Il y a par contre beaucoup de tests qui ne passent pas parce qu'on retourne l'opposé du résultat attendu. Je pense a priori juste mettre des `-` dans les tests YAML.

**Comment by benjello** [comment]
Oui l'irpp est l'impôt payé par le foyer fiscal donc retiré aux ménages donc négatifs dans la convention openfisca.

**Comment by fpagnoux** [comment]
Après nettoyage, on a [4674 tests qui passent en 40 minutes](https://circleci.com/gh/openfisca/openfisca-france/44).

Les tests supprimés sont disponibles sur la branche `removed-tests`.
