### ISSUE TITLE
Vérifier le calcul de la PPA pour un micro-entrepreneur (données de test)

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#735]
Suite à un message depuis Mes Aides, pouvez-vous vérifier et éventuellement corriger le calcul d'éligibilité de la PPA pour un micro-entrepreneur ? Le point principal serait que le calcul se fait sur la moyenne des trois derniers mois et non mois par mois. Ci-joint le mail anonymisé avec les données de calcul de la Caf :

> en réponse à votre mail et après étude de votre dossier, je vous informe que vous n'ouvrez pas droit à la Prime d'Activité pour le trimestre d'Avril à Juin 2017 pour ressources supérieures au plafond.
> 
> Le calcul est fait en prenant compte des ressources perçues le trimestre précédent, soit en Janvier Février et Mars 2017.
> 
> Les ressources retenues sont:
> - les revenus non salariés de Monsieur : 1994.33 euros par mois (**ce montant correspond à la moyenne mensuelle des revenus de Monsieur** : 628+2339+3016=5983)
> - les revenus déclarés sur votre avis d'imposition 2016 (ressources 2015) en "autres revenus imposables" divisés par 12. Soit pour Monsieur 153 euros (459 /12 = 153) et pour Madame 3 euros (32 / 12 = 2.66)
> - les prestations familiales : 130.12 euros
> - un forfait logement est aussi retenu en fonction de la composition de votre foyer du fait que vous soyez propriétaires sans charge de remboursement de prêt. Pour une famille composée d'un couple avec 2 enfants le forfait est de 155.83 euros.

**Comment by Morendil** [comment]
> Le point principal serait que le calcul se fait sur la moyenne des trois derniers mois et non mois par mois

D'après ma compréhension de ce qu'on appelle "l'effet figé" qui est la règle de calcul de la PPA, c'est précisément l'inverse et la CAF a mal analysé cette situation. Je peux bien entendu me tromper sur ce point, n'hésite pas à réouvrir le cas échéant.
