### ISSUE TITLE
Supprimer le dossier Extensions

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#736]
Ce dossier est vide et d'ailleurs, une extension qui ferait partie du dépôt ne serait, par définition, pas une _extension_.
Le mécanisme de chargement par le dossier `extensions` était utile lorsque le packaging était déficient, car il permettait de cloner le dépôt `france` est de travailler à l'intérieur.
Maintenant qu'un import est simple à faire, ce mécanisme est déprécié.

- [ ] Retirer le dossier.
- [ ] Retirer le support du chargement automatique des extensions.

**Comment by Anna-Livia** [comment]
Dans openfisca-france/notebooks/getting-started.ipynb line 179 : 
« Import the extension corresponding to a reform of your concern. » 
—> A reformuler ? si oui, comment ?
