### ISSUE TITLE
Retirer le fichier model/datatrees

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#738]
Ces fichiers n'ont pas été modifiés (autrement que par du renommage de masse) depuis novembre 2014. Ils ne semblent pas utilisés.

Ils sont ajoutés comme attribut de classe au `tax_benefit_system`, mais cet attribut n'est pas utilisé par OpenFisca-Core.

@cbenz @eraviart savez-vous ce à quoi servent (ou ont servi) ces données ?

**Comment by benjello** [comment]
Ils servaient à formater l'interface de saisie des variables d'entrées dans l'UI.

**Comment by MattiSG** [comment]
D'après @cbenz sur Slack : 

> Le datatree servait à l'UI pour regrouper de façon logique les input widgets HTML correspondant aux input variables, dans des accordéons. Ce n'est pas la peine à mon avis de le conserver car il existe à présent un regroupement plus logique : les modules Python du sous répertoire "model". À l'époque les variables étaient moins bien triées dans des fichiers, c'est pour ça que datatrees avait été introduit.

**Comment by MattiSG** [comment]
- [ ] Supprimer le fichier.
- [ ] Supprimer le script qui le génère.
- [ ] Supprimer toutes les références.
