### ISSUE TITLE
Consolider l'import des barèmes IPP

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#740]
Les [barèmes IPP](http://www.ipp.eu/outils/baremes-ipp/) sont une source importante des paramètres d'OpenFisca-France aujourd'hui. L'import en est en partie automatisé, mais selon un processus éclaté dans plusieurs dépôts.

Ce processus doit être documenté et consolidé dans le dépôt OpenFisca-France, dans le dossier `openfisca_france/scripts/parameters/baremes_ipp/`. Les dépôts intermédiaires ne sont pas nécessaires, le seul dépôt dans lequel une écriture est faite sera `openfisca-france`.

**Comment by MattiSG** [comment]
Les erreurs de parsing sont rendues visibles lors de l'exécution, directement dans le terminal.

**Comment by cbenz** [comment]
Pour info les dépôts mentionnés dans la description de l'issue sont ici : https://framagit.org/french-tax-and-benefit-tables/

**Comment by cbenz** [comment]
Contrairement à ce qui est dit dans la description de cette issue, les dépôts intermédiaires sont nécessaires car utilisés dans un pipeline CI côté IPP, en production.

Je propose donc que:
- la partie qui concerne l'IPP (CSV taxipp) reste dans ces dépôts intermédiaires,
- et que la partie qui concerne OpenFisca seulement soit consolidée dans un seul répertoire comme indiqué.

**Comment by fpagnoux** [comment]
Merci pour l'update! C'est dommage, ça remet en question le coeur de l'issue.

On a deux choix :

- Soit on considère que notre source de donnée sont les YAML "cleans". Cela revient à laisser la responsabilité complète à l'IPP de la production de ces YAML, qui se situe hors du monde OpenFisca. L'inconvénient, c'est que ce pipeline a été construit par d'anciens (ou futurs anciens) membres de l'équipe OpenFisca. On a donc un risque sur la maintenance.
- Soit on considère que notre source est le XLS, et on internalise dans OpenFisca toute la chaîne. L'inconvénient c'est qu'on va dupliquer une bonne part de la chaîne de traitement.

Je n'ai pas encore d'avis tranché sur la question...


J'ai l'impression donc on considère que les fichiers "yaml clean" sont garantis être en cohérence aves

**Comment by MattiSG** [comment]
> Soit on considère que notre source est le XLS, et on internalise dans OpenFisca toute la chaîne.

C'était bien le sujet de cette issue.

Soit on internalise toute la chaîne, soit on l'externalise totalement, responsabilité à chaque contributeur de déverser ses mises à jour dans les paramètres. Vu que les barèmes IPP sont aujourd'hui la meilleure source disponible, il me semble pertinent de tenter l'internalisation. Cela implique bien entendu d'accompagner l'IPP à l'utilisation du système. La consolidation technique est une première étape.

**Comment by MattiSG** [comment]
Partir des fichiers Excel pour aboutir à la réécriture des fichiers `parameters/*.xml`. Cela génère un diff visible dans le dépôt local `openfisca-france`. Il y aura donc effacement de tous les paramètres qui sont définis dans OpenFisca mais pas dans les barèmes IPP. Documenter que la responsabilité revient au committer de faire le tri et de retirer les effacements inopportuns.
