### ISSUE TITLE
Unifier la déclaration des paramètres

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#741]
Follows #740 

Le fichier `param.xml` contient des déclarations de paramètres qui ne sont pas utilisées directement par OpenFisca-France, mais uniquement par les scripts d'import des barèmes IPP. Ce fichier est source de confusion, puisque le modifier n'a pas d'impact sur le système socio-fiscal.

Il faut donc le supprimer et permettre la modification des valeurs directement dans les fichiers du dossier `parameters`.

**Comment by MattiSG** [comment]
@fpagnoux cela a-t-il été traité par #746 ?

**Comment by cbenz** [comment]
Oui, la #746 supprime bien `param.xml`
