### ISSUE TITLE
Corriger le calcul du revenu disponible en corrigeant le calcul des salaires et des retraites nettes.

### ISSUE THREAD

**Issue by robert49** [openfisca/openfisca-france#743]
Bonjour @cbenz,
J'ai effectué ces derniers jours des simulations de revenus de base financés par la csg imposable et je me suis rendu compte que la variable "revenu_disponible" ne prend en compte la "csg_imposable_salaire" que jusqu'à un montant de salaire brut variable selon la configuration familiale (environ 3300 euros de salaire brut mensuel pour une personne seule sans enfant et environ 6700 euro pour un couple avec 3 enfants), selon une logique que je ne comprends pas. Par contre, au-delà de ce montant, la csg imposable n'est plus du tout prise en compte. Il semble donc que le calcul du revenu disponible se fasse actuellement sur la base de revenus (et retraites) imposables et non sur celle de revenus (et retraites) nets, ceux-ci étant calculés après déduction de la csg imposable (et de la crds).
Je tiens à préciser que, dans mes simulations, je supprime la csg déductible, mais cette option est sans effet sur l'anomalie constatée pour la csg imposable. 
J'ai donc modifié la classe "revenu_disponible" dans mon notebook, en prenant en compte pour son calcul  "csg_imposable_salaire",ainsi que "csg_imposable_retraite" et "crds" qui ne sont pas non plus prises en compte. Et cela fonctionne. Mes tests sont concluants.
Si je finance la réforme non par la csg imposable, mais par la csg déductible, et si je supprime la déductibilité de ce prélèvement, le problème est identique, et je dois intégrer la prise en compte de "csg_deductible_salaire" dans le calcul de "revenu_disponible", ce qui semble logique, puisque la csg déductible a alors le même effet que la csg imposable.
A l'occasion, je me pose la question de savoir s'il est bien normal que "revenu_disponible" ne prenne pas non plus en compte les allocations chômage perçues ni la "csg_imposable_chomage".
Si mon constat est correct, ne serait-il pas pertinent pour vous de modifier en conséquence la variable "revenu_disponible" dans openfisca_france ?
Merci d'avance et bonne journée.

**Comment by fpagnoux** [comment]
Bonjour @robert49,

Sur des questions de législation, je pense que @benjello sera plus à même de vous répondre :).

**Comment by benjello** [comment]
Cher @robert49, vous avez parfaitement raison, ce sont les revenus nets qui doivent entrer en compte.
Je vais régler cela très rapidement. Pourriez-vous me fournir un test qui me permettrait de valider mes corrections.

**Comment by robert49** [comment]
Bonjour @benjello,
Ce sera avec plaisir. Mais, pour ce test, y-a-t'il un formalisme particulier ? Une version simplifiée du notebook dans lequel j'ai constaté et rectifié cette anomalie serait-elle suffisante ?

**Comment by benjello** [comment]
@robert49 : ce serait un bon départ !

**Comment by robert49** [comment]
Bonjour @benjello 
Vous trouvrez le fichier ici : https://github.com/robert49/tests/blob/master/Test_rc_20_05_2017.ipynb
Bon week-end

**Comment by MattiSG** [comment]
@benjello as-tu eu l'occasion de regarder ce fichier ? 🙂

**Comment by benjello** [comment]
Oui mais corriger tout cela implique une plage de temps assez conséquente que je n'ai pas encore trouvée ...

**Comment by fpagnoux** [comment]
Il semble que cette issue soit plus une demande d'amélioration de la législation qu'un véritable ticket de support.

@benjello, comment est-ce que tu résumerais le problème soulevé ici en une phrase, que je renomme l'issue et change son status ?

**Comment by benjello** [comment]
Correction du calcul du revenu disponible en corrigeant le calcul des salaires et des retraites nettes.

**Comment by fpagnoux** [comment]
Merci !

**Comment by benjello** [comment]
@bfabre01 : c'est corrigé maintenant non ?
Si oui n'hésite pas à fermer.

**Comment by Morendil** [comment]
Vérification faite
- `revenu_disponible` tient compte des retraites via `pensions_nettes` et du salaire via `revenus_nets_du_travail`
- `pensions_nettes` tient bien compte du chomage via `chomage_net` et de la retraite via `retraite_nette`
- `chomage_net` tient bien compte de `csg_imposable_chomage`
- `retraite_nette` tient bien compte de `csg_imposable_retraite`
- `revenus_nets_du_travail` tient bien compte du `salaire_net`
- `salaire_net` tient bien compte de `csg_imposable_salaire`

Je ferme donc cette issue comme résolue.
