### ISSUE TITLE
Explorer l'arborescence des variables

### ISSUE THREAD

**Issue by robert49** [openfisca/openfisca-france#744]
Bonjour,

Comme je l'ai évoqué dans #743, les simulations de revenus de base que j'ai effectuées récemment m'ont permis d'identifier une apparente anomalie dans la classe `revenu_disponible`, identification qui m'a demandé de longues recherches, car j'avais beaucoup de mal à situer la variable `csg_imposable_salaires` dans la chaîne d'exécution du calcul.
Et je me suis dit qu'un outil permettant de visualiser l'arborescence des variables me serait, dans ce cas de figure, très utile.

Ne serait-il donc pas possible de mettre à notre disposition un programme générique qui, partant d'une variable, nous permettrait de visualiser l'ensemble des variables en relation avec elle, en quelque sorte un sous-ensemble du "graphe des formules socio-fiscales" disponible sur le site, comme cela existait pour "revenu_disponible" en 1ère page de "openfisca legislation" ?

Mais cet outil existe peut-être déjà.

Merci d'avance de l'attention que vous pourrez porter à cette question.

**Comment by MattiSG** [comment]
Bonjour @robert49 !

Merci de cette suggestion. L'explorateur de législation affichait effectivement jusqu'à récemment cette information. Nous l'avons supprimée car elle n'était que partielle, et donc potentiellement trompeuse (voir https://github.com/openfisca/legislation-explorer/issues/41).

L'explorateur de législation affiche le code source des formules. Cela fournit, certes de manière moins lisible aujourd'hui, l'information concernant les dépendances directes d'une formule. Votre retour sur ce sujet serait bienvenu : une coloration syntaxique qui mettrait en avant les noms des variables utilisées serait-elle suffisante pour permettre d'identifier ces dépendances ?

Le problème que vous décrivez semble néanmoins nécessiter plus qu'un parcours des dépendances directes, mais bien de pouvoir remonter le graphe.
Un outil statique tel que [ce graphe](https://www.openfisca.fr/tools/variables-graph) aurait-il permis d'y répondre, ou un outil qui permettrait de déterminer chaque étape intermédiaire du calcul vous aurait-il été plus utile ?

**Comment by robert49** [comment]
Bonjour @MattiSG,
Merci, pour votre retour.
Dans un certain nombre de cas, simples, la lecture du code source des formules est suffisante pour comprendre l'articulation entre les diverses variables. Et je ne suis pas certain qu'une coloration syntaxique du nom des variables utilisées serait suffisante, puisqu'il n'est possible de visualiser que le code d'une seule variable à la fois. Cette solution obligerait donc  à continuer à chercher dans le code des autres variables concernées.
Oui, ma recherche a à voir avec la remontée du graphe. J'imagine un sous-ensemble du graphe global de l'ensemble des variables dont vous avez joint le lien à votre post, qui permettrait de visualiser concrètement l'ensemble des variables reliées.
Mais, au-delà de l'identification des variables liées, il est bien évident, comme vous le suggérez, qu'un outil permettant de déterminer chaque étape intermédiaire d'un calcul donné serait très utile.
Merci à vous.

**Comment by MattiSG** [comment]
Très bien, c'est noté. Merci pour ces précisions et pour avoir pris le temps de décrire votre besoin.

Nous sommes bien conscients de l'importance d'un outil de ce type. Nous n'avons pas prévu d'y travailler dans l'immédiat, mais j'espère que nous aurons l'opportunité de nous en occuper dans les prochains mois. Nous notifierons dans cette _issue_ lorsque ce sera le cas.

**Comment by Morendil** [comment]
J'utilise beaucoup actuellement [cette représentation](https://gexf-js-dmrvejtrxv.now.sh/) produite grâce à un travail expérimental dans openfisca/openfisca-core#719 et une chaîne de traitement basée sur Gephi.

Une des difficultés que cela rencontre est que "un outil d'exploration" est beaucoup trop vague pour déterminer entièrement les choix techniques à opérer. Gephi répond à certains besoins mais absolument pas à tous, par exemple il ne permet pas de répondre à la question "montre-moi le lien entre revenu_disponible et csg_imposable_salaire", il serait peut-être plus judicieux, par exemple, pouvoir coder ce type de requêtes dans l'explorateur de législation. En parallèle avec ce besoin nous investissons actuellement dans l'amélioration du "traceur" mais je ne sais pas exactement ce que cela va produire.

Je préfère fermer cette issue dans la mesure où aucune résolution définitive n'est envisageable dans un avenir proche, elle relève plus de l'exploration du besoin; et qu'il me semble préférable de procéder, sur ce type de question qui reste très présente à l'esprit des mainteneurs d'OpenFisca France et Core, car proche de leurs propres besoins quotidiens, de façon plus incrémentale.
