### ISSUE TITLE
Comment modifier dynamiquement le nombre de tranches dans un barème ?

### ISSUE THREAD

**Issue by robert49** [openfisca/openfisca-france#745]
Dans #706, @fpagnoux m'a indiqué comment modifier les seuils et les taux des 5 tranches de l'IRPP, ce que j'ai réalisé, et qui fonctionne bien.
Cependant, je ne sais pas comment modifier le nombre de tranches lui-même.
Merci d'avance pour votre aide.

**Comment by cbenz** [comment]
Bonjour @robert49 

Il existe 2 manières de modifier les tranches d'un barème.

## Modifier la structure de données

Tu peux modifier la structure de données en Python comme indiqué dans la solution de @fpagnoux dont tu parles, mais de façon plus poussée.

Par exemple:

```python
bareme = reference_legislation_json_copy['children']['impot_revenu']['children']['bareme']
tranches = bareme['brackets']
deuxieme_tranche = tranches[1] 
seuil_deuxieme_tranche = deuxieme_tranche['threshold']
seuil_deuxieme_tranche_today = seuil_deuxieme_tranche[0]


# Je modifie le seuil de la deuxième tranche
seuil_deuxieme_tranche_today['value'] = 10000

# Suppression de la dernière tranche
del tranches[-1]

# Ajout d'une tranche
tranches.append({
    'thresholds': [{'start': '2012-01', 'value': 10000}],
    'rates': [{'start': '2012-01', 'value': 0.1}],
})
```

C'est pas sûr que ça fonctionne, il faut que je teste. Mais d'autre part c'est de la « petite cuisine », et je souhaite creuser les solutions suivantes, meilleures.

## Fournir un nouveau fragment Python

L'idée ici est de générer un barème à partir de zéro grâce à une fonction Python à laquelle on passerait les tranches ainsi que le chemin dans la législation auquel insérer le nouveau barème.

À explorer.

## Fournir un nouveau fragment XML

Cette solution me demande plus de temps car je n'ai pas d'exemple tout prêt à te montrer.

En gros l'idée est de copier-coller le nœud XML correspondant au barème, de le modifier à la main toujours en XML, et de le sauvegarder dans le répertoire de travail. Ensuite la réforme donne le nom du fichier à une fonction OpenFisca ainsi que le chemin XML auquel doit apparaître le nouveau nœud.

---

Je reviens vers toi quand j'ai expérimenté un peu plus.

**Comment by robert49** [comment]
Merci @cbenz pour ton retour.
Effectivement, la 1ère solution plante avec le message "ValueError: The modified legislation_json of the reform "ReformeRevenuDeBaseparCSG" is invalid: {"
suivi de nombreuses pages d'informations relatives à l'erreur.
Bon week-end

**Comment by cbenz** [comment]
Bonjour @robert49 

J'ai concocté un fichier contenant du code qui marche car cette fois-ci il est testé automatiquement.

Voici :
- [un barème nommé `social_security_contribution`](https://github.com/openfisca/country-template/blob/d64eea5d0e5dd748de8a4520c34e3de7a65a629f/openfisca_country_template/parameters/taxes.xml#L16-L49)
- [une réforme qui modifie les tranches d'un barème](https://github.com/openfisca/country-template/blob/d64eea5d0e5dd748de8a4520c34e3de7a65a629f/openfisca_country_template/reforms/modify_social_security_brackets.py)
- [des tests](https://github.com/openfisca/country-template/blob/d64eea5d0e5dd748de8a4520c34e3de7a65a629f/openfisca_country_template/tests/reforms/modify_social_security_brackets.yaml)

Tout ceci a été implémenté dans notre relativement nouveau pays factice : le [country-template](https://github.com/openfisca/country-template)

Si tu rencontres une difficulté dis-moi, et si tu as une erreur, pense bien à la donner en entier, car l'info utile n'est pas forcément dans les premières lignes.

Merci

**Comment by robert49** [comment]
Bonjour @cbenz 
J'ai appliqué ton code à 'impot_revenu'. Cela a été compliqué pour moi à tester, mais cela fonctionne bien, aussi bien pour l'augmentation d'un taux que pour la suppression et l'ajout d'une tranche. J'ai également testé avec les tranches et les taux du barème actuel, et cela colle.
Dans la mesure où une réforme contiendra bien évidemment d'autres modifications que celle du barème de l'impôt sur le revenu, j'ai inséré dans la 'def_apply' de la 
'class modify_impot_revenu_brackets(Reform)'  les suppressions de variables, ainsi que les mises à jour de variables. Et cela fonctionne bien.
Mais je n'arrive pas à faite fonctionner au sein de  cette nouvelle classe une augmentation du taux de la csg imposable par exemple, dont voici le code tel que je l'utilise dans un autre notebook  :

def modify_legislation_json(reference_legislation_json_copy):
    for value_json in reference_legislation_json_copy['children']['prelevements_sociaux']['children']['contributions']['children']['csg']['children']['activite']['children']['imposable']['children']['taux']['values']:
        value_json['value'] = csg_deduc_complem
    return reference_legislation_json_copy

Je te joins le code la nouvelle classe qui fonctionne bien pour 'impot_revenu' dans lequel je teste la suppression des tranches actuelles, puis leur remplacement par des mêmes tranches identiques, ainsi que l'ajout d'une 6ème tranche :

class modify_impot_revenu_brackets(Reform):
    # A reform always defines an `apply` method that builds the reformed tax and benefit system from the reference one.
    # See https://doc.openfisca.fr/coding-the-legislation/reforms.html#writing-a-reform
    def apply(self):
        # Our reform modifies the 'impot_revenu' parameter, which is a scale.
        # This parameter is declared in `taxes.xml` using a `<BAREME>` XML element, the French name for "scale".
        #
        # See https://doc.openfisca.fr/coding-the-legislation/legislation_parameters.html
        self.modify_legislation_json(modifier_function=self.modify_brackets)
        
        # Suppression de variables
        self.neutralize_variable('af')
        self.neutralize_variable('cf')
        self.neutralize_variable('ars')
        self.neutralize_variable('rsa_socle')
        self.neutralize_variable('ppa')
              
        # Mise à jour de variables
        for variable in [rdb, rdb_enf, credit_impot_monoparentales,revenu_disponible]:
            self.update_variable(variable)
 
    def modify_brackets(self, reference_legislation_json_copy):
        # This function takes an argument `reference_legislation_json_copy` which is a JSON-like representation
        # of the XML element. It can be modified and must be returned.

        # Access the right legislation node:
        scale = reference_legislation_json_copy['children']['impot_revenu']['children']['bareme']
        brackets = scale['brackets']

        # Add 0.1 to the rates of the second bracket, keeping the same thresholds:
    #    for rate in brackets[1]['rate']:
    #        rate['value'] += 0.9

        # Remove the first bracket : pour modifier un taux, il est nécesaire de supprimer la tranche, puis de la recréer 
        del brackets[0]
        del brackets[1]
        del brackets[2]
        del brackets[3]
        del brackets[4]
                    
        # Add a new bracket:
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0}],
            'threshold': [{'start': '2016-01-01', 'value': 0}]
            })
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0.14}],
            'threshold': [{'start': '2016-01-01', 'value': 9710}]
            })
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0.3}],
            'threshold': [{'start': '2016-01-01', 'value': 26818}]
            })
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0.41}],
            'threshold': [{'start': '2016-01-01', 'value': 71898}]
            })
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0.45}],
            'threshold': [{'start': '2016-01-01', 'value': 152260}]
            })
        brackets.append({
            'rate': [{'start': '2016-01-01', 'value': 0.55}],
            'threshold': [{'start': '2016-01-01', 'value': 250000}]
            })

        return reference_legislation_json_copy

Pour l'augmentation de la csg imposable, une solution pourrait être de créer une seconde réforme au sein du même notebook. Je l'ai testé et cela fonctionne, mais cela n'a pas de sens pour la définiion d'une variable devant agréger des montants modifiés de variables venant de ces 2 réformes, comme 'revenu_disponible' par exemple.

Merci d'avance pour ton aide.
Bonne journée.

**Comment by cbenz** [comment]
Bonjour @robert49 

Je ne suis pas sûr de comprendre la question, mais il me semble que tu peux faire les 2 modifications de la législation dans la fonction `modify_brackets` : après tous les `brackets.append` tu peux continuer par les lignes :

```python
    for value_json in reference_legislation_json_copy['children']['prelevements_sociaux']['children']['contributions']['children']['csg']['children']['activite']['children']['imposable']['children']['taux']['values']:
        value_json['value'] = csg_deduc_complem
```

et terminer par `return reference_legislation_json_copy`.

Cette fonction, du coup, peut s'appeler plutôt `modify_legislation` car elle ferait plus que modifier les *brackets*. Si tu la renommes pense à modifier :

```diff
-        self.modify_legislation_json(modifier_function=self.modify_brackets)
+        self.modify_legislation_json(modifier_function=self.modify_legislation)
```

Je ne vois pas l'intérêt de partir sur plusieurs réformes, pour l'instant. Tu peux envisager une réforme "revenu de base" qui exprime toutes les modifications. Bien sûr tu peux factoriser ton code en fonctions ou méthodes de la classe réforme, pour morceller le traitement.

Cette issue portant sur la modification dynamique des tranches du barème, si spécifiquement ce problème est résolu pour toi, je t'invite à fermer l'issue, quitte à continuer sur une nouvelle issue en disant qu'elle suit celle-ci (en mettant #745 dans la description, le lien se fera tout seul) :smiley:

**Comment by robert49** [comment]
Bonjour @cbenz 
De cette manière, cela fonctionne parfaitement.
En fait, comme je ne ne parvenais pas à englober l'ensemble des modifications dans le même code, mon intention était de contourner le problème en créant 2 réformes dans le même notebook, ce qui bien évidemment aurait posé problème pour une variable "transversale" comme 'revenu_disponible'. 
Je procède donc à la fermeture de cette issue.
Merci infiniment.
Bien à toi.

**Comment by cbenz** [comment]
Ah oui je comprends maintenant :smile: 

J'étais ravi de pouvoir t'aider.

Aujourd'hui était mon dernier jour dans l'équipe "noyau" OpenFisca ! Je pars vers d'autres aventures mais je continuerai de suivre le projet OpenFisca.

À bientôt d'une manière ou d'une autre :grinning:

**Comment by robert49** [comment]
Je regrette ton départ, @cbenz 
Notre communication se fait essentiellement par le web et en fait nous nous connaissons très peu, mais je dois dire que j'ai beaucoup apprécié ton aide dans ma démarche de découverte d'Openfisca.
Quoi qu'il en soit, je te souhaite une pleine réussite dans tes futures fonctions.
Bien à toi.
