### ISSUE TITLE
Supprimer les valeurs dupliquées des taux ASF

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#748]
https://legislation.openfisca.fr/?q=asf#search-input

# Taux plein
- prestations.prestations_familiales.asf.montant_de_l_asf_dans_le_calcul_du_rsa_et_de_la_ppa_en_de_la_bmaf.orphelin_ou_assimile_d_un_seul_parent
- prestations.prestations_familiales.asf.taux_1_parent
- prestations.minima_sociaux.rmi.forfait_asf.taux1
- prestations.minima_sociaux.rsa.forfait_asf.taux1

# Taux partiel
- prestations.prestations_familiales.asf.montant_de_l_asf_dans_le_calcul_du_rsa_et_de_la_ppa_en_de_la_bmaf.orphelin_ou_assimile_des_deux_parents
- prestations.prestations_familiales.asf.taux_2_parents
- prestations.minima_sociaux.rmi.forfait_asf.taux2
- prestations.minima_sociaux.rsa.forfait_asf.taux2

A priori, seul `prestations.prestations_familiales.asf.taux_1_parent` est utilisé.

Dans le cadre de la mise à jour des taux, je ne vais modifié que :
- prestations.prestations_familiales.asf.taux_1_parent
- prestations.prestations_familiales.asf.taux_2_parents

**Comment by Morendil** [comment]
Je ferme en faveur de #1164
