### ISSUE TITLE
Documenter l'utilisation des nouvelles entités (famille)

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#756]
Les holders semblent disparaitre des nouvelles formules au profit d'une notation `entity("formula", period)` , comme [ici](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/rsa.py#L44) par exemple.

Y a-t-il un endroit ou l'on peut voir comment les utiliser ? Que fait famille.member("variable_individuelle", period) comparé à un simulation.calculate ? 

Ce message d'erreur est-il normal ?

```python 
Exception: Variable rsa is not defined for famille but for famille
```

<details><summary>Detail</summary><p>

```python

from openfisca_france.model.base import Famille
famille = Famille(simulation)
famille("rsa","2012")
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-25-7ee0fbf8cfef> in <module>()
----> 1 famille("rsa","2012")

/home/adrien/.local/lib/python2.7/site-packages/openfisca_core/entities.pyc in __call__(self, variable_name, period, options, **parameters)
     53 
     54     def __call__(self, variable_name, period, options = [], **parameters):
---> 55         self.check_variable_defined_for_entity(variable_name)
     56 
     57         if ADD in options and DIVIDE in options:

/home/adrien/.local/lib/python2.7/site-packages/openfisca_core/entities.pyc in check_variable_defined_for_entity(self, variable_name)
     41             raise Exception(
     42                 "Variable {} is not defined for {} but for {}".format(
---> 43                     variable_name, self.key, variable_entity.key)
     44                 )
     45 

Exception: Variable rsa is not defined for famille but for famille
```

</p></details>

Merci d'avance pour votre aide !

**Comment by fpagnoux** [comment]
> Y a-t-il un endroit ou l'on peut voir comment les utiliser ? Que fait famille.member("variable_individuelle", period) comparé à un simulation.calculate ?

Tu peux regarder la [doc sur la syntaxe des formules](https://doc.openfisca.fr/coding-the-legislation/10_basic_example.html).

Ce message d'erreur n'est pas normal. Dans quel contexte d'exécution est-ce qu'il est apparu ?

**Comment by fpagnoux** [comment]
Je viens de voir les détails.

Peux-tu essayer de remplacer `famille = Famille(simulation)` par `famille = simulation.famille` ?

**Comment by fpagnoux** [comment]
Bonjour @adrienpacifico,

Est-ce que le fix proposé fonctionne ?

**Comment by MattiSG** [comment]
En l'absence de réponse en deux semaines, je considère que la solution proposée par @fpagnoux a résolu le problème. Si ce n'est pas le cas, ne pas hésiter à commenter à nouveau sur cette issue ou à en ouvrir une nouvelle 🙂
