### ISSUE TITLE
Error 502 : Bad gateway

### ISSUE THREAD

**Issue by xtrembaker** [openfisca/openfisca-france#758]
Bonjour, 

Nous avons actuellement un problème avec un call API qui fonctionnait bien jusqu'à présent :
- url : https://api.openfisca.fr/api/1/calculate
- Method : POST
- Body : 
`{"intermediate_variables":false,"labels":true,"scenarios":[{"test_case":{"familles":[{"parents":["30000000-0000-0000-0000-000000000001"],"enfants":[],"proprietaire_proche_famille":false,"rsa_isolement_recent":null}],"foyers_fiscaux":[{"declarants":["30000000-0000-0000-0000-000000000001"],"personnes_a_charge":[]}],"individus":[{"id":"30000000-0000-0000-0000-000000000001","tns_micro_entreprise_type_activite":null,"tns_auto_entrepreneur_type_activite":null,"tns_autres_revenus_type_activite":null,"tns_avec_employe":false,"enfant_a_charge":{"2017":false},"date_naissance":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"handicap":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"inapte_travail":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"etudiant":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"enfant_place":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"taux_incapacite":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"scolarite":{"2017-04":"0","2017-03":"0","2017-02":"0","2017-01":"0"},"activite":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"garde_alternee":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"ass_precondition_remplie":{"2017-04":"0","2017-03":"0","2017-02":"0","2017-01":"0"},"enceinte":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"boursier":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false}}],"menages":[{"personne_de_reference":"30000000-0000-0000-0000-000000000001","enfants":[],"statut_occupation_logement":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"loyer":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"charges_locatives":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"depcom":{"2017-04":null,"2017-03":null,"2017-02":null,"2017-01":null},"coloc":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false},"logement_chambre":{"2017-04":false,"2017-03":false,"2017-02":false,"2017-01":false}}]},"period":"2017-04"}],"variables":["af","cf","asf","paje","rsa","aide_logement","ppa","aah","asi","acs","cmu_c","bourse_college","bourse_lycee","ass","aspa"]}`

Le serveur nous retourne :
```<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>```

Merci de revenir vers nous au plus vite

**Comment by Anna-Livia** [comment]
Bonjour xtrembaker,

Merci pour ce signalement, nous regardons cela tout de suite et nous corrigeons aussi vite que possible.

Bonne journée,

Anna-Livia

**Comment by fpagnoux** [comment]
Ça devrait être rentré dans l'ordre.

J'ai juste desinstallé puis réinstallé `openfisca_web_api` sur le serveur de prod. L'origine du problème n'est pas claire.

**Comment by cbenz** [comment]
Je ferme l'issue car j'ai vérifié que l'API tournait correctement. @xtrembaker n'hésitez pas à rouvrir si cela se reproduit. Il y a un léger risque tant que nous n'avons pas compris exactement l'origine du problème.
