### ISSUE TITLE
Incohérence RSA

### ISSUE THREAD

**Issue by jdesboeufs** [openfisca/openfisca-france#76]
Bonjour,

Je viens de repérer une incohérence (a priori apparue après le Hackathon de vendredi).
Voici la simulation : 

``` json
{
    "scenarios": [
        {
            "test_case": {
                "familles": [
                    {
                        "parents": [
                            "ind0"
                        ]
                    }
                ],
                "foyers_fiscaux": [
                    {
                        "declarants": [
                            "ind0"
                        ]
                    }
                ],
                "individus": [
                    {
                        "activite": "Actif occupé",
                        "birth": "1989-01-01",
                        "id": "ind0",
                        "sali": 60000,
                        "statmarit": "Pacsé"
                    },
                    {
                        "activite": "Actif occupé",
                        "birth": "1989-01-01",
                        "id": "ind1",
                        "sali": 0,
                        "statmarit": "Pacsé"
                    }
                ],
                "menages": [
                    {
                        "personne_de_reference": "ind0",
                        "so": "Locataire ou sous-locataire d'un logement loué vide non-HLM",
                        "loyer": 1300
                    }
                ]
            },
            "legislation_url": "http://openfisca.fr/api/1/default-legislation",
            "year": 2013
        }
    ]
}
```

En tout logique ce ménage n'a pas droit au RSA étant donné les rémunérations élevées de l'individu 0. Pourtant il a droit au RSA socle dans la réponse.

Y-a-t'il une erreur dans ma requête ?

**Comment by scenaristeur** [comment]
Bonjour, j'aimerais utiliser la web-api d'openfisca, pour simuler 3 situations et comparer les prestations auxquelles ces situations donnent droit : 
- un couple marié avec 4 enfants (avant séparation)
- le parent 1 avec les enfants après séparation
- le parent 2 sans les enfants après séparation

mais je ne parvient pas à construire mon json : dois-je faire 3 JSON (1 par situation) et 3 requetes ou puis-je faire 1 seul JSON avec des scenarios différents ? ou des test_case différents ? des foyers différents ? des familles différents ???...

quelle tête doit avoir mon JSON... 
Merci
