### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by cougil** [openfisca/openfisca-france#764]
Hi!

I'm trying to install Openfisca, but unfortunately I'm not able to do it.

After following [the instructions](https://doc.openfisca.fr/for_developers.html) and running the command `pip install --editable .` the installation failed trying to download some dependencies:
```
Collecting Biryani[datetimeconv]>=0.10.4 (from OpenFisca-France==18.2.6)
  Using cached Biryani-0.10.4.tar.gz
Collecting numpy>=1.11 (from OpenFisca-France==18.2.6)
  Using cached numpy-1.12.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6)
  Could not find a version that satisfies the requirement OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6) (from versions: )
No matching distribution found for OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6)
```
How we can solve that?

Best,

**Comment by guillett** [comment]
Thanks a lot @cougil for your feedback, we are striving to improve OpenFisca usability.

I guess that your issue comes from the fact that OpenFisca currently requires Python 2.
I created an issue to improve the documentation https://github.com/openfisca/openfisca-doc/issues/73.

If you create your `virtualenv` using that command `virtualenv --python=python2` you should be able to install OpenFisca.

Let us know if that solves your issue.

Thanks again for your message.

**Comment by cougil** [comment]
Hi @guillett 

I've checked and I've python 2.7.10 installed (Mac OS X El Capitan), but may be it was not setup via `virtualenv`. I tried to create my environment with the mentioned command and it didn't work:
```
$ virtualenv --python=python2
The path python2 (from --python=python2) does not exist
```
What I tried later is just following the instructions that came from [virtualenv](https://virtualenv.pypa.io/en/latest/userguide/), I created a new environment, activated and verified that I have installed correctly Python v 3.4.2:
```
$ virtualenv test
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in /.../test/bin/python3.4
Also creating executable in /.../test/bin/python
Installing setuptools, pip, wheel...done.
$
$ source ~/.virtualenv/test/bin/activate
$ python -V
Python 3.4.2
```

But unfortunately, after trying to run the installer (`pip install --editable . `) again, it fails with the same error:

```
Obtaining file:///.../openfisca/openfisca-france
Collecting Biryani[datetimeconv]>=0.10.4 (from OpenFisca-France==18.2.6)
  Using cached Biryani-0.10.4.tar.gz
Collecting numpy>=1.11 (from OpenFisca-France==18.2.6)
  Using cached numpy-1.12.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6)
  Could not find a version that satisfies the requirement OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6) (from versions: )
No matching distribution found for OpenFisca-Core<13.0,>=12.1.1 (from OpenFisca-France==18.2.6)
```

So, what I'm doing wrong?

**Comment by guillett** [comment]
@cougil, you are pretty much set up!

The recommended command was not the correct one, [the idea is to create a `virtualenv` with the appropriate python version](https://virtualenv.pypa.io/en/latest/reference/#cmdoption-p). In `virtualenv --python=python2`, `python2` should probably be replaced by `python2.7` as you have python 2.7.10 installed.

**Comment by cougil** [comment]
It seems that finally I was able to install the environment via 'virtualenv' following:
```
virtualenv --python=python2.7 python2.7
source python2.7/bin/activate
pip install --editable .
Obtaining .../openfisca/openfisca-france
Requirement already satisfied: Biryani[datetimeconv]>=0.10.4 in ...virtualenv/python2.7/lib/python2.7/site-packages (from OpenFisca-France==18.2.6)
(...)
Installing collected packages: lxml, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, flask-cors, gunicorn, PyYAML, OpenFisca-Core, requests, OpenFisca-France
  Running setup.py develop for OpenFisca-France
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 OpenFisca-Core-12.1.4 OpenFisca-France PyYAML-3.12 Werkzeug-0.12.2 click-6.7 flask-0.12 flask-cors-3.0.2 gunicorn-19.7.1 itsdangerous-0.24 lxml-3.7.3 requests-2.14.2
```
;-)

**Comment by cougil** [comment]
Last comment, I found that the last instruction also didn't work:
```
python setup.py compile_catalog
running compile_catalog
error: you must specify either the input file or the base directory
```
Also, trying to run the tests failed:
```
python -m openfisca_france.tests.test_basics
/.../python2.7/bin/python: No module named tests

```
Best,

**Comment by fpagnoux** [comment]
Hi @cougil,

Sorry, it seems that you are following [outdated instructions](https://doc.openfisca.fr/for_developers.html). I'm opening an issue about it.

To test that you installation went correctly, you can try to run some tests. You'll need to install some extra requirements : 

```py
pip install --editable ".[test]"
```

Then run from the root of the repository:
```
 nosetests tests/test_basics.py
```

**Comment by fpagnoux** [comment]
Also, I don't know how you are planning to use OpenFisca, but if you are thinking about building another legislation than the French one, you may want to check out [this repository](https://github.com/openfisca/country-template) ;).

**Comment by MattiSG** [comment]
@cougil we assume you got proper answers, and opened corresponding issues to avoid such problems to crop up again. Feel free to comment or open another issue if you encounter other problems! 🙂
