### ISSUE TITLE
Supprimer les commentaires des fichiers XML de paramètres

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france#766]
Au cours de l'issue #752 avec @michelbl nous avons remarqué que les fichiers XML de paramètres d'OpenFisca contenaient des commentaires.

Problème : ces commentaires ne sont pas découvrables par l'API web par exemple.

Plusieurs sortes :
- commentaires d'organisation ([exemple](https://github.com/openfisca/openfisca-france/blob/068aa0ec610d8d7783c500b43f93866641728954/openfisca_france/parameters/cotsoc.xml#L209)
  ```
  <CODE code="hsup_exo" description="Exonération des heures supplémentaires" format="bool" origin="openfisca"> # TODO: find a better place
  ```
- références législatives ([exemple](https://github.com/openfisca/openfisca-france/blob/068aa0ec610d8d7783c500b43f93866641728954/openfisca_france/parameters/cotsoc.xml#L388-L392))
  ```
      <NODE code="commun" description="Communes aux cadres et non cadres" origin="openfisca">
      <!-- Cotisations patronales au titre de la pénibilité
        - https://www.service-public.fr/professionnels-entreprises/vosdroits/F33777
        - https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/les-cotisations-patronales-au-ti/cotisations-dues.html
        - Code du travail - Article L4162-19
     -->
  ```
- commentaires de vérifications ([exemple](https://github.com/openfisca/openfisca-france/blob/068aa0ec610d8d7783c500b43f93866641728954/openfisca_france/parameters/fonc.xml#L74))
  ```
  <VALUE deb="2006-11-01" valeur="449" /># TODO: check in july 2014 for "fin"
  ```
- des précisions ([exemples](https://github.com/openfisca/openfisca-france/blob/068aa0ec610d8d7783c500b43f93866641728954/openfisca_france/parameters/taxation_capital.xml#L206))
  ```
  <NODE code="droits_soc" description="Droits sociaux" origin="openfisca"> ## parts actions détenus par salariés et mandataires sociaux intro en 2006 ##
  ```

Proposition : selon les cas, convertir ces commentaires en attributs XML ou les supprimer.

**Comment by MattiSG** [comment]
1. Poubelle.
2. Import dans un attribut `reference`.
3. Remplacement par `<PLACEHOLDER>`.
4. Import dans `description`.

**Comment by michelbl** [comment]
Il y a aussi des commentaires sur l'implementation, par exemple : (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/taxation_capital.xml#L290)

```
      <CODE code="max" description="Plafond pour investissement dans les PME" format="integer" origin="openfisca" type="monetary"> ## ce type de réductions apparaît seulement en 2008 ##
      # <VALUE deb="2014-01-01" valeur="45000" />
        <VALUE deb="2011-01-01" valeur="45000" />
        <VALUE deb="2009-01-01" valeur="50000" />
        <VALUE deb="2008-01-01" valeur="50000000" /> ## no upperbound before 2009- set arbitrarily large##
      <VALUE deb="2002-01-01" valeur="0" /> # taux set to 0 to avoid error- expect prog to pass when date inf to 2008 #
      # </CODE>

```

**Comment by benjello** [comment]
@michelbl: Pour régler les commentaires concernant l'implémentation;
  - l'idéal serait de corriger le code,
  - remonter les commentaires dans le code
  - me lister ces occurrences ici et j'essaierais de m'en charger  (au moins elle ne serotn pas complètement perdues)

**Comment by michelbl** [comment]
@benjello en fait c'est le seul cas de commentaire sur l'implementation

J'ai corrigé le code de la formule pour avoir quelque chose de moins tricky.
