### ISSUE TITLE
Erreur certificat https

### ISSUE THREAD

**Issue by xtrembaker** [openfisca/openfisca-france#777]
Bonjour,

Nous rencontrons actuellement un problème de certificat sur l'url suivante : "https://api.openfisca.fr/api/1".

Erreur : Error in cURL request: Peer's Certificate has expired.

Tout fonctionnait bien jusqu'à vendredi dernier

**Comment by fpagnoux** [comment]
Bonjour @xtrembaker,

Merci beaucoup de nous avoir signalé ce problème, nous allons le résoudre au plus vite.

**Comment by MattiSG** [comment]
Notre certificat a expiré. Nous mettons tout en œuvre pour le renouveler au plus vite. Nous pensons résoudre ce problème dans la journée.

Si vous avez un besoin de continuité, vous pouvez désactiver temporairement la vérification des certificats en ajoutant l'option `--insecure` à `curl`.

Toutes nos excuses pour cet incident.

**Comment by fpagnoux** [comment]
Bonjour, tout devrait-être rentré dans l'ordre. @xtrembaker vous confirmez ?

**Comment by xtrembaker** [comment]
Yes ! Merci !
