### ISSUE TITLE
Calculs divergents du "coût du travail"

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#783]
J'essaie de comprendre pourquoi OpenFisca et le [Simulateur de Cout d'Embauche](https://embauche.beta.gouv.fr/simulateur/) ne donnent pas la même réponse pour le "coût du travail" en partant d'un même salaire de base de 2300€

Dans les deux cas c'est la "simulation minimale": la valeur renvoyée par OpenFisca est celle qu'on peut lire quand on fait [le test avec curl après une install](https://github.com/openfisca/openfisca-france/blob/master/README.md#servez-openfisca-france-avec-lapi-web-openfisca) réussie; la valeur du simulateur est celle obtenue avant toute interaction avec le formulaire.

Une partie de la différence s'explique par la prise en compte du CICE. Le simulateur d'embauche rapporte deux chiffres: avant prise en compte du CICE (3196€) et après (3035€).

Dans OpenFisca la variable `cout_du_travail` intègre le CICE et c'est donc 3078€.

La différence résiduelle tient à ce que le simulateur d'embauche intègre deux réductions: allègement Fillon et réductions d'allocations familiales; et deux cotisations, la formation professionnelle ainsi qu'une complémentaire santé arbitrairement fixée à 20€. (Dans ce cas précis le simulateur explique que c'est un exemple et propose d'affiner la description de sa situation, donc pour ces 20€ l'écart est compréhensible.)

Les trois autres variables ne sont pas présentes dans le calcul réalisé par OpenFisca, et ça comble l'écart. Mais maintenant je me demande pourquoi OpenFisca n'intègre pas ces trois variables dans le calcul, ou pourquoi (et comment) le simulateur d'embauche les intègre, dans la mesure où ça semble être la même requête vers OpenFisca.

**Comment by benjello** [comment]
Je subodore que les variables déclinant les [modes de recouvrement](https://legislation.openfisca.fr/?q=mode_recouvrement#search-input) ne sont pas correctement renseignés. Quel est le contenu exacte de la requête ?

**Comment by benjello** [comment]
@laem, tu me corriges si je dis des bêtises ;-)

**Comment by laem** [comment]
Très probablement ça : github.com/sgmap/cout-embauche/wiki/Note-sur-le-calcul-des-allègements-(Fillon-général-et-allocations-familiales)

**Comment by Morendil** [comment]
Merci bien :)
