### ISSUE TITLE
Eligibilité ACS avec AAH / CAAH / APL

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#790]
Simulation de départ : 59561c10e31cc2156687a777 
Simulation de test : 595b560d1215294381503e20

Contexte :
La simulation renvoie un droit à l’ACS (200€)
La CPAM n’attribue pas ce droit car les plafonds sont dépassés.

Investigations et problèmes :
- Le plafond n’est pas le même entre la CPAM et le notre.
CPAM : 11776
acs_plafond : 11670,1015625

- Les ressources totales ne sont pas calculées identiquement
CPAM : 12132,40
cmu_base_ressources : 10424,2734375
→ Problème identifié, le CAAH n’est pas inclus dans les ressources. En intégrant les ressources du CAAH à l’AAH à la main, cmu_base_ressources passe à 11858,7539025, nous donnant un résultat supérieur au plafond et confirmant les résultats de la CPAM
→ Autres problèmes à investiguer : prise en compte du forfait logement ?

**Comment by monbocal** [comment]
Up ! Une autre situation de test au 5a4d68981bd35e0eec1e8eab (ludwig : https://mes-aides.gouv.fr/tests/5a4dfb8d1bd35e0eec1e9693/show )

Pour en savoir plus : https://informations.handicap.fr/art-AAH-ACS-mutuelle-853-10086.php

> Les allocataires de l'AAH (allocation adulte handicapé), avec un maximum à taux plein à 810,89 euros, sont donc concernés même s'ils perçoivent la majoration pour la vie autonome (104,77 euros) mais pas s'ils touchent le complément de ressources (179,31 euros). En effet, 179,31 + 810,89 = 990,20 : le plafond est dépassé de 8.87 euros.

**Comment by monbocal** [comment]
Les aides à exclure du calcul sont au https://www.cmu.fr/ressources-cmu-complementaire.php ; le CAAH n'est pas mentionné dedans.

**Comment by Morendil** [comment]
Corrigé par #868
