### ISSUE TITLE
Condition d'âge pour l'ASS

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#791]
Il y a une condition d'âge sur l'ASS qui n'est pas explicité. Lorsque le demandeur dépasse l'âge légal du départ à la retraite et qu'il a cotisé assez pour partir en retraite, alors l'ASS est refusé. Si les trimestres ne sont pas atteint, alors il y a un délai supplémentaire.

> Le versement de l’ASS est interrompu si :
> • Vous avez 60 ans (60 ans et 4 mois pour les personnes nées entre le 1er juillet et le 31 décembre 1951, 60 ans et 9 mois pour celles nées à compter du 1er janvier 1952) et totalisez le nombre de trimestres requis pour bénéficier d’une retraite à taux plein.
> • Si le nombre de trimestres exigés n’est pas atteint, le versement est maintenu jusqu’à ce qu’il le soit et au plus tard jusqu’à 65 ans (65 ans et 4 mois pour les personnes nées entre le 1er juillet et le 31 décembre 1951, 65 ans et 9 mois pour celles nées à compter du 1er janvier 1952).

En savoir plus : http://www.pole-emploi.fr/front/common/tools/getElementStream.jspz?id=190029&prop=file .

Cas d'usage : proposition de l'ASS à une personne de 66 ans (simulation 595ce35972a5ac39c17a120c).

**Comment by fpagnoux** [comment]
Bonjour @monbocal,

Merci d'avoir signalé ce problème. @guillett, je te laisse prioriser la résolution de cette imprécision de calcul 🙂.

**Comment by monbocal** [comment]
Lien vers ludwig : https://mes-aides.gouv.fr/tests/5bc468d44a41961c64ba6ca6/show
