### ISSUE TITLE
Rename this repo to “country-france”

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#799]
In order to increase readability, rename this repo so that its full name is “openfisca/country-france” rather than “openfisca/openfisca-france”.

**Comment by MattiSG** [comment]
- [ ] Document this naming convention.
- [ ] Open PRs to suggest renaming openfisca/tunisia to openfisca/openfisca-tunisia.
- [ ] Rename openfisca/senegal to openfisca/country-senegal.

**Comment by Morendil** [comment]
Nous avons maintenany Mali, Italy, Cote d'Ivoire qui suivent le schéma de nommage que cette PR entendait contrer; et CEQ qui sans y adhérer vraiment, le renforce aussi. Indépendamment du bien-fondé de cette démarche de renommage je pense qu'elle a peu d'espoir d'aboutir, je ferme en conséquence.
