### ISSUE TITLE
Unifier les `origin` (`reference`) des paramètres

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#804]
Actuellement, les attributs `origin` des paramètres contiennent majoritairement deux valeurs : `ipp` ou `openfisca`.
Ces attributs sont en voie d'être dépréciés pour être remplacés par une propriété `reference` (https://github.com/openfisca/openfisca-core/issues/523), qui donnera de préférence une URL vers une page officielle, à défaut une URI.

Je propose donc de :

1. Remplacer les références `ipp` par l'URL des barèmes IPP : http://www.ipp.eu/outils/baremes-ipp/
2. Supprimer les références `openfisca`, qui n'ont pas de sens.

Alternative :

2. Remplacer les références `openfisca` par le nom / handle GitHub de l'auteur qui l'a ajouté. Lorsque c'est possible et simple (sur la base de son email, par exemple), indiquer plutôt le nom de l'organisation représentée par la personne ayant contribué.

- - - -

poke @benjello @fpagnoux @michelbl

**Comment by MattiSG** [comment]
(unassignez-vous quand vous aurez donné un avis :wink:)

**Comment by michelbl** [comment]
@fpagnoux @benjello êtes-vous d'accord avec les évolutions proposées ?

**Comment by fpagnoux** [comment]
Plutôt pour la première hypothèse.

**Comment by benjello** [comment]
Ok (même pour 2).
