### ISSUE TITLE
Introduire un paramètre documentaire versement_transport.taux

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#805]
Comme indiqué dans https://github.com/openfisca/openfisca-france/pull/788#pullrequestreview-57221670 :

> `versement_transport.taux` n'est [pas chargé comme un paramètre](https://legislation.openfisca.fr/?q=versement_transport.taux#search-input) 😞
Il est [utilisé](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/versement_transport.py#L54-L69) comme une `global` 😱

Il n'y a donc aujourd'hui pas de moyen de découvrir ces valeurs, ni leur usage dans OpenFisca.

Je propose donc d'introduire a minima un paramètre vide dont la description explique comment accéder aux valeurs, et au mieux d'ajouter dynamiquement ces valeurs à la liste des paramètres afin de les exposer via l'API.

**Comment by MattiSG** [comment]
cc @laem @fpagnoux @benjello

**Comment by Morendil** [comment]
@MattiSG je ne connais pas assez l'explorateur pour savoir si je dis une bêtise, mais par acquis de conscience: est-ce que ça n'a pas pour conséquence que la majorité des variables accessibles via l'explorateur deviendraient des taux de versement transport ? Si oui, est-ce que c'est acceptable en termes d'UX ?

**Comment by MattiSG** [comment]
Dans le second cas, c'est possible, mais j'imagine que ça dépend du schéma de nommage employé et de qui sont les feuilles dans ces taux. Dans le cas où on ajoute simplement un paramètre documentaire, ça n'ajoute qu'un seul élément :)

**Comment by Morendil** [comment]
Je ferme en faveur de #1167.
