### ISSUE TITLE
Document entities

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#807]
Explain what is the use and give examples of usage of all entities in docstrings.

Related to https://github.com/openfisca/legislation-explorer/issues/80.

**Comment by MattiSG** [comment]
@benjello On prévoit de présenter la doc sur les entités dans l'explorateur de législation, si tu as déjà un peu de texte sur le sujet (ou peut en rédiger  ;)  ) on sera preneurs  :)

**Comment by benjello** [comment]
@MattiSG : je vais faire une proposition. Je mets cela où ?

_Sent from my BLU STUDIO G PLUS using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MattiSG** [comment]
Excellent !! L'idéal est de faire direct une PR en ajoutant des docstrings dans les entités 😃

```diff
  from openfisca_core.entities import build_entity
+ '''
+ Une Famille représente…
+ Elle s'utilise de la manière suivante :
+ …
+ Elle diffère d'un Ménage car…
+ '''
  Famille = build_entity(
    key = "famille",
    plural = "familles",
    label = u'Famille',
```

**Comment by fpagnoux** [comment]
Partilly fixed by https://github.com/openfisca/openfisca-france/pull/811

**Comment by benjello** [comment]
@MattiSG, @maukoquiroga @fpagnoux : peut-on fermer ce ticket ?
Si vous voyez des améliorations à apporter ne pas hésiter à les lister.

**Comment by maukoquiroga** [comment]
(Je me permet d'écrire en français ici)

Si je bien compris, et on regardant le [code](https://github.com/openfisca/openfisca-france/blob/ba11290af525c72682f9db0c38af9778dd66a8ef/openfisca_france/entities.py), nous avons déjà documenté :

- [x] Foyer fiscal ; et
- [x] Menage

mais, il reste encore à documenter :

- [ ] Individu ; et
- [ ] Famille

Est-ce correct ? cc @benjello

**Comment by benjello** [comment]
Yep

**Comment by fpagnoux** [comment]
Les individus, il n'y a sans doute pas grand chose à dire, à par peut-être préciser que ce sont des personnes physiques.

Les familles oui, mais c'est une entité qui est assez mal définie. Le concept vient de la CAF, mais je ne suis pas sûr que la définition soit explicitée quelque part. En gros c'est un adulte, un conjoint qui "partage la vie" de cette personne, et des enfants qui sont "à leur charge". Le tout sans contrainte d'habiter sous le même toit, ni d'être dans le même foyer fiscal, et parfois à l'appréciation du contrôleur de la CAF.

@benjello est-ce que tu as une définition plus rigoureuse?

**Comment by benjello** [comment]
On pourrait traduire famille par foyer social, l'entité au nom duquel on touche des prestations sociales et/ou des minimas sociaux. Le problème est qu'il y a un foyer social pour la CAF concernant les familles, mais il diffère de celui pris en compte pour le RSA, l'ASPA etc.
L'idéal serait d'avoir une entité par chacun de ce cas. Mais c'est lourd à mois d'avoir un moyen meta de définir ces entités par des liens entre les individus.

**Comment by fpagnoux** [comment]
> On pourrait traduire famille par foyer social, l'entité au nom duquel on touche des prestations sociales et/ou des minimas sociaux. Le problème est qu'il y a un foyer social pour la CAF concernant les familles, mais il diffère de celui pris en compte pour le RSA, l'ASPA etc.

Oui. En pratique la `Famille` actuelle est l'union de tous les foyers sociaux de toutes les prestations, et ensuite chaque prestation ne prend en compte qu'une sous-partie des individus. 

> L'idéal serait d'avoir une entité par chacun de ce cas. Mais c'est lourd à mois d'avoir un moyen meta de définir ces entités par des liens entre les individus.

Une entité par prestation, ça semble en effet très lourd (les 3 entités sont déjà parfois pénibles à gérer) et ça ne colle pas avec des entités définies en avance : la composition du foyer social d'une prestation peut dépendre des ages, des revenus, etc.

**Comment by benjello** [comment]
C'est pour tant ce que font souvent les autres modèles de microsimulation. Il définissent l'entité au moment du calcul de la prestation. Ce que l'on fait en partie en prenant un sous ensemble de famille.

**Comment by Morendil** [comment]
Je pense que les besoins en termes de documentation sont atteints, je rejoins l'idée qu'on sait ce que sont un individu et une famille sans avoir besoin de plus d'explication (ou alors il faut rentrer dans des détails qui vont sans doute dépasser la demande implicite de l'usager faisant une recherche ou lisant le fichier de définition).

Il me semble qu'on pourrait améliorer l'UX de la recherche dans le legislation explorer (rien ne distingue les entités, les variables et les paramètres) et qu'il serait intéressant de tester l'intérêt d'une navigation entité -> variables (rattachées à cette entité) comme suggéré par Matti initialement ("give examples of usage"). Plus largement je m'interroge sur ce que sont les "jobs to be done" par le legislation explorer.

Mais ces questions dépassent le cadre de l'issue, et il me semble que la conversation a déjà dérivé, je ferme par souci de noter que _quelque chose_ a été résolu.
