### ISSUE TITLE
Renommer la variable "famille"

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-france#808]
Il y a collision de nommage entre la variable et l'entité `famille`.
Pour faciliter la lecture, il convient de renommer l'une ou l'autre. Le plus légitime semble être de renommer la variable plutôt que l'entité, qui a une existence sous ce nom dans la loi.

Related to https://github.com/openfisca/openfisca-core/issues/562.

**Comment by benjello** [comment]
Il y a en fait plusieurs problèmes qui m'empêchent d'avoir une idée claire:
 - L'entité famille dans openfisca est assez hybride: on l'utilise pour définir les famille au sens de la CAF (ou foyer sociaux ou foyer CAF, je ne connais pas le terme exact) mais aussi les couples au sens de l'ASPA (et peut-être d'autres choses encore). 
 - Ces définitions sont en fait pas très strictes car on veut pouvoir modifier le périmètre des familles CAF par exemple en changeant les âges donnant droit aux allocations familiales.
 -  Le terme est consacré pour la cotisation employeur famille. On pourrait la nommer `famille_employeur` mais comme il n'existe pas de `famille_salarie` c'est trompeur.

**Comment by guillett** [comment]
@benjello peut-on renommer cette variable en `cotisation_famille_employeur` ?

**Comment by benjello** [comment]
Disons que je suis pour un statu-quo car on va casser un nommage des cotisations assez homogène (qui évite d'avoir cotisation dans le nom) pour sanctifier famille qui est le concept le plus flou. Mais s'il faut vraiment renommer, ma préférence va à `famille_employeur` (en précisant qu'il n'y pas de famille_salarie dans la docstring ...)

**Comment by Morendil** [comment]
Personnellement je suis favorable à `cotisation_famille`, c'est court et suffisant. La ventilation employeur/salarié correspond à ce qu'on nomme des _composantes_ dans syso et j'y vois une trouvaille qu'OpenFisca devrait s'empresser de voler - _good frameworks copy, great frameworks steal_.

Cela dit le statu quo semble l'avoir emporté, en tout cas la décision sur #1028 va dans ce sens et il ne me semble pas cohérent d'avoir rejeté #1028 et de laisser cette issue ouverte. Je ferme donc.

Si vous m'accordez une réflexion plus meta et peut-être psychologisante, j'ai le sentiment que nous (pour une valeur de _nous_ pas très bien définie) avons du mal à traiter nos désaccords par une action (_disagree and commit_) et que de trop nombreux sujets sans beaucoup d'enjeux finissent par languir indéfiniment.

Je recommande de privilégier plus souvent l'action, sous la forme de petits pas qui vont limiter l'investissement en temps et en énergie. Plutôt qu'ouvrir une issue pour susciter une discussion, créer une PR qui résoud le problème; plutôt que bloquer une PR pour des "request changes" sur des points mineurs, ajouter un commit qui traite le point. (Si la PR est pourrie on peut la fermer, si le commit est pourri on peut le revert. L'action est sans risque.)

**Comment by fpagnoux** [comment]
Pour information, une nouvelle raison de renommer cette variable:

Aujourd'hui, elle n'est plus directement exposée dans le legislation explorer, c'est l'entité qui prend le pas:

https://fr.openfisca.org/legislation/famille

Dans #1028, on parlait d'un chantier cotisations après le PLF et le merge des barèmes IPP, deux chantiers qui devraient bien avancer ce mois-ci. J'espère qu'on pourra donc avancer sur les cotisations à partir du mois prochain 🙂
