### ISSUE TITLE
AL Primo Accédant : revenus 2015 + RFR

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#816]
La simulation de test qui a tout déclenché : https://mes-aides.gouv.fr/tests/59b6548a8adbaa29787e41ed/show

Contexte : malgré les salaires entrés, l'allocation logement proposée est fantaisiste (dépasse le montant des mensualités de prêt, de plusieurs milliers d'euros).

Pistes de réflexion : 
- Dès qu'on commence à entrer les revenus 2015, le montant de l'allocation logement explose. En particulier, à partir du moment où on entre un revenu 2015 pour le conjoint qui n'a pas travaillé sur les douze derniers mois
- Le montant de l'allocation logement augmente avec les revenus 2015, comme s'il y avait un dépassement quelque part

Une trace manuelle pourrait peut-être trouver d'où vient l'erreur et corriger le calcul ? Cela a peut-être une influence sur d'autres calculs ?

Sylvain

**Comment by monbocal** [comment]
Bonjour, j'ai une autre simulation dans le même cas : https://mes-aides.gouv.fr/foyer/resultat?situationId=59ba77338adbaa29787e9a8a .

Même schéma : j'ai un montant d'APL avec le warning sans entrer l'année 2015, même si ici c'était 1190 euros
**En entrant le RFR, le montant de l'AL augmente avec le RFR.** semble être le point commun à ces deux simulations

Lien vers le test : https://mes-aides.gouv.fr/tests/59ba7c218adbaa29787e9b61/show .

**Comment by fpagnoux** [comment]
Arg, pile quand @guillett est en vacances ! 

Le problème est-il apparu récemment depuis que @guillett a rendu calculables les ALs pour les primo-accédants ?

Si oui, le plus sage serait de repasser à la version précédente d'OpenFisca en attendant de trouver la source du problème. Je peux aider.

**Comment by monbocal** [comment]
A vue de nez, il s'agit d'un problème pour les primo-accédant uniquement : en faisant la simulation en changeant primo-accédant par locataire, l'AL n'est plus proposée.

**Comment by fpagnoux** [comment]
Ok, je fais une PR sur mes-aides pour regarder le problème, et on attend le retour de @guillett pour un fix pérenne.

**Comment by fpagnoux** [comment]
@monbocal @guillett est ce que https://github.com/openfisca/openfisca-france/pull/829 a résolu ce problème ?

**Comment by guillett** [comment]
Ça devrait être bon. J'ai fait les tests en local ça passe. J'attends le déploiement en production et la validation des tests sur Ludwig et je ferme cet issue.

**Comment by guillett** [comment]
Les tests sont passés au vert. C'est bon pour moi. Je ferme. Merci @monbocal.
