### ISSUE TITLE
Referencer les taux de transports dans le législation explorer

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#818]
Aujourd'hui les paramètres du [versement transport](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/assets/versement_transport/taux.json) sont chargées de manière non-standard dans OpenFisca.

De ce fait, ils n'apparaissent pas dans le legislation explorer, et ne sont pas exposés par l'API.

---

Étapes :

- [ ] Définir un format pour representer un format pour rep les params locaux - parent #1117 
- [ ] Implémentation et application sur la législation française (versements)
- [ ] Implémentation et application sur la législation française (apl)
- [ ] Implémentation et application sur législation explorer

**Comment by fpagnoux** [comment]
Voir https://github.com/openfisca/openfisca-france/compare/master...simplify-al et https://github.com/openfisca/openfisca-core/compare/dynamic-leg-computing

**Comment by fpagnoux** [comment]
Issues: 
- Certaines communes n'ont pas de versement transport. Pour les intégrer de manière iso-fonctionnelle, il faudrait avoir une forme de valeur par défault
- Ajouter les paramètres tels quels signifieraient 10000 paramètres de plus dans la législation (qui sont en fait tous le même paramètre pour différentes communes). Est-ce qu'il ne faudrait pas plutôt créer une structure spéciale (table) ? Si oui, comment ?

Possibilités : 

```
keys:
  01004:
    values:
        2010-01-01: 0.45
  01005:
    values:
        2016-07-01: 0.6
```

```
  type: table
  01004:
    values:
        2010-01-01: 0.45
  01005:
    values:
        2016-07-01: 0.6
```

```
  tags:
    - table
  01004:
    values:
        2010-01-01: 0.45
  01005:
    values:
        2016-07-01: 0.6
```

**Comment by benjello** [comment]
Je vote pour la 1ère si on veut se limiter aux tables unidimensionnelles sinon pour la seconde solution mais avec plus d'information sur la structure de la table.

**Comment by benjello** [comment]
On peut aussi rajouter une valeur par défaut pour les clés non présentes. Si cette valeur par défaut est absente et qu'une clé non renseignée est demandée alors une erreur est retournée.

**Comment by Morendil** [comment]
Je ferme en faveur de #1167.

**Comment by maukoquiroga** [comment]
@Morendil Je comprends l'intérêt de #1167, c'est génial.

Il me semble que la différence entre cette issue et #1167 est que celle-ci est bottom-up, et #1167 top-down.

Au-delà de ce fait, j'ai l'impression que la discussion est bien avancée sur ce sujet en particulier, et qu'on généralisant de façon exclusive la discussion on pert la richesse du design émergent.

Je re-ouvre pour l'instant.

**Comment by Morendil** [comment]
Il me semble qu'on a appris des choses dans les 4 semaines depuis cette réouverture: de la dette technique a été mise à jour dans Core autour des paramètres et de leur exposition par l'API, c'était ressenti notamment au cours de https://github.com/openfisca/openfisca-core/pull/765 et https://github.com/openfisca/openfisca-core/pull/756

Mon sentiment est que ce sujet est d'abord à traiter dans Core (alignement de la représentation interne des paramètres et de leur exposition par l'API), et seulement ensuite dans France (choix d'une représentation interne qui permette de traiter le cas des VT).

Par ailleurs je ne suis pas convaincu qu'il existe une réelle demande usager pour accéder à ces paramètres en particulier via le legislation explorer. Je ferme à nouveau.
