### ISSUE TITLE
Seuil de non recouvrement de l'IR

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#82]
Le seuil de non recouvrement de l'IR à 61e existe dans param.xml (cf. _P.ir.seuil_recouvrement) mais pas appliqué dans irpp.py. Or il le faut, dit http://www2.impots.gouv.fr/documentation/2013/brochure_ir/files/assets/basic-html/page310.html p310.
N'est ce pas ? Ou alors je me trompe, dans ce cas, pourquoi ?

**Comment by MattiSG** [comment]
> Ça sera dans mon prochain commit.

Il y a 3 ans.

Je ferme, ne pas hésiter à rouvrir quand du travail est alloué sur ce sujet.
