### ISSUE TITLE
Adapt bareme ipp scripts to YAML parameters

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#820]
Since the parameters have been rewritten in YAML, the [import scripts](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/scripts/parameters/baremes_ipp) don't work.

The script should take into account the fact that the path length should be less than 150 chars. See #819.

**Comment by michelbl** [comment]
Une liste de problèmes rencontrés lors de l'import des barèmes IPP : 

* Barème chômage, alloc_base, 30/12/1974 : le format est un nombre, pas une date
* impot revenu/bareme IGR,  prelevements sociaux/aubry I, taxation/tva-par-produits : ces feuilles ne sont pas parsées
* prestations sociales/icaf, cf-plaf; retraites/pt-unirs-arrco, salref-probtp, salref-unirs : pas d'unité monétaire indiquée
* travail/GMR : les noms taxIPP sont en majuscule, donc ils sont interprétés comme des noms courants
* reférences legislatives CNRACL (prelevements sociaux) : il y a plusieurs colonnes qui ne peuvent pas être parsées

Pour parser la totalité des barèmes, je pense qu'il faudrait appliquer des conventions sur les fichiers XLSX : 
* distinguer formellement s'il y a une ligne "noms taxipp" ou pas (actuellement : le script regarde si les initiales sont des capitales ou pas)
* distinguer formellement les labels des données (actuellement : le script regarde si la première valeur de la ligne est une date ou pas)
* format unifié des montant (euro ou franc)
* donner des noms de colonnes standards pour les ref législative et les dates
* donner des noms standards aux tranches des baremes. Actuellement : tranche 1, tranche 2... ou tranche1 tranche2... ou 1ere_tranche, 2eme_tranche...

**Comment by Morendil** [comment]
Doublon de #905, je ferme.
