### ISSUE TITLE
Nettoyer les statistiques Piwik

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#821]
Relates to openfisca/openfisca-core#685

There are polluted by:

- Uptime robots
- Legislation explorer integration tests
- localhost

**Comment by Anna-Livia** [comment]
For uptime robot : 
Issue : The uptime robot calls to the API are sent undiferenciated for calls from users.
Solution investigated : Add IP address from user to the tracking from the API, and filter out the uptime robot API

**Comment by Anna-Livia** [comment]
To clean the Piwik logs concerning the Legislation explorer integration tests, we need to change either Leg.Expl. code and/or the API tracker code. It cannot be done from the Piwik interface.
Sauce lab IPs are always changing and cannot be filtered out.
Working idea : Launch LEG.EXP in a NO_TRACKING mode, that is passed down to the API call.

**Comment by maukoquiroga** [comment]
<img width="1057" alt="capture d ecran 2018-07-09 a 22 15 42" src="https://user-images.githubusercontent.com/329236/42473740-baa04c02-83c5-11e8-84b6-4c504f129f9a.png">

**Comment by Anna-Livia** [comment]
@maukoquiroga This might be due to the fact that In order to run the test on the new api version tracking, I had to allow localhost once more :) I will deactivate it as soon as the PR are merged. When is the screen shot from ?

**Comment by maukoquiroga** [comment]
Hi @Anna-Livia, oh ok thanks. I did a last month filter and calls look proper. False-positive.

<img width="1418" alt="capture d ecran 2018-07-18 a 16 47 31" src="https://user-images.githubusercontent.com/329236/42889271-51de8f30-8aaa-11e8-8f7d-62b14913949b.png">

**Comment by Anna-Livia** [comment]
I think we can close this issue. @fpagnoux  Don't hesitate to open it again if you think there is still work to be done :)
