### ISSUE TITLE
Mettre à jour fr.openfisca.org

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#824]
Objectif : [Améliorer la communication (France)](https://trello.com/c/VgL0jBcC/50-am%C3%A9liorer-la-communication-france)

Le site https://fr.openfisca.org (anciennement openfisca.fr) présente de nombreux problèmes:

- Contenu périmé
- Liens morts
- Bugs (des blocs de texte se chevauchent).

Il est souvent le premier résultat concernant OpenFisca sur les moteurs de recherche, ce qui nuit à l'image de marque d'OpenFisca.

Un [consensus](https://github.com/openfisca/openfisca-web-site/issues/56) a émergé en faveur d'une ré-écriture d'un site simple _from scratch_.

Ce site mettra en valeur:
  - Les partenaires d'OpenFisca en France
  - Les réutilisations

Pourront y figurer également:
  - L'UI et le démonstrateur, en tant qu'exemples de réutilisations
  - Un lien vers le législation explorer du système socio-fiscal français
  - Un lien vers `status.openfisca.fr` pour consulter l'état des API

**Comment by Anna-Livia** [comment]
[ ] Get contact@openfisca.org to function.
[ ] Transfer Communauté  and Contact to openfisca.org

**Comment by sandcha** [comment]
Atelier prévu mardi 28 novembre 10h30 - Mirabeau.

**Comment by maukoquiroga** [comment]
Hello, y a-t-il de next steps issus de l'atelier ? Mockups ?

**Comment by Anna-Livia** [comment]
Ajouter aussi un lien vers la doc swagger de l'API

**Comment by monbocal** [comment]
Proposition de page :

Dans l’ordre de la page

fixed-top navbar avec des accès directs dont status.openfisca.org
+ Lien retour vers .org

Bloc de teasing :
- le logo à gauche
- un pitch engageant en 250 caractères à droite
- un lien à droite à définir

Bloc de présentation détaillée
- une présentation de 750-1000 caractères d’OpenFisca
- le même lien que précédemment (à définir)

Bloc 3 réutilisation
- 3 logos de 3 projets réutilisant OpenFisca
- Une phrase de présentation en dessous pour chaque très succinte
- Un lien « En voir plus » qui amène sur la page des réutilisations
⚠ Ne pas mettre de liens sortants vers ces réutilisations sur la 1re page, uniquement sur la page des réutilisations

Bloc Utiliser OpenFisca
- Un texte à liens de 500 caractères sur les premières choses à savoir pour utiliser OpenFisca
- Un top 3 (3 logos, 3 phrases) des meilleurs outils pour utiliser OpenFisca : l’API, le legislateur, la doc
- Un lien vers une page détaillée « Utiliser OpenFisca ».

Bloc X partenaires
- Mise en avant des logos des partenaires, maximum 3 par ligne

Big Footer
- Avec les liens classiques : mentions légales, contact, etc.

**Comment by monbocal** [comment]
Wireframe pour aller avec le texte, au propre et en couleurs.
[WireframeFrOpenFisca.pdf](https://github.com/openfisca/openfisca-france/files/1635115/WireframeFrOpenFisca.pdf)

**Comment by monbocal** [comment]
Une première version des textes d'entrée : le pitch + la description d'OpenFisca

Codez la loi ! OpenFisca permet la transcription du code législatif en code informatique. Son moteur de calcul aide à comprendre les lois, analyser leurs changements et simuler des situations. Entièrement libre et gratuit, modulable et réutilisable, OpenFisca transforme le droit en logiciel.

DECOUVREZ COMMENT

OpenFisca est un moteur ouvert de microsimulation du système socio-fiscal. A travers OpenFisca France, une communauté de développeurs, économistes, enseignants, instituts d'études et de recherche enrichissent et améliorent les modèles de simulation du système socio-fiscal français. Un de ses objectifs, pédagogique, est de permettre d’aider les citoyens à mieux comprendre les réformes qui impactent leur quotidienne. OpenFisca et OpenFisca France sont des projets libres. Cela signifie que vous pouvez utiliser les logiciels associés, les installer, étudier leur code source, les modifier, les redistribuer de la façon que vous souhaitez. Une seule condition est imposée : les travaux dérivés d’OpenFisca doivent eux aussi être libres. Cette contrainte permet à la communauté de grandir à travers des améliorations constantes du moteur de calcul, des mises à jour des systèmes représentés et des nouveaux usages.

**Comment by maukoquiroga** [comment]
J'ajoute une liste d'issues pour une première version :

- [ ] Atelier pour choisir la technologie
- [ ] Créer la homepage
- [ ] Deployer la homepage
- [ ] Créer les test d'intégration
- [ ] Mettre en place du CI
- [ ] Mettre en place du CD

**Comment by maukoquiroga** [comment]
📦

**Comment by fpagnoux** [comment]
Super ! C'est une page qui se tourne 🙂 

👏 @Anna-Livia @maukoquiroga @sandcha
