### ISSUE TITLE
Mettre à jour le barème de la taxe sur les salaires pour 2017

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#827]

**Comment by fpagnoux** [comment]
Bonjour @Morendil,

Est-ce que tu penses pouvoir ouvrir toi même la PR, ou souhaites-tu que la communauté OpenFisca investigue cette issue ? 

Si deuxième option, est-ce que tu aurais plus de contexte ? Éventuellement une référence ou article de presse qui mentionne l'évolution de ce taux ? 

Merci !

**Comment by Morendil** [comment]
@fpagnoux je me suis auto-assigné avec l'intention de prendre la tâche et ouvrir une PR, et je pense que c'est sans complication; mais je suis toujours preneur d'un coup de main :)

Pour les références j'ai au moins SP: https://www.service-public.fr/professionnels-entreprises/vosdroits/F22576

**Comment by Morendil** [comment]
Rendons à César… il me semble que je n'ai pas fait le job en 2017, et cette année c'est à @benjello que nous devions #1097 qui a embarqué les nouveaux taux.
