### ISSUE TITLE
Migrate all formula to the `v4` syntax

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#830]
Some formulas still use the `def formula(self, simulation, period)` syntax.

All france formulas should be migrated, and this syntax explicitely deprecated.

**Comment by Anna-Livia** [comment]
De Florian :
 une formule récalcitrante que j'ai du mal à migrer 
sur la cmu

**Comment by benjello** [comment]
@fpagnoux @sandcha: cette issue est-elle oubliée ? ;-)

**Comment by sandcha** [comment]
C'est dans le sprint qui s'achève mercredi 17.

**Comment by fpagnoux** [comment]
Pas oubliée, laissée de côté, mais je compte bien la terminer. Il faudrait merger les énums d'abord pour que je puisse en suite rebaser.
