### ISSUE TITLE
Définir les statuts de la future association OpenFisca-France

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#832]
Objectif : [Améliorer la gouvernance](https://trello.com/c/gwFjkX0p/47-am%C3%A9liorer-la-gouvernance)

Suite au premier atelier, faire émerger un consensus sur les statuts.

Proposition :

- Admission de nouveaux membres sur votes des membres existants (cooptation), en tenant compte des contributions du candidat.
- Pas de board, ni de CA
- Responsabilité juridique diluée parmi les membres

**Comment by sandcha** [comment]
Vous trouverez une proposition de statuts à la suite du compte-rendu de notre dernière réunion (Google Drive). 

@Anna-Livia @benjello @cbenz @fpagnoux @MattiSG Un paragraphe `Structure proposée` présente l'idée générale. Il est suivi par la proposition de `Statuts`. En fin de document, vous trouverez d'`autres articles usuels` qui n'ont pas été intégrés mais qui sont là pour information.

Qu'en pensez-vous ? Que souhaitez-vous modifier ?
En dehors du principe de collégialité des décisions, les articles sont classiques de statuts associatifs.

**Comment by sandcha** [comment]
Statuts mis à jour avec : 
* Ajout du principe d'un règlement intérieur (pour modalités de convocation des réunions du conseil, ...)
* Ajout des modalités de représentation des personnes morales

**Comment by fpagnoux** [comment]
Futurs membres relancés aujourd'hui pour approuver les statuts.

**Comment by fpagnoux** [comment]
Nous irons signer les status vendredi dans les locaux de l'IPP.

**Comment by benjello** [comment]
Je peux réserver un salle si on me donne une plage horaire.

**Comment by sandcha** [comment]
Une relecture des statuts est à prévoir par les personnes physiques et les personnes morales de la communauté  pour obtenir un consensus.

**Comment by adrienpacifico** [comment]
Bonjour,
Est-ce que tout est signé ? C'est consultable ?

**Comment by benjello** [comment]
Non Adrien, ce n'est pas encore fait.

**Comment by sandcha** [comment]
Todo : 
- [ ] Transmettre un bilan des règles de quorum (mail)
- [ ] Statuer sur la proposition de collèges : en règlement intérieur ?
- [ ] Recueillir les correctifs/accords des participants
