### ISSUE TITLE
Ajouter l'allocation de la Garantie jeunes

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#834]
En savoir plus : https://www.service-public.fr/particuliers/vosdroits/F32700 .

Il s'agit d'une ressource potentielle. 

"La garantie jeunes permet d'accompagner les jeunes en situation de grande précarité vers l'emploi ou la formation. C'est une modalité spécifique du parcours contractualisé d'accompagnement vers l'emploi et l'autonomie (PACEA). Pour la mettre en œuvre, un contrat est signé entre le jeune et la mission locale. Ce dispositif s'accompagne d'une aide financière."

**Comment by monbocal** [comment]
Up ?

**Comment by Morendil** [comment]
Question meta: à ton avis qu'est-ce qui fait que cette issue n'a pas avancé sur l'année ou presque qui s'est écoulée depuis ta demande ?

Une piste potentielle de mon point de vue: à la lecture du commentaire ci-dessus, j'ai du mal à voir en quoi consisterait une implémentation satisfaisante. Faut-il créer une variable input qui dit "cette personne bénéficie de la garantie jeunes" et calcule le montant ? Faut-il évaluer aussi l'éligibilité, et dans ce cas en s'appuyant sur quelles variables existantes, en introduisant quelles variables nouvelles ? (Par exemple "avoir intégré un PACEA".)

Sur le sujet lui-même, j'ai regardé les textes de référence qui ne mentionnent pas de montants spécifiques mais font référence au RSA, si je comprends bien c'est un clone du RSA sous certaines conditions ?

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
