### ISSUE TITLE
Ajouter le RSO

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#835]
En savoir plus (issue Mes Aides associée) : https://github.com/sgmap/mes-aides-ui/issues/531 .

Il s'agit d'une nouvelle ressource.

"Créé par la loi d'orientation pour l'outre-mer du 13 décembre 2000, le Rso a été mis en place dans l'archipel au printemps 2002.

Cette allocation concerne les résidents permanents de l'archipel ou d'un DOM, bénéficiaires depuis au moins deux ans, sans interruption, du revenu de solidarité active, âgés d’au moins 55 ans(1) et de moins de 65 ans, s’engageant à n’exercer aucune activité rémunérée pendant la période de perception du revenu de solidarité. L’allocation ne peut être cumulée avec certaines prestations (allocation aux adultes handicapés…)."

**Comment by Anna-Livia** [comment]
C'est faisable :) 
Il faut savoir : 
- Comment  calculer l'éligibilité (avec des tests eligible/non eligible)?
(peut être une formule à part, comme `rsa_eligibilite`)
- Comment calculer le montant? (formule + tests)
- Comment cela affecte les autre aides et impots (comme `rsa_eligibilite`par exemple)  ? (+tests)

Voilou. Est-ce que ça vous parait complet @guillett @benjello ?

**Comment by benjello** [comment]
@Anna-Livia : il faut voir dans quelles bases ressources le rso pourrait intervenir également.
Mais comme cela à l'air d'être un minima intervenant en bout de chaîne, je pense qu'il n'y aura pas de problèmes de ce côté là. Mais à vérifier.

**Comment by Anna-Livia** [comment]
@monbocal Est-ce que cela répond à ta question ?

**Comment by guillett** [comment]
Une référence https://www.legifrance.gouv.fr/affichCode.do;jsessionid=C415B933909545415B47A617C472B811.tplgfr41s_2?idSectionTA=LEGISCTA000023396891&cidTexte=LEGITEXT000006074069&dateTexte=20180102

**Comment by Morendil** [comment]
Je ferme après avoir consolidé [sur le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
