### ISSUE TITLE
Corriger la définition des revenus utilisée pour la variable biactivite

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#836]
La condition de `biactivite`  dans [ce fichier](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/base_ressource.py) ne doit dépendre que des niveaux de revenus professionnels, c'est-à-dire correspondant à une activité, et non de toute la base ressources des prestations familiales.

**Comment by fpagnoux** [comment]
Bonjour @bfabre01, merci d'avoir signalé ce problème.

Est-ce que tu penses être capable de modifier le code pour corriger le problème, via une pull request ? 

Merci !

**Comment by Anna-Livia** [comment]
Hello @bfabre01,
Est ce que utiliser `revenus_du_travail`te semblerait plus approprié ?
D'autre part, @benjello @guillett , dans la formule de la biactivité, le seuil de revenu utilisé est `12 * pfam.af.bmaf` ce qui est le calcul du seuil pour l" "Abattement forfaitaire pour double activité" des APL (http://www.cohesion-territoires.gouv.fr/IMG/pdf/MEDDAT_Plaq_logement_2013_bd.pdf).
Cependant, [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F2552) décrit le seuil de revenu pour la biactivité dans le cas de la PAGE à 5173 EUR par revenu pour 2015, ce qui n'équivaut *pas* à `12 * pfam.af.bmaf`.
Qu'en pensez-vous ?

**Comment by benjello** [comment]
@Anna-Livia : pourrais-tu préciser les montants en jeu (BMAF) et les dates ?
Les contacts à la CAF de l'équipe de mes aides pourraient être utile pour éclairer ce point.

cc @guillett

**Comment by maukoquiroga** [comment]
Bump @guillett

**Comment by bfabre01** [comment]
Déjà, toutes mes excuses pour avoir fait traîner cette issue... @Morendil : merci pour ton retour. Je viens de créer une autre branche (`corrige-la-biactivite`, cf. PR [1206](https://github.com/openfisca/openfisca-france/pull/1206) ), qui code la correction autrement. Je vais voir ce que ça donne. `revenus_nets_du_travail` n'est pas la variable adéquate, car il s'agit d'une mesure de revenu net, alors qu'on doit prendre des revenus imposables. De plus, il faut que ces revenus soient annuels, et relatifs à l'année N-2. Est-ce que je peux supprimer ta branche `corrige-biactivite`, pour éviter les doublons ?

**Comment by bfabre01** [comment]
Je viens de merger #1206 . Je ferme.
