### ISSUE TITLE
MicroBNC

### ISSUE THREAD

**Issue by askz** [openfisca/openfisca-france#841]
Bonjour, je n'ai pas réussi à trouver s'il était possible de calculer les impot sociaux et fiscaux d'une personne étant sous le régime microbnc.. sauriez-vous m'indiquer ceci?

**Comment by Anna-Livia** [comment]
@benjello ?

**Comment by benjello** [comment]
Les impôts sûrement même si je ne suis pas sûr que tout soit à jour.
Les cotisations sociales peut-être également.

Désolé pour ces réponses vagues, mais ces types de revenus n'étaient pas notre priorité quand openfisca a été développé mais le but est de tout couvrir.

Si @askz nous écrivait un petit test, cela nous permettrait de vérifier tout cela.
Notamment en nous précisant les cases de la feuille d'impôt qu'il a en tête.

Merci !

**Comment by Anna-Livia** [comment]
@askz : Quelques pistes pour les tests :

Le guide pour écrire des tests sur Openfisca :
(writing yaml tests [en anglais]])[http://openfisca.org/doc/coding-the-legislation/writing_yaml_tests.html]

- pour les charges sociales, l'input variable (`tns_micro_entreprise_type_activite`)[https://legislation.openfisca.fr/tns_micro_entreprise_type_activite] et (`tns_micro_entreprise_chiffre_affaires`)[https://legislation.openfisca.fr/tns_micro_entreprise_chiffre_affaires] devraient vous permettre d'insérer le CA de la  micro BNC. --> (`tns_micro_entreprise_revenus_net`)[https://legislation.openfisca.fr/tns_micro_entreprise_revenus_net] devrait vous donner le revenu net.
- pour les impôts, Le calcul de l'(`irpp`)[https://legislation.openfisca.fr/irpp] devrait vous donner l'impot sur le revenu.

**Comment by Anna-Livia** [comment]
Bonjour @askz,
Est-ce que vous avez pu trouver la réponse que vous cherchiez ?

**Comment by askz** [comment]
Bonjour @Anna-Livia, malheureusement je ne bosse plus sur le sujet c'est @bibzz qui reprends le flambeau je vais essayer de le pinguer aileurs pour une update la dessus.
Et je pense que la question est toujours d'actualité!
Merci pour votre temps ! Bonne continuation !

**Comment by BiBzz** [comment]
Bonjour @Anna-Livia et merci @askz !
En effet, j'ai avancé sur le sujet et ai remarqué que certains paramètres ont besoin d'être mis à jour. Je n'ai pas encore pris le temps d'écrire les tests mais ne manquerai pas de le faire très bientôt.
Merci!

**Comment by fpagnoux** [comment]
Il y a aussi un problème de variables qui représentent la même chose, mais qui ne sont pas forcément cohérentes entre elles : https://github.com/openfisca/openfisca-france/issues/564.

Du coupe je suis pas sûr qu'on puisse calculer l'`irpp`en fonction de `tns_micro_entreprise_revenus_net ` par exemple. Il y a un peu de nettoyage à faire 😅
