### ISSUE TITLE
Prime d'activité et primo accédant ?

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#849]
Mes Aides à 50, caf à 0. Memes informations des deux cotés. La seule chose qui change : déclaration primo accédant sur Mes Aides, pas de trace sur la Caf. En passant de primo accedant à pas primo accédant, prime d'activité à 0.

Le lien vers le test : https://mes-aides.gouv.fr/tests/5a16d8d4a45dce641d8bed44/show

**Comment by benjello** [comment]
Je crois savoir que les primo accédants avec un prêt à rembourser ont droit aux APL.
@bfabre01 @SophieIPP : vous souvenez-vous si les primo-accédant avait droit à quelque chose dans la prime d'activité ?

**Comment by Anna-Livia** [comment]
@bfabre01 @SophieIPP @benjello : Des nouvelles sur ce front ?

**Comment by Anna-Livia** [comment]
@bfabre01 @SophieIPP @benjello :  Est ce que vous avez eu le temps de regarder cela ?

**Comment by benjello** [comment]
J'ai cherché en vain. @guillett a peut-être des billes

**Comment by guillett** [comment]
@benjello merci beaucoup pour la piqûre de rappel. Je pense que le problème vient de la mise à zéro des prestations sur les 3 derniers mois plutôt que laisser OpenFisca calculer les prestations sur ces périodes là.

**Comment by Anna-Livia** [comment]
@guillett Quels sont les prochaines étapes ?

**Comment by guillett** [comment]
J'ai _rebase_ mon dev sur les Enums, j'attends que les Enums soient mergés, je _rebase_, _fixup_ et request review. 🙂

**Comment by maukoquiroga** [comment]
@guillett Les enums ont été mergés 🎉

**Comment by guillett** [comment]
Fixed by https://github.com/openfisca/openfisca-france/pull/866
