### ISSUE TITLE
Le montant calculé de la prime d'activité n'est pas exact

### ISSUE THREAD

**Issue by deFranchisG** [openfisca/openfisca-france#850]
J'ai l'impression que le façon dont la prime d'activité est calculée dans OpenFisca France est erronée. Par exemple, pour un célibataire à 1300 € nets par mois, OpenFisca France retourne 54,02 € de prime d'activité par mois (mois de décembre), tandis que selon le site service public le montant correspondant est de 36,37 € (https://www.service-public.fr/particuliers/vosdroits/F2882). 

Cet écart me semble dû au fait que dans OpenFisca le montant forfaitaire de la PA (parameter.prestations.minima_sociaux.rsa.montant_de_base_du_rsa.yaml) est de 536,36 € alors qu'il est de 526,25 € selon service-public.
Par ailleurs, dans OpenFisca, le montant forfaitaire du RSA (parameter.prestations.minima_sociaux.rmi.rmi.yaml) n'est pas à jour : il est maintenu à 535,17 € depuis le 1er septembre 2016, alors qu'il a été revalorisé à 545,48 € le 1er septembre 2017 (source : https://www.legifrance.gouv.fr/eli/decret/2017/5/4/AFSA1707122D/jo).

Pour corriger cette erreur, il me semble qu'il faut fournir un travail plus important qu'une simple mise à jour des deux paramètres sus-cités, si on veut que l'ensemble fonctionne bien pour toutes les années de législation déjà codées.

Ci-dessous, le cas-type que j'ai essayé de simuler :
# Initialize test case
scenario.init_single_entity(
    period = 2017,
# Variable describing the individuals
    parent1 = dict(
        age = 30,
        salaire_net = 1300*12, # Annual basis
        ),
 # Variable describing the entity
    menage = dict(loyer = 5000, # Annual basis
            statut_occupation_logement = 1,
            taxe_habitation = -600,
            ),
    )

**Comment by guillett** [comment]
Bonjour @deFranchisG,

Merci beaucoup d'avoir apporté ces éléments et d'avoir pris le temps de détailler les incohérences identifiées.

C'est grâce à des retours comme le votre que la communauté OpenFisca améliore son moteur de calculs.

## Calcul de la prime d'activité pour un cas-type :

Je n'arrive pas à reproduire la valeur de  54.02 € que vous avez obtenu pour le calcul de la PPA pour OpenFisca.

Avec le snippet suivant on obtient un montant de 186.02 € pour la prime d'activité. 
```python
# Call module describing the French System
from openfisca_france import FranceTaxBenefitSystem
from datetime import date

# Initialize the legislation
tax_benefit_system = FranceTaxBenefitSystem()
scenario = tax_benefit_system.new_scenario()

# Initialize test case
my_scenario = scenario.init_single_entity(
    period = 2017,
# Variable describing the individuals
    parent1 = dict(
        age = 30,
        salaire_de_base = 1300*12, # Annual basis
        ),
 # Variable describing the entity
    menage = dict(loyer = 5000, # Annual basis
            statut_occupation_logement = 1,
            taxe_habitation = -600
            ),
    )

simu = my_scenario.new_simulation()
simu.calculate('ppa', '2017-12')
```

Comment avez-vous obtenu le montant de 54.02 € ?
Est-il possible de nous transmettre (copié/collé dans l'issue)  le document que vous avez utilisé dans son intégralité ?

## Actualisations des barèmes

Un des challenges d'un moteur de calcul tel qu'OpenFisca est l'actualisation et la mise à jour des barèmes des différentes formules. En ce qui concerne le [montant_de_base_du_rsa](https://legislation.openfisca.fr/prestations.minima_sociaux.rsa.montant_de_base_du_rsa) a  bien été mis à jour et prend bien en compte la revalorisation au 01/09/17.

## Implémentation de la prime d'activité

Vous avez entièrement raison, l'implémentation de la prime d'activité doit être revue pour refléter précisément la législation. C'est un des chantiers sur lequel nous souhaitons nous focaliser pour augmenter la fiabilité des calculs et des informations mises à disposition (en particulier sur https://mes-aides.gouv.fr/).

Merci beaucoup pour ces retours, n'hésitez pas à créer des issues pour clarifier les sujets qui le nécessitent.

**Comment by deFranchisG** [comment]
Bonjour, en exécutant votre snippet, j'obtiens bien une PA de 186.02 €. 

Ci-dessous le snippet qui me permet de calculer une PA de 54.02 €. Pour l'instant je n'arrive pas à avoir en quoi nos deux snippets diffèrent. 

```
# Call module describing the French System
from openfisca_france import FranceTaxBenefitSystem

# Initialize the legislation
tax_benefit_system = FranceTaxBenefitSystem()
scenario = tax_benefit_system.new_scenario()

# Initialize test case
scenario.init_single_entity(
    period = 2017,
# Variable describing the individuals
    parent1 = dict(
        age = 30,
        salaire_net = 1300*12, # Annual basis
        ),

 # Variable describing the entity
    menage = dict(loyer = 5000, # Annual basis
            statut_occupation_logement = 1,
            taxe_habitation = -600,
            ),
    )


# Create a simulation from a scenario
simulation = scenario.new_simulation()

# Calcul of the 'impot sur le revenu des personnes physiques'
impot = simulation.calculate('irpp', '2017')
allocations_familiales = simulation.calculate('af', '2017-12')
rev_disp = simulation.calculate('revenu_disponible','2017')
csg_1 = simulation.calculate('csg','2017')
brut = simulation.calculate('assiette_csg_non_abattue','2017-12')
TH = simulation.calculate('taxe_habitation','2017')
rsa = simulation.calculate('rsa','2017-12')
PpA = simulation.calculate('ppa','2017-12')
rev_net = simulation.calculate('revenu_net','2017')

print(impot)
print(allocations_familiales)
print(rev_disp)
print(csg_1)
print(brut)
print(TH)
print(rsa)
print(PpA) # C'est ce montant qui nous interesse
print(rev_net)
```

**Comment by benjello** [comment]
@deFranchisG : tu renseigne le salaire net et pas le salaire_de_base (brut). Il se peut qu'il y ait un problème sur le calcul de la base ressource car les salaires sont calculés brut -> imposable -> net.

Normalement on peut introduire le net et calculer ce qui vient en aval mais il y a peut-être un problème de période annuelle vs mensuelle dans les initialisations

**Comment by deFranchisG** [comment]
Oui c'est vrai j'ai renseigné un salaire net, pour coller à l'exemple donné sur service public.

Effectivement, en mettant un salaire brut de 1612 € j'obtiens bien un salaire net de 1300 €, mais une PA de 137 €, ce qui ne colle pas avec la PA de 54€ obtenue en renseignant directement une salaire net de 1300 €.

**Comment by benjello** [comment]
@deFranchisG : si tu veux vraiment partir du net,  tu peux essayer d'utiliser la "réforme" [de_net_a_brut](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/de_net_a_brut.py) (je ne suis pas sûr à 100 % qu'elle fonctionne encore après les différents refactoring mais cela vaut le coup de le tenter... )

**Comment by deFranchisG** [comment]
En fait, dans mon dernier message j'ai confondu les variables rev_net et salaire_net. La différence entre les deux est que dans rev_net il y a en fait la CSG/CRDS imposable. 
Du coup pour avoir un salaire_net de 1300 € il faut un salaire brut de 1671 €.

Mais avec un salaire brut de 1671 € on calcule une Prime d'activité de 121.53 €, alors qu'avec un salaire net de 1300 on a une PA de 54 €.

**Comment by guillett** [comment]
L'écart constaté avec un salaire net de 1300 provient de l'utilisation du _pilier_ du RSA à 545,48 € à la place de celui de la PPA qui est à 526,25 € dans la formule de la PPA. J'ai commencé #855 mais je voudrais aussi corriger le forfait logement (qui se base pour le moment sur le _pilier_ du RSA aussi).

**Comment by guillett** [comment]
@deFranchisG, c'est bon (normalement 🙂).

J'ai mis à jour la PPA sur 18.1.1 et je l'ai déployé sur [mes-aides.gouv.fr](https://mes-aides.gouv.fr/).
J'ai aussi crée une simulation dont [les résultats sont accessibles](https://mes-aides.gouv.fr/foyer/resultat?situationId=5a302c994467e91675d7fa7f) (arrondis à la dizaine d'euros près).

Le résultat brut à 36.37 est visible dans [la réponse d'OpenFisca](https://mes-aides.gouv.fr/api/situations/5a302c994467e91675d7fa7f/openfisca-response).

Tu serais dispo pour discuter de ton usage d'OpenFisca (dans [nos locaux](https://github.com/sgmap/beta.gouv.fr/wiki/Locaux#s%C3%A9gur) lors d'un standup le mercredi midi ou à un autre moment ou/et endroit ? Je pense que connaître ta perspective serait très enrichissant.

**Comment by deFranchisG** [comment]
@guillett Merci !

Avec grand plaisir pour discuter ! Je ne parviens pas à trouver ton adresse de messagerie, mais normalement sur mon profil tu dois voir la mienne. Envoie-moi un ping !
