### ISSUE TITLE
Impossible d'estimer une réforme sur les taux de cotisations chômage des salariés

### ISSUE THREAD

**Issue by deFranchisG** [openfisca/openfisca-france#851]
La procédure standard d'estimation d'une réforme décrite dans http://openfisca.org/doc/coding-the-legislation/reforms.html ne fonctionne pas lorsqu'il s'agit de modifier le taux de cotisation chômage des salariés (parameters.cotsoc.sal.commun.assedic) : le changement de taux n'est pas pris en compte. Le même problème se produit pour l'ensemble des taux de cotisation qui se trouvent dans parameters.cotsoc.sal.commun.

C'est dommage, car la bascule de cotisations/CSG contenue dans le PLFSS 2018 consiste justement à supprimer les taux de cotisation chômage et vieillesse qui sont définis dans parameters.cotsoc.sal.commun.

Après investigation, il me semble que la cause de ce problème est due au fait que lors de la construction de l'arbre des paramètres (à l'aide de la fonction FranceTaxBenefitSystem), le taux de cotisation chômage, est recopié dans un noeud cadres (parameters.cotsoc.cotisations_salarie.prive_cadre.assedic) et dans un noeud non cadres (parameters.cotsoc.cotisations_salarie.prive_non_cadre.assedic) et ce sont les paramètres de ces nouveaux noeuds qui sont utilisés pour calculer les cotisation salariales d'assurance chômage. 

Or lorsqu'on modifie le taux de cotisation chômage à l'aide de la fonction modify parameters, on modifie un taux qui n'est pas utilisé dans le calcul des cotisations chômage. 

def modify_parameters(parameters):
    reform_year = 2017
    reform_period = period(reform_year)
    parameters.cotsoc.sal.commun.assedic[0].rate.update(period=reform_period, value=0.0)
    return parameters

Les taux des noeuds parameters.cotsoc.cotisations_salarie.prive_cadre.assedic et  parameters.cotsoc.cotisations_salarie.prive_non_cadre.assedic restent inchangés.

Pour pouvoir simuler la réforme, je vois deux solutions : 
1) modifier les taux des noeuds parameters.cotsoc.cotisations_salarie.prive_cadre.assedic et parameters.cotsoc.cotisations_salarie.prive_non_cadre.assedic à l'aide de la syntaxe suivante : 

def modify_parameters(parameters):
    reform_year = 2017
    reform_period = period(reform_year)
   parameters.cotsoc.cotisations_salarie.prive_cadre.assedic[0].rate.update(period=reform_period, value=0.0)
 parameters.cotsoc.cotisations_salarie.prive_non_cadre.assedic[0].rate.update(period=reform_period, value=0.0)
    return parameters

 mais cette syntaxe ne fonctionne pas, car curieusement le noeud cotisations_salarie n'est pas reconnu (AttributeError: 'ParameterNode' object has no attribute 'cotisations_salarie'), alors même qu'il apparaît lorsqu'on fait un print(parameters.cotsoc)

2) recalculer l'ensemble de l'arbre des paramètres, après avoir modifié les paramètres communs cadres non cadres, en appelant la fonction preprocess_parameters. Mais je n'ai pas réussi à trouver la bonne syntaxe pour faire cette dernière opération.

**Comment by Anna-Livia** [comment]
Bonjour @deFranchisG, merci pour ton retour.

Je reproduis en effet ce bug, c'est un usage auquel nous n'avions pas pensé. 
Nous ajoutons cela au backlog, tu pourras suivre l'évolution sur cette issue :)

Bonne journée !

**Comment by benjello** [comment]
En attendant une solution plus complète annoncée par @Anna-Livia, tu peux essayer ce workaround:
```python
parameters.cotsoc.children['cotisations_salarie'].children['prive_non_cadre'].children['assedic'][0].rate.update(
    start = reform_period, value=0.0)
```

**Comment by deFranchisG** [comment]
Merci Anna-Livia et Mahdi !
En attendant, le workaround fonctionne très bien !

**Comment by laem** [comment]
@deFranchisG Bravo pour l'analyse, le problème vient en effet du fichier `preprocessing.py` (plus d'infos  [ici](https://github.com/openfisca/openfisca-france/issues/409#issuecomment-173160942)).

[Cette nouvelle fonctionnalité](http://openfisca.org/doc/coding-the-legislation/legislation_parameters.html#computing-a-parameter-that-depends-on-a-variable-fancy-indexing) des paramètres est une piste pour corriger le problème. 

Le script `preprocessing.py` est un hack qui répond au besoin de logique dans les paramètres des cotisations sociales. C'est une des raisons du travail sur une nouvelle base qui ne fait pas la distinction entre paramètres et formules, exemple avec cette [cotisation chômage](https://github.com/sgmap/syso/blob/master/r%C3%A8gles/r%C3%A9mun%C3%A9ration-travail/cotisations/ok/chomage.yaml#L31).

**Comment by fpagnoux** [comment]
Si le workaround fonctionne, je ferme l'issue :)
