### ISSUE TITLE
Mettre à jour les paramètres venant des barèmes IPP

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#852]
Comme souligné par @ClaireLeroyIPP (qui teste le calcul de l'impôt récent) sur slack et par @deFranchisG (#850), nombre de paramètres ne sont pas à jour alors qu'ils ont été mis à jour sur les barèmes IPP. 

Il serait peut-être utile de les importer dans openfisca en faisant tourner la moulinette décrite [ici](https://github.com/openfisca/openfisca-france/blob/744b7041159c0778bdbbbc0f8dbe7ff32111efb1/openfisca_france/scripts/parameters/baremes_ipp/README.md).

Qu'en pensez-vous ? @Anna-Livia @sandcha @fpagnoux

**Comment by benjello** [comment]
@Anna-Livia @sandcha @fpagnoux @michelbl : pourriez-vous m'expliquer pourquoi il y a deux façons possibles pour mettre à jour les paramètres à partir des barèmes IPP ?
Pourquoi l'option passage par le serveur openfisca existe-t-elle ?
Est-ce juste la dépendance à gnumeric ?
Merci !

**Comment by benjello** [comment]
Il semble aussi que la documentation décrite [ici](https://github.com/openfisca/openfisca-france/blob/744b7041159c0778bdbbbc0f8dbe7ff32111efb1/openfisca_france/scripts/parameters/baremes_ipp/README.md) soit obsolète car elle ne génère que des XML.

**Comment by michelbl** [comment]
Lorsqu'on est passé aux paramètres en YAML, l'import des barèmes IPP n'a pas été terminé, cf #837. Il faut soit rajouter un script pour passer de XML vers YAML, soit réécrire des parties des anciens scripts.

**Comment by sandcha** [comment]
On a des scripts XML vers YAML dans [v16_2_to_v17/](https://github.com/openfisca/openfisca-core/tree/master/openfisca_core/scripts/migrations/v16_2_to_v17).
Et un script de réduction de la profondeur de l'arborescence (car paths limités sous windows) [reduce_parameters_paths.py](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/scripts/parameters/reduce_parameters_paths.py).
Mais la chaîne complète nécessite encore des interventions manuelles.

**Comment by benjello** [comment]
Il ya des problèmes en amont:
````
Traceback (most recent call last):
  File "./openfisca_france/scripts/parameters/baremes_ipp/convert_ipp_xlsx_to_openfisca_xml.py", line 29, in <module>
    from merge_ipp_xml_files_with_openfisca_parameters import merge_ipp_xml_files_with_openfisca_parameters
  File "/home/benjello/openfisca/openfisca-france/openfisca_france/scripts/parameters/baremes_ipp/merge_ipp_xml_files_with_openfisca_parameters.py", line 19, in <module>
    from openfisca_core import legislationsxml
ImportError: cannot import name legislationsxml
````

**Comment by fpagnoux** [comment]
> Pourquoi l'option passage par le serveur openfisca existe-t-elle ?

Parce qu'on a pas été capable de faire tourner le script sur un Mac, et que personne n'avait de linux dans l'équipe

**Comment by Morendil** [comment]
Je ferme en faveur de #1164
