### ISSUE TITLE
Prise en compte de l'emploi de salariés à domicile pour crédit /réduction d'impôts

### ISSUE THREAD

**Issue by vspanneut-preconys** [openfisca/openfisca-france#854]
Il semble que sur `FoyerFiscal`, les variables `f7db` , `f7df`, `f7dg`, `f7dl` , `f7dq` ne sont pas prises en compte pour déterminer les valeurs de  `credits_impot` et `reductions` alors que ces crédits/réductions sont toujours valables ( voir https://www.impots.gouv.fr/portail/www2/fichiers/documentation/brochure/ir_2017/files/assets/common/downloads/publication.pdf p. 169).
La source semble être dans la présence d'une date de fin au `2013-12-31` dans le calcul de `saldom` et `saldom2` dans respectivement `prelevements_obligatoires/impot_revenu/reductions_impot.py` et
`prelevements_obligatoires/impot_revenu/credits_impot.py` .

**Comment by benjello** [comment]
Bonjour @vspanneut-preconys : en effet, cela commence à être pris en compte [ici](https://github.com/openfisca/openfisca-france/tree/update-irpp).

**Comment by vspanneut-preconys** [comment]
Merci pour votre réponse @benjello .
