### ISSUE TITLE
Taxe habitation, TypeError: The numpy boolean negative

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france#860]
## Problème 
En faisant un `simulation.calculate("revenu_disponible", year)` ,  sous `OpenFisca 18.11.0` j'obtiens l'erreur suivante :

```python
/Users/adrienpacifico/.local/share/virtualenvs/qf_lowering/lib/python2.7/site-packages/openfisca_france/model/prelevements_obligatoires/taxe_habitation.pyc in formula(menage, period, parameters)
    169 
    170 
--> 171         return - exonere_taxe_habitation * 0

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

```
## Explication
Cela semble être du à   [`- exonere_taxe_habitation * 0`](https://github.com/openfisca/openfisca-france/blob/93a1c17eb85c4fe0016de1fe5cdd8fdd99a7cae0/openfisca_france/model/prelevements_obligatoires/taxe_habitation.py#L171) qui effectue une soustraction à un array de booléen. 

## Solution de fortune 
Étant donné qu'ensuite l'array est multiplié par 0, je n'ai pas eu de scrupule à enlever le `-`, ce qui supprime mon erreur. Je ne fais pas de PR car je ne sais pas du tout si c'est approprié (et je ne suis pas sûr de comment faire). @benjello gitblame te désigne comme la personne concernée ;-) !

### Questionnement

Je ne sais pas pourquoi j'ai obtenu soudainement cette erreur alors que je ne l'obtenais pas avant sur les mêmes simulations...

**Comment by benjello** [comment]
Essaie avec des parenthèses
````
- (exonere_taxe_habitation * 0)
````

Je pense que c'est dû aux version récentes de numpy

**Comment by adrienpacifico** [comment]
Mahdi, 
Tu sembles avoir raison pour numpy.

NumPy 1.13.0 Release Notes:
[Compatibility notes/DeprecationWarning to error](
https://docs.scipy.org/doc/numpy-1.13.0/release.html#deprecationwarning-to-error):

> negative(bool_), TypeError when negative applied to booleans.

Ta solution fonctionne, merci !

**Comment by benjello** [comment]
@fpagnoux : si tu repère toutes les erreurs de ce genre et que ton code tourne avec numpy 1.13 merci de nous le signaler.

**Comment by Morendil** [comment]
Je ne vois rien à corriger ici, je ferme.
