### ISSUE TITLE
Gestion variables revenus fonciers

### ISSUE THREAD

**Issue by bfabre01** [openfisca/openfisca-france#861]
Dans OF France coexistent les variables `revenus_locatifs` (variable mensuelle) et `revenus_fonciers_minima_sociaux` (mensuelle aussi, mais découlant des revenus fonciers des déclarations fiscales). Comment gérer ces deux variables, qui traitent des mêmes revenus ?

**Comment by guillett** [comment]
Aujourd'hui, [`revenus_fonciers_minima_sociaux`](https://legislation.openfisca.fr/revenus_fonciers_minima_sociaux) utilise [`revenus_locatifs`](https://legislation.openfisca.fr/revenus_locatifs) via [`f4ba`](https://legislation.openfisca.fr/f4ba).

**Comment by benjello** [comment]
Tout cela est bien compliqué et j'en suis en particulier responsable.
Problème: on a des revenus fonciers (f4ba) et micro-foncier (f4be) au niveau annuel et des revenus locatifs au niveau mensuel entrant dans les minima sociaux.
Pour simplifier je suggère:
 - renommer `revenus_locatifs` en `revenus_fonciers` qu'on garde en mensuel sur l'individu
 - renommer f4ba en `revenus_fonciers_imposables` en annuel (en précisant le CERFA field) sur le foyer fiscal
 - renommer f4be en `revenus_micro_fonciers_imposables` en annuel également

Et bien sûr il faut tracer les f4ba /12 partout dans le code.

Qu'en pensez-vous ?

**Comment by guillett** [comment]
Je te suis sur le sujet car tu as bien plus de visibilité. Je ferai mes modifications côté client [mes-aides.gouv.fr - mes-aides-ui](https://github.com/sgmap/mes-aides-ui)

**Comment by Morendil** [comment]
Je ferme après avoir [consolidé sur le wiki](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le).
