### ISSUE TITLE
Impôt sur le revenu : Réduction d'impôt sous condition de revenu

### ISSUE THREAD

**Issue by vspanneut-preconys** [openfisca/openfisca-france#863]
Bonjour,
Il semble que la version actuelle ne traite pas la réduction sous condition de revenu (intervenant après la décote mais avant les réductions classiques) décrit ici : http://bofip.impots.gouv.fr/bofip/2495-PGP.html
J'ai inclus cette variable dans ce commit tiré de la branche update-irpp-rebase : 
https://github.com/vspanneut-preconys/openfisca-france/commit/0373b1923cb4e8f82a4da862c01dafffe10d7769

**Comment by claireleroy** [comment]
Cette réduction a été ajouté par la PR #918
