### ISSUE TITLE
Changements 2018 des cotisations sociales

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#864]
Voici une liste des changements repérés. Certains points sont peut-être déjà intégrés dans OpenFisca. Liste probablement à compléter. 

- le plafond de la sécurité sociale
- le SMIC
- les cotisations salariales de maladie et chômage baissent
- la CSG sur les salaires augmente
- vérifier la valeur de l'AGS
- le CICE baisse, en attendant qu'il change de nature en 2019
- comme d'habitude, une petite partie des taux de versement transport est modifiée

**Comment by laem** [comment]
@deFranchisG 
une partie de ces items sont faits dans ta réforme : https://github.com/deFranchisG/PLF2018/commit/431cba15e496d42f9ef73a8be871974219c408b6

**Comment by monbocal** [comment]
J'ajoute ce lien : https://www.service-public.fr/particuliers/actualites/A12255

**Comment by laem** [comment]
Ces changements sont (presque entièrement) faits ici : sgmap/syso/pull/143, il faudra les décalquer.

**Comment by laem** [comment]
Commencé ici : #867

**Comment by benjello** [comment]
@Morendil : pourrais-tu me confirmer que tu as bien tout intégré ? Si c'est le cas fermons ce ticket.
Et surtout un grand merci !

**Comment by benjello** [comment]
Good catch @laem. Je mets à jour tout cela.

**Comment by benjello** [comment]
Done in #1094. 
@Morendil @laem : me dire si vous ne voyez rien d'autres pour savori si je ferme.
Merci !
