### ISSUE TITLE
AL primo accédant à 40e avec loyer de 0e

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#869]
Simulation de test : 5a5371dfab31d64c4fe8cb87
Ludwig : https://mes-aides.gouv.fr/tests/5a5374a6ab31d64c4fe8cbe2/show

Problème : dans cette situation, l'AL pour un primo accédant est accordé à hauteur de 40 euros - alors que la personne est à 0 euros de remboursement de prêt.
 
cc @guillett

**Comment by guillett** [comment]
Fixed by #875 .
