### ISSUE TITLE
Variables de patrimoine

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#872]
@benjello je voudrais faire un point avec toi sur les variables qui existent déjà dans OpenFisca France et que je pourrais utiliser pour prendre en compte correctement le patrimoine dans les bases ressources du RSA et des AL cf. https://github.com/betagouv/mes-aides-ui/issues/617.

J'imaginais utiliser/créer ces variables là :
- la valorisation totale du patrimoine, peut-être vu comme la somme de :
    - l'immobilier ayant généré des revenus imposables ;
    - l'immobilier n'en ayant pas généré des revenus imposables ;
    - le mobilier ayant généré des revenus imposables et
    - le mobilier n'en ayant pas généré des revenus imposables.

J'imaginais _recycler_ des variables de l'impôts sur la fortune, ou bien l'impôts sur le patrimoine immobilier, mais je ne sais pas ce qui existe et ce qui reste à créer…

**Comment by benjello** [comment]
@guillett : quelle magnifique initiative !

Tu as parfaitement raison, il faut recycler les variables préexistantes pour des raisons de cohérence d'ensemble (éviter d'introduire des doublons etc).

Et oui il faut recycler [les variables de l'ISF](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/isf.py).

Tu peux renommer les variables de la feuille d'impôt de l'ISF vers des noms meaningful tout en gardant la référence au cerfa comme pour ceratines variable de l'impôt sur le revenu.

Essaie de créer le moins possible de variables et n'hésitez pas à partager tes questionnements et j'essaierai d'être utile.

**Comment by guillett** [comment]
Merci @benjello.

À quoi correspond `b1ab` ?
Je ne vois rien dans [2725_1954.pdf](https://github.com/openfisca/openfisca-france/files/1632422/2725_1954.pdf) ni dans les annexes mais j'ai peut-être raté quelque chose.

Merci !

**Comment by benjello** [comment]
`b1ab`: Page 3 section case AB de la déclaration que tu cites.
Et ainsi de suite. je ne me souviens plsu ce que veut dire la première lettre `b`.

**Comment by guillett** [comment]
La subdivision pour les calculs des prestations est _orthogonale_ à celle faite pour l'ISF (ISF par type d'actifs, prestations selon l'actif est productif de revenus imposable ou non).

Une possibilité est de subdiviser certaines variables fiscales en deux parties (loué/non-loué - productif/non-productif) et de sommer pour le fiscal et d'utiliser les découpes pour les prestations…

Note : Je pense aux variables suivantes :

- 1AC (autres immeubles)
- 1BK (autres biens)
-

**Comment by Morendil** [comment]
Je ferme après avoir [consolidé sur le wiki](https://github.com/openfisca/openfisca-france/wiki/Mise-en-coh%C3%A9rence-du-mod%C3%A8le).
