### ISSUE TITLE
Vérifier la formule de calcul de l'ASI/ASPA pour un couple 

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#876]
Suite à un retour utilisateur, j'ai regardé la formule de calcul de l'ASI/ASPA. Je me demande si toutes les ressources sont bien prises en compte, par exemple l'AAH.

Le lien vers la formule : https://legislation.openfisca.fr/asi_aspa_base_ressources_individu
```
    # Inclus l'AAH si conjoint non éligible ASPA, retraite et pension invalidité
    aah = individu('aah', three_previous_months, options = [ADD])
    aah = aah * not_(aspa_eligibilite) * not_(asi_eligibilite) * not_(pension_invalidite)
```

Les documents sur service-public laissent penser que l'AAH est cependant prise en compte tout le temps : https://www.service-public.fr/particuliers/vosdroits/F16940 et https://www.service-public.fr/particuliers/vosdroits/F16871 .

Il faut aussi tenir en compte de https://www.service-public.fr/particuliers/vosdroits/F16941 - même si cela semble être le cas après quelques tests.

La simulation qui a tout déclenché : https://mes-aides.gouv.fr/foyer/resultat?situationId=5a574d9acde8444b5eb661b3 . Je me renseigne pour en savoir plus.

**Comment by benjello** [comment]
Vérifier aussi si cela n'a pas été le cas un moment puis a évolué. L'AHH a été fortement revalorisée dernièrement.

**Comment by Morendil** [comment]
@guillett Ton travail en cours couvre-t-il ce cas ?

**Comment by Morendil** [comment]
Alors on a exactement un test KO, `tests/mes-aides.gouv.fr/test_mes_aides_546b087df76135f463c9e1da.yaml`, dont le nom est "L'AAH du demandeur est exclue de la base ressource" (c'est bien le commentaire qui est mensonger, _comments always lie_),  et dont la description précise:

> L' AAH du demandeur doit être exclue : application lettre ministérielle n°558 G/79 du 19/03/1982 et annexe circulaire Cnav n°2007/15 du 01/02/2007

qui sont justement les deux textes que je citais.

Le test porte sur un individu seul: on est donc dans le cas B de la LM, qui n'est pas considéré comme "rare". Le test est très ancien (février 2015, dfbfb9076d932e24e6a1735e9281d26c15c0426c).

Je transforme la branche en PR qui va fermer l'issue en clarifiant par un commentaire.
