### ISSUE TITLE
Erreur 500 sur calcul de la PPA

### ISSUE THREAD

**Issue by fpalluel** [openfisca/openfisca-france#880]
Bonjour,
En tentant un calcul de la PPA sur un jeux de données standard, une erreur 500 est renvoyée avec le message suivant :
`The parameter 'prestations.prestations_familiales.paje.clca.sansab_tx_inactif' requested by variable 'paje_clca' was not found in the 2018-03-01 tax and benefit system.`

Ce taux n'existe t'il vraiment plus en 2018 ou faut-il juste le mettre à jour pour 2018 ?
D'avance, merci !

**Comment by Anna-Livia** [comment]
Bonjour @fpalluel,
Merci pour votre message. En effet, il faut qu'on investigue cet éléments.

@benjello :

**Comment by Anna-Livia** [comment]
Bonjour @fpalluel ,

Merci pour votre message. La `paje_clca`  n'existe plus depuis (avril 2017) [https://www.service-public.fr/particuliers/vosdroits/F313] .

@guillett Il me semble que  `paje_clca` a été remplacée par la [`paje_prepare`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/paje.py#L317) mais celle -ci est une imput varable. Est-ce que tu as des infos sur la modélisation  ?

**Comment by fpalluel** [comment]
Merci pour la rapidité de votre réponse !
Je viens de remarquer que les calculs du RSA et de la CMU-C sont aussi impactés par ce problème...

**Comment by fpalluel** [comment]
Merci !
