### ISSUE TITLE
Différence dans le montant des impôts net

### ISSUE THREAD

**Issue by xplodwild** [openfisca/openfisca-france#885]
Bonjour à tous,

En voulant comparer les valeurs simulées d'OpenFisca avec les valeurs du simulateur d'impôts officiel, je me retrouve avec un écart dans le montant des impôts qui est calculé.

Avec les données suivantes:
- Couple marié, nés en 1970
- 29023€ de retraite (1AS)
- 522907€ de revenus fonciers imposables (4BA)

J'obtiens via le simulateur en ligne (modèle simplifié), un montant net à payer de 290286€ (209235€ d'impôts sur le revenu net), or via OpenFisca j'obtiens un ip_net/irpp de 188173€.

Le RFR/RBG est identique (549028), CSG également (42878), et CRDS également (2615).

Par quoi est alors provoqué cet écart dans le montant des impôts ?
Ci-dessous la requête vers l'API Web qui est réalisée:

```
{"familles":{"Bidochon":{"enfants":[],"parents":["parent_1","parent_2"]}},"foyers_fiscaux":{"Maison":{"declarants":["parent_1","parent_2"],"f4ba":{"2017":522907},"fon":{"2017":null},"irpp":{"2017":null},"isf_apres_plaf":{"2017":null},"ip_net":{"2017":null},"rbg":{"2017":null},"rfr":{"2017":null},"rni":{"2017":null},"maries_ou_pacses":{"2017":true}}},"individus":{"parent_1":{"retraite_imposable":{"2017":29023},"csg":{"2017":null},"crds":{"2017":null}},"parent_2":{"csg":{"2017":null},"crds":{"2017":null}}},"menages":{"menage_1":{"conjoint":["parent_2"],"impots_directs":{"2017":null},"personne_de_reference":["parent_1"],"revenu_disponible":{"2017":null},"revenu_net":{"2017":null}}}}
```

Merci

**Comment by benjello** [comment]
@xplodwild : nous avons un peu de retard sur l'évolution des impôts ... mais nous essayons de le rattraper. Du travail est en train d'être accompli sur cette [branche](https://github.com/openfisca/openfisca-france/tree/update-and-test-irpp). Dès qu'elle est intégrée, nous testerons votre situation.

cc @ClaireLeroyIPP  @fpagnoux (pour un coup de main sur le rebase à venir)

**Comment by xplodwild** [comment]
Merci pour la réponse rapide. Pas d'inquiétude, je posais surtout la question pour m'assurer que ça n'était pas un problème de compréhension des champs ou de ma requête.

Je vous laisse le choix de clore le ticket, mais vous souhaitez peut-être le garder sous le coude pour vos tests ;)

**Comment by adrienpacifico** [comment]
Bonjour,
J'avais également quelques problèmes sur les calculs de l'impôt pour les années récentes avec `OF-France 19.0.1`.

 Sur la version pip d'`openfisca-france` de ce jour 
(`20.7.0`), j'ai des différences par rapport au calculateur DGFiP ont disparues sur 2016. 

@xplodwild peut être en est-il de même pour votre simulation ?

Pour ma part il semblerait que les écarts de quelques euros étaient du à une non actualisation des barèmes de l'Irpp.

@benjello ne serait-il pas intéressant qu'il existe des warnings possible pour indiquer qu'un paramètre est calculé sur une version probablement datée du système socio-fiscal ? Ça éviterait des erreurs bêtes (e.g, un calculate sur l'année 2020 m'avertirais que je fais une simulation sur des paramètres "hypothétiques").

**Comment by benjello** [comment]
@adrienpacifico : je partage ton point de vue en terme d'objectif mais pour savoir qu'un paramètre est périmé, il faut renseigner pour chaque paramètre sa fréquence attendue de modification et/ou la prochaine date de modification. Ce qui représente un travail conséquent mais qque peux valoir le coup, en effet.

**Comment by benjello** [comment]
@adrienpacifico : puis-je fermer ce ticket ? L'idéal serait de rajouter le test présenté ici.
cc @ClaireLeroyIPP

**Comment by adrienpacifico** [comment]
> puis-je fermer ce ticket ?

Vu que ça semble être ok pour @xplodwild , je pense que c'est bon.


>  il faut renseigner pour chaque paramètre sa fréquence attendue de modification et/ou la prochaine date de modification

Simplement renseigner une `end_date` estimée par la personne ajoutant le paramètre avant révision dans le yaml pourrait être une solution plus accessible et progressive.

```
brackets:
- rate:
    2017-01-01:
      value: 0.3
  threshold:
    2017-01-01:
      value: 27086.0
- rate:
    2018-01-01:
      value: unactualized
  threshold:
    2018-01-01:
      value: unactualized
```

Avec un warning qui dirait "attention 78 paramètres sont potentiellement non-actualisé dans votre simulation" avec une invitation à contribuer et à actualiser les paramètres en questions.

**Comment by benjello** [comment]
Merci @adrienpacifico : je vais fermer ce ticket dès que le test sera ajouté s'il le faut.
@Anna-Livia et @maukoquiroga : quelle est la bonne pratique dans ce cas.   

@adrienpacifico : Peux-tu ouvrir un ticket pour discuter de ton point dans [openfisca-core](https://github.com/openfisca/openfisca-core) ?

**Comment by adrienpacifico** [comment]
Fait https://github.com/openfisca/openfisca-core/issues/629

**Comment by Morendil** [comment]
L'erreur d'origine semble être résolue.
