### ISSUE TITLE
Règles de calcul APL et retraités

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#889]
Je viens de recevoir plusieurs dossiers pour l'AL de retraités. A chaque fois, le même schéma, et des résultats de la Caf qui différent. J'ai compilé ici tous ces cas avec des liens vers les simulations Ludwig :

## 1. Dossier 5a6056eed6fcd84089edd5fa
Simulation corrigée 5a7072a98b19992fa2906af2  et https://mes-aides.gouv.fr/tests/5a7072368b19992fa2906abd/show
Différence entre l'attribution d'une part et la simulation Mes Aides / Caf concordante

Mes Aides | Simulateur CAF | Attribution CAF | [Sans abattement](https://github.com/openfisca/openfisca-france/issues/889#issuecomment-362576038)
-----------|-----------------|------------------|----
69.72 | 71 | 15 | 69

## 2. Dossier 5a69b29b1d190377302a6f80
https://mes-aides.gouv.fr/tests/5a7073848b19992fa2906b1a/show
Simulation Mes Aides différente de simulation Caf

Mes Aides | Simulateur CAF | Attribution CAF | [Sans abattement](https://github.com/openfisca/openfisca-france/issues/889#issuecomment-362576038)
-----------|-----------------|--------------------|--
122.75 | 49 | 47| 47.88

## 3. Dossier 5a65e035acce5154da85efe9
https://mes-aides.gouv.fr/tests/5a7077078b19992fa2906bfb/show
Simulation Mes Aides différente de simulation Caf

Mes Aides | Simulateur CAF | Attribution CAF | [Sans abattement](https://github.com/openfisca/openfisca-france/issues/889#issuecomment-362576038)
-----------|-----------------|----------------------|---
191.38 | 121 | 121| 119

## 4. Dossier 595df6da72a5ac39c17afe08
https://mes-aides.gouv.fr/tests/5a70857e8b19992fa2906f08/show
Simulation Mes Aides différente de simulation Caf

Mes Aides | Simulateur CAF | Attribution CAF | [Sans abattement](https://github.com/openfisca/openfisca-france/issues/889#issuecomment-362576038)
-----------|-----------------|--------------------|--
104.52 | 30 | 22 | 33.75

## 5. Dossier 5a71e1cd9a7bdd1d7a3e1bc7
https://mes-aides.gouv.fr/tests/5a72d6fde7d768364fe9ba53/show
Simulation Mes Aides différente de simulation Caf

Mes Aides | Simulateur CAF | Attribution CAF | [Sans abattement](https://github.com/openfisca/openfisca-france/issues/889#issuecomment-362576038)
-----------|-----------------|-----------------|-----
120 | 46 | 49 | 47.88

Autres dossiers :
5a7db243d7e09f619d5dd90d

**Comment by guillett** [comment]
Merci beaucoup @monbocal .

Pourrais-tu ajouter les récapitulatifs des simulations CAF que tu as réalisés ?

Merci beaucoup !

**Comment by monbocal** [comment]
@guillett Elles sont incluses dans les tests Ludwig

**Comment by monbocal** [comment]
Ajout d'un nouveau cas de test

**Comment by guillett** [comment]
Pour le premier dossier 5a6056eed6fcd84089edd5fa, je pense qu'il faut essayer de faire de la médiation avec la CAF. L'écart ne provient pas de l'abattement spécial

https://mes-aides.gouv.fr/trace?situationId=5a7072a98b19992fa2906af2
```
aide_logement<2018-01>
    als<2018-01>
        als_non_etudiant<2018-01>
            aide_logement_montant<2018-01>
                aide_logement_montant_brut<2018-01>
                    aide_logement_montant_brut_avant_degressivite<2018-01>
                        aide_logement_participation_personnelle<2018-01>
                            aide_logement_base_ressources<2018-01>
                                aide_logement_base_ressources_defaut<2018-01>
                                    rev_coll<2016>
```

**Comment by guillett** [comment]
En forçant `rev_coll<2016>` à zéro, c'est à dire en désactivant l'abattement :

Dossier | Valeur sans abattement
------|---------------------------------
1 - 5a7072a98b19992fa2906af2 | 69.7200
2 - 5a69b29b1d190377302a6f80 | 47.88999938964844
3 - 5a65e035acce5154da85efe9 | 119.62999725341797
4 - 595df6da72a5ac39c17afe08 | 33.7599983215332
5 - 5a71e1cd9a7bdd1d7a3e1bc7 | 47.88999938964844

Ces abattements sont-ils légitimes ?
Faut-il indiquer aux usagers qu'ils devraient signaler leur changement de situation ?



Notes :
```js
var situationId = process.argv[process.argv.length - 1]

var rp = require('request-promise')

function determinePeriod(request) {
    var periodKey = Object.keys(request.familles._.aide_logement_non_calculable)[0];
    return {
        request: request,
        period: {
            value: new Date(periodKey),
            key: periodKey
        }
    }
}

function addRevColl(simulation) {
    var request = simulation.request
    var rev_coll = request.foyers_fiscaux._.rev_coll || {}

    var revCollPeriod = (simulation.period.value.getFullYear()-2).toString()
    rev_coll[revCollPeriod] = 0

    request.foyers_fiscaux._.rev_coll = rev_coll

    return simulation
}

rp({
    json: true,
    url: `https://mes-aides.gouv.fr/api/situations/${situationId}/openfisca-request`,
})
.then(determinePeriod)
.then(addRevColl)
.then((simulation) => {
    return rp({
        json: true,
        url: 'http://localhost:2000/calculate',
        method: 'POST',
        body: simulation.request,
    })
    .then((response) => {
        simulation.response = response
        return simulation
    })
})
.then((simulation) => {
    console.log(simulation.response.familles._.aide_logement[simulation.period.key])
})
```

**Comment by monbocal** [comment]
@guillett Ce serait donc un problème d'abattement que nous calculons alors que nous ne devrions pas ?

**Comment by guillett** [comment]
Comme discuté avec @helaG, l'abattement est **à prendre** en compte mais si les personnes ne déclarent pas leur revenus aux impôts sachant qu'elles ne sont pas imposables et la CAF ne peut pas récupérer les revenus auprès de la DGFIP mais se base sur le déclaratif, l'abattement n'est pas appliqué et le montant de l'aide au logement ne vaut pas ce qu'il devrait !

To  be continued…

**Comment by monbocal** [comment]
Je viens de contacter les cas concernés afin de savoir quelles pièces justificatives elles avaient données et si elle déclaraient leurs revenus aux impots.

**Comment by guillett** [comment]
@monbocal peux-tu transférer les emails reçus à ce sujet à l'adresse contact@ ?

Merci !

**Comment by Morendil** [comment]
Traité par #948
