### ISSUE TITLE
Fiabilisation base ressources CMU-c ACS

### ISSUE THREAD

**Issue by SChiusa** [openfisca/openfisca-france#898]
La base ressources est-elle à jour dans OpenFisca ?

**Comment by guillett** [comment]
Quelles sont les ressources pour lesquelles vous avez des doutes ? (ie. pas prise en compte ou prise en compte de façon erronée)

Auriez des personnes qui pourraient faire des tests sur MA ou le PNDS ?
Par exemple pour les IJ.
