### ISSUE TITLE
Vérifier si d'autres formules peuvent être vulnérables à des bugs similaires à #844

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-france#904]
Le défaut pointé par #844 avait pour origine un comportement surprenant lorsqu'on demandait la valeur de `contrat_de_travail_debut` en dehors de la période de définition du scénario. Pour simplifier, on a implicitement un "contrat de travail par défaut" mais on ne tombait dessus que quand on évaluait *avant* la période de définition. Grâce à @fpagnoux on a une idée de ce qu'il faudrait écrire pour traiter ça plus symétriquement (il faut mettre un `last_or_next` quelque part), du coup c'est peut-être une bonne idée de relire le code où on évalue `contrat_de_travail_debut` de la même façon qu'on le faisait dans `allegements.py` pour `coefficient_proratisation`.

Or donc:

```
ack "'contrat_de_travail_debut', period"
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
161:        contrat_de_travail_debut = simulation.calculate('contrat_de_travail_debut', period)
224:        contrat_de_travail_debut = simulation.calculate('contrat_de_travail_debut', period)

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
150:        contrat_de_travail_debut = simulation.calculate('contrat_de_travail_debut', period)
300:        contrat_de_travail_debut = simulation.calculate('contrat_de_travail_debut', period)

openfisca_france/model/revenus/activite/salarie.py
645:        contrat_de_travail_debut = simulation.calculate('contrat_de_travail_debut', period)
```

**Comment by fpagnoux** [comment]
Si tu mets l'attribut `requested_period_last_or_next_value` dans la variable `contrat_de_travail_debut` à sa déclaration, tu n'as pas besoin de faire quoi que ce soit de spécifique quand tu l'appelles. Donc a priori, le problème ne se reproduira pas pour cette variable.

**Comment by Morendil** [comment]
Yep ! Je n'avais pas en tête au moment de créer cette issue que c'était un attribut de la variable (vs par exemple un paramètre de l'appel). On ferme donc, merci encore. :)
