### ISSUE TITLE
Création de tests sur l'impôt sur le revenu

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#920]
Suite aux PR relatives à la mise à jour de l'impôt sur le revenu (PR #906 à #919), il faudrait associer à chacun de ces changements, un ou deux tests représentatifs qui permet de tester les grands dispositifs de l'IR. 
Ces tests pourront être générés via comparaison avec les simulations de l'impôt de la DGFiP [ici](https://www3.impots.gouv.fr/simulateur/calcul_impot/2018/index.htm). Les scripts permettant de générer ces tests de manière automatique feront l'objet d'une PR ultérieure (PR #1024).

Liste des tests à créer : 

- Tests charges déductibles (PR #907) : 
  - [x] Cas type d'un célibataire sans enfants avec des charges déductibles non plafonnées
- Tests taxation des revenus du capital (PR #908) (PR #1034): 
  - [ ] Cas type d'un célibataire sans enfants avec des revenus du capital (plus-values , valeurs mobilières:  cases f2 et f3) avant 2013
  - [ ] Cas type d'un célibataire sans enfants avec des revenus du capital (plus-values , valeurs mobilières: cases f2 et f3) après 2013
- Tests divers crédits et réductions d'impôt (PR #909)
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'donapd'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'dfppce'* 
  - [x] Cas type d'une famille avec 2 enfants percevant un crédit d'impôt *'ci_garext'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'invlst'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'patnat'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'spfscpi'*
  - [x] Cas type d'un célibataire sans enfants percevant un crédit d'impôt *'assloy'*
  - [x] Cas type d'un célibataire sans enfants percevant un crédit d'impôt *'inthab'*
- Tests réductions d'impôt pour investissements immobiliers (PR #910)
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'scelli'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'duflot'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'rpinel'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'resimm'*
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'locmeu'*
- Tests réduction d'impôt pour investissements forestiers (PR #911)
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'invfor'
- Tests réduction d'impôt spéciale DOM-TOM (PR #912)
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'doment'
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'domlog'
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'domsoc'
- Tests réduction qualité environnementale (PR #913)
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'quaenv' avec bouquet 
  - [ ] Cas type d'un célibataire sans enfants percevant une réduction d'impôt 'quaenv' sans bouquet
- Tests réduction/crédit pour emploi d'un salarié à domicile (PR #914)
  - [x] Cas type d'un célibataire actif sans enfants percevant un crédit d'impôt *'saldom'*
  - [x] Cas type d'un célibataire inactif sans enfants percevant une réduction d'impôt *'saldom'*
- Tests réduction souscription au capital de PME (PR #915)
  - [x] Cas type d'un célibataire sans enfants percevant une réduction d'impôt *'cappme'*
- Tests crédit pour dépenses d'aide aux personnes (PR #916)
  - [x] Cas type d'un célibataire sans enfants percevant un crédit d'impôt *'aidper'*
- Tests imposition des revenus non salariaux (PR #917)
  - [x] Cas type d'un célibataire sans enfants avec des bénéfices agricoles faibles (régime du forfait agricole)
  - [x] Cas type d'un célibataire sans enfants avec des bénéfices agricoles élevés (régime du bénéfice réel)
  - [x] Cas type d'un célibataire sans enfants avec des bénéfices industriels et commerciaux faibles (régime micro-BIC)
  - [x] Cas type d'un célibataire sans enfants avec des bénéfices industriels et commerciaux élevés (régime du bénéfice réel)
  - [x] Cas type d'un célibataire sans enfants avec des revenus de locations meublés
  - [ ] Cas type d'un célibataire sans enfants avec des bénéfices non commerciaux faibles (régime micro-BNC)
  - [ ] Cas type d'un célibataire sans enfants avec des bénéfices non commerciaux élevés (régime du bénéfice réel)
- Tests plafonnement du quotient familial (PR #918)
  - [x] Cas type d'un couple marié 3 enfants dont le quotient familial est plafonné
  - [x] Cas type d'un couple marié 2 enfants dont le quotient familial est plafonné (handicap), cases P, F cochees, nbG = 1, nbI = 1
  - [x] Cas type d'un célibataire 1 enfant dont le quotient familial est plafonné (parent isolé), case T
  - [x] Cas type d'un veuf cochant les cases W et G
- Tests réduction complémentaire intervenant juste après le plafonnement du quotient familial
  - [ ] Cas type d'un célibataire domicilié en Martinique, Guadeloupe ou Réunion
  - [ ] Cas type d'un célibataire domicilié en Guyane ou Mayotte

**Comment by Morendil** [comment]
Corrigée par #1193
