### ISSUE TITLE
Simulation fiscalité d'entreprise

### ISSUE THREAD

**Issue by etnbrd** [openfisca/openfisca-france#923]
Hello,

Je travaille sur un simulateur de création/gestion d'entreprise à destination des freelances.
Est-ce que openfisca permet de calculer la fiscalité des entreprises ?

Je trouve des variables qui semblent indiquer que oui ([`cotisations_employeur`](https://legislation.openfisca.fr/cotisations_employeur)), mais quand je [creuse](https://github.com/openfisca/openfisca-france/blob/5fd9375c8a78787c242b21731d18ed12d3f94f15/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/base.py#L9) j'ai l'impression que l'individu sur lequel s'applique ces variables sont les salariés eux-même.

Je trouve aussi des variables qui semblent s'appliquer à des entreprises ([`entreprise_bilan`](https://legislation.openfisca.fr/entreprise_bilan)).
Et je trouve même des variables ([`entreprise_assujettie_is`](https://legislation.openfisca.fr/entreprise_assujettie_is)) concernant l'impôt sur les sociétés.
Mais je ne parviens pas à faire le lien entre toutes ces variables.

Donc est-ce que c'est que j'ai mal cherché, et il est effectivement possible de faire des simulations de fiscalité d'entreprise ? Ou est-ce que ça sort du scope actuel de openfisca ?

Merci,

**Comment by benjello** [comment]
Bonjour @etnbrd,

openfisca ne traite pas de la fiscalité des entreprises directement. 
openfisca essaie de calculer l'ensemble des impôts, cotisations, prestations etc qui permettent de passer du coût du travail d'un salarié à son revenu disponible (pour consommer et épargner).
A ce titre certains éléments de la fiscalité des entreprises liés au salarié sont pris en compte dont notamment les allègement de charges (Fillon, CICE).

**Comment by etnbrd** [comment]
Merci pour cette réponse rapide :)
Est-ce qu'il est raisonnablement envisageable de développer les parties manquantes ?
Ou les deux ne cohabiterais pas bien ensemble ?

**Comment by benjello** [comment]
Je ne sais pas vraiment répondre à cette question.
Je pense que l'on peut se servir d'openfisca-core voire de morceaux de france pour faire des calculs au niveau d'une entreprise mais je n'ai pas de schéma clair en tête pour un grand système tout intégré.
Pour avancer, j'essaierais de me définir les objectifs que je veux atteindre et j'essaierais de voir comment je peux réaliser mes calculs à moindre coût en utilisant openfisca:
  - qu'est-ce que je peux déjà récupérer d'openfisca ?
  - quel calcul essentiel dois-je ajouter à openfisca si cela est possible ?
  - si ce n'est pas possible comment modifier plus structurellement openfisca ?

**Comment by etnbrd** [comment]
Ok, merci pour ta réponse :)
