### ISSUE TITLE
Paramétrage des dépenses revalorisées au 01/01/2018 - Aides au logement (AL-FAM_Reval_01janv18)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#928]

**Comment by guillett** [comment]
Merci @ThibaultCCMSA , je propose d'échanger sur cette issue pour clarifier au mieux le sujet pour facilement répliquer cet ajout de détails dans les autres issues.

Il y a deux dates dans l'issue 01/10/2017 et 01/01/2018.
Quelle est l'étendue du sujet ?

Aussi, quel paramètre de la législation est à faire évoluer ?
Quelle est sa valeur avant la(les) revalorisation(s) ?
Quelle est sa valeur après ?

Merci !
