### ISSUE TITLE
Prise en compte du patrimoine dans le calcul de l'aide  - Aides au logement (AL-FAM_Reforme_patrimoine)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#929]
L'estimation du patrimoine du foyer est pris en compte dans le calcul de l'aide au logement pour tous les dossiers déposés à compter du 1er octobre 2016.

**Comment by AdeleHankache** [comment]
Sera-t-il possible de rajouter des cas de tests couvrant les personnes qui sont concernés par cette mesure tous les bénéficiaires d'ALS, ALF et APL sauf :
-	Les personnes âgées résidant en EHPAD ou autres structures assimilés.
-	Les foyers d'un bénéficiaire d'AAH (allocataire, conjoint ou enfant)
-	Les foyers dont l'un des membres est bénéficiaire de l'AEEH.
Merci d'avance, 
Adèle

**Comment by frtomas** [comment]
Il existe dans openfisca une donnée "**statut_occupation_logement**" dont l'une des valeurs possible est "**locataire_foyer**", avec pour description : 
"Locataire d'un foyer (résidence universitaire, maison de retraite, foyer de jeune travailleur, résidence sociale...)"

Cette notion comprend-elle également le fait de résider en EHPAD ?
Si non, n'ayant pas trouvé ailleurs de notion semblant s'y rattacher, le fait de resider en EHPAD est-il pris en compte dans openfisca ?

Cordialement.

**Comment by guillett** [comment]
Bonjour @frtomas , les aides au logement pour les personnes en foyer reposent sur un barème spécifique qui n'est, aujourd'hui, pas implémenté dans OpenFisca (cf. [aide_logement_non_calculable](https://fr.openfisca.org/legislation/aide_logement_non_calculable)).

Les personnes en EHPAD sont-elles titulaires et figurent-elles sur un bail ?

**Comment by jmdallais** [comment]
@guillett , tu peux me donner les droits que je mette à jour les issues stp ?Je ne peux modifier leur statut dans le projet créé par @SChiusa

**Comment by ThibaultCCMSA** [comment]
Bonjour à tous, je confirme ce que Thomas précise à savoir que les aides pour les personnes en EPHAD sont sur un autre type de barème.
Par contre ce que j'ai du mal à saisir c'est que si je comprends bien "locataire_foyer" inclus la notion de maison de retraite or maison de retraite = EPHAD.

Pour la partie bail, je ne saurais pas vous répondre avec exactitude. Pour la demande d'AL, nos caisses réclament juste une quittance de loyer ou une attestation de résidence de l'EHPAD.

**Comment by jmdallais** [comment]
PR https://github.com/openfisca/openfisca-france/pull/975 merged.
