### ISSUE TITLE
Revalorisation des barèmes spécifiques à certains publics "logements foyers" - Aides au logement (FAM_Reforme_Logements Foyers)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#930]
Au 1er octobre 2017, la plupart des barèmes logement accession et logement-foyer ainsi que dans le secteur locatif sont revalorisés, que ce soit en APL, en ALF ou en ALS.

**Comment by Morendil** [comment]
La date jalon associée à cette issue étant dépassée, et ayant pu constater que certains barèmes liés à l'accession contiennent des valeurs actualisées au 1/10/2017, je me permets de fermer cette issue. Si ce n'est pas la bonne décision, merci de réouvrir en ajoutant quelques précisions sur ce qu'il reste à faire.

**Comment by JenniferTelep** [comment]
@Morendil ,
Les modifications l'issue ont prises en compte dans la PR #1199
