### ISSUE TITLE
Intégration des nouvelles règles de l'intéressement - Allocation de Solidarité Spécifique (FAM ASS_interressement)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#932]
Depuis le 1er septembre 2017 , le bénéficiaire de l’ASS reprenant une activité peut intégralement cumuler la rémunération tirée d’une ou de plusieurs activités professionnelles avec le versement de l’ASS pendant une période de 3 mois, consécutifs ou discontinus.

**Comment by JenniferTelep** [comment]
Le dispositif d’intéressement permet d’encourager financièrement les bénéficiaires de l’allocation de solidarité spécifique à reprendre une activité professionnelle. Ainsi, les demandeurs d’emploi indemnisés qui bénéficient de l’ASS peuvent, dans certaines conditions et certaines limites, cumuler leur allocation avec les revenus tirés d’une activité reprise.

Depuis le 1er septembre 2017 (date d’entrée en vigueur du décret n°2017-826 du 5 mai 2017), le bénéficiaire de l’ASS reprenant une activité peut intégralement cumuler la rémunération tirée d’une ou de plusieurs activités professionnelles avec le versement de l’ASS pendant une période de 3 mois, consécutifs ou discontinus.

Références législatives : Décret n°2017-826 du 5 mai 2017 qui prévoit la réforme de l’intéressement à la reprise d’activité des bénéficiaires de l’allocation de solidarité spécifique (et la suppression de l’allocation temporaire d’attente). Le décret est pris pour l’application de l’article 87 de la loi n°2016-1917 du 29 décembre 2016 de finances pour 2017.

Décret n°2017-826 du 5 mai 2017 : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000034603502&categorieLien=id

Loi n°2016-1917 du 29 décembre 2016 :
https://www.legifrance.gouv.fr/eli/loi/2016/12/29/ECFX1623958L/jo

**Comment by AdeleHankache** [comment]
Afin de pouvoir effectuer le calcul de l’intéressement du mois en cours d'une façon générique pour couvrir les différents cas spécifiques, nous aurons besoin de connaitre le nombre de mois précédant le mois au courant à prendre en compte.
Si ce nombre de mois n'est pas limité par la loi, il serait préférable d'établir une limite afin de permettre de traiter un maximum de cas et de faciliter l'implémentation.
Merci d'avance.

**Comment by frtomas** [comment]
@ThibaultCCMSA d'après nos précédents échanges, j'étais resté dans l'idée de ne regarder les antécédents que sur un mois, mais j'aurais besoin d'une dernière confirmation à ce sujet.

@guillett je pense avoir identifié une solution, mais elle implique l'utilisation d'une sous méthode contenant une petite boucle for (qui va boucler 12 fois, une par mois de recul), or ayant remarqué le très petit nombre de ce genre de boucle dans openfisca, je souhaiterai savoir si une telle solution serait acceptable ou si je dois m’évertuer à trouver une alternative ?

Merci d'avance.

**Comment by guillett** [comment]
Merci @frtomas pour la notification. Le mieux pour commencer est d'ouvrir une PR même si ce n'est pas fini. D'ailleurs avez-vous des dépôts privés à la MSA ? Où se trouve les branches en cours de dev ? (Question cachée : Que se passe-t-il si ton ordinateur prend feu ?)

**Comment by ThibaultCCMSA** [comment]
@frtomas Je pense qu’effectivement, comme discuté ensemble, les antécédents sur une année glissante sont suffisants pour couvrir l'ensemble des règles métier / de cumul.

**Comment by jmdallais** [comment]
PR https://github.com/openfisca/openfisca-france/pull/986 merged.
