### ISSUE TITLE
Paramétrage de dépenses revalorisées au 01/04/2018 - Prime d'activité (PPA)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#935]
Les barèmes sont à paraître au 1er avril 2018.

**Comment by benjello** [comment]
@JenniferTelep @ThibaultCCMSA : il me semble que ce ticket peut être fermé. Et il me semble aussi que de nombreux tickets taggués `contrib:msa` puvent l'être. Si c'est bien le cas pourriez-vous les fermer s'il vous plaît.
Par avance merci !

**Comment by jmdallais** [comment]
PR https://github.com/openfisca/openfisca-france/pull/984 merged.
