### ISSUE TITLE
Modulation des plafonds des ressources applicables Métropole - Allocations familiales (AF FAM_Reval_01janv18)

### ISSUE THREAD

**Issue by ThibaultCCMSA** [openfisca/openfisca-france#936]
Au 1er janvier 2018, en métropole, les plafonds des aides sociales familiales sont revalorisés.

**Comment by jmdallais** [comment]
#970

**Comment by jmdallais** [comment]
PR https://github.com/openfisca/openfisca-france/pull/970 merged
