### ISSUE TITLE
Éligibilité à la PPA avec un·e conjoint·e étudiant·e

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#951]
Une famille ayant un des parents étudiant est aujourd'hui considérée comme éligible à la PPA.

Est-ce correct ?

Cf. situation 5aaab5fd43e1927ba2deaf5e

**Comment by maukoquiroga** [comment]
Bonjour @guillett,

Ce que j'ai trouvé pour l'instant dans le Code de la sécurité sociale :

* [Article L842-5](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=9C63D0FDCDE9E6920D28302FEEE07C49.tplgfr40s_2?idArticle=LEGIARTI000031077014&cidTexte=LEGITEXT000006073189&dateTexte=20180416) : « Pour être pris en compte au titre des droits du bénéficiaire, son conjoint, son concubin ou le partenaire auquel il est lié par un pacte civil de solidarité doit remplir les conditions prévues aux 2°, 4° et 5° de l'article L. 842-2.  »

* [Article L842-2](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=9C63D0FDCDE9E6920D28302FEEE07C49.tplgfr40s_2?idArticle=LEGIARTI000031087615&cidTexte=LEGITEXT000006073189&dateTexte=20180416) : « 3° Ne pas être élève, étudiant, stagiaire, au sens de l'article L. 124-1 du code de l'éducation, ou apprenti, au sens de l'article L. 6211-1 du code du travail. Cette condition n'est pas applicable aux personnes dont les revenus professionnels excèdent mensuellement, pendant la période de référence mentionnée à l'article L. 843-4 du présent code, le plafond de rémunération mentionné au 2° de l'article L. 512-3 ; elle ne l'est pas non plus aux personnes ayant droit à la majoration prévue à l'article L. 842-7 ; »

**Comment by guillett** [comment]
Super, merci beaucoup @maukoquiroga .

**Comment by Morendil** [comment]
@guillett @maukoquiroga Je n'ai pas compris à quelle conclusion vous arrivez, vous avez l'air d'accord mais il ne s'est rien passé. Que faut-il faire ?

**Comment by Morendil** [comment]
Bon, il semble que la réponse est "rien". En effet rien n'interdit à un bénéficiaire de la PPA d'avoir un conjoint qui n'en remplit pas les conditions, le 842-5 (sauf erreur de ma part) conditionne la prise en compte des *ressources* du conjoint, et le 842-2 dit qu'on peut cumuler le statut d'étudiant avec des revenus professionnels (par exemple une bourse de recherche, mais pas une bourse sur critère sociaux) et dès lors ces ressources sont prises en compte.

Je ferme donc.
