### ISSUE TITLE
Erreur formule "unites_consommation"

### ISSUE THREAD

**Issue by ClaireLeroyIPP** [openfisca/openfisca-france#953]
Il me semble qu'il y a une erreur dans la formule de la variable `unites_consommation`  :

<pre>
class unites_consommation(Variable):
    value_type = float
    entity = Menage
    label = u"Unités de consommation du ménage, selon l'échelle de l'INSEE"
    definition_period = YEAR

    def formula(menage, period, parameters):
        <b>age_indiv</b>= menage.members('age', period.first_month)
        uc_indiv = 0.5 * (<b>age_i</b> >= 14) + 0.3 * (<b>age</b> < 14)
        tot_uc_indiv = menage.sum(uc_indiv)

        return 0.5 + tot_uc_indiv
</pre>

Est-ce qu'il ne faudrait pas remplacer `age_i` et `age` par `age_indiv`  ?

**Comment by Anna-Livia** [comment]
Je suis d'accord avec toi. Cela donnerait : 
```py
class unites_consommation(Variable):
    value_type = float
    entity = Menage
    label = u"Unités de consommation du ménage, selon l'échelle de l'INSEE"
    definition_period = YEAR

    def formula(menage, period, parameters):
        age_indiv = menage.members('age', period.first_month)
        uc_indiv = 0.5 * (age_indiv >= 14) + 0.3 * (age_indiv < 14)
        tot_uc_indiv = menage.sum(uc_indiv)

        return 0.5 + tot_uc_indiv
```

Est-ce que quelqu'un aurait une référence et des tests pour cette variable ? (@guillett @Morendil @benjello ) ?

**Comment by ClaireLeroyIPP** [comment]
Référence INSEE par exemple : https://www.insee.fr/fr/metadonnees/definition/c1802
