### ISSUE TITLE
CAAH attribué par défaut dans les ressources pour le calcul de la CMU-C / ACS

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#955]
Par défaut, le montant du CAAH (179 euros et des bananes) s'ajoute aux revenus des individus lors du calcul de la CMU-C / ACS.

Cela fait suite à l'ajout du CAAH à la liste des ressources prises en compte pour le calcul de la CMU-C / ACS.

Exemple sur cette trace : https://mes-aides.gouv.fr/trace?situationId=5abd5c0ce1e32a2123c3b0c7 .
Bien que l'individu n'ai pas déclaré recevoir le CAAH, son montant s'ajoute à ses ressources dans cmu_base_ressources_individu , ce qui fausse l'estimation.

Preuve, la même simulation en déclarant un CAAH à 0 euros par mois, le résultat correct de la simulation apparait (proposition de l'ACS) : https://mes-aides.gouv.fr/trace?situationId=5abe0775e1e32a2123c3b9b5

Je ne sais pas comment corriger cela :)

**Comment by monbocal** [comment]
up ! cc @guillett dans le cadre de l'expérimentation

**Comment by guillett** [comment]
Ce que tu décris est, selon moi, le comportement attendu d'OpenFisca :
- Le CAAH est estimé par OpenFisca si il n'a pas été indiqué en entrée
- Le CAAH indiqué en entrée est directement utilisé.

En revanche, il faudrait peut-être
- vérifier que la personne est bien éligible au CAAH
- afficher le montant du CAAH dans mes-aides sur la page des résultat.

**Comment by monbocal** [comment]
C'est bien ça le problème : le CAAH est attribué par défaut à tout le monde, peu importe sa situation. Alors que non : https://www.service-public.fr/particuliers/vosdroits/F12911 . En gros, dès que tu déclares l'AAH, alors hop on t'ajoute virtuellement 179 euros par mois en plus, du coup toutes les simulations ACS / CMU sont fausses sauf si tu déclares manuellement ne pas le recevoir.

**Comment by guillett** [comment]
Dans [la situation envoyée et considérée comme erronée](https://mes-aides.gouv.fr/api/situations/5abd5c0ce1e32a2123c3b0c7) pourquoi penses-tu que la personne n'est pas éligible au CAAH ?

**Comment by monbocal** [comment]
Parce que le CAAH n'est pas attribué automatiquement et que peu importe la situation, le CAAH s'ajoute toujours aux ressources.

Exemple supplémentaire avec ce cas qui cumule toutes les incompatibilités :
- invalide à moins de 80%
- AAH qui n'est pas perçue à taux plein
- reçoit des revenus à caractère pro
- est hébergé chez un particulier
--> trace https://mes-aides.gouv.fr/trace?situationId=5afeb49138a9b057ccde66f4 , CMU_base_ressources_individus : le CAAH apparait.

C'est surement un problème à la source dans la formule de calcul du CAAH : https://fr.openfisca.org/legislation/caah (il y a beaucoup de TODO sur cette formule et des erreurs, comme le aah > 0, ça devrait être aah == taux plein), mais en attendant, on l'attribue à tord dans toutes les simulations déclarant l'AAH sauf si l'utilisateur explicite ne pas le recevoir, ce qui entraîne de nombreuses erreurs.

**Comment by benjello** [comment]
Je confirme que le CAAH codé est très sommaire. Mais rien n'empêche de l'améliorer même graduellement pour éviter qu'il n'apparaisse trop intempestivement.

**Comment by Morendil** [comment]
Je [pousse une branche](https://github.com/openfisca/openfisca-france/tree/fix-caah) pour investiguer l'effet de limiter l'attribution du CAAH aux bénéficiaires de l'AAH à taux plein.

**Comment by Morendil** [comment]
@guillett @alexsegura Est-ce qu'on laisse tomber cette issue?

Sinon je veux bien transformer la branche mentionnée ci-dessous en PR si ça vous convient.

**Comment by Morendil** [comment]
Je ferme pour l'instant, faute d'éléments sur la suite à donner, n'hésitez pas à réouvrir.
