### ISSUE TITLE
Échanger sur le milestone de la MSA au 31/05/2018

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#957]
Ce fil de discussion pour échanger publiquement sur le [milestone](https://github.com/openfisca/openfisca-france/milestone/1) de la MSA autour de sa contribution dans OpenFisca-France.

Il y a 19 sujets à traiter et 38 jours ouvrés d'ici là.
Je n'ai vu ni PR ouverte ni question.

Je pense qu'il est important de prendre les sujets 1 par 1 de l'analyse à la mise en production en passant par l'implémentation et les tests associés.
Le travail de revue de code prend lui aussi du temps à la communauté qu'il faut prévoir.

@openfisca/msa Comment voulez-vous avancer ? 🙂

**Comment by ThibaultCCMSA** [comment]
Bonjour Thomas
Nous allons envoyer nos premiers PR aujourd'hui ou demain (sur reval de barèmes).
Certains sujets ont été milestonés au 31 mai mais nous les avions daté par défaut, cela afin de donner de la visibilité sur les issues que la MSA a prévu de développer. Je vais affiner les milestones des issues en fonction de nos dates de PR visée.

**Comment by guillett** [comment]
Merci @ThibaultCCMSA.

C'est une bonne idée de créer les autres milestones. Cela dit, tu n'es pas obligé.
Tu peux sortir les issues du milestone de fin mai.

**Comment by jmdallais** [comment]
Bonjour @guillett 

Pour partager plus concrètement nos échéances : nos PR seront soumises en 4 lots : 

Lot 1 : 17/04 : 
[AF]   revalorisation des barèmes applicables en métropole
[CF]   revalorisation des barèmes applicables en métropole
[PAJE]   revalorisation des barèmes applicables en métropole
Soumises par @frtomas hier.

Lot 2 : 27/04 : 
[AL] paramètres de dépenses revalorisés
[ASS] paramètres de dépenses revalorisés 
[PPA] paramètres de dépenses revalorisés 
[RSA] paramètres de dépenses revalorisés 
[AAH] paramètres de dépenses valorisés au 01/04/2017
[ASS] intégration des nouvelles règles de l'intéressement

Lot 3 : 04/05 :
[CMUc-ACS]   revalorisation annuelle des plafonds de ressources 
[CMUc-ACS]   fiabilisation de la base ressources (1/2)
[PAJE]   alignement de l'allocation de base de PAJE sur le complément familial   (montants et plafonds)

Lot 4 : 18/05 : 
[CMUc-ACS]   fiabilisation de la base ressources (2/2)

Je mettrai les milestones à jour prochainement.

**Comment by jmdallais** [comment]
@guillett , pour info, les évols. sur la fiabilisation de la base ressources CMUc-ACS sont copieuses. Je les mets en point d'attention pour nous tous.

**Comment by guillett** [comment]
Merci pour ce point d'attention, cette contribution peut-elle être publiée plus tôt pour échanger sereinement ?

**Comment by jmdallais** [comment]
On fait notre max :-)

**Comment by jmdallais** [comment]
@guillett , as tu en visbilité des  travaux éventuellement en cours côté DINSIC ou autres contributeurs qui viendrait nous impacter (par ex. : Impacts sur l'API publique d'OpenFisca France, renommage ou suppression de variables) dans les 2 mois à venir ?

**Comment by guillett** [comment]
Je n'ai pas en tête de changements majeurs.

Côté contribution, j'échange avec différents acteurs pour fiabiliser l'AAH mais c'est un sujet encore loin côté MSA.

**Comment by guillett** [comment]
Les tests de recette rédigés à la MSA contiennent-il des informations qui permettent de mieux les qualifier et les décrire ?

```yaml
- name: "Allocations familiales - Cas N°1"
```
> Les numéros de cas de test ne permettent pas de comprendre ce qui est testé dans le test. Le fichier à ta disposition contient-il des informations complémentaires pertinentes ?

Cette question est en lien avec [mon commentaire](https://github.com/openfisca/openfisca-france/pull/970#discussion_r182467317) sur [la revalorisation des AF](https://github.com/openfisca/openfisca-france/pull/970).

**Comment by jmdallais** [comment]
@guillett , tu peux donner un exemple de ce qui conviendrait stp ?

**Comment by guillett** [comment]
Pour le test en question peut-être que _Cas N°1_ pourrait être remplacé par :
- tranche 3/3 (ie. ressources élevées) ou bien
- 3ème tranche.

**Comment by guillett** [comment]
Un commentaire pour partager des échanges téléphoniques avec @ThibaultCCMSA .

La MSA et la DDS souhaitent intégrées toutes les PRs ouvertes + une d'ici la fin de la semaine. Cela va mettre de la tension sur la communauté ce qui n'est pas souhaitable.

Nous allons faire notre maximum pour que ces PRs soient intégrées rapidement.

Cela dit, je vous conseille de faire une branche dans laquelle il y aurait tous les développements qui vous souhaitez intégrer à votre production en fin de semaine. De cette façon, vous aurez une solution de replis en cas de non intégration de toutes les PRs.
