### ISSUE TITLE
Ajout du régime des micro-bénéfices agricoles (depuis 2016 )

### ISSUE THREAD

**Issue by claireleroy** [openfisca/openfisca-france#963]
Comme décrit dans la PR #917, le **régime du forfait agricole** qui s'appliquait aux agriculteurs dont les recettes ne dépassaient pas un certain plafond est remplacé à partir de l'imposition des revenus 2016 par le **régime du micro-bénéfice agricole**.

La formule de calcul ainsi que les paramètres sont modifiés.

**Comment by Morendil** [comment]
Je ferme, le recensement des dispositifs législatifs à modéliser se fait désormais sur [le Wiki](https://github.com/openfisca/openfisca-france/wiki/Droit-%C3%A0-mod%C3%A9liser).
