### ISSUE TITLE
Studieuse Openfisca tous les Tx

### ISSUE THREAD

**Issue by sebshulz** [openfisca/openfisca-france#974]
Supersedes #973 

Chère communauté,

Comme l'amicale, l'idée est de se réunir, en tant que communauté OpenFisca France, pour discuter ensemble autour des sujets qu'on voudrait faire évoluer, soient-ils techniques, features, stratégie, gouvernance, etc.

La sortie de cette issue est une validation de :

- [x] Date     -> 29/05 entre 14h et 18h
- [x] Lieu      -> 20, avenue de Ségur, 75007 Paris
- [x] Format -> [Lean coffee](http://leancoffee.org/)

### Date

Remplir le [framadate](https://framadate.org/qACDmRG1SREheunp)

L'idée est de consacrer un après-midi plein à cette studieuse, composée d'une séance de lean coffee thématique : stratégie produit, sujets techniques, et gouvernance de la communauté. 

### Lieu

20, avenue de Ségur, 75007 Paris (DINSIC).

### Format

https://docs.google.com/document/d/14ip-UtnRgARubFU75I_ILVitj1lXF5WCQrjbRC5uUo4/edit?usp=sharing

@sebshulz fait partie de l'équipe DINSIC pendant deux semaines, et s'est porté volontaire de nous aider dans l'organisation de cette belle initiative.

**Comment by benjello** [comment]
@bfabre01 @ClaireLeroyIPP you are definitively welcome !

**Comment by benjello** [comment]
Je partage les points soulevés par @guillett que ce soit sur la synchronisation sur les sujets que l'on voudrait aborder et la liste des priorités.

Si tout le monde est d'accord, peut-être que @sebshulz pourrait nous aider à accoucher d'un ordre du jour avec éventuellement des mini-intros assignées à certaines personnes/petits groupes. En bref essayons de faire le max en amont et en asynchrone pour que la studieuse IRL soit bien ciblée et serve à lever des bottleneck, résoudre des incompréhensions et/ou clarifier des objectifs.

**Comment by maukoquiroga** [comment]
Hello @guillett, merci pour ces retours. J'ai du mal à voir comment es-tu en train de _hijacker_ l'issue vu que tu es en train d'y contribuer.

> La studieuse demande une synchronisation et je pense que les priorités de chacun peuvent être recueillies en asynchrone.

Complètement d'accord, et c'est pour cela que l'objectif que la studieuse va au-delà des priorités. L'objectif est qu'elle soit _bien ciblée et serve à lever des bottleneck, résoudre des incompréhensions et/ou clarifier des objectifs_, dixit @benjello (merci !).

Comme évoque @sebshulz, l'idée est de consacrer à aborder _3 blocs (Retour d'expérience / Technique / Gouvernance)_.

- **Retour d'expérience : **
  - Revue des dernières mois
  - Points d'amélioration
  - Objectifs des mois à venir (PLF ? International ? ...)

- **Technique :**
  - Priorités (comment on arrive à nos objectifs)
  - Bottlenecks
  - Architecture

- **Gouvernance :**
  - Rôle de chacun-e dans la communauté France, inclus l'équipe DINSIC :
    - qui mis en œuvre les différentes priorités
    - politique d'animation / contribution / review / merge
    - comment faire face à la croissance à l'international
    - entre autres

> Si tout le monde est d'accord, peut-être que @sebshulz pourrait nous aider à accoucher d'un ordre du jour avec éventuellement des mini-intros assignées à certaines personnes/petits groupes.

On fera notre mieux 😃

**Comment by ThibaultCCMSA** [comment]
Bonjour à tous, 
Avez-vous pu arrêter une date ? Je vois sur le framadate que cela serait le 29/05. 
La MSA est-elle invitée ? :)

**Comment by maukoquiroga** [comment]
Bonjour @ThibaultCCMSA, je prépare l'email de confirmation maintenant.

> Avez-vous pu arrêter une date ?

La studieuse aura lieu le 29/05 entre 14h et 18h au 20 avenue de Ségur, 75007.

> La MSA est-elle invitée ? :)

Bien sûr !

Plus de détails dans un instant 😃

**Comment by maukoquiroga** [comment]
Bonjour,

Merci à tous pour vos réponses au [sondage](https://framadate.org/qACDmRG1SREheunp) de la Studieuse !

Nous nous donnons donc rendez-vous :  mardi prochain, le 29 mai de 14h à 18h*, au 20 avenue de Ségur, 75007, salle 5.120.
 
L'accueil sera informé de votre visite et vous fournira un badge, et nous serons également joignables par téléphone au 06 84 54 97 96.

Pour rappel l'objectif est de se réunir, en tant que communauté OpenFisca France, pour discuter des sujets que nous voudrions faire évoluer, soient-ils techniques, stratégiques, produit, de gouvernance...

Pour ceci, nous vous proposons un format [lean coffee](http://leancoffee.org/) clôturé par un bilan des actions à entreprendre. Nos espaces de travail seront également à votre disposition dans le cas où vous voudriez suivre la [loi des deux pieds](https://fr.wikipedia.org/wiki/M%C3%A9thodologie_Forum_Ouvert#M%C3%A9thode).

Nous avons aussi mis à disposition un [document](https://docs.google.com/document/d/14ip-UtnRgARubFU75I_ILVitj1lXF5WCQrjbRC5uUo4/edit?usp=sharing) pour pouvoir commencer à proposer et à débroussailler en amont les sujets qu'on pourrait aborder pendant la studieuse. N'hésitez pas à ajouter des sujets directement ! 

Ces travaux bien achevés, nous pourrons migrer vers le café d'à côté pour partager un verre et un moment sympathique. 

À bientôt !

Anna-Livia, Mauko & Sandra.

(*) Quelques départ seront probables à 16h, nous nous organiserons en fonction.
