### ISSUE TITLE
Mettre à jour plafond deficits agricoles

### ISSUE THREAD

**Issue by MalkIPP** [openfisca/openfisca-france#979]
https://github.com/openfisca/openfisca-france/blob/bfcc62d28c7c0706931c207d843fbc0296ad18d0/openfisca_france/parameters/impot_revenu/rpns/micro/imputation_sur_le_revenu_global/plafond_deficits_agricoles.yaml#L34

Ce paramètre n'est pas à jour et vaut 
2017: 108904 €
2016: 107826 €
2015: 107718 €

**Comment by guillett** [comment]
Bonjour et merci @MalkIPP !
Ce paramètre est-il dans les barèmes IPP ? (je ne l'ai pas trouvé avec un rapide coup d'oeil)
Si oui où ? (pour faire les modifications avec les références législatives)

**Comment by claireleroy** [comment]
Cette issue a été résolue par la PR #1017
