### ISSUE TITLE
Calcul de la PPE

### ISSUE THREAD

**Issue by bixiou** [openfisca/openfisca-france#98]
Le calcul de la prime pour l'emploi est délicat. La meilleure source que j'ai trouvée est wikipedia (http://fr.wikipedia.org/wiki/Prime_pour_l%27emploi) combinée avec la notice des impôts (cf. NOT dans https://www.dropbox.com/home/IDEP_OPENFISCA/python_project/mSim/doc/Documentation/formulaires%20IR/Formulaires%202012). Le revenu pris en compte pour le calcul de la PPE est le revenu d'activité. Il semble qu'il y a une anomalie dans le fichier irpp.py qui clacule la base de ressources utile au calcul de la PPE, dans _ppe_rev :+1: 
on lit "    rev_ns = min_(0, rpns) / ppe.abatns + max_(0, rpns) \* ppe.abatns
    return rev_sa + rev_ns"
C'est étrange qu'un revenu négatif fasse baisser la base de ressources (donc la PPE) (min(0,rpns)).
Je vais essayer de définir dans une autre fonction les revenus d'activité salarié et non salarié, qu'on pourra reprendre dans _ppe_rev.
@clems @benjello

**Comment by MattiSG** [comment]
La PPE a été remplacée par la prime d'activité au 01/01/2016, et implémentée dans OpenFisca via Mes Aides. Personne ne travaillant activement à restaurer le calcul de la PPE pour raisons historiques, je ferme.
