### ISSUE TITLE
Implémenter les règles de calculs de la réduction du loyer de solidarité

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#987]
La réduction du loyer de solidarité (RLS) vient compenser la baisse d'APL pour les personnes en logement social.

Plus d'informations sur [service public](https://www.service-public.fr/particuliers/actualites/A12467).

**Comment by claireleroy** [comment]
Je m'intéressais justement à la question de la RLS et j'ai vu que cela avait été codé dans la PR #1058, ce qui résout cette issue @guillett il me semble !

**Comment by guillett** [comment]
Merci @claireleroy
