### ISSUE TITLE
Abattement / Neutralisation des ressources dans le cadre de l'ASS

### ISSUE THREAD

**Issue by monbocal** [openfisca/openfisca-france#995]
Suite à un retour utilisateur sur l'ASS, je me pose des questions sur la formule de calcul de l'ASS pour une personne seule et dans un couple.

En particulier, je ne comprends pas pourquoi l'abattement et la neutralisation des ressources précédentes est gérée différemment entre le demandeur et le conjoint pour calculer `ass_base_ressources`.

Pour le demandeur https://fr.openfisca.org/legislation/ass_base_ressources_individu , il s'agit d'une neutralisation totale des précédents salaires si le salaire du dernier mois est à 0 :

```
    salaire_imposable_interrompu = (salaire_imposable > 0) * (salaire_imposable_this_month == 0)
    # Le Salaire d'une activité partielle est neutralisé en cas d'interruption
    salaire_imposable = (1 - salaire_imposable_interrompu) * salaire_imposable
```

Pour le conjoint, https://fr.openfisca.org/legislation/ass_base_ressources_conjoint , l'abattement est de 100 ou de 30%, en se basant sur https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000020398006&cidTexte=LEGITEXT000006072050 . Deux variables spécifiques sans contreparties pour l'individu sont même disponibles :

```
        tx_abat_partiel = parameters(period).prestations.minima_sociaux.ass.abat_rev_subst_conj
        tx_abat_total = parameters(period).prestations.minima_sociaux.ass.abat_rev_non_subst_conj
```

Je ne trouve pas de trace de cette distinction d'abattement entre le conjoint et le demandeur dans les textes.

Pour aller plus loin, pour le conjoint, trois autres ressources sont prises en compte : la retraite nette, le chômage net et les indemnités de stage alors que ces ressources sont normalement exclues de l'ASS. La formule de calcul appliqué devrait normalement neutraliser le chômage et les indemnités de stage ; cependant, après avoir tracé à la main la formule de la neutralisation (avec le paramètre à true), cette neutralisation n'intervient que si elles sont interrompues, ce qui va à l'encontre de ce que j'ai compris de l'ASS (l'allocation chomage et les revenus des stages sont exclus de la base ressource : https://www.service-public.fr/particuliers/vosdroits/F12484 ).

- Est ce que quelqu'un peut m'aider à y voir plus clair et me corriger dans la compréhension de l'ASS et de son interprétation par OpenFisca ?

Merci !

_Cette issue a peut-être un lien avec https://github.com/openfisca/openfisca-france/issues/932_

**Comment by maukoquiroga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure developers know when France's performance improves/decreases](https://trello.com/c/A3GQ1HMS/30-ensure-developers-know-when-frances-performance-improves-decreases)

**Comment by Morendil** [comment]
Fermée par #1326
