### ISSUE TITLE
Application d'un montant minimal de l'AAH en cas d'hospitalisation/incarceration

### ISSUE THREAD

**Issue by frtomas** [openfisca/openfisca-france#999]
Un montant minimal de l'AAH doit être utilisé après 60 jours d'hospitalisation, d'accueil en MAS (Maison d'Accueil Spécialisé) ou d'incarcération.
Ce montant minimal correspond aujourd'hui à 30% du montant à taux plein.
Les variables représentants les condition associée à ce montant minimal ne semblent ne pas exister à l'heure actuelle dans OpenFisca.

**Comment by Morendil** [comment]
A réouvrir au moment du début des travaux sur ce point.
